### ISSUE TITLE
net.box watch doesn't always release its function after unregister

### ISSUE THREAD

**Issue by alyapunov** [tarantool/tarantool#10050]
Adding a test to net_box_watcher_test.lua
```lua
g.test_callback_gc = function(cg)
    local conn = net.connect(cg.server.net_box_uri)
    local cb = function() end
    local weak = setmetatable({cb = cb}, {__mode = 'v'})
    local w = conn:watch('foo', cb)
    fiber.sleep(0.1)
    w:unregister()
    w = nil -- luacheck: ignore
    cb = nil -- luacheck: ignore
    t.helpers.retrying({timeout = 10, delay = 0.1}, function()
        collectgarbage('collect')
        t.assert_equals(weak.cb, nil)
    end)
end
```
And running it like `./test-run.sh $(yes net_box_watcher_test | head -n 128) -j16`
Sometimes (about 4%) results in error:
```
[008] not ok 8	box-luatest.net_box_watcher.test_callback_gc
[008] #   ...Work/tarantool/test/box-luatest/net_box_watcher_test.lua:232: expected: nil, actual: function: 0x40f09590
[008] #   stack traceback:
[008] #   	...Work/tarantool/test/box-luatest/net_box_watcher_test.lua:232: in function 'retrying'
[008] #   	...Work/tarantool/test/box-luatest/net_box_watcher_test.lua:230: in function 'box-luatest.net_box_watcher.test_callback_gc'
[008] #   	...
[008] #   	[C]: in function 'xpcall'
```
Increasing timeout does not affect the test failure probability.

**Comment by alyapunov** [comment]
I'm sure that net_replicaset_test.lua fails in line `t.assert(weak_ref.watcher == nil)` because of this issue.

**Comment by Buristan** [comment]
I suppose that the reason is the same as for tarantool/tarantool-qa#233, tarantool/tarantool-qa#276 -- the `cb()` is referenced on the trace:
```
---- TRACE 22 start 13/2 net_box.lua:703
---- TRACE 22 IR
...
0026 >  fun EQ     0015  net_box_watcher_test.lua:436 -- cb declaration
```
So, the object is not dead at the moment of the assertion check.
See a more detailed explanation [here](https://github.com/tarantool/tarantool/wiki/LuaJIT-function-inlining).

Fortunatelly, it is easily fixed by adding 
```lua
jit.off(cb)
```
after the `cb()` declaration. Since compilation for this function is disabled, it can't be a part of the trace, so it can't be referenced by any trace.

**Comment by sergepetrenko** [comment]
Since there's an explanation of what's going on from @Buristan, this doesn't seem like watcher issue, rather test design one.
