### ISSUE TITLE
Update quorum in `on_commit` trigger instead of `on_replace` trigger.

### ISSUE THREAD

**Issue by CuriousGeorgiy** [tarantool/tarantool#10087]
For addition of new replicas, let's update the quorum in the `on_commit` trigger. This way we’ll be able to insert a node regardless of the current configuration. This contradicts with the Raft specification, which requires application of all configuration changes in the `on_replace` trigger (i.e., as soon as they are persisted in the WAL, without quorum confirmation).

**Comment by sergepetrenko** [comment]
This is a bugfix and we should backport it to 2.11 and 3.1

**Comment by sergepetrenko** [comment]
Another manifestation of this issue:
When we change quorum in the `on_replace` trigger instead of `on_commit`, this spoils quorum for transactions which were added to limbo even before the `_cluster` insertion. For example, if a node has quorum 2 and has some transactions in limbo and tries to insert a new node into `_cluster`, making the quorum 3, the previous transactions will also wait for quorum 3 (which might be unreachable, because the newly added node doesn't ack its own addition).
As soon as `replication_synchro_timeout` passes, the previous transactions start rolling back the queue, starting from the  last transactions (_cluster addition):
https://github.com/tarantool/tarantool/blob/2131743e3bea9b7d923c02508ed10683209085e1/src/box/txn_limbo.c#L320-L333
Rolling back the _cluster addition turns the quorum back to 2, and initiates quorum recalculation for not yet rolled back transactions. Given that quorum 2 was achievable, the transaction which failed to wait for quorum suddenly becomes "confirmed", and a confirm is written for the same lsn for which a rollback was already written. Split-brain.
https://github.com/tarantool/tarantool/blob/2131743e3bea9b7d923c02508ed10683209085e1/src/box/txn_limbo.c#L1246-L1260

@Gerold103, @Serpentian, please also take a look at this. It seems the issue is fixed by moving quorum change to `on_commit` trigger, but I might miss something here. The `txn_limbo_on_parameters_change` in `on_commit` or `on_rollback` triggers for space `_cluster` might still break something, although I can't think of a scenario right now.

Here's a repro for the case when quorum is changed in `on_replace` triggers (you may check latest 2.11 for this)
```lua
-- Instance 1.
-- Step 1.
box.cfg{listen=3301, replication={3301,3302}, replication_synchro_quorum='N', replication_synchro_timeout=1}

-- Step 3.
box.schema.user.grant('guest', 'replication')
box.ctl.promote()
box.schema.space.create('test', {is_sync=true}):create_index('pk')
box.space._cluster:alter{is_sync=true}

-- Step 4.
fiber = require('fiber')
fiber.new(function() box.space.test:insert{1} end) fiber.new(function() box.space._cluster:insert{3, tostring(require('uuid').new())} end)

-- Step 5.
-- Wait for replication_synchro_timeout to pass and observe:
-- If the node is built in debug mode, it will fail with assertion:
-- tarantool> boxAssertion failed: (in_txn() == NULL), function txn_limbo_complete, file txn_limbo.c, line 84.
--
-- If the node is built in release, it will work just fine, but the second node will say:
-- RAFT: rejecting RAFT_CONFIRM (40) request from origin_id 1 replica_id 1 term 0. confirmed lsn 8431065181 < request lsn 8431065183 and empty limbo
-- ER_SPLIT_BRAIN: Split-Brain discovered: got a request mentioning future lsn 

-- Instance 2.
-- Step 2.
box.cfg{listen=3302, replication={3301,3302}, replication_synchro_quorum='N', replication_synchro_timeout=1}
```
