### ISSUE TITLE
documentaion: upate 'plugins' chapter, mysql and pg are not longer 'plugins'

### ISSUE THREAD

**Issue by kostja** [tarantool/tarantool#1011]
MySQL and PostgreSQL are no longer plugins, it means you dodn't have to build/install them along with the master. They are available as Lua Rocks at rocks.tarantool.org

**Comment by pgulutzan** [comment]
This is waiting for a fix of #855.

**Comment by condor-the-bird** [comment]
Hi all)
This issue seems more or less "trivial", and I decided to pick it to analyze the project & to let you, guys, have a closer look at me ;-).
What I would suggest within the existing framework/structure is:
a) Removing appendix D (http://tarantool.org/doc/book/app_d_plugins.html?highlight=postgre) OR Editing it to indicate that the content is obsolete/applies to older versions. 
b) Adding two sections to the Reference Manual (it may need an overhaul, but that's another story). 

These chapters could start like this: http://rst.ninjs.org/?n=55fa7e1674b0f82d42c3006099f7a76b&theme=nature & http://rst.ninjs.org/?n=f32f741e2022cce8d0cfafb516cea1f1&theme=nature and contain detailed examples/guidelines on deploying rocks.
To do the job, I would, first and foremost, need info on the subject matter & we would need to decide how I work with the framework (publishing, styles, etc.). Writing the text is more or less trivial, but the publishing procedure seems tricky.  
I guess, it'd take installing the latest version of Tarantool and playing with it. As you know, I'm an evil Windows person, so, before I get a decent VM configured and learn some of the ropes, I'd sugget using teamviewer (https://www.teamviewer.com) at an office PC where the solution is deployed/or where I could deploy it myself using the existing docs.
BR,
Maria Kondorskaya
