### ISSUE TITLE
UBsan: runtime error: member access within null pointer of type 'typeof (*trigger)' (aka 'struct trigger')

### ISSUE THREAD

**Issue by ligurio** [tarantool/tarantool#10143]
**Bug description**

* OS: Linux
* Architecture: amd64

**Steps to reproduce**

```
python /home/runner/work/oss-fuzz/oss-fuzz/infra/helper.py build_fuzzers tarantool --engine libfuzzer --sanitizer undefined --architecture x86_64
python /home/runner/work/oss-fuzz/oss-fuzz/infra/helper.py check_build tarantool --engine libfuzzer --sanitizer undefined --architecture x86_64
```

**Actual behavior**

```c++
Dictionary: 2 entries
INFO: Running with entropic power schedule (0xFF, 100).
INFO: Seed: 1337
INFO: Loaded 1 modules   (24025 inline 8-bit counters): 24025 [0x55af3f6acca8, 0x55af3f6b2a81), 
INFO: Loaded 1 PC tables (24025 PCs): 24025 [0x55af3f6b2a88,0x55af3f710818), 
INFO: -max_len is not provided; libFuzzer will not generate inputs larger than 4096 bytes
/src/tarantool/src/lib/core/trigger.h:121:2: runtime error: member access within null pointer of type 'typeof (*trigger)' (aka 'struct trigger')
    #0 0x55af3f4af3ce in trigger_destroy /src/tarantool/src/lib/core/trigger.h:121:2
    #1 0x55af3f48fc45 in fiber_destroy /src/tarantool/src/lib/core/fiber.c:1643:2
    #2 0x55af3f48f9b7 in cord_destroy /src/tarantool/src/lib/core/fiber.c:1947:2
    #3 0x55af3f49ad16 in fiber_free /src/tarantool/src/lib/core/fiber.c:2262:2
    #4 0x55af3f43c14c in LLVMFuzzerTestOneInput /src/tarantool/test/fuzz/swim_proto_member_fuzzer.c:41:5
    #5 0x55af3f3801d0 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:614:13
    #6 0x55af3f3816d1 in fuzzer::Fuzzer::ReadAndExecuteSeedCorpora(std::__Fuzzer::vector<fuzzer::SizedFile, std::__Fuzzer::allocator<fuzzer::SizedFile>>&) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:807:3
    #7 0x55af3f381cb7 in fuzzer::Fuzzer::Loop(std::__Fuzzer::vector<fuzzer::SizedFile, std::__Fuzzer::allocator<fuzzer::SizedFile>>&) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:867:3
    #8 0x55af3f36f676 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:914:6
    #9 0x55af3f39c7f2 in main /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerMain.cpp:20:10
    #10 0x7eff4ac1a082 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x24082) (BuildId: 0702430aef5fa3dda43986563e9ffcc47efbd75e)
    #11 0x55af3f3607ed in _start (/tmp/not-out/tmpmlr5u3tj/swim_proto_member_fuzzer+0x1d17ed)

DEDUP_TOKEN: trigger_destroy--fiber_destroy--cord_destroy
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /src/tarantool/src/lib/core/trigger.h:121:2 in 
MS: 0 ; base unit: 0000000000000000000000000000000000000000


artifact_prefix='./'; Test unit written to ./crash-da39a3ee5e6b4b0d3255bfef95601890afd80709
Base64: 
```

https://github.com/google/oss-fuzz/actions/runs/9563697700/job/26362775183?pr=12085

**Expected behavior**

**Comment by LevKats** [comment]
Looks like it's actually an rlist issue:

1. The error happens in this line: 
    `rlist_foreach_entry_safe(trigger, list, link, tmp)`
    [here](https://github.com/tarantool/tarantool/blob/7db4de75f8bd975066635f942ee49f33a2209353/src/lib/core/trigger.h#L121C2-L121C52)
2. Let's think what would happen in case of empty list. In that case `item->next == item->prev && item->next == item`
3. `rlist_foreach_entry_safe` executes `(trigger) = rlist_first_entry((list), typeof(*trigger), link);`
4. It checks if `trigger->link` it the list's head: `rlist_entry_is_head((trigger), (list), link) `. It means it checks if `trigger->link == list`. And if it is actually list's head it would exit.
5. The problem here occurs if the head of the list is not a member of valid trigger structure. In that case  `(trigger) = rlist_first_entry((list), typeof(*trigger), link);` would result in accessing memory by pointer `(struct trigger *)( (char *)(list) - offsetof(struct trigger,link));` which is not a valid trigger because it was created [here](https://github.com/tarantool/tarantool/blob/7db4de75f8bd975066635f942ee49f33a2209353/src/lib/core/fiber.c#L1033) this way `rlist_create(&fiber->on_yield);`
6. Let's test out assumption. This lines actually fix the build:
```c
if (rlist_empty(list)) {
	return;
}
struct trigger *trigger, *tmp;
rlist_foreach_entry_safe(trigger, list, link, tmp) {
//...
``` 
```
INFO:__main__:Check build passed.
```
7. I think we should add checks to `rlist_foreach_entry*` macros so it is not empty for loop init statement to get valid first list element.
8. I haven't test following idea but should't it crash the same way for head not being a valid trigger pointer in case of nonempty list? In the end of the loop it would access that memory too `(tmp) = rlist_prev_entry((item), member)`.

What do you think?

**Comment by Serpentian** [comment]
> I haven't test following idea but should't it crash the same way for head not being a valid trigger pointer in case of nonempty list? In the end of the loop it would access that memory too (tmp) = rlist_next_entry((item), member).

We have to write unit test and run it under UBsan. It seems to me we'll fail here too. 

SInce any list might be empty during `rlist_foreach_entry*`, we have to fix this in macroses. Moreover, not only `rlist_foreach_entry_safe` is affected, but also `rlist_foreach_entry`, `rlist_foreach_entry_reverse`, rlist_foreach_entry_safe_reverse`. All of them should be fixed.

The alternative solution may be returning `NULL` from `rlist_first_entry` (if `rlist_first() == head`) and `rlist_next_entry` (if `rlist_next == head`). For the last one we'll have to introduce `rlist_next_entry_safe`, in which we'll pass `head`.In such case the condition for stopping a loop will be `item == NULL`.  However, such solution makes sense only if `rlist_next_entry` is affected by this problem, otherwise, it's enough to check if the list is not empty

**Comment by ligurio** [comment]
How-to reproduce:

```diff
--- a/cmake/compiler.cmake
+++ b/cmake/compiler.cmake
@@ -229,6 +229,8 @@ macro(enable_tnt_compile_flags)
                 alignment bool bounds builtin enum float-cast-overflow
                 float-divide-by-zero function integer-divide-by-zero return
                 shift unreachable vla-bound
+            null nonnull-attribute nullability-arg returns-nonnull-attribute nullability-assign
+            nullability-return
             )
 
             # Exclude "object-size".
```

```sh
CC=clang-19 CXX=clang++-19 cmake -S . -B build -DCMAKE_BUILD_TYPE=RelWithDebInfo -DENABLE_UB_SANITIZER=ON
cmake --build build/ --parallel
./build/test/fuzz/swim_proto_member_fuzzer
<snipped>

./build/test/unit/swim_proto.test
<snipped>

ok 3 - subtests
# *** swim_test_route: done ***
/home/sergeyb/sources/MRG/tarantool/src/lib/core/trigger.h:121:2: runtime error: member access within null pointer of type 'typeof (*trigger)' (aka 'struct trigger')
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /home/sergeyb/sources/MRG/tarantool/src/lib/core/trigger.h:121:2
```

**Comment by locker** [comment]
Unit tests fail too with the compilation flags from https://github.com/tarantool/tarantool/issues/10143#issuecomment-2222668971:

```
$ test/unit/swim.test
src/lib/small/include/small/region.h:279:24: runtime error: member access within null pointer of type 'struct rslab'
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior src/lib/small/include/small/region.h:279:24
```

[`region.h:279`](https://github.com/tarantool/small/blob/cb4b61851b9b08f713b33eea18ed6680dd3bbfbe/include/small/region.h#L279-L281)

```C
		struct rslab *slab = rlist_first_entry(&region->slabs.slabs,
						       struct rslab,
						       slab.next_in_list);
```

I think ASAN complains about this null derference:

[`rlist.h:282`](https://github.com/tarantool/small/blob/cb4b61851b9b08f713b33eea18ed6680dd3bbfbe/include/small/rlist.h#L282-L285)

```C
#define rlist_entry(item, type, member) ({				\
	const typeof( ((type *)0)->member ) *__mptr = (item);		\
	(type *)( (char *)__mptr - offsetof(type,member));		\
})
```

Apparently, this is FP but I don't know how to suppress it.
