### ISSUE TITLE
'console' configuration in box.cfg{} style

### ISSUE THREAD

**Issue by mejedi** [tarantool/tarantool#1045]
It would be nice to be able to change the console listen port in the same way as it is possible to change box IPROTO listen port, i.e. by setting a new listen port.

In other words, it would be nice to have console.cfg{listen='3303'} which works the same way  as box.cfg{listen='3303'}

**Comment by Totktonada** [comment]
Since #8724 (which lands to 3.0.0-alpha1) the console can be configured from the declarative config (represented by the YAML file or environment variables).

https://github.com/tarantool/tarantool/blob/3fccfc8fe64c9a23eab0a0888313d7ac64db2200/src/box/lua/config/instance_config.lua#L370-L379

The admin socket is also created by default.

I hope it handles the desired user scenario.

**Comment by kyukhin** [comment]
So, let's consider this done.
