### ISSUE TITLE
config: on_rw callback in a role

### ISSUE THREAD

**Issue by Totktonada** [tarantool/tarantool#10538]
## Context

`cartridge` [passes](https://github.com/tarantool/cartridge/blob/7d99ecf639e8bc979fe7fc1b7cc94ae8530e1620/cartridge/roles.lua#L457-L459) an `opts.is_master` flag into the role's `apply_config` function. Also, it calls the `apply_config` function on transition from RO to RW. (See also https://github.com/tarantool/doc/issues/4280.)

Tarantool 3.x roles are different in this regard. `apply` is called on a reconfiguration -- when a new config arrives. It is not called on a transition from RO to RW.

After #10520 an RW status will be suitable to perform (most of) DDL operations. We need a convenient way to write role's database schema initialization code.

A user needs to register/unregister a watcher now:

```lua
-- myrole.lua
local function schema_init()
    box.once('myrole_init', function()
        box.schema.space.create('myrole_space')
        box.space.myrole_space:create_index('pk')
    end)
end

local box_status_watcher

local function apply(role_cfg)
    if box_status_watcher == nil then
        box_status_watcher = box.watch('box.status', function(_, status)
            if not status.is_ro then
                schema_init()
                box_status_watcher:unregister()
                box_status_watcher = nil
            end
        end)
    end
    <...>
end

return {
    <...>,
    apply = apply,
}
```

Or spawn a fiber with `box.ctl.wait_rw()`.

Both variants are a bit too wordy for such a typical scenario.

## Proposal

I propose to add an `on_rw` callback into the role next to the `apply` and others:

```lua
-- myrole.lua

<...>

return {
    <...>,
    apply = apply,
    on_rw = schema_init,
}
```

This way config's code takes all the complexity around waiting RW status and give a role author a simple API for that.

Details:

* `on_rw` is called on startup after `apply` if the instance is started in the RW mode.
* `on_rw` callbacks from different roles are started in the same order as their `apply` functions (as written in `roles` in the YAML configuration with reordering, where one role depends on another).
* Call `apply` for all the roles and then `on_rw` for all the roles. It seems more consistent with a situation, when the RW mode is assigned after a startup.
* The callback should also be called if the database schema version is changed (i.e. `box.schema.upgrade()` is called) and the status of the instance is RW. It allows to issue a DDL that uses a new feature only when the database is ready for it. We should pass the schema version into the callback (a user may use #10521 to compare verisons).

  ```lua
  local version = require('version')

  local function on_rw(status)
      init_schema_base()

      if status.version >= version.fromstring('3.4.5') then
          init_schema_3_4_5()
      end
  end

  return {
      <...>
      on_rw = on_rw,
  }
  ```

Also tracked in TNTP-225
Part of TNTP-41

**Comment by R-omk** [comment]
I think it's a bad idea to add callback to roles API in the form in which it is described in this issue.

> on_rw is called on startup
> should also be called if the database schema version is changed 

it is not clear from the description whether it is called every time when switching ro->rw  or only after applying the config. If the call is a one-time, then this greatly limits the scope of application of such a callback.  Sometimes the app still needs to know that it can write data, for various background service or something like that, in which case it still need to manually monitor rw->ro->rw->  transitions state.

Since the example focuses on creating a schema, I will make the following comments:
- the scheme may depend on the config, in the proposed version there is no direct connection with the config, the user needs to extract it independently? how to achieve config consistency?
- the lifecycle of a full migration can be much more complex than just atomically creating tables or something like that.  It is unclear how to synchronize the behavior and state of the application because the apply and on_rw calls become independent, the application's operation is almost always tied to the state of the scheme, it turns out that the problem (wait rw) simply moves to another place in a different form.   ()

> on_rw is called on startup after apply

but why not in reverse order? the application needs to know that the schema is ready (created or updated) before starting the main job, even if it is in read-only state. What should I do? check by a timer that the correct schema has appeared? this is ugly, but I don't see any other way.


----

I think that everything related to migrations and the scheme requires more careful development.

As for solving the problem initially posed in this ticket, there is no need to do things that you will have to fight with later.

**Comment by R-omk** [comment]
related https://github.com/tarantool/ddl/issues/119

**Comment by Totktonada** [comment]
@R-omk Thanks for your time to leave a feedback. I think that most of your points are addressed in my proposal (the problem is that I wrote it in a bit too informal way). I'll answers in bullets below.

* The `on_rw` callback is invoked every time the instance changes its state from RO to RW and *also* if the schema version is changed in the RW state. We can consider it as a 'you possibly want to perform some DDL' notification.
* We can add `on_ro`. I didn't mention it explicitly in the initial proposal, but I'm sure that there is no problem to do so.
* A configuration may be taken from `on_rw` using `config:get()`. We can add a role config as a callback parameter as well.
* If configuration changes require DDL operations, I would call the same 'perform DDL if needed' role's function from `apply` and from `on_rw`. The function should be no-op if the instance is RO, if the schema version is less than needed, if current config doesn't mean that DDL is needed. I agree that it is not always possible to do just a runtime configuration in `apply` and just a database schema configuration (migration) in `on_rw`. Still much easier than without the new callback, because it reduces a need to create/drop watchers/triggers/fibers to writing a correct predicate that says when do a specific DDL.
* I don't think that the reverse order (`on_rw` before `apply`) will make things really simpler. It is possible that all the instances are started in RO, then one goes to RW. In this case the order will be `apply`, then `on_rw` anyway. If `apply` is guaranteed to be called before `on_rw`, we push role authors to make their code ready for this situation.
* Taking system schema version or a user defined schema version on an RO instance is actually not covered by this proposal. It becomes easier with the new `trigger` module, but still needs a knowledge about some specific tarantool details (on_replace, on_commit triggers and their constraints). It would be nice to cover it with some simple API too, but I've no such goal now.

It seems, that my proposal is not so terrible and it simplifies many usual scenarios for role authors. At least, it is proposed as a reaction to users' questions and review requests.

If you have a vision how to make easier to write this 'when I should do my DDL' code, I would like to read an alternative proposal.

If you mostly positive about my proposal, but see some flaws, I'm also open for a discussion.
