### ISSUE TITLE
Retain xlogs for anonymous replicas

### ISSUE THREAD

**Issue by drewdzzz** [tarantool/tarantool#10755]
WAL GC consumers are used for regular replicas to retain required xlogs, otherwise data needed by a replica that left behind too much would be deleted. Regarding anonymous replicas, the problem is not solved and such replica can easily receive a `XlogGapError` - let's use the consumers for anonymous replicas as well.

Also, since their number is unlimited and the new anonymous replicas can appear very often and disappear without any notification, we need some convenient ways to release their resources. Let's provide a new function that releases all resources occupied by a disconnected replica and let's release them automatically if we haven't heard from a replica for too long.

**Comment by d1rebear** [comment]
@Gerold103 @sergepetrenko Any chances it gets backported to 2.11.8 LTS?

**Comment by sergepetrenko** [comment]
@d1rebear, unfortunately, no. The feature also depends on persistent GC state (#10154), which brings a whole new system space `_gc_consumers`. We don't backport schema changes to older releases.

To workaround the issue you could make Tarantool always store closed xlogs for at least as long as it typically takes your anonymous replicas to reconnect.

If you have 2.11.8 enterprise edition, there is an `experimental_wal_retention_periood` configuration option, which makes Tarantool always keep older xlogs for as long as the option specifies. The full option description can be found in 3.x docs, it is named `wal.retention_period` there, but its description is correct for 2.11.8 and `experimental_wal_retention_period` as well: https://www.tarantool.io/en/doc/latest/reference/configuration/configuration_reference/#confval-wal.retention_period

If you use community edition, you could guarantee that xlogs are kept for at least M * N seconds by setting `checkpoint_count = M`, `checkpoint_interval = N`. But this is suboptimal, of course, because it'll require storing M checkpoints at all times.
