### ISSUE TITLE
net.box: an active connection is never garbage collected

### ISSUE THREAD

**Issue by kostja** [tarantool/tarantool#1138]
Since there are reader and writer workers, there are always references to a connection, from worker fibers, even if there are no other references. Thus the connection which is not closed is never garbage collected.
Maintain some sort of reference count and recheck from worker fibers once in a few seconds the reference count. If there are only references from worker fibers, exit the fibers (this will garbage collect the connection).

**Comment by mejedi** [comment]
Suggest splitting the object in two; the user will be holding reference to the 'facade', while the workers are referencing the 'backend'. Once the user releases the last reference, facade will be garbage collected eventually, killing the 'backend' in gc handler.

**Comment by kostja** [comment]
Affects Avito. Up.

**Comment by mejedi** [comment]
Posting a little design spec to outline the direction we are going with `net.box`.

We are doing the major refactoring/rewriting with the following goals in mind:
 * improve code structure making it more maintainable and approachable;
 * the design must allow for an active `net.box` to be GC-ed, implicitly closing the connection;
 * the performance is super import, it looks like the major source of overhead is fiber coordination; remove as much overhead as possible.

These goals are closely related, actually. To allow for GC, object graph must be carefully designed. If done carelessly, we will reproduce the situation we currently have at hands — a background fiber referencing the connection prevents GC. Abstraction layers and similar features of a *good design* should be treated with extreme caution to avoid performance degradation.

### 1. Extracting net_connector

Tarantool speaks 2 network protocols:
 1. `console` — textual protocol, human readable & writable (think telnet);
 2. `iproto` — binary protocol, DB queries + remote Lua code execution.

In both protocols server speaks first. The initial server message mentions the protocol being used. The initial server message is compatible between protocols, allowing to implement a protocol-oblivious client. For instance, a remote console can work on top of both protocols.

However, `iproto` is a much more feature reach protocol. Currently, console is implemented on top of the `net.box`. The later speaks both protocols, but unless the wire protocol is `iproto`, `net.box` is in the special degraded mode with all requests but `EVAL` failing.

We are extracting the basic connection facility into `net_connector` object. The later is responsible for establishing the connection, multiplexing simultaneous requests and parsing responses. The client API is relatively low level — a client obtains a send buffer with `begin_response()`. She renders the request in the buffer provided. Finally, the client invokes `wait_response()` obtaining a response.

```lua
m = net_connector('<url>', { <options> } )
status, buf, id = m.begin_request(timeout);
if (status) then
  format_request(buf, id, 'SELECT', ...)
  return m.wait_response(id, timeout)
end
```

The connector performs implicit close on GC. In the absence of user references it will be eventually collected.

Both remote console and `net.box` builds on top of `net_connector`.

### 2. The Internals of net_connector
The connector employs a single background fiber. The later executes the following procedure:
  1. connect;
  2. read handshake;
  3. invoke the protocol-specific procedure.

The `iproto` procedure goes as follows:
 1. do auth;
 2. repeatedly extract a response, and dispatch it to the matching fiber;
 3. (while waiting for a response, send buffered outgoing data;)
 4. (if result code indicates an outdated schema, run update-schema procedure.)

The programming model is as follows:
 * There is a socket, plus a send buffer plus a receive buffer.
 * The background fiber is responsible for moving data between the socket and buffers.
 * The task is accomplished with `send_and_recv()` primitive: *flush `send_buf` and put incoming data in `recv_buffer` until either N bytes are available or a boundary string is encountered*.
 * Protocol-specific routines `recv_console_response()` and `recv_iproto_response()` are built on top of the `send_and_recv()` primitive.
 * The background fiber has direct access to both buffers.
 * User obtains `send_buf` form `begin_request()` method. It is mandatory to begin a request with `begin_request()`. The method waits if requests aren't processed in the current state or if `send_buffer` usage exceeds a limit.

**Comment by mejedi** [comment]
Preliminary results arrived: **15%**  to **20%** performance improvement!

### 1M pings in 10K concurrent fibers (-20%):

This one measures the overhead of fibers coordination and exchanging requests and responses. The messages themselves are very small.

```
$ time ./tarantool benchmark_new_net.lua
real    0m2.288s
user    0m2.127s
sys     0m0.065s
```

```
$ time ./tarantool benchmark_old_net.lua
real    0m2.899s
user    0m2.793s
sys     0m0.092s
```


### 100K selects in 1K concurrent fibers (-15%):

Performing the *real* requests here! Each result is ~700 bytes, expanding into ~250 objects on 3 nesting levels.

```
$ time ./tarantool benchmark_new_net.lua

real    0m1.877s
user    0m1.749s
sys     0m0.056s
```

```
$ time ./tarantool benchmark_old_net.lua
real    0m2.193s
user    0m2.109s
sys     0m0.084s
```

### What Did the Profiler Say?

`PING` results were hardly surprising. However in the second test we were expecting to see little to no difference since the major time is spent performing msgpack serialisation. Check out the flame graphs:

https://www.dropbox.com/s/h6bz1tw8avm73lu/new_box.svg?dl=0
https://www.dropbox.com/s/zsqlolc771xeuxv/old_box.svg?dl=0

It appears that msgpack serialisation indeed takes up to 80% time.

However there is the important difference: the `lj_tab_newkey` stack that is responsible for more then 8% running time in the current implementation is virtually missing from the new implementation's flame graph!

It appears that `SELECT` has a significantly higher latency then `PING`, hence more fibers are waiting for a response simultaneously. In the current implementation there are ~10 insert operations involving a hash table sized proportional to the number of waiting fibers, per requests (`lj_tab_newkey`).

The new implementation performs only 2 inserts per request.
