### ISSUE TITLE
Stacked diagnostics area in fiber

### ISSUE THREAD

**Issue by rtsisyk** [tarantool/tarantool#1148]
Add support for multiple errors in `struct diag`. Accumulate all occurred errors during processing a request in `struct diag`.

**Comment by rtsisyk** [comment]
refactoring, rolling feature => 1.7.3

**Comment by pgulutzan** [comment]
I comment here about why at some time Tarantool should support warnings with SQL.
Suppose one says SELECT AVG(s1) FROM t; and table t has NULLs in column s1.
The standard says
"
If one or more null values are eliminated,
then a completion condition is raised:
warning — null value eliminated in set function.
"
I mentioned this in issue#2364
SQL clauses related to groups and aggregates
https://github.com/tarantool/tarantool/issues/2364
and that was closed, with Kirill Shcherbatov
saying that other DBMSs don't do it. Quoting him:
"
MySQL - no warning
Oracle - no warning
Postgres - no warning
SQLite - no warning
MSSqlServer - no warning
"
Actually SQL Server does have a warning but it
can be missed if warnings are not enabled
https://docs.microsoft.com/en-us/sql/t-sql/statements/set-ansi-warnings-transact-sql?view=sql-server-2017
Also DB2 has a warning
https://www-01.ibm.com/support/docview.wss?uid=swg21285374
So I'd express it as "two of the big three DBMSs do it".
I realize, the real problem is that Tarantool cannot
do warnings. There are only 3 warning conditions that
the standard SQL/Foundation document mentions that
I think are relevant to what Tarantool might support soon:
* string data, right truncation (sometimes) >> * privilege not granted
* When null values are eliminated in set functions.
So, someday, Tarantool must support warnings.
Meanwhile in Tarantool's list of mandatory SQL-standard features
the E091 items could be marked as "not fully supported".
