### ISSUE TITLE
loop with snapshot_period

### ISSUE THREAD

**Issue by pgulutzan** [tarantool/tarantool#1218]
I have Ubuntu 12.04 and Tarantool-1.6.8 pulled from tarantool-1.6 source today.

I execute these requests:
"
box.cfg{}
box.schema.space.create('T2')
box.space.T2:create_index('primary')
box.cfg{snapshot_period=1}
"

I get this message:
"2015-12-18 10:46:55.851 [13692] main/104/snapshot_daemon [string "-- snapshot_daemon.lua (internal file)..."]:198 E> [string "-- snapshot_daemon.lua (internal file)..."]:68: variable 'snaps' is not declared"
The message repeats until I stop with control-C.

**Comment by rtsisyk** [comment]
https://github.com/tarantool/tarantool/blob/985d9fa05a094ad0601e5e869a35844f65daebcd/src/box/lua/snapshot_daemon.lua#L64 (one line above your fix) is also buggy.
What is about a test case?

**Comment by mejedi** [comment]
We already have a rather thorough test case. Why does it pass? Due to the sheer luck. Snapshot daemon failed due to undefined `snaps` global variable being accessed. Coincidently, the test defined `snaps` variable.

I feel the test is ok. We should check for this kind of errors in compile time, see #1234.

Shall we close the issue?

**Comment by rtsisyk** [comment]
OK, now it is clear for me.
