### ISSUE TITLE
Can't insert tuples with positive, but incorrect encoded primary keys.

### ISSUE THREAD

**Issue by mialinx** [tarantool/tarantool#1241]
Original issue: https://github.com/tarantool/go-tarantool/issues/9

Go implementation of MsgPack always encodes signed ints as negative values, even if they are positive:
msgpack.Marshal(int(128))  => d10080

So, tuples like []interface{}{ int(128), "Hello" }  can't be inserted.

**Comment by mialinx** [comment]
https://github.com/tarantool/tarantool/issues/1241 - ticket on server for supporting suboptimaly encoded ints.

**Comment by rtsisyk** [comment]
Temporary workaround is to use `msgpack.Marshal(uint(128))` instead of `msgpack.Marshal(128)`.

Possible solutions:

1. Download space formats from box.space._space and use on Go client for encoding (like we planned to fix Perl)
2. Implement universal numeric index (unsigned + signed + float) 
3. Rewrite tuples on the fly

**1.** is already needed at least for space names.
**2.** is a complex feature, but 1.6.x is feature frozen.
**3.** implies HUGE performance ovehead, although it is possible to replace typecodes in-place in some cases.

I discussed with @mialinx and he promised to take a look on https://github.com/tarantool/go-tarantool/issues/7 on NY weekends.

Superseded by https://github.com/tarantool/go-tarantool/issues/7
