### ISSUE TITLE
Eval-style marshalling in IPROTO_CALL  (1.7)

### ISSUE THREAD

**Issue by kostja** [tarantool/tarantool#1296]
Never wrap objects into arrays, or implicitly unwrap an array of tuples in 1.7.

This is a breaking change.

**Comment by rtsisyk** [comment]
+1

**Comment by rtsisyk** [comment]
All breaking changes should be done ASAP.

**Comment by rtsisyk** [comment]
Moved to 1.8.0 after discussion with @kostja

**Comment by rtsisyk** [comment]
1.7.2

**Comment by mejedi** [comment]
Re-opening for discussion.

The burning question is how to introduce new features in connectors while maintaining backwards compatibility. We should decide how to implement it in `net.box` and use it as a model for other connectors.

Basically we have three options:

 1. Leave `call` method as is, add `call_17` to request new marshalling for early adopters.
 2. Modify `call` to behave in 1.7 semantics, add `call_16` for back compat.
 3. Smart `call` behaving as `call_16`/`call_17` depending on the server version + `call_16` and `call_17`.

*Option 1* is conservative and doesn't break things.

*Option 2* may work but requires complex migration procedure which needs to be documented:

  * Tarantool team neads to implement `call_16` in 1.6 branch;
  * the latest 1.6 Tarantool is deployed;
  * application is updated to use `call_16` in place of `call`;
  * finally update Tarantool to 1.7.

*Option 3* doesn't work because of the scalars (`net.box` user has to write different code depending on the server version, even more broken code.)

Personally, I like *option 1* most. We could do *option 2* but we should update connectors first for consistency and that's hard to do in a timely fashion because of the connectors maintained by the community.

**Comment by mejedi** [comment]
Summing up discussion with @kostja:

 * Call semantics (1.6 vs 1.7) is defined in connect options and is independent of the actual server version.
 * Default is 1.7.
 * Connectors must implement similar option, starting with Python. Consistency matters!
 * Migration procedure will be included in the docs.

Once the interested parties agree on this, I am updating the linked tickets and creating one in docs.

**Comment by rtsisyk** [comment]
>Call semantics (1.6 vs 1.7) is defined in connect options and is independent of the actual server version.
> Default is 1.7.

Why don't use 1.6 for 1.6 server by default?

**Comment by mejedi** [comment]
> Why don't use 1.6 for 1.6 server by default?

Because it's more complex and adds non-determinism.
