### ISSUE TITLE
Ubuntu /etc/init.d/ script problem

### ISSUE THREAD

**Issue by Nickmob** [tarantool/tarantool#1390]
If I delete one of instances in /etc/tarantool/instances.available and then stop service tarantool, I get tarantool up and running using old configuration (deleted instances).
I expect 'service tarantool stop' command should stop all the instances.

**Comment by rtsisyk** [comment]
/etc/tarantool/instances.enabled is the only registry of instances used by sysvinit script.
In other words, there is no magic under the hood.  Please stop an instance first and then remove it from /etc.

This behaviour is fixed in systemd configuration (centos 7, fedora, Debian/Ubuntu is coming soon), because systemd tracks started instances somewhere in its internals.
I don't think that a fix of this problem for sysvinit is really important for the project. Sorry.
