### ISSUE TITLE
upsert syntax

### ISSUE THREAD

**Issue by pgulutzan** [tarantool/tarantool#1400]
I have Ubuntu 12.04 and Tarantool 1.6, pulled from source today.

For upsert, I must enclose one-part keys in braces.
This is a difference between update syntax and upsert syntax.

For example:

tarantool> box.space.tester:update(1,{{'=',2,'B'}})
---
- [1, 'B']
...

tarantool> box.space.tester:upsert(1,{{'=',2,'B'}})
---
- error: Usage index:upsert(tuple_key, ops)
...

So I  have to say
box.space.tester:upsert({1},{{'=',2,'B'}})

**Comment by rtsisyk** [comment]
`:upsert()` requires a **tuple** as the first argument, `:update()` requires a **key**.
Actually key is also tuple(=array), but Lua bindings automatically wrap scalars to one-element array for convenience, i.e. `box.space.tester:update(1,{{'=',2,'B'}})`  is equivalent to `box.space.tester:update({1},{{'=',2,'B'}})`.

I don't think that wrapping scalars to one-element tuples for `:upsert()` and `:replace()` is very useful and needed for any real cases.

**Comment by kostja** [comment]
Roman, I thought it's easy to do so we could just do it.

**Comment by rtsisyk** [comment]
@kostja  do you think that `box.space.tester:upsert(1 <!-- scalar,{{'=',2,'B'}})` actually makes sense?

**Comment by kostja** [comment]
Now that I think of it, no, it doesn't. We expect a tuple, not a key, and in no context in which we expect a tuple we accept a scalar. So I think we should stress the difference in the docs, rather than accept a scalar. If we do accept a scalar in this context, we may be tempted to add this feature to other places which now expect a tuple and fail on a simple scalar.
