### ISSUE TITLE
Can't resave snapshot after snapshot file deletion

### ISSUE THREAD

**Issue by Boiler** [tarantool/tarantool#1433]
Tarantool 1.6.8-611-g944d005

Steps to reproduce:
1. box.snapshot()
2. Delete last snapshot file
3. box.snapshot()
`error: can't save snapshot, errno 17 (File exists)`

but file doesn't exists

**Comment by kostja** [comment]
The logic of this error is that there is a checkpoint inside Sophia engine, which still exists even after you delete the snapshot file, which represents the checkpoints of the memtx engine.
I agree this is not good design, and check with Dmitry what can be done about it. We're changing the way sophia checkpointing works in 1.7. Does this problem affect production use? If not, it'll be fixed in 1.7 only.

**Comment by Boiler** [comment]
Yes, this problem affect production use, because we run the risk of losing data.

**Comment by kostja** [comment]
Fixed in 1.6.8-618-g39df8a9

**Comment by Boiler** [comment]
It works! Thanks.
