### ISSUE TITLE
Have you considered supporting lua 5.3 version?

### ISSUE THREAD

**Issue by kinbei** [tarantool/tarantool#1486]
Have you considered supporting lua 5.3 version?

**Comment by bigbes** [comment]
We have deep integration with LuaJIT, so it'll be problematically to use PUC-Rio Lua, instead.

**Comment by kinbei** [comment]
LuaJIT is compatible to the Lua 5.1 language standard and Lua 5.1 does not support 64 bit integers.

**Comment by bigbes** [comment]
I don't understand the problem, sorry

**Comment by aleclarson** [comment]
Here's what Tarantool is missing since it uses Lua 5.1 instead of 5.3:
# Lua 5.3

### Main changes
- integers (64-bit by default)
- official support for 32-bit numbers
- bitwise operators
- basic utf-8 support
- functions for packing and unpacking values

### Language
- userdata can have any Lua value as uservalue
- floor division
- more flexible rules for some metamethods

### Libraries
- ipairs and the table library respect metamethods
- strip option in string.dump
- table library respects metamethods
- new function table.move
- new function string.pack
- new function string.unpack
- new function string.packsize

### C API
- simpler API for continuation functions in C
- lua_gettable and similar functions return type of resulted value
- strip option in lua_dump
- new function: lua_geti
- new function: lua_seti
- new function: lua_isyieldable
- new function: lua_numbertointeger
- new function: lua_rotate
- new function: lua_stringtonumber

### Lua standalone interpreter
- can be used as calculator; no need to prefix with '='
- arg table available to all code

# Lua 5.2

### Main changes
- yieldable pcall and metamethods
- new lexical scheme for globals
- ephemeron tables
- new library for bitwise operations
- light C functions
- emergency garbage collector
- goto statement
- finalizers for tables

### Language
- no more fenv for threads or functions
- tables honor the __len metamethod
- hex and \z escapes in strings
- support for hexadecimal floats
- order metamethods work for different types
- no more verification of opcode consistency
- hook event "tail return" replaced by "tail call"
- empty statement
- break statement may appear in the middle of a block

### Libraries
- arguments for function called through xpcall
- optional 'mode' argument to load and loadfile (to control binary x text)
- optional 'env' argument to load and loadfile (environment for loaded chunk)
- loadlib may load libraries with global names (RTLD_GLOBAL)
- new function package.searchpath
- modules receive their paths when loaded
- optional base in math.log
- optional separator in string.rep
- file:write returns file
- closing a pipe returns exit status
- os.exit may close state
- new metamethods __pairs and __ipairs
- new option 'isrunning' for collectgarbage and lua_gc
- frontier patterns
- \0 in patterns
- new option *L for io.read
- options for io.lines
- debug.getlocal can access function varargs

### C API
- main thread predefined in the registry
- new functions lua_absindex, lua_arith, lua_compare, lua_copy, lua_len, lua_rawgetp, lua_rawsetp, lua_upvalueid, lua_upvaluejoin, lua_version.
- new functions luaL_checkversion, luaL_setmetatable, luaL_testudata, luaL_tolstring.
- lua_pushstring and pushlstring return string
- nparams and isvararg available in debug API
- new lua_Unsigned

### Implementation
- max constants per function raised to 226
- generational mode for garbage collection (experimental)
- NaN trick (experimental)
- internal (immutable) version of ctypes
- simpler implementation for string buffers
- parser uses much less C-stack space (no more auto arrays)
- Lua standalone interpreter
- new -E option to avoid environment variables
- handling of non-string error messages

**Comment by kokizzu** [comment]
until LuaJIT support 5.3 i don't think it can be done
