### ISSUE TITLE
vinyl: upsert succeeds despite field_count violation

### ISSUE THREAD

**Issue by pgulutzan** [tarantool/tarantool#1622]
I have Ubuntu 14.04 and Tarantool 1.7 pulled from source today.
I execute these requests:
"
box.schema.space.create('vinyl',{engine='vinyl',field_count=1})
box.space.vinyl:create_index('p')
box.space.vinyl:insert{1}
box.space.vinyl:upsert({1},{{'=',2,5}})
"
Now there are two fields in the tuple.
This does not happen if engine=memtx'.

**Comment by rtsisyk** [comment]
Good catch.

**Comment by rtsisyk** [comment]
See also #1069

**Comment by rtsisyk** [comment]
@pgulutzan, we've failed to fix this problem in the simple way. I move this ticket to 1.7.3.

**Comment by Gerold103** [comment]
Assume, that there is a sequence of UPSERTs of the same key. And in the middle of the sequence one UPSERT is incorrect. What to do with the newer UPSERTs?
- Drop all the newer UPSERTs. Then the user must explicitly REPLACE or DELETE the key to fix the error.
- Skip only invalid UPSERT. This way seems to be unrealizable. Such sequence of UPSERTs can be merged in one UPSERT during compaction or dump, and it is impossible to split the merged UPSERTs back to delete only one invalid UPSERT.

**Comment by Gerold103** [comment]
Need some research. The main idea - if the UPSERT is broken and it had been commited, possibly the best solution is to discard all newer UPSERTs, including from newer transactions, until REPLACE/DELETE is commited.

The main problem is how to report this problem. We cannot report for each newer upsert the error, because upserts RPS can be very big and the log size would grow very fast.

Need more time to think about.

**Comment by kostja** [comment]
We need a way to mark an upsert which we failed to apply: this is also necessary for gh-1947, and store this information persistently. I think we should first fix gh-1947 then return to this bug in the light of the fix.
