### ISSUE TITLE
Vinyl: too many runs in range

### ISSUE THREAD

**Issue by alyapunov** [tarantool/tarantool#1816]
Running an issue:

```
#!/usr/bin/env ../src/tarantool

box.cfg {
    wal_mode = 'write',
    vinyl = {
        memory_limit = 0.5;
        range_size = 10 * 64;
        page_size = 10;
    }
}

s = box.schema.create_space('test', { engine = 'vinyl', id = 512, if_not_exists = true })
i = s:create_index('test', { type = 'TREE', parts = {1, 'scalar'}, if_not_exists = true })

for k = 1,5 do
    for i=1,1000 do s:upsert({i, 1}, {{'+', 2, 1}}) end

    print(k, 'range_count', box.info.vinyl().db['' .. s.id .. '/0'].range_count)
    print(k, 'run_count', box.info.vinyl().db['' .. s.id .. '/0'].run_count)
end

os.exit(0)
```

I got the results:

```
1   range_count 1
1   run_count   16
2   range_count 1
2   run_count   30
3   range_count 1
3   run_count   53
4   range_count 1
4   run_count   78
5   range_count 1
5   run_count   95
```

There are TOO many runs is one range

**Comment by alyapunov** [comment]
It's strange, but with cfg {wal_mode = 'none'...} I got run_count = 0

**Comment by locker** [comment]
It seems that the problem occurs, because (1) dump task has a higher prio than compact and (2) there's a strict limit on the size of a range's in-memory index - cfg.vinyl.range_size. The Lua script inserts new statements so quickly that dump doesn't catch up and so there's always a range to dump. As a result, we never call compact and hence have the number of ranges growing without bounds.

Per se, prioritizing dump over compact looks reasonable to me, because if we don't offload in-memory data in time, we will get throttled hitting the quota hard. However, I find the cfg.vinyl.range_size limit to be artificial and unnecessary. I think we should get rid of it and schedule dump only on global quota shortage (or checkpoint). If there's no risk of hitting the quota, it should be up to compact to decide when a range's in-memory index should be dumped (by compacting it with one or more on-disk runs). For example, it might be worth scheduling compaction of a range if its in-memory index is as big as the smallest run on disk. That said, this problem is sort of tied to the multi-level design.

It should also be noted that just removing cfg.vinyl.range_size limitation wouldn't be enough, because if the client is so fast that it manages to consume the global quota before a range is dumped, then we would face the exactly same problem. To avoid that, we should throttle the client when dump doesn't catch up.

**Comment by rtsisyk** [comment]
range_size is being removing, there is a patch to set it 16Gb.

**Comment by kostja** [comment]
range_size should be ignored when considering time to dump. It is ignored already. Other than that, we should set a hard lower limit on range size to 16MB.

**Comment by alyapunov** [comment]
Is not reproducible now, must be closed
```
1	range_count	1
1	run_count	0
2	range_count	1
2	run_count	0
3	range_count	1
3	run_count	0
4	range_count	1
4	run_count	0
5	range_count	1
5	run_count	0
```
