### ISSUE TITLE
vinyl: double delete aborts upsert+select transaction

### ISSUE THREAD

**Issue by alyapunov** [tarantool/tarantool#1944]
```
s = box.schema.create_space('test', { engine = 'vinyl', id = 512, if_not_exists = true })
i = s:create_index('test1', { type = 'TREE', parts = {1, 'uint'}, if_not_exists = true })

s:delete{1}
c1 = txn_proxy.new()
c1:begin()
c1('s:upsert({1}, {{"=", 2, 42}})')
c1('s:select{1}')
s:delete{1}
result = c1:commit()
print(result[1].error)
```

**Comment by alyapunov** [comment]
After fix it will be possible to remove ignore_unnecessary_conflict1 branches in vinyl/tx_conflict.test.lua

**Comment by locker** [comment]
This is an inherent difference between memtx and vinyl transaction managers:
- In memtx, we track reads right in indexes, because an index is stored completely in memory. So if `select{key}` reads nothing, we don't track the read, and so `delete{key}` won't abort the transaction.
- In vinyl, we maintain a separate range index for tracking reads, because indexes are stored on disk. When we delete a key, we don't know if it exists so we just abort all transactions that could possibly read the key, directly or in a range.

Fixing the issue in vinyl could result in performance degradation or increased memory consumption so we won't fix it. I filed a ticket to document this difference in transaction handling: https://github.com/tarantool/doc/issues/2977
