### ISSUE TITLE
Package manager based on LuaRocks

### ISSUE THREAD

**Issue by rtsisyk** [tarantool/tarantool#2067]
I propose to re-pack [LuaRocks](https://github.com/luarocks/luarocks) to create a minimal viable package manager for Tarantool: 

* `tarantoolpm install module` - install a module
* `tarantoolpm search module` - search for modules
* `tarantoolpm remove module` - remove installed module
* `tarantoolpm list` -  list currently installed modules

This package manager can be included into base package (`tarantool`) to be available on all supported platforms out of the box. 

The main differences between upstream LuaRocks and our tarantoolpm are:

 * `tarantoolpm` uses /usr/bin/tarantool as Lua intepreter instead of /usr/bin/lua-5.x
 * `tarantoolpm` install modules to /usr/share/tarantool and /usr/lib*/tarantool instead of /usr/share/lua/5.x and /usr/lib*/5.x
 * `tarantoolpm` has pre-configured https://rocks.tarantool.org/ repository by default instead of luarocks.org <sup>[1](#repository)</sup>
* `tarantoolpm` provides a preinstalled stub rock `tarantool` to handle dependencies on tarantool versions

In other words, `tarantoolpm` works out of the box for Tarantools users, whereas upstream `luarocks` is for lua-5.x users. 

Please note that we are not going to fork a LuaRocks. LuaRocks is the great product which can be customized in various way and has flexible configuration options. Probably we can completely avoid changes into luarocks repository and do all work in tarantool/tarantool repo.

## IMPLEMENTATION NOTES

1. Update our copy of LuaRocks in  [tarantool/tarantoolpm](https://github.com/tarantool/luarocks) from  [luarocks/luarocks](https://github.com/luarocks/luarocks) and add it as a submodule to [tarantool/tarantool](https://github.com/tarantool/tarantool). According to our policy all submodules of tarnatool must have a copy in `tarantool/` organization just to be safe.

2. Copy the main script `luarocks` to tarantool/extra, rename to `tarantoolpm" and remove all command line options except "install", "remove", "search", "uninstall":

```
#!/usr/bin/tarantool

local cfg = require("luarocks.cfg")
local loader = require("luarocks.loader")
local command_line = require("luarocks.command_line")
program_description = "Tarantool Package Manager"

commands = {
   help = "luarocks.help",
   install = "luarocks.install",
   search = "luarocks.search",
   list = "luarocks.list",
   remove = "luarocks.remove",
}

command_line.run_command(...)
```

3. Patch CMakeLists in Tarantool to generate suitable site_config.lua as described above.

4. Install `tarantoolpm` to $PREFIX/bin and luarocks sources to $PREFIX/share/tarantool/luarocks

5.  Install `tarantool-version.rockspec` stub into /var/lib/tarantoolpm/ to allow "dependencies { tarantool = "1.7.4" }

6. Ensure that `tarantoolpm` doesn't share common directories and doesn't have conflicts with upstream luarocks.

7. Add simple test cases to `app/` suite (install/remove/list using a local repository).

8. Open ticket in `tarantool/doc`

9. ???

10. PROFIT

<a name="myfootnote1">1</a>: we can redirect rocks.tarantool.org to "tarantool" when https://github.com/luarocks/luarocks-site/issues/57 will be implemented.

**Comment by bigbes** [comment]
We may override [`loader`](https://github.com/luarocks/luarocks/blob/master/src/luarocks/loader.lua) with our custom.
Every command accepts `flags`, that contains `rock-trees`, for example (https://github.com/luarocks/luarocks/blob/master/src/luarocks/config_cmd.lua).
For example [`install`](https://github.com/luarocks/luarocks/blob/master/src/luarocks/install.lua#L150) accepts `flags`, `name`, `version`. I've described `flags` before (command line arguments), `name` is name of a rock, `version` is a rock version.

**Comment by bigbes** [comment]
Also, `site_config.lua` can be overrided using [`cfg`](https://github.com/luarocks/luarocks/blob/ba1ba4be6e0ecc6936c49fae38c71e22250ceb65/src/luarocks/install.lua#L14) module

**Comment by bigbes** [comment]
We can use `tarantoolctl` as one entry point:
```
tarantoolctl rock install
tarantoolctl rock search
...
```
We should be able to maintain local instances by using `.tarantoolctl` configuration. If started using tarantoolctl we can use local `LUA_PATH/LUA_CPATH`.

**Comment by rtsisyk** [comment]
I'd also like to enable --local by default for non-root users.

**Comment by hishamhm** [comment]
Since it's not a fork, it would be really nice (and less confusing for your users) if you didn't rename it completely. A name like `luarocks-tarantool` or `tarantool-luarocks` (tab-completion for the win :) ) would make it clearer for users what is it that they're using. After all, they will have to go to the LuaRocks documentation to read about writing rockspecs, etc.

Users seeing `tarantoolpm` will think that this is a further fragmentation of the package manager ecosystem, just like recently happened with OpenResty's `opm`. :-(

Also, I'm not sure if there are significant advantages in stripping the main script down. You'll have greater documentation overhead and users will lose useful features (like `luarocks doc` and `luarocks show`). If you say "it's just vanilla `luarocks` configured to use the tarantool paths" you'll be able to point users to the LuaRocks documentation as-is. I would really just use a wrapper with a custom config. It will make maintenance and packaging easier for you. No worries to keep the code in sync: note that the modules used by the main `luarocks` script are _not_ a public API.

> Install tarantool-version.rockspec stub into /var/lib/tarantoolpm/ to allow "dependencies { tarantool = "1.7.4" }

This is not necessary. You can enter `rocks_provided = { tarantool = "1.7.4" }` in the config file and it will behave as such. :)

But overall, I think the idea of shipping an instance of LuaRocks configured for the tarantool specificities is in the right direction! 👍

**Comment by rtsisyk** [comment]
Thanks for your feedback, @hishamhm! Appreciate your input.

I spent couple hours discussing this proposal with our users. Some of them have already re-invented the wheel with their homegrown package managers based on LuaRocks. 

Here is the final plan for the first stage of this ticket:

* LuaRocks will be integrated into `tarantoolctl` tool and shipped with the main tarantool package:
  -  `tarantoolctl rock install`
  -  `tarantoolctl rock remove`
  -  `tarantoolctl rock search`
  -  `tarantoolctl rock list`
* `tarantoolctl rock install <name>` will install modules into `${PWD}/.rocks` directory, similar to `node_modules` in **npm** and `vendor/bundles` in **gem**. 
* `tarantool` will have `./.rocks/` in `package.path`/`package.cpath` by default.

**Comment by hishamhm** [comment]
@rtsisyk Ah, that sounds like a very interesting approach! I like it!

Note that we don't really provide a stable API for LuaRocks internals other than the command-line, so bundling an internal copy of LuaRocks and launching it via `os.execute` is the safest bet, while we don't have a library API. We do want to have a library API eventually, but running `luarocks` command is not a performance-critical operation anyway, so the `os.execute` approach should be enough at least as a first approach. If you do decide to plug into LuaRocks internals directly, well, you're free to do so of course, but since we don't have a public API I thought it would be responsible of me to say so. :)

**Comment by rtsisyk** [comment]
1.7.4-294-g54d06d7bf

    Usage:
    
        tarantoolctl rocks install ROCK - install a rock
        tarantoolctl rocks remove ROCK - remove a rock
        tarantoolctl rocks show ROCK - show information about an installed rock
        tarantoolctl rocks search PATTERN - search repository for rocks
        tarantoolctl rocks list - list all installed rocks

 All rocks are installed to ${PWD}/.rocks directory to support separate rocks trees per project, as proposed by #2067. Rockspec can use "tarantool >= 1.7.x" inside dependencies = {} block to depend on a specific Tarantool version.  See 9e7c421758af156d19a66cebf713e24b42d8654b for details.

**Comment by rtsisyk** [comment]
1.7.4-294-g54d06d7bf
1.8.1-384-g39584f59e
