### ISSUE TITLE
[the second step] Built-in tarantool-curl

### ISSUE THREAD

**Issue by dedok** [tarantool/tarantool#2107]
https://github.com/tarantool/tarantool/issues/2083 - brings tarantool-curl into Tarantool.

the second step is:

1) The code style of the new module have to be compatible with the tarantool code style.
2) https://github.com/tarantool/curl/blob/master/curl/init.lua#L165 - The busy loop have to be removed. It should be used 'condition variable' for syncing states between C API and Lua API.
3) Lua's callback have to be replaced by C callbacks. That means that user will not have an access to callbacks.
4) The built-in tarantool curl should have Lua and C APIs to make http requests.

**Comment by rtsisyk** [comment]
- Amalgamate all *.c source files into one
- Remove all typedefs and add "curl_" prefix to all names
- Add ipc_cond to `struct curl_request`
- Remove lua_ctx  from `struct curl_request`
- In function check_multi_info() instead of calling lua_ctx->done_fn call ipc_cond_wakeup(request->cond);
-  In function `async_request` remove handling of "read", "write", "done" arguments
-  In function `async_request` add ipc_cond_wait() and then push `response` object onto Lua stack after the following code:

```
CURLMcode rc = request_start(r, &req_args);
    if (rc != CURLM_OK)
        goto error_exit;
```

- Rename async_request() into luaT_curl_request()
- Inline request_pool_get_request() code into new_request()
- Remove request pool.
- Use luaT_curl_request() from Lua code
- Remove sync_request/async_request from Lua code
- Remove all callbacks from  Lua code

**Comment by dedok** [comment]
@rtsisyk I agree with all you have gave good details for 1-4 points except 'request pool' - we will not remove request pool.

**Comment by rtsisyk** [comment]
I think this ticket duplicates #2083. Let's move to #2083.
