### ISSUE TITLE
Support collations using ICU library

### ISSUE THREAD

**Issue by kyukhin** [tarantool/tarantool#2121]
It'd be great to have `COLLATE` using ICU in upcoming release.
But looks like `UPPER()` and `LOWER()` is enough

Here's what we need to do:
* Check that license is OKay
* Check other DBMS: Postgres, MySql etc. to understand what are they using
* Evaluate performance and hence found some benchmarks first
* Evaluate best approach for ICU integration into Tarantool's source base. Git submodule is OK?

>Currently these functions are only working for ASCII, so
lower('Я') = upper('Я'), which is rather nasty
(by the way I see that the character set is always
assumed to be UTF-8, which is okay for now).
So here's why it's urgent ...
SQLite allows for an ICU extension, via the
compile-time option SQLITE_ENABLE_ICU.
If the ICU extension is brought in,
then lower() and upper() should work for Cyrillic
-- but they didn't work without ICU, so
it's a behaviour change.
Perhaps SQLite didn't include ICU because of
the licence -- see
http://site.icu-project.org/ and
http://icu-project.org/repos/icu/icu/trunk/LICENSE
re licence.
But it's superseded, since May 2016 ICU is a
Unicode Technical Committee, see
http://site.icu-project.org/
so either licence might be used.
Perhaps they're incompatible with public domain
but compatible with BSD.
A second reason to avoid ICU is size.
I think that's a silly reason.
A third reason is fear that ICU will change.
Actually, though, that's a reason that one must
include a frozen version within Tarantool.
Besides, future change mostly affects obscure
languages.
So ICU should be in the alpha and not optional.
Notice I'm not saying COLLATE should exist and
should be used -- that can happen later.
Only UPPER() and LOWER() must use it.
And the procedure for object-name case-sensitive search.

**Comment by kyukhin** [comment]
SQLite collations only support ASCII [1].
However it contains ICU extension [2, 3].

[1] - http://www.sqlite.org/datatype3.html#collation
[2] - https://www.sqlite.org/faq.html#q18
[3] - https://www.sqlite.org/src/artifact?ci=trunk&filename=ext/icu/README.txt

**Comment by pgulutzan** [comment]
In regard to the suggestion above "Check other DBMS", I recently wrote a blog post which answers part of the question. http://ocelot.ca/blog/blog/2017/04/11/mysql-mariadb-international-components-for-unicode/

**Comment by pgulutzan** [comment]
Summary of work involved:
* Get confirmation from a developer that building
with SQLITE_ENABLE_ICU does not break builds or tests.
* Get confirmation from a legal expert that the licence
doesn't present a problem.
* Get confirmation from someone experienced with
negotiating with distro makers that it would be okay
to provide a frozen ICU copy with Tarantool instead of
use the distro's ICU copy -- and if not, allow for
extra work whenever a new ICU version appears.
* Get confirmation from a manager that it will be
okay to increase the size of a Tarantool download
by perhaps 15MB.
* Get confirmation from a benchmark tester that
ICU claims about speed (relative to strcoll) are
correct as applicable to a sample Tarantool database.
* Get confirmation from a PostgreSQL expert that their
experience with the recent ICU switch is not smooth.
* Support UPPER(), LOWER(),
comparisons of identifiers with system tables
(see also Issue#2295 Properly encode UTF strings in system table),
and validity tests that characters are valid UTF-8 byte sequences
(see https://en.wikipedia.org/wiki/UTF-8#Invalid_byte_sequences).
But not new collations, UCS_BASIC ("binary") is okay.
There is an assumption that BINARY and CHAR are not
the same data type.

**Comment by kyukhin** [comment]
Blocked by #2649

**Comment by kyukhin** [comment]
Note blocked anymore.
