### ISSUE TITLE
Increase identifier maximal length.

### ISSUE THREAD

**Issue by kyukhin** [tarantool/tarantool#2127]
Right now maximal length of space is 32. Need to increase it.

>Okay, box.schema.NAME_MAX is 32.
But automatically-created indexes have names that
include the space name, and the maximum is in
bytes not characters, so I can't easily create a
table with a 13-character Cyrillic name. Example:
"
tarantool> ocelot_conn:execute('create table ИИИИИИИИИИИИИ (s1 int, primary key (s1))')
2016-09-08 18:59:34.309 [4571] main/101/interactive key_def.cc:156 E> ER_MODIFY_INDEX: Can't create or modify index 'a_ind_ИИИИИИИИИИИИИ_1' in space 'ИИИИИИИИИИИИИ': index name is too long
"
In standard SQL and DB2 the usual maximum is 128.
In most DBMSs the maximum is something smaller.

**Comment by kyukhin** [comment]
Right now:
```
tarantool> box.schema.NAME_MAX
---
- 64
...
```

So, I suppose 64 is good enough for 1.8.0. Rescheduling the issue to 1.8.1

**Comment by kostja** [comment]
We need to make sure that space name is effecitvely unlimited (i.e. is a dynamic string). We need to store SQL in system spaces and space cache anyway, so space_def, as well as index_def becomes a non-copyable object. The only way to ensure that there are no memory leaks is to remove OPT_STR (static size buffers) altogether, and make sure all space and index buffers are dynamic. Setting as top priority since it's a refactoring.

**Comment by kyukhin** [comment]
Resolution of #944 should solve this issue.

We need to make sure that issue is solved and prepare tests
which verify this.
