### ISSUE TITLE
`with` clause in `UPDATE` statement does not work

### ISSUE THREAD

**Issue by kyukhin** [tarantool/tarantool#2177]
WITH ... UPDATE does not work.
box.sql.execute("CREATE TABLE te43 (s1 INT PRIMARY KEY, s2 INT);")
box.sql.execute("INSERT INTO te43 VALUES (1, 2);")
box.sql.execute("INSERT INTO te43 VALUES (2, 1);")
box.sql.execute("WITH te44 AS (SELECT * FROM te43) UPDATE te44 SET s2 = s2 + 10;")
Result = error: 'no such table: te44'

**Comment by pgulutzan** [comment]
WITH ... UPDATE does not work.
box.sql.execute("CREATE TABLE te43 (s1 INT PRIMARY KEY, s2 INT);")
box.sql.execute("INSERT INTO te43 VALUES (1, 2);")
box.sql.execute("INSERT INTO te43 VALUES (2, 1);")
box.sql.execute("WITH te44 AS (SELECT * FROM te43) UPDATE te44 SET s2 = s2 + 10;")
Result = error: 'no such table: te44'

**Comment by iproha94** [comment]
The query 
```WITH te44 AS (SELECT * FROM te43) UPDATE te44 SET s2 = s2 + 10;```
should not work as it is not logical to update the temporary table ```te44```.

There is an example of work ```WITH ... UPDATE```
```
CREATE TABLE te43 (s1 INT PRIMARY KEY, s2 INT);
INSERT INTO te43 VALUES (1, 1);
INSERT INTO te43 VALUES (2, 2);

CREATE TABLE  test1 (a  INT PRIMARY KEY, b INT);
INSERT INTO test1 VALUES(1, 10);
INSERT INTO test1 VALUES(2, 20);

WITH te44 AS (SELECT s1 FROM te43) UPDATE test1 SET b = 100 WHERE a IN (SELECT * FROM te44);
```

**Comment by kyukhin** [comment]
@pgulutzan, do you think that example provided in Ilya's comment proves feature is working (or semi-working)?

**Comment by pgulutzan** [comment]
This does not work:
CREATE VIEW te44 AS SELECT * FROM te43;
UPDATE te44 SET s2 = s1 + 10;
because views are not updatable in Tarantool.

I think this statement is similar:
WITH te44 AS (SELECT * FROM te43) UPDATE te44 SET s2 = s2 + 10;
therefore it is consistent that it does not work either.

It's not wonderful to create temporary tables for such cases, but it's not a bug.
I think that this bug report is based on a mistake that I made, I had forgotten that limitation.

**Comment by kyukhin** [comment]
So, this is not an issue and I am closing it, right @pgulutzan?
Same goes for #2177, #2173, #2171.

**Comment by kyukhin** [comment]
Closing then (and similar issues as well).
