### ISSUE TITLE
Expose pure msgpack from net.box

### ISSUE THREAD

**Issue by Sulverus** [tarantool/tarantool#2195]
To implement fast map/reduce using net.box we need to sort tuples without lua. So, we need expose pure msgpack. For example we can setup special flag in net.box.new() or somewhere else in net.box api.

**Comment by rtsisyk** [comment]
This feature is not "breaking change", but it needed for the customer  => 1.7.4

**Comment by rtsisyk** [comment]
### Proposal

1. Extend all requests with optional keyword arguments: 

```
conn.space:insert(tuple)  => :insert(tuple[, opts]) 
conn.space:replace(tuple) => :replace(tuple[, opts])
conn.space.name.index:get(key) => :get(key[, opts])
conn.space.name.index:select(key[, opts]) => no changes
conn.space.name.index:delete(key) => :delete(key[, opts])
conn.space.name.index:update(key, expr) => :update(key, expr[, opts])
conn.space.name.index:upsert(key[, expr]) => :upsert(key[[, expr], opts])
```


2. Add a new per-request option `buffer = <ibuf object>`:

```
conn.space.name.index:select(key, { buffer = <ibuf object> })
```

* If `buffer` option is set then net.box **skips** msgpack.decode() on xrow->body and **copies** (memcpy()) entire  xrow->body directly to `<ibuf object>`. The buffer **is not** truncated before copying. The number of written bytes is returned from :requestname() functions.  

* { buffer = nil } case is not changed and continues to return Lua tables as results.

* Error handling is not changed in both cases.

We already have unofficial internal bindings to `struct ibuf` - see `require('buffer')`.

Alternative: copy only xrow->body[IPROTO_DATA] instead of just entire xrow->body.

3. A follow up enhancement. Add `timeout` option to all requests and deprecate weird :timeout(): construction:

```
conn:timeout(<timeout>).space:insert(tuple) => conn.space.insert(tuple, { timeout = <timeout> }) 
```

### Reasonable

Raw MessagePack output is needed  to workaround buggy GC in LuaJIT. For example, space:select(key, { limit = 100000}) may create 100000 cdata objects and kill LuaJIT by finalizers limit.  

@Sulverus will be able to implement C function in [tarantool/shard](https://github.com/tarantool/shard) to merge multiple `<ibuf>` without producing Lua garbage.

### Pros

* This change is easy to implement and backward-compatible.

* This proposal doesn't violate encapsulation of net.box and doesn't require merging of tarantool/shard into net.box and vice versa. 

* I plan to extended `require('buffer')` as a replacement of slow Lua strings. For example, `buffer` can be used to implement encoding/decoding of `raw` types in MessagePack. `socket` module already supports `buffer` in some functions.

* `opts` can be used of other options in the future

### Cons

Current API of conn:call() and conn:eval() can't be extended with `opts` table:

```
conn:call(funcname, arg1, arg2, arg3, ...)
conn:eval(expr, arg1, arg2, arg3, ...) 
```

Possible solutions:

1. Don't extend call() and eval() with `opts` and ignore problem for now.  Obviously :timeout: can't be deprecated in this case.

2. Wrap arguments into Lua table (a breaking change):

```
conn:call(funcname, arg1, arg2, arg3, ...) => conn:call(funcname, {arg1, arg2, arg3, ... }[, opts]) 
conn:eval(expr, arg1, arg2, arg3, ...)  => conn:eval(expr, {arg1, arg2, arg3, ... }[, opts]) 
```

Please note that `net.box` already wraps `...` into `{...}` under the hood:

```
function remote_methods:call_16(func_name, ...)
    remote_check(self, 'call')
    return self:_request('call_16', tostring(func_name), {...})
end

function remote_methods:call(func_name, ...)
    remote_check(self, 'call')
    return unpack(self:_request('call_17', tostring(func_name), {...}))
end
```

`{...}` breaks JIT traces, but we already know that LuaJIT doesn't have real JIT.
ANyway, call(name, arg1, arg2, ...) is like very conventional syntax. Builtin `pcall()` has the same syntax.

3. The same as 2, but use existing `call_16` per-connection option to switch between old and new API:

```
net.box:connect(host, port, {call_16 = true}):call(funcname, arg1, arg2, ...)
net.box:connect(host, port):call(funcname, {arg1, arg2, ...}, opts)
```

We have already broken call() in 1.7.x, so call_16 is not big deal.

4. Add new functions:

```
conn:xcall(funcname, {arg1, arg2, arg3, ...}[, opts]) 
conn:xeval(expr, {arg1, arg2, arg3, ...}[, opts]))
```

I have no idea how to name these functions.

5. Put `opts` table as the first argument:

```
conn:call({ name = <funcname>, timeout = <timeout>, buffer = <buffer>}, arg1, arg2, arg3, ...) 
conn:eval({ expr = <expr>, timeout = <timeout>, buffer = <buffer>}, arg1, arg2, arg3, ...) 
```

6.  Discard the first part of my proposal and  continue in `:timeout:` style:

```
conn:opts({timeout = <timeout>, buffer = <buffer>}.space:select()
```

**Comment by Sulverus** [comment]
Interface (6) is looking good and is easy to understand(imho). Also in the future we'll be able to add more options.

**Comment by bigbes** [comment]
Interface (6) seems ok.

**Comment by rtsisyk** [comment]
@mejedi said that (4) is better than (6), but we need to find some better name than "call_ex".

**Comment by mejedi** [comment]
> @mejedi said that (4) is better than (6), but we need to find some better name than "call_ex".

I'd like to elaborate. I like @rtsisyk proposal for adding extendable options a lot. 

The downside of `:opts` and `:timeout` interface is implementation complexity and runtime overhead. The complexity is due to the fact that `:opts` and `:timeout` must be aware of each other. This interface resemble currying concept — i.e. given a function, create a new one taking fewer arguments. The new function invokes the original one, passing constants for missing arguments. Ex: `add_1 = curry(add, 1)`.

It's technically legal to have invocation like `:opt({A=1}):opts({B=2}):opts({C=3})`, with every subsequent `opts` creating a new context based on existing one.

Runtime overhead is due to the need to create a new object for each `:opts` and `:timeout` call.

<hr>

*A side note.* The current `:timeout` implementation is a mess. Timeout uses the global table keyed by the calling fiber. It would be reasonable to expect that `:timeout` sets a default timeout for any connection method. Once we did `c_t_1 = conn:timeout(1)`, the expectation is that `c_t_1:methodA()` will fail if it takes longer than 1 second to complete. No matter how `methodA` fared, the subsequent `c_t_1:methodB()` should still have 1 second timeout applied.

Actually, the timeout is 1 second minus `methodA` execution time! If `methodA` timed out, the timeout is cleared and `methodB` will never timeout even if it hangs forever!

Since the global table is keyed by the calling fiber, passing `c_t_1` to another fiber will clear the timeout.

*End side note.*

<hr>

If we were re-designing the API from scratch, I would suggest making every API call use named parameters (there's no such thing in Lua, hence a table.) That way, extending the API with new optional parameters in a consistent way would be easy.

The less radical approach would be retrofitting options table into existing API in a consistent fashion.

Since `call` and `eval` take variable number of arguments, I suggest adding new functions with the following signature:

```
func( options, name_or_code, param1, ... )
```

I.e. options go first!

There's another issue @rtsisyk didn't mention. Currently, `:select()` argument is optional. Adding options create an ambiguity: how to treat `:select()` with 1 argument?

**Comment by bigbes** [comment]
Troubles with current implementation shouldn't bother us in API redesign.
We can (and should) use `:opts` construction like these:

```
nb_object = net.box:connect('host:port')
nb_wrapper = nb_object:opts()
nb_wrapper:select(...)
nb_wrapper:insert(...)
```

> It's technically legal to have invocation like `:opt({A=1}):opts({B=2}):opts({C=3})`, with every subsequent opts creating a new context based on existing one.
> Runtime overhead is due to the need to create a new object for each :opts and :timeout call.

`opts` API has all this problems, but we can describe this overheads and show what is the "Right Way". Everyone who'll do differently will be "his own worst enemy".

BTW: subsequently opts may not be based on the existing ones.

PS: Desing of call-like functions `func( options, name_or_code, param1, ... )` leads to ambiguity (`select` and other requests uses different convention) and looks drearily since options (not only in lua) are located, usually, in the end of function signature (natural and well-established method of function declaration).

**Comment by rtsisyk** [comment]
> There's another issue @rtsisyk didn't mention. Currently, :select() argument is optional. Adding options create an ambiguity: how to treat :select() with 1 argument?

select(key) should be handled as select(key, {})

**Comment by rtsisyk** [comment]
> Troubles with current implementation shouldn't bother us in API redesign.
We can (and should) use :opts construction like these:
> ```
> nb_object = net.box:connect('host:port')
> nb_wrapper = nb_object:opts()
> nb_wrapper:select(...)
> nb_wrapper:insert(...)
> ```

Let's take a look on our real problem:

```
local ibuf = require('buffer').ibuf
nb_object = net.box:connect('host:port')
nb_wrapper = nb_object:opts({ buffer = ibuf, timeout = 100500 })

ibuf:reset()
nb_wrapper:select(key)
handle_raw_msgpack(ibuf.rpos, ibuf.wpos)

ibuf:reset()
nb_wrapper:insert(tuple)
handle_raw_msgpack(ibuf.rpos, ibuf.wpos)
```

vs

```
local ibuf = require('buffer').ibuf
nb = net.box:connect('host:port')

ibuf:reset()
nb_wrapper:select(key, { buffer = ibuf, timeout = 100500 })
handle_raw_msgpack(ibuf.rpos, ibuf.wpos)

ibuf:reset()
nb_wrapper:insert(tuple, { buffer = ibuf, timeout = 100500 })
handle_raw_msgpack(ibuf.rpos, ibuf.wpos)
```

In the second example per-request arguments are explicitly passed per request. It is so obvious that per-request arguments are per-request arguments, isn't it? I have no idea why `buffer`, which is an in-out argument to request, should be stored somewhere in a global state (`nb_wrapper`). The first example is simple more error-prone than the second one, especially for our `buffer` case.

 I vote for ` conn:call(name, {arg1, arg2, arg3, ...}, {opts})` with `call_v16` per-connection option for compatibility:

1. The second example above looks more natural for me, because request parameters are actually request parameters.
2. I agree with @mejedi that :timeout: implementation is a mess and there is no way to fix it.
3. varargs to `conn:call(name, ...)` are implicitly packed to a Lua table under the hood and this operation is very inefficient in LuaJIT.
4. `conn:call(name, arg, nil, arg2, nil)` doesn't work as expected and it can't be fixed in any efficient way.
5. We already transformed `box.replace(space_id, part1, part, part3, ...)` to `space:replace({part1, part2, part3, ...})` somewhere  in the past and I have no motivation to keep legacy non-extendable `call()` API.
6. CALL has already been broken in 1.7.x and the most 1.6.x users will need `call_v16` per-option to migrate.

Let's schedule a meeting today to find a consensus.

**Comment by rtsisyk** [comment]
We forgot to change call() API. Re-opened.
