### ISSUE TITLE
Verify that  `TRUNCATE` causes `box.space.t:truncate()`.

### ISSUE THREAD

**Issue by kyukhin** [tarantool/tarantool#2201]
Subj.

> "TRUNCATE TABLE t;" could cause box.space.t:truncate().

**Comment by rtsisyk** [comment]
We already have box_truncate() C API for that.

**Comment by kyukhin** [comment]
Right, just need to make sure SQL FE uses it.

**Comment by kyukhin** [comment]
`TRUNCATE TABLE` is part of ANSI SQL 2008+. Here [1] is a description of the feature.
Original SQL sources lack it. So, proposed to move it to the further milestones

[1] - https://www.postgresql.org/docs/9.2/static/sql-truncate.html

**Comment by Korablev77** [comment]
Currently, truncating can occur when executing simple `DELETE * FROM table;`. To be more precise, if we need to сlear whole table and there is no active transaction (since truncating acts as insertion into `_truncate `and can be interpreted as DDL), then truncate is used.
We have decided to add separate SQL statement for that: `TRUNCATE TABLE table;` and prohibit such optimisation from traditional table clearing (i.e. simple deletion row by row).

**Comment by Gerold103** [comment]
Now truncate is not used even for `DELETE FROM table`.
