### ISSUE TITLE
Response to JOIN request without SYNC

### ISSUE THREAD

**Issue by rkravchik** [tarantool/tarantool#2334]
I have tried to send the same JOIN request:
> {0xce, 0x0, 0x0, 0x0, 0x2d, 0x82, 0x0, 0x41, 0x1, 0x2, 0x81, 0x24, 0xd9, 0x24, 0x37, 0x63, 0x30, 0x32, 0x35, 0x65, 0x34, 0x32, 0x2d, 0x32, 0x33, 0x39, 0x34, 0x2d, 0x31, 0x31, 0x65, 0x37, 0x2d, 0x61, 0x61, 0x63, 0x66, 0x2d, 0x30, 0x32, 0x34, 0x32, 0x61, 0x63, 0x31, 0x31, 0x30, 0x30, 0x30, 0x32}
* to v1.6.9 master instance and got this VCLOCK response for the first time:
  > Response CMD:OK(0), ReqID:0, Scheme:0, Err:<nil>
  > Header:{0x82, 0x0, 0x0, 0x2, 0x1}
  > Body:{0x81, 0x26, 0x81, 0x1, 0x0}
  
  no SYNC header, 
* to v1.6.9 master and got this VCLOCK response for the second (and so on) time:
  > Response CMD:(32771), ReqID:2, Scheme:52, Err:0x8003: Duplicate key exists in unique index 'uuid' in space '_cluster'
  > Header:{0x83, 0x0, 0xce, 0x0, 0x0, 0x80, 0x3, 0x1, 0xcf, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x2, 0x5, 0xce, 0x0, 0x0, 0x0, 0x34}
  > Body:{0x81, 0x31, 0xdb, 0x0, 0x0, 0x0, 0x3f, 0x44, 0x75, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x65, 0x20, 0x6b, 0x65, 0x79, 0x20, 0x65, 0x78, 0x69, 0x73, 0x74, 0x73, 0x20, 0x69, 0x6e, 0x20, 0x75, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x20, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x20, 0x27, 0x75, 0x75, 0x69, 0x64, 0x27, 0x20, 0x69, 0x6e, 0x20, 0x73, 0x70, 0x61, 0x63, 0x65, 0x20, 0x27, 0x5f, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x27}

  SYNC header exist
* to v1.7 (default docker from git) master got THREE VCLOCK responses for one request:
  > Response CMD:OK(0), ReqID:0, Scheme:0, Err:<nil>
  > Header:protocol.Packet{0x81, 0x0, 0x0}
  > Body:protocol.Body{0x81, 0x26, 0x80}
  
  > Response CMD:OK(0), ReqID:0, Scheme:0, Err:<nil>
  > Header:protocol.Packet{0x81, 0x0, 0x0}
  > Body:protocol.Body{0x81, 0x26, 0x81, 0x1, 0x4}
  
  > Response CMD:OK(0), ReqID:0, Scheme:0, Err:<nil>
  > Header:protocol.Packet{0x81, 0x0, 0x0}
  > Body:protocol.Body{0x81, 0x26, 0x81, 0x1, 0x4}

  no SYNC header.

So, there are few questions:
1. Should there be a SYNC header like it is mentioned in docs?
2. Will be "No error" behavior to repeated join requests in v1.7 backported to v1.6.9?
3. Why does v1.7 master repeat VCLOCK response three times?

**Comment by rtsisyk** [comment]
1. Yes, it should. We will investigate this regression.
2. I don't understand what do you mean.
3. Please see comment in box_process_join().

**Comment by rkravchik** [comment]
1) As i've understood it is in [xrow.cc](https://github.com/tarantool/tarantool/blob/1.6.9/src/box/xrow.cc):
  ```
  #if 0
  	if (header->sync) {
  		d = mp_encode_uint(d, IPROTO_SYNC);
  		d = mp_encode_uint(d, header->sync);
  		map_size++;
  	}
  #endif
  ```
  And it was added by https://github.com/tarantool/tarantool/commit/d130255ee28abc07c850f313ad6d38962d705d26 on #801.

2) When i'm trying to join (send JOIN request) with UUID that is already in cluster space:
  v1.6.9 response with snapshot and errror 40 duplicate uuid in cluster and no VCLOCK
  v1.7 send VCLOCKs without any errors

3) Have seen in source this morning already. Thank you.

**Comment by rtsisyk** [comment]
> 1. As i've understood it is in xrow.cc

Exactly. You are absolutely right. `box_process_join()` uses `xrow_encode_header()` to prepare response, but  `xrow_encode_header()` skips `IPROTO_SYNC` key during encoding. We commented out this block in order to avoid writing `IPROTO_SYNC` to disk files. As you can see, the function `xrow_encode_header()` is used both for network packets and disk rows.

> 2.  When i'm trying to join (send JOIN request) with UUID that is already in cluster space:
    v1.6.9 response with snapshot and errror 40 duplicate uuid in cluster and no VCLOCK
    v1.7 send VCLOCKs without any errors

I've got it. There is a separate ticket for this problem. Please see https://github.com/tarantool/tarantool/issues/2327

> 3.  Have seen in source this morning already. Thank you.

Here is a link to this comment:
https://github.com/tarantool/tarantool/blob/1fd570cfeb048130f011d60cc99e87421f665992/src/box/box.cc#L1127-L1166

This comment is ultimate source of truth about replication JOIN protocol in 1.7.x. 

>4. Will fix be applied to v1.6.9 (not only 1.7.5)?

I wonder why do you need `SYNC` value in `IPROTO_JOIN` response? Some admin commands, like `IPROTO_JOIN` and `IPROTO_SUBSCRIBE` can't be mixed with other DML requests, like  `IPROTO_REPLACE`, `IPROTO_DELETE` and others. The reason `IPROTO_JOIN`/`IPROTO_SUBSCRIBE` can't multiplexed is just technical - we transfer client's fd to a separate thread to send snapshots and xlogs from the disk. Due to fact that even our replication client doesn't need `SYNC` value, I don't think this problem is important for us. Anyway,  pull requests && patches are always welcome :)

**Comment by rkravchik** [comment]
> I wonder why do you need SYNC value in IPROTO_JOIN response?
Maybe becuase that is said in docs? :)) 
It wasn't "needed", but "expected".

Well, it isn't critical at all. Waiting for v1.7.5
Hope, the docs will be more relevant to reality in the future.

**Comment by rtsisyk** [comment]
1.7.4-332-gd5dfc597e

**Comment by rtsisyk** [comment]
92bb45f48be64167f2ed946a0624937c1e6b3832
