### ISSUE TITLE
Constraints in SQL

### ISSUE THREAD

**Issue by pgulutzan** [tarantool/tarantool#2353]
Some problems with constraints in SQL.

* The constraint name is not stored and using
duplicate constraint names is allowed.
?? There will already be a bug report for this, see above.

It is possible to say s1 INT NULL PRIMARY KEY.
box.sql.execute("CREATE TABLE te15 (s1 INT NULL PRIMARY KEY);")
Result = no error

Even if CREATE TABLE fails due to a constraint definition error,
something is still created, so the error cannot be fixed.
box.sql.execute("CREATE TABLE t99 (s1 INT,UNIQUE(s1,s1),PRIMARY KEY(s1));")
box.sql.execute("CREATE TABLE t99 (s1 INT,UNIQUE(s1),PRIMARY KEY(s1));")
Result = error in the first statement (good), error in the second statement (bad).

ON UPDATE|DELETE CASCADE etc. are accepted, but they do not work.
They should cause syntax errors until support exists.
box.sql.execute("CREATE TABLE te16 (s1 INT PRIMARY KEY, s2 INT, FOREIGN KEY (s2) REFERENCES te16 (s1) ON UPDATE CASCADE);")
Result = no error

It doesn't matter if a FOREIGN KEY constraint fails, the update
or delete happens anyway.
box.sql.execute("PRAGMA foreign_keys=on;")
box.sql.execute("CREATE TABLE te18 (s1 INT PRIMARY KEY);")
box.sql.execute("CREATE TABLE te19 (s1 INT PRIMARY KEY, s2 INT REFERENCES te18 (s1));")
box.sql.execute("INSERT INTO te18 VALUES (1);")
box.sql.execute("INSERT INTO te19 VALUES (1, 1);")
box.sql.execute("UPDATE te19 SET s2 = 2;")
box.sql.execute("SELECT * FROM te19;")
Result = [1, 2]

There are no ALTER statements to drop a constraint,
or to add a constraint, after the table is created.

**Comment by kyukhin** [comment]
Confirmed.

**Comment by kyukhin** [comment]
@pgulutzan could you please submit separate issues for constraints altering?
I've checked recent 2.0 branch and issue w/ foreign key violation seems to be solved:
```
box.sql.execute("PRAGMA foreign_keys=on;")
box.sql.execute("CREATE TABLE te18 (s1 INT PRIMARY KEY);")
box.sql.execute("CREATE TABLE te19 (s1 INT PRIMARY KEY, s2 INT REFERENCES te18 (s1));")
box.sql.execute("INSERT INTO te18 VALUES (1);")
box.sql.execute("INSERT INTO te19 VALUES (1, 1);")
box.sql.execute("UPDATE te19 SET s2 = 2;")

2018-06-20 14:22:39.562 [13951] main/101/3.lua F> FOREIGN KEY constraint failed
```

So, to solve the issue we need to this three mentioned problems (verified):
1. It is possible to say s1 INT NULL PRIMARY KEY.
`box.sql.execute("CREATE TABLE te15 (s1 INT NULL PRIMARY KEY);")`
Result = no error
2.  If CREATE TABLE fails due to a constraint definition error,
something is still created, so the error cannot be fixed.
`box.sql.execute("CREATE TABLE t99 (s1 INT,UNIQUE(s1,s1),PRIMARY KEY(s1));")`
`box.sql.execute("CREATE TABLE t99 (s1 INT,UNIQUE(s1),PRIMARY KEY(s1));")`
Result = error in the first statement (good), error in the second statement (bad).
3. ON UPDATE|DELETE CASCADE etc. are accepted, but they do not work.
They should cause syntax errors until support exists.
`box.sql.execute("CREATE TABLE te16 (s1 INT PRIMARY KEY, s2 INT, FOREIGN KEY (s2) REFERENCES te16 (s1) ON UPDATE CASCADE);")`
Result = no error

**Comment by pgulutzan** [comment]
Okay.
Primary key can be declared with NULL #3473
Constraint definition errors create unwanted objects #3474
Foreign keys can be declared with CASCADE #3475

**Comment by kyukhin** [comment]
Superseded by other issues.
