### ISSUE TITLE
Cleanup usage of index_def

### ISSUE THREAD

**Issue by kostja** [tarantool/tarantool#2426]
- Do not use idnex_def in vinyl.c
- in memtx_tree.c
- in other places, where a key_def will sufice

Please try to slice this task into several patches, it's a big one.

**Comment by Gerold103** [comment]
It can't be deleted from memtx_tree.c, since memtx_tree comparators need key_def and is_unique, but bps tree API allows only one additional argument for comparators. So we must use index_def, or something like:
```C
struct compare_arg {
    struct key_def *def;
    bool is_unique;
}
```

**Comment by Gerold103** [comment]
In MemtxTree we could create function pointers on each bps_tree function and union with two bps trees, but then each search in the tree will use calling function be pointer. It will slow the searching.

Also we can create two MemtxTree classes, but they will fully duplicate each other instead of bps functions. It is ugly.

Also we can create MemtxTree template c++ class and inherit from it two trees, but then template implementation must be defined in the header file.

Also we can create MemtxTree template using #defines, but then the implementation must also be in the header file.

Too complex changes for deletion of the index_def.
