### ISSUE TITLE
fiber: remove fiber->gc

### ISSUE THREAD

**Issue by Gerold103** [tarantool/tarantool#2503]
Why: interactive transactions during execution of different requests can be moved between various fibers. Transactional data and a transaction object must be valid during whole transaction's lifetime. That means, the transactional data can not be stored in a fiber memory.

How: introduce single buffer per cord and separate buffer per each transaction.
Cord buffer must be cyclical, have fixed size and clear itself in a case of filling up. It can be used for temporary data, for example, for building the body of a tuple to place it in the `struct tuple` then. Or for other temporary calculation results.
Transaction buffer must contain data, needed during whole transaction's lifetime: transactional logs, transaction object, read view etc.

Cyclic cord buffer can be implemented as a region or as a simply malloced memory space. API must hide looping of the buffer and must raise an error on an attempt to allocate more memory, than the buffer has. Obviously, that data, allocated on such a buffer, become invalid after any yield.

**Comment by Gerold103** [comment]
---------------- План по gc для cord, fiber и txn.
-------- Вариант с удалением fiber.gc:

Удалить gc из fiber, ввести новые regions для cord и txn.
```C
struct fiber {
-   struct region gc;
}

struct cord {
+   struct region *region;
}

struct txn {
+   struct region *cord_region;
}
```

В отсутствие транзакции cord.region указывает на регион, аллоцированный в себе.
При появлении транзакции memtx ничего не меняется, поскольку невозможны yield.
При появлении транзакции vinyl:
```C
txn()->cord_region = cord()->region;
cord()->region = region_new_in_self();
```
На каждый yield: `swap(txn()->cord_region, cord()->region)`, на каждый выход из yield - снова `swap`.
На commit/rollback:
```
swap(cord()->region, txn()->cord_region);
region_destroy(txn()->cord_region);
```
Меняем все fiber()->gc на cord()->gc.


-------- Вариант с рефакторингом fiber.gc:

```C
struct fiber {
-   struct region gc;
+   struct region *region;
}

struct cord {
+   struct region region;
}

struct txn {
+   struct region *region;
}
```

В отсутствие транзакции fiber.region указывает на cord.region.
При появлении транзакции memtx ничего не меняется, поскольку невозможны yield.
При появлении транзакции vinyl:
```C
txn()->region = region_new_in_self();
fiber()->region = txn()->region;
```
При завершении транзакции:
```C
fiber()->region = cord()->region;
region_destroy(txn()->region);
```
Все fiber()->gc остаются на местах.

**Comment by kostja** [comment]
This is necessary for gh-2016

**Comment by Gerold103** [comment]
-------- Вариант 3: struct region как часть txn.
```C
struct fiber {
-   struct region gc;
}

struct cord {
+   struct region *active_region;
+   struct region *saved_region;
}

struct txn {
+   struct region region;
}
```
txn объекты аллоцировать из мемпула вместо какого-либо региона.
В отсутствие транзакции использовать `cord.active_region`. Когда появляется транзакция, то
```C
cord.saved_region = cord.active_region;
cord.active_region = &txn.region;
```
Далее используем как обычно `cord.active_region`. Возможно он так и не понадобится.
Далее рассмотрим события fiber_yield/fiber_wakeup.
---- fiber_yield.
`cord.active_region = cord.saved_region;`
Теперь другой файбер не затронет регион транзакции, которая только что ушла в yield.

---- fiber_wakeup.
```C
cord.saved_region = cord.active_region;
cord.active_region = &txn.region;
```
Если транзакция существует в текущем файбере, значит надо ее продолжить. В том числе, вернуть ее регион в cord.

Рассмотрим, как транзакция заканчивается. Если происходит запись в вал, то это обычные yield + wakeup, рассмотренные выше.
Допустим wal уже записан. Тогда время удалить регион транзакции и вернуть активный регион корда:
```C
+txn_delete() {
+   region_destroy(&txn.region);
+   mempool_free(&pool, &txn);
+}
```

**Comment by locker** [comment]
So, this issue is actually about interactive transactions (#2016). Currently, transactions use `fiber()->gc` for storing statements so we can't start a transaction in one fiber and commit it in another fiber, which is what interactive transactions are about in a nutshell. There is a number of things we have to take into account when implementing interactive transactions:

1. I think we should leave `fiber()->gc` as is, because it's quite useful as extra stack - fiber stack is quite limited so having a practically inexhaustible stack extension comes in handy.
2. I don't think we can move `fiber()->gc` to `cord()->gc`, because there are places in the code where we allocate something on the region, then yield, then use it. Moving the region to `cord()->gc` wouldn't allow us to do that, which looks like a rather artificial limitation to me.
3. Creating a new region per each transaction (`txn->gc`) is rather expensive both from cpu and from memory consumption point of view, because we would have to allocate a slab per each active transaction. Even non-interactive transactions would be affected.

Keeping those in mind, I suggest the following implementation:

1. Add a region to `struct txn`. Left it uninitialized when a transaction is started. As before, allocate transaction data from `fiber()->gc`.
```C
struct txn {
	/* ... */
	struct region gc;
}
```
2. Add new method for detaching/attaching a transaction from/to a fiber. The methods will move all slabs and stats from `fiber()->gc` to `txn->gc` or vice versa (this is what `region_swap` is supposed to do):
```C
void txn_detach(struct txn *txn)
{
	assert(in_txn() == txn);
	region_create(&txn->gc, &cord()->slabc);
	region_swap(&txn->gc, &fiber()->gc);
	fiber_set_txn(fiber(), NULL);
}
void txn_attach(struct txn *txn)
{
	assert(in_txn() == NULL);
	region_swap(&txn->gc, &fiber()->gc);
	region_destroy(&txn->gc);
	fiber_set_txn(fiber(), txn);
}
```
3. Use `txn_detach` on an interactive transaction upon returning from CALL/EVAL. Use `txn_attach` on an interactive transaction upon the next CALL/EVAL.

Such a design will introduce absolutely no overhead if interactive transactions are not used. For interactive transactions, we will have to allocate and maintain a slab, but this is what we have to do anyway.

**Comment by locker** [comment]
Each transaction now has its own region which it uses for allocating objects that should stay till transaction completion. `fiber()->gc` is supposed to be used only for temporary allocations which don't fit in stack. In other words, nothing prevents us from starting a transaction in one fiber and completing it in another. The issue may be closed.
