### ISSUE TITLE
vinyl: add max tuple size config option

### ISSUE THREAD

**Issue by alyapunov** [tarantool/tarantool#2569]
Now vinyl allocates tuples in runtime arena with fixed slab size (4MB now). Thus vinyl cannot store tuples greater than about 4MB.
We should add personal vinyl memory arena, add configure option for vinyl similar to memtx_max_tuple_size option for memtx and adjust vinyl arena slab size appropriately.

**Comment by rtsisyk** [comment]
This problem is caused by usage of slab_map() by lsregion_alloc(). slab_map() allocates slabs of size arena->slab_size (4mb by default), therefore lsregion can't allocate chunks larger than slab_size bytes. 
Possible solutions:

1. Use malloc() for huge chunks in lsregion, like in slab_cache. Caveats: it will duplicate slab_get() logic from slab_cache().
2. Switch to slab_cache() in lsregion, like it was done in the first version of lsregion.
3. Create a separate arena for vinyl with configurable slab_size. Caveats:  huge slab_size is ineffective.

**Comment by rtsisyk** [comment]
Blocked by #2588 (can't write a test case)

**Comment by alyapunov** [comment]
I think that memory management in vinyl must be similar to memtx. Memtx doesn't use 'malloc' feature of slab_get, all memtx tuples are allocated inside memtx arena. If the tuple size exceeds limit, a proper error message comes:
```
ER_MEMTX_MAX_TUPLE_SIZE: Failed to allocate 10485787 bytes for tuple in the slab allocator: tuple is too large. Check 'memtx_max_tuple_size' configuration option.
```
Storing long-live tuples in runtime arena is not a good idea, I'm sure.
So I still think that solution (3) is the best one. With options and error messages similar to memtx's.

**Comment by rtsisyk** [comment]
>  So I still think that solution (3) is the best one.

Accepted, let's go with a separate arena for Vinyl tuples.
