### ISSUE TITLE
Implement custom aggregate functions for SQL

### ISSUE THREAD

**Issue by kyukhin** [tarantool/tarantool#2579]
SQLite has nice feature which allows to register custom aggregate
functions written in C (and Lua in case of Tarantool) and available
from SQL like any other.

Example is `count_x()` which counts number of non-NULL values
of the column.

**Comment by pgulutzan** [comment]
@ImeevMA:
Hi, I looked at meevma/gh-2579-introduce-custom-aggregate-functions
I'd like to make a few ignorable suggestions.

Regarding the error message if I define incorrectly
The body of an aggregate function should be a map with two string fields: step and finalize.
This might be clearer if it was "keys" or "key fields" or "string keys" rather than "string fields".

Regarding the error message if there are no rows
(Assuming the first parameter is a string that I've  named "accumulator")
It seems to me that in this case there is no call to step, so accumulator is not initialized.
Fine, but then I would expect finalize to return nil.
That doesn't happen, I get an error:
[string "return function(accumulator)..."]:3: attempt to concatenate local ''accumulator''
  (a nil value)'
If I add a line in the finalize function like 
"if accumulator == nil then return nil end"
then all is well, but this is tedious, can you not handle this case automatically?

Regarding NULLs which are ignored
Eventually, I guess, Tarantool will support warnings, and that will include the
standard warning "null value eliminated in set function".
It seems to me that this will mean it is necessary to have another parameter besides
the accumulator, for both step and finalize.
If I've guessed correctly, then will it be good to have this, unused, in the initial design?

Regarding order
Ordinarily, I should not expect that the steps will be called in order.
But it is simple to write a function that will return a different result if the
rows are not always returned in the same order.
So is there any guarantee that you can give for stability?
Perhaps AGG(...) OVER (ORDER BY ...) -- the sort of syntax that one sometimes
sees with window functions -- is necessary, though I suppose that is difficult.
