### ISSUE TITLE
sql: hold optional tuple next to the msgpack (op_column -> O(1))

### ISSUE THREAD

**Issue by kyukhin** [tarantool/tarantool#2740]
Currently we're using msgpack to store rows of the table (in makerecord routines).

In order to move from SQLite's ephemeral tables to Tarantool temporary spaces (part of #2680), let's use struct tuple instead of naked msgpack.

**Comment by Khatskevich** [comment]
The thing is that box api (box.cc) which is currently in use by sqlite engine takes msgpack as an argument.
If Op_MakeRecord produces tuple, the box.cc takes only msgpack part of this tuple and will create a new tuple and copy all data to it. At this point, we have already copied the data at least three times (to sqlite registers, to create msgpack and to create tuple).

At the same time, tuples we can create by now (of default type) do not give us any advantages, because it does not store offsets to the fields.

All these points convinced us to create an intermediate layer for direct tuple insertions in box api.

**Comment by Khatskevich** [comment]
We discussed this topic once again.
Results:
Unified api creation is not a solution for the reason that in case we decide support sql over vinyl, we can not just create tuples and insert them to the engine (it is a complex procedure for vinyl).
