### ISSUE TITLE
Extend msgpack Lua API

### ISSUE THREAD

**Issue by kostja** [tarantool/tarantool#2755]
http://github.com/tarantool/dump currently can not perform piece-by-piece restore of a dump because there is no way to parse a partial msgpuck chunk with the built-in msgpuck. 

Please extend the built-in msgpuck to not throw exceptions on error/partial parse. After that it will be bossible to improve http://github.com/tarantool/dump.

On the same token it would be nice to finish msgpackffi and make sure it has the same API as msgpuck.

Thanks.

**Comment by locker** [comment]
Proposed API extension:

- msgpack.encode(obj, opts)

  (This function already exists, added 'opts' argument)

  Encode a Lua object as msgpack.

  If opts.buffer = ibuf, store the result in the given ibuf and
  return the number of bytes written. Otherwise store the result
  in a new Lua string and return the Lua string.

- msgpack.internal.encode_ibuf(ibuf, obj)

  (New function)
  
  Internal method used by msgpack.encode().

- msgpack.decode(str, offset) -> obj, new_offset
  msgpack.decode(buf, size) -> obj, new_buf

  (1st variant already exists, 2nd is new)

  Decode a Lua object from msgpack.

  Both variants return the decoded Lua object on success.

  The first variant works with a Lua string and an offset in the
  string. It returns the new offset in the second argument.

  The second variant works with a C buffer and its size. It
  returns a pointer to the position following the last written
  byte in the buffer in the second argument.

  On failure, raise an error. Alternatively, we could return
  {nil, error message}, but this would break compatibility.

- msgpack.decode_unchecked(str, offset) -> obj, new_offset
  msgpack.decode_unchecked(buf) -> obj, new_buf

  (New function, supposed to replace msgpack.ibuf_decode)

  Same as msgpack.decode(), but don't check the buffer with
  mp_check() before decoding it. It is intended to be used in
  hot paths where the caller is sure that the decoded data are
  not corrupted.

- fio.write(fh, str)
  fio.pwrite(fh, str, offset)

  fio.write(fh, buf, size)
  fio.pwrite(fh, buf, size, offset)

  (Added variants for working with a C buffer)

  Write a Lua string (1st variant) or a C buffer (2nd variant)
  to a file. Return true on success, {false, error} on failure.

- fio.read(fh, size) -> str
  fio.pread(fh, size, offset) -> str

  fio.read(fh, buf, size) -> true/false
  fio.pread(fh, buf, size, offset) -> true/false

  (Added variants for working with a C buffer)

  Read a file to a Lua string (1st variant) or to a C buffer
  (2nd variant).

  The first variant returns a new string where the read data has
  been stored or {nil, error} on failure.

  The second variant returns true on success, {false, error} on
  failure.

**Comment by rtsisyk** [comment]
fio  => https://github.com/tarantool/tarantool/issues/2960
No-exceptions  API has been discarded because it is a breaking change.
ibuf support for msgpack has been pushed.
