### ISSUE TITLE
Stop caching global grants or disconnect after a global grant

### ISSUE THREAD

**Issue by kostja** [tarantool/tarantool#2763]
There is a race condition with an external application at bootstrap:
- box.cfg{listen} is calledeline
- a remote application connects as guest
- box.schema.user.grant('guest', 'read,write,execute', 'universe') is called
- remote application tries to execute a query, and gets "access denied", because global grants are cached in all connections
- the problem can not be fixed in any way except reconnect.

Possible solutions:
- stop caching global grants in struct credentials
- disconnect all clients when making a global grant
- add struct credentials into a linked list associated with a user and push global grants to all existing  credentials after grant.

The problem is observed at Beeline and Mail.Ru

**Comment by rtokarev** [comment]
I've encountered this issue in our production setup.

**Comment by locker** [comment]
Actually, the spurious "access denied" issue due to cached privileges can happen even if privileges were granted long ago - in case a client connects as guest before recovery is complete. Here's a sequence of events leading to the problem:

1. box.cfg opens a port and starts recovery.
2. A client connects to the port, but doesn't issue AUTH request, i.e. connects as guest, hence he doesn't get ER_LOADING, because in contrast to AUTH request, CONNECT doesn't check if box.cfg has completed.
3. Client caches privileges. Since recovery hasn't completed, _priv system space is empty and he caches none.
4. box.cfg recovers _priv table and grants the execute privilege to the guest user.
5. The client tries to execute a function, but fails, because the execute privilege was recovered after it connected.

Observed by @rtokarev.

@kyukhin it might be worth scheduling this issue for 1.10.

**Comment by alyapunov** [comment]
* Vladimir Davydov <notifications@github.com> [19/06/05 15:09]:

The fix is:

- link all sessions into a list
- update all cached privileges or disconnect the session on global
  grant/revoke, drop user, enable/disable user.

-- 
Konstantin Osipov, Moscow, Russia

**Comment by Gerold103** [comment]
I would rather keep users connected, and update credentials cache. But should anything special be done in case a user was doing replication, and its right to work with _cluster was revoked? Should the user be disconnected?
