### ISSUE TITLE
http.client cookie parser

### ISSUE THREAD

**Issue by rtsisyk** [tarantool/tarantool#2801]
Add response.cookies array to http.client.

**Comment by kostja** [comment]
Georgy, please review this patch.

**Comment by Gerold103** [comment]
@kostja  I already have started review. Please, let me finish.

**Comment by GeorgyKirichenko** [comment]
Please export cookies as an array with values:
{{cookie_name, cookie_value, cookie_option_1, ..},
  {...},}
where cookie option may be a plain flag or a pair like {option_name = option_value}.
The job may be done at lua level at httpc.lua.
Take a look on a cookie_value quotation because a cookie_value may contain semicolon separators.

**Comment by IlyaMarkovMipt** [comment]
I propose the following schema of cookies array in response object:
``` lua
response.cookies['key'] = {{value1, value2}, {{opts1_1, opts1_2}, {opts2_1, opts2_2}}}
```
Where `value1`, `value2` are values from different `Set-Cookie` header.
Opts are cookie options, mentioned in corresponding to value `Set-Cookie header` (`HttpOnly`, `Expires=<date>`) left as strings.
If there are several equal keys in one `Set-Cookie` header, parser saves the value of the first one.
