### ISSUE TITLE
logical replication

### ISSUE THREAD

**Issue by kostja** [tarantool/tarantool#2870]
Allow to mark a stored procedure for logical replication. 

We need to provide users with a way in which we replicate CALL rather than effects of a stored procedure.
The first and primary purpose of this is to keep vinyl slaves behind a memtx master, but this is also necessary for CRDT style replication.

**Comment by alyapunov** [comment]
I think this idea can be also used in conflict-free TX manager. Just retry stored procedure on conflict. But (in vinyl) this approach would also require cache improvement - update cached value on write instead of throwing away.

**Comment by locker** [comment]
Proposed API:
- Add a new `box.cfg()` option, `replication_type = [ 'call' | 'row' ]`. If `replication_type` is set to `'row'`, use the conventional (row-based) replication, otherwise replicate function calls, see below. This option must be set to the same value on all replicas of the cluster.
- In case of call-based replication write iproto function calls (`IPROTO_CALL`, name, arguments) to xlog. These records are ignored on recovery and when saving a snapshot, but they are sent to all subscribed replicas instead of DML records. All iproto function calls are logged and replicated. It's up to the replica to filter certain function calls.
- Only 'subscribe' stage is affected by `replication_type = 'call'`. When joining a replica, we send rows, not function calls, irrespective of the value of `replication_type`.
- The replica must define all functions that may be called during 'subscribe' stage before setting up replication (i.e. before calling `box.cfg()`).

**Comment by rtsisyk** [comment]
Problem: how to rollback CALL effect in case of error?

**Comment by locker** [comment]
> Problem: how to rollback CALL effect in case of error?

I don't understand why we should rollback anything in case of error? The function was called so it should be logged and replicated. Whether the call was successful or not from the user point of view is a different story IMO - AFAIU our responsibility is to blindly replicate function calls while it is completely up to the user how to react to them on the replica.

**Comment by kostja** [comment]
We don't need this any more as long as we have BEFORE REPLACE triggers.
