### ISSUE TITLE
Upgrade from 1.7.4.103-1 to 1.7.5.0-1 failed

### ISSUE THREAD

**Issue by anton-barabanov** [tarantool/tarantool#2886]
Simple reproduce way: create 3 tarantool replicas in first host (test1.lua, test2.lua, test3.lua) and 1 in second (test.lua). After initial start stop the second replica and upgrade tarantool in second host to 1.7.5. After start it you will see this messages in logs in first host:
`
2017-11-01 13:56:32.035 [148626] main/108/applier/test@192.168.0.3:3 I> can't read row
2017-11-01 13:56:32.035 [148626] main/108/applier/test@192.168.0.3:3 alter.cc:1591 E> ER_CREATE_ROLE: Failed to create role 'public': authentication data can not be set for a role
`
[tntreport.tar.gz](https://github.com/tarantool/tarantool/files/1433906/tntreport.tar.gz)

**Comment by locker** [comment]
Upgrade from 1.7.4 to 1.7.5 was marked automatic, which means that `box.schema.upgrade()` is invoked implicitly by the first call to `box.cfg()`. This was done, because initially it just created the `_truncate` system space and didn't modify existing tables, neither user nor system. However, after a while some extras were added to the upgrade procedure in preparation for strict space format checking. In particular, the `_user` system space was modified so that now every tuple has to have the `auth` map (field 5) while before only users had that field and an attempt to set the `auth` data for a role resulted in the error you observed:
```
ER_CREATE_ROLE: Failed to create role 'public': authentication data can not be set for a role
```
(see commits a6128fcd224f506138f1a3959d8505ee0bc97287, 5ac86f763d7b038eda94edc088a34f6d8694865b)

We should probably have disabled auto-upgrade to 1.7.5 after this change, but we didn't and this broke replication in your case: the master running tarantool 1.7.5 sets `auth` to an empty map for all existing roles during auto-upgrade, but this is not permitted by replicas, which are still running 1.7.4. Unfortunately, it doesn't seem there is anything we can do about it now. The only feasible solution seems to be upgrading **all** your tarantool instances to the same version first and only then enabling replication.

**Comment by locker** [comment]
Sorry, I was wrong. Upgrading all replicas simultaneously won't work either, because it will result in a conflict on an attempt to create the `_truncate` space (it's done with `insert`). I see no solution apart from upgrading one replica and then bootstrapping others from it.

**Comment by locker** [comment]
So, the cause of all troubles is auto upgrade. It seems that we should disable it in case of replication, otherwise it will inevitably result in replication conflicts.
