### ISSUE TITLE
Don't wait for all remote replicas when starting a replica set instance

### ISSUE THREAD

**Issue by rtsisyk** [tarantool/tarantool#2958]
# Preamble

Tarantool 1.7 waits until all remote upstreams from box.cfg.replication are connected before proceeding with boot, whereas 1.6 didn't. This breaks high availability in a few important cases:

- there is a master-master set up operating in eventual consistency mode. One of the masters is down. When the second master restarts for whatever reason, it doesn't boot without a DBA intervention
- there is a master-slave set up, and the master is down. The slave restarts, again, for whatever reason. Instead of continuing in read only mode, which is entirely safe, it sits in box.cfg{} waiting for master to respond to the slave's replication handshake request.

# The change

The current behavior implements the motto "better to be safe than sorry". In all cases when an instance failed to boot in its previously defined configuration it is clearly visible to the DBA which then can intervene and change the configuration according to the circumstances. For example, Tarantool 1.6 could start with wrong slave URIs in the configuration file and never finish initializing replication - and this used to be missed by ops.

Therefore, the spirit of the new changes is to preserve and improve the level of safety introduced in 1.7, while giving the power users flexibility to automate restart as they wish.

## First boot

On first boot, when the replica set is not yet initialized, the procedure will not change. We will wait for all replicas specified in the configuration to be up and running before finishing the bootstrap.

## Subsequent starts

On a subsequent start, the replica will continue to try to connect to all peers specified in ```box.cfg.replication``` configuration variable, making at least 3 attempts to connect to each peer during the period specified in ```replication_timeout```. If these attempts succeed until the timeout is reached, the replica will get up to date with all the changes accumulated at peers, as specified in a new ```replication_lag``` variable (in seconds). When the replica is behind its peers for fewer seconds than specified in ```replication_lag```, it ends booting by leaving box.cfg{} in read-write or read-only mode, as defined in ```box.cfg.read_only```.

In case replica was not able to reach some of its peers in ```replication_timeout``` seconds, it syncs up with the peers it was able to connect to and then leaves box.cfg{} in a degraded mode:
- if ```box.cfg.read_only``` is true, the mode is "read only".
- if ```box.cfg.read_only``` is false, the replica checks a new variable, ```box.cfg.replication_connect_quorum```, which defaults to the number of entries in ```box.cfg.replication```, and specifies the number of peers the replica should be in sync with to enter read-write mode. If the quorum is reached, the mode is read-write. Otherwise the mode is read-only. The new, forced read-only mode can be changed only by changing box.cfg.replication or box.cfg.replication_connect_quorum.

**Comment by kostja** [comment]
@rtsisyk , first, this is a duplicate. Second, please do not assign bugs to milestones. Third, I disagree, and there is no way we will restore 1.6 "way", worst case there will be an option which is off by default. This is a yet another "before you guys automatically restart in case of crash we're not going to use you".

**Comment by rtsisyk** [comment]
Sorry for the duplicate. This problem has been mentioned earlier in https://github.com/tarantool/tarantool/issues/1956 at Nov 28, 2016 by @unera. I received a support request from a Mail.Ru customer yesterday and opened the new issue. I was unable to find original issue and I agree that its my fault. 

I knew about this issue, it was in our 1.7.6 list and we actually planned to fix this regression in 1.7.6. Unfortunately, the original ticket has quietly [disappeared](https://github.com/tarantool/tarantool/issues/1956#event-1206518585) from 1.7.6 milestone first to 1.7.7 and then to wishlist. Since we only work on GitHub issues assigned to active milestones, #1956 wasn't fixed in 1.7.6 and we didn't plan to fix it in 1.7.7. 

![2017-11-26-133412_2560x1401_scrot](https://user-images.githubusercontent.com/1799054/33239237-a060225e-d2ae-11e7-9c2d-1ba78553caf2.png)

Our customer rightfully believes that this issue can cause **significant** damage for his business. I completely agree with him. Moreover, I know at least one more corporate customer and dozens of community users who are also affected or can be affected by this issue. 

Currently customer has to stop Tarantool adoption and waits any resonable ETA from us. Could you please return this ticket back to 1.7.x? We can try to fix and release it as part of upcoming 1.7.7.

**Comment by kostja** [comment]
I chatted with Mons, there are several options to choose from, we'll meet Monday 7pm to discuss.

**Comment by rtsisyk** [comment]
OK, thanks for the fast response! I invited to this meeting too.

**Comment by rtsisyk** [comment]
Discussed with @kostja => wait 50%+1 of remote appliers.

**Comment by rtsisyk** [comment]
50%+1 solution has been discarded because it is not suitable for @Mons.
Kostja works on a new design document.

**Comment by GeorgyKirichenko** [comment]
I assume that there is no point in waiting until all replicas are inserted in the case of the initial cluster load, because any of the replicas should not contain any data (for correct configurations, of course). So, if a 'bootsrap is not finished' status was received during initial bootstrap/join then box.cfg may be finished without all other masters.

**Comment by unera** [comment]
- шансы есть?
- есть!
- в каком году?

**Comment by kostja** [comment]
We need another replication_timeout variable, using the same variable for everything doesn't work.
Please try setting a broken box.cfg.replication second time, and you'll see that it doesn't try to reconnect, because reconnect timeout = replication timeout. This is broken, reconnect_timeout should be < replication_timeout, to allow for at least a few reconnects.

**Comment by locker** [comment]
Instead of adding new `box.cfg` options, such as `replication_quorum`, we could add new functions for replication configuration with clear semantics and let users decide what to do. The functions could be:
- `box.subscribe(addr, timeout)` Subscribe to events from a master at `addr`. Try to connect for `timeout` seconds. On success, return the master id that could be used to track the subscription state via `box.info.replication`. To cancel the function before timeout, cancel the current fiber.
- `box.unsubscribe(id | uuid)` Remove the master with the given id (or uuid) from the replication configuration.

Assume the cluster has already been bootstrapped. Then a replica's workflow could look like this:
1. Call `box.cfg` without specifying `replication` for local recovery. Replication will be configured later. To prevent the instance from processing user requests before replication configuration is complete, do not set `listen` (alternatively, one could set `read_only` flag or write some code in Lua to reject client requests in case the instance hasn't been fully initialized).
2. Create a fiber per each configured master. Call `box.subscribe` in each fiber to connect to a master. In the main fiber (or a special monitoring fiber), wait until the instance is connected to a sufficient number of masters, then complete configuration either by setting `listen` or clearing `read_only` flag depending on the decision made on step 1. One could also wait until the replication lag (as reported by `box.info.replication`) to be small enough before proceeding to handling user requests (see #999).
3. After configuration has been completed, the fibers created on step 2 could be left for monitoring subscription. For instance, they could be used for removing masters by calling `box.unsubscribe` that are found to be permanently down or they could switch the instance to the read-only mode if the replication lag gets too high.

It would definitely require writing more code in Lua, but at the same time it would be more flexible, as the users could decide for themselves what they want to do in various extreme cases. This would also spare us from adding a bunch of new configuration options for each use case and then maintaining them for good. To ease the initial setup, we could probably ship a script implementing the default behavior right in the Tarantool package.

**Comment by rtsisyk** [comment]
Added replication_quorum option to box.cfg():

- box.cfg { replication = {xx, yy, zz}, replication_quorum = 0 } - don't wait replicas (old 1.6 behaviour)
- box.cfg {  replication = {xx, yy, zz, replication_quorum = 100500} - wait all replicas (new 1.7 behaviour)
- box.cfg {  replication = {xx, yy, zz, replication_quorum = N} - wait N replicas (custom logic)

Proposed logic with replication_lag + read_only on box.cfg() doesn't solve the problem that replica can fall behind master AFTER box.cfg(). The comprehensive solution is needed to forbid read/write queries on stale replicas. Currently this logic can be implemented using Lua without patching server.

box.cfg { replication_quorum - X } - 1.7.6-140-gf1167c429 (1.7-next)
