### ISSUE TITLE
Allow to specify instance uuid via box.cfg()

### ISSUE THREAD

**Issue by rtsisyk** [tarantool/tarantool#2967]
Problem: I want to store Tarantool configuration in a centralized configuration system (e.g. ZooKeeper). In this case it would be nice to allow to configure instance uuid via box.cfg():

 `box.cfg { uuid = 'xxx' }`

**Comment by kostja** [comment]
Good to go. Let's call replication uuid 'replication_uuid' in box.cfg{}, and allow to assign it as well.

The assignment should work as follows:
- at bootstrap, we use the assigned values, rather than generate values
- at restart, we verify that assigned values mach the ones written to the snapshot, and fail if they don't match.

**Comment by rtsisyk** [comment]
There are two uuids: instance uuid and cluster uuid. I actually wanted to override them all.
--
Sent from Mail.Ru app for Android Wednesday, 29 November 2017, 04:22PM +03:00 from Konstantin Osipov  notifications@github.com :

**Comment by kostja** [comment]
This is exactly what I'm saying. But cluster_uuid as name is ambiguous - I removed it from 1.7. The uuid is now called replica_set_uuid. cluster_uuid is reserved for uuid of entire sharded cluster.

**Comment by rtsisyk** [comment]
@kostja box.cfg { replicaset_uuid = xxx and instance_uuid = xxx } ?

**Comment by rtsisyk** [comment]
1.7.6-62-gf0200c1cd
