### ISSUE TITLE
string.rstrip and string.lstrip should accept symbols to strip

### ISSUE THREAD

**Issue by knazarov** [tarantool/tarantool#2977]
It is a very common use-case to strip certain symbols from a string. For example, when working with paths or URLs, it may be needed to strip leading or trailing slashes.

Because of this, Python's string.strip/lstrip/rstrip accept an optional argument with characters to strip. It would be nice to do it the same way in Tarantool.

**Comment by gdrbyKo1** [comment]
@Totktonada and I looked into this issue recently, and we were able to come up with a couple of implementations, but it's still not clear which of these would work best in this case. Almost all of the variants we tried were faster compared to others for certain inputs, and at the same time slower when called with some other parameters.
I created this gist to preserve most of what we've experienced so far: https://gist.github.com/gdrbyKo1/7716a1ee37277f7f1387aff2a955f1f0
There, you can see the benchmark results of all the implementations. I obtained these with Tarantool running inside an otherwise idle VM with Debian Stretch (GCC toolchain). It should be noted that due to LuaJIT's GC and/or some other unidentified factors, the timings can potentially vary greatly between multiple Tarantool instances. It's likely needed to run more tests to achieve greater accuracy.

**Comment by Totktonada** [comment]
I didn't made wide research, but look at CPython and Redis, both use memchr:

* https://github.com/python/cpython/blob/0e5f771f38138714415f665651de7e674fcebc38/Objects/bytearrayobject.c#L1790-L1808
* https://github.com/antirez/sds/blob/8dc8d6fb373bdc08eb82a72904841998d30b7cf2/sds.c#L700-L713

PyPy uses memchr-like loop (in RPython!) and separate implementations for single-character case and ascii spaces:

* https://github.com/mozillazg/pypy/blob/50d6bf76ef1f93c234ab42d4dd4a3b974f9665d6/rpython/rtyper/rstr.py#L137-L161
* https://github.com/mozillazg/pypy/blob/50d6bf76ef1f93c234ab42d4dd4a3b974f9665d6/rpython/rtyper/lltypesystem/rstr.py#L460-L521
* https://github.com/mozillazg/pypy/blob/50d6bf76ef1f93c234ab42d4dd4a3b974f9665d6/rpython/rtyper/lltypesystem/rstr.py#L1102-L1112

Boost just iterate over a string and call a predicate:

* https://github.com/boostorg/algorithm/blob/1cbe285841e073f4e7c685662c74bb6cf5be934b/include/boost/algorithm/string/trim.hpp

**Comment by gdrbyKo1** [comment]
PHP uses `char mask[256]`, but only if there's more than one character to strip: https://github.com/php/php-src/blob/3b0f05119383fe21ee75adaed3d0239ba8976aef/ext/standard/string.c#L785-L875

**Comment by Totktonada** [comment]
I added plain C implementation, benchmarked them all again and created the simple harness (poor-fast-bash-make-gnuplot-written): https://gist.github.com/Totktonada/f9420530a3697dfa90e0b66170a97be2 . Download SVG files to see them.

I think we should use uint8_t array in C. It has quite good performance across different inputs (length of input strng, length of `chars` string). The plain C implementation could outperform it in case of `#chars == 1`, but it is so until around `#inp == 50`, then uint8_t array is faster. I think we should use most universal implementation (at least while we have no real feedback from an application developers) and it is uint8_t array in C.

Maybe it worth to run separate implementation in case of `#chars == 1` and `#inp > some_const` (use one level loop to compare with char), but determining this constant requires more effort: benchmarking on many inputs and on many machines. I propose to skip this step until it will requested explicitly by users.

Re code:

* Need to reformat in according to our [C code style][1].
* I think we can use it for the case when `chars` parameter is not provided too (instead of regexps). It should be faster.
* Strip can be implemented as lstrip + rstrip (and, please, try to minimize code duplication).

[1]: https://tarantool.io/en/doc/2.1/dev_guide/c_style_guide/

**Comment by knazarov** [comment]
I think it would be better to use plain lua for this, because calls to C break luajit performance

**Comment by Totktonada** [comment]
@knazarov See the graphs.

**Comment by knazarov** [comment]
I don't have any hard evidence in favor of pure lua implementation, so feel free to dismiss this as insubstantial. The only reason I see for this is that less expensive C code can potentially prevent jitting of more expensive lua code that is around the call to string.rstrip().

I personally wouldn't bother and just take the implementation from Penlight: https://github.com/stevedonovan/Penlight/blob/master/lua/pl/stringx.lua

**Comment by Totktonada** [comment]
AFAIK, ffi calls don't break traces. I don't see NIY in `luajit -jv` output for the `c_uint8_array` function. Penlight uses lua re, it is the slowest way to do so, see the graphs.
