### ISSUE TITLE
tuple access by field name for net.box

### ISSUE THREAD

**Issue by nekufa** [tarantool/tarantool#2978]
```localhost:3301> box.info.version
---
- 1.7.6-12-g2db448b21
...

localhost:3301> box.schema.create_space("named", {format = {{name = "id"}}})
---
- index: []
  on_replace: 'function: 0x41bc9548'
  temporary: false
  id: 4963
  engine: memtx
  enabled: false
  name: named
  field_count: 0
- created
...

localhost:3301> box.space.named:create_index('id', {parts = {{1, 'unsigned'}}})
---
- unique: true
  parts:
  - type: unsigned
    is_nullable: false
    fieldno: 1
  id: 0
  space_id: 4963
  name: id
  type: TREE
...

localhost:3301> box.space.named:insert({1})
---
- [1]
...

localhost:3301> box.space.named:get(1)
---
- [1]
...

localhost:3301> box.space.named:get(1).id
---
- 1
...

localhost:3301> require('net.box').connect('localhost', 3301).space.named:get(1)
---
- [1]
...

localhost:3301> require('net.box').connect('localhost', 3301).space.named:get(1).id
---
- null
...```

**Comment by Gerold103** [comment]
It is a big matter, must we add tuple formats to a binary protocol or not. Consider both variants:
## Do not change protocol. Only Lua and netbox hacks.
If the binary protocol does not support format then, `CALL/EVAL` requests can not return tuples with names. Formats and field names for DML/DQL results can be build on a client side. (Via either switching netbox to box.tuple + tuple_format from lua tables, or adding names as attributes of lua tables);

## Extend binary protocol. `IPROTO_TUPLE_FORMAT`.
If the binary protocol supports format, then any tuple returned from any request can have names and other format features on a client side. But this extends the binary protocol in a complicated way with at least two problems:
* There are several requests, that return multiple tuples as array of arrays. And there is no place to insert a new field - format content or format id for each tuple. Two decisions of the problem exist:
    * Reuse `IPROTO_METADATA` to store format identifiers for each tuple in the packet header like in SQL is done;
    * Change format and store each tuple as map: `{IPROTO_METADATA: <tuple_format>, IPROTO_TUPLE: <tuple_data>}`. To provide back compatibility by default use the old protocol with no `IPROTO_METADATA` for each tuple. And to switch to a new protocol add a new iproto command: `IPROTO_CTL`, which apart from subcommands in #3055 will have `IPROTO_CTL_RETURN_TUPLE_META: <boolean>` subcommand.
* How to send tuple formats to a client? They can not be returned with each response because it is too expensive. And how to identify formats - by identifiers from a server, or generate another identifiers on a client? There are several decisions:
    * The first and the most correct as I think - return tuple formats as results of `IPROTO_CTL_RETURN_TUPLE_META: true`;
    * Add a new system temporary readonly space `_format` and simply select from it to get formats (including identifiers, nullability, types, names, is_key_part ...). A client must select formats, send `IPROTO_CTL_RETURN_TUPLE_META: true` to a server and use formats;
    * Introduce a new iproto command: `IPROTO_GET_FORMATS`. It seems to be a crutch;
    * Do not use identifiers from a server formats. Build them on a client side from _space and _index, and with each tuple return not format identifier, but space identifier (in `IPROTO_METADATA`).

**Comment by Gerold103** [comment]
With @kostja we have decided to do not modify a binary protocol. And it is enough to provide names for DML/DQL responses. Tuples, returned from it, must have tuple format with corresponding names. And a new problem is that tuple formats count is limited by UINT16_MAX. So if an instance have about 10k connections, tuple format count is already too big. The raw idea is to store tuple formats per connection. And do not store them in a global array - it is not necessary for tuples on a client side.
