### ISSUE TITLE
sql: extra copy in tarantoolSqlite3Insert

### ISSUE THREAD

**Issue by Khatskevich** [tarantool/tarantool#3021]
This function do extra memcpy, because wal thread accesses this memory on commit.

2 solutions 
 - pass data which is already allocated on region (allocate on region during OP_MakeRecord)
 - make wal use tuple right from memtx or vinyl and not make passed msgpack live until the end of commit.

**Comment by Gerold103** [comment]
* We can not pass region data. The tuples live time is longer, the a transaction live time. But region is truncated after transaction is finished.
* Wal writes not tuples, but specially encoded structures (see struct xrow_header and xrow_encode_dml). And a tuple data is encoded here within a message pack map with key IPROTO_TUPLE. So it is not enough to reference tuple and pass its raw data. The entire xrow encoding mechanism must be redesigned to do it. And in any case tuple data will be copied during encoding xrow_header - it will be done either in tx thread or in wal thread. And a second case is even slower, because Wal thread has single fiber which will encode rows from all transactions, but tx thread is multifiber, and it encodes rows in different fibers - one per transaction. It allows to encode new rows in new transactions, while Wal thread is busy by commited transactions.

**Comment by Gerold103** [comment]
Ok, I understood, that the first proposal is not for tuples, but for OP_MakeRecord and raw tuple data in btree payload. For this goal the proposal seems to be ok.

**Comment by Khatskevich** [comment]
Blocked by #2680
(The patches intersect heavily)

**Comment by Khatskevich** [comment]
Chosen solution:
- Allocate msgpacks (in Op_MakeRecord) directly on region
- Allocate msgpacks for ephemeral tables by malloc, so that it is possible to free them before box.commit?
- Stop using box api (due to begin_ro_stmt -> fiber_gc)

**Comment by kyukhin** [comment]
Not blocked anymore
