### ISSUE TITLE
Improve error reporting in SQL

### ISSUE THREAD

**Issue by kyukhin** [tarantool/tarantool#3036]
Here is an example w/ nasty error message.
Testcase:
```
$ cat 1.lua
box.cfg{wal_mode='none'}
box.sql.execute([[CREATE TABLE t (a INTEGER primary key, b INTEGER NOT NULL]])
```

Error produced:
```
2018-01-10 16:55:30.198 [26365] main/101/1.lua F> keyword "NULL" is reserved`
```
(error is that closing brace is missing)

**Comment by TheAviat0r** [comment]
Key problem is that we have syntax error and fallback error.

Fallback is when you use keyword in not appropriate place, for example you can execute next statement:

`CREATE TABLE ABORT(a int primary key);`

We have "ABORT" keyword with token type TK_ABORT, we have fallback rule in parse.y which says to fallback TK_ABORT to TK_ID (identifier token type), therefore error doesn't happen. If you try something else without fallback rule, you will get an error.

Key of the problem is that parser doesn't separate fallback errors and syntax errors, handling of that situation now is being done in the same parser state. If both happens and last processed keyword is reserved, we will see message 'keyword "KEYWORD" is reserved" like in the example above, not 'syntax error ... '. 

We need to implement %fallback_error clause for lemon and to distinct fallback error and syntax error and to make syntax error priority higher.
