### ISSUE TITLE
Trigger garbage collector before exit to prevent valgrind's false positives

### ISSUE THREAD

**Issue by Totktonada** [tarantool/tarantool#3071]
At least it worth to check whether this helps us with valgrind.

**Comment by Totktonada** [comment]
Tried like so:

cmake . -DSQL_MAINTAINER_MODE=1 -DCMAKE_BUILD_TYPE=Debug -DENABLE_VALGRIND=ON && make -j
valgrind --leak-check=full --show-leak-kinds=all --track-origins=yes -v --suppressions=./third_party/luajit/src/lj.supp ./src/tarantool < <(echo "print('hello'); collectgarbage()")

With and without collectgarbage() call. Got 654 errors with collectgarbage and 710 errors w/o. A lot luajit errors still reported, the overall picture does not changed significantly. We need either investigate luajit futher and deeper, or skip this effort for now and close the issue.

**Comment by igormunkin** [comment]
I believe the root cause is that [`tarantool_lua_free`](https://github.com/tarantool/tarantool/blob/master/src/lua/init.c#L750-L785) routine [**is not called**](https://github.com/tarantool/tarantool/blob/master/src/main.cc#L536-L547) due to some reasons (unclear to me). I remember @Buristan also has some complains regarding this.

**Comment by Buristan** [comment]
Yes, It is disabled via tarantool/tarantool@a718d469100a2992707c16cd251a56e5e5159be2. To me it looks like a black hole attracting memory leaks. Also, I see no tests failures (at least locally) if enable back `tarantool_lua_free()` routine. I assume, that we may **carefully** enable part of those "atexit handlers". But enabling the only one `tarantool_lua_free()` is already the good start.
