### ISSUE TITLE
sql: sql.c errors are not properly handled

### ISSUE THREAD

**Issue by Khatskevich** [tarantool/tarantool#3114]
There are a lot of places in `sql.c` where `SQLITE_TARANTOOL_ERROR` is returned and diag message is not set. This behavior leads to segfault, as `vdbe.c` `abort_due_to_error` expects it.

**Comment by kyukhin** [comment]
kyukhin@titus:/export/kyukhin/tarantool/src/src/box$ grep SQLITE_TARANTOOL_ERROR sql.c |wc -l
39

**Comment by Korablev77** [comment]
@Khatskevich Could you please provide example(s) which leads to seagfault (as more as possible/you have)? I'm asking due to the fact that error handling routine in the vdbe contains following code:
```
if (p->zErrMsg==0 && rc!=SQLITE_IOERR_NOMEM) {
	const char *m = (rc!=SQLITE_TARANTOOL_ERROR) ? sqlite3ErrStr(rc) :
		tarantoolErrorMessage();
	sqlite3VdbeError(p, "%s", m);
}
```
It can be seen that even if error is not set, the last one occurred in Tarantool will be emitted. Thus, segfault is only possible in case of returning `SQLITE_TARANTOOL_ERROR` without any error occurred in Tarantool. If it can really happen, whatever status should be returned except for an error.

**Comment by Khatskevich** [comment]
Right you are. The last error is returned. But for now it is not ok for 2 reasons:
- If an error occurred previously in Tarantool - then you will get wrong error message (about the last problem)
- If there were no errors before - you get a segfault.

I do not think that I should spend time for snippets which lead to the segfault, because it is easier just to fix the bug, then create those test cases.
Here is what I had to fix to continue work on another ticket:  https://github.com/tarantool/tarantool/commit/354e7e4d348b274f1d3dbc8b5eded24c7f167c72

**Comment by Korablev77** [comment]
> I do not think that I should spend time for snippets which lead to the segfault

Sorry, I thought you had already had them when you created this issue. 

Well, it seems that not all Tarantool routines use diag_set() when SQL-Tarantool interface returns `SQL_TARANTOOL_ERROR` -- it is a bug without any doubts . However, it wouldn't be informative enough, if always set `SQL_ERROR` code. Thus, in order to avoid passing Vdbe* structure to Tarantool-SQL interface functions (to set error message), I suggest to introduce additional set of errors (instead of one simple `SQLITE_TARANTOOL_ERROR`). For instance, it could be:
`SQL_TARANTOOL_ITERATOR_ERROR` -- in case of failure of cursor_advance/seek functions;
`SQL_TARANTOOL_INSERT/REPLACE/DELETE_ERROR` -- in case one of mentioned functions failed;
Emit `SQL_TARANTOOL_ERROR` in other cases (when we definitely sure that Tarantool used diag_set()).

Is this proposal OK to you?

**Comment by kyukhin** [comment]
I think so. But, this is still temporal solution and all those errors should be integrated into Tarantool's backend in future.
