### ISSUE TITLE
Remove collation pointers from SQL FE

### ISSUE THREAD

**Issue by kyukhin** [tarantool/tarantool#3123]
Pointer to collation string might be found in following structs:
1. `Column` (pColl)
2. `sqlite3` (xCollNeeded, pDfltColl, pCollNeededArg)
3. `KeyInfo` (aColl)
4. `Index`
5. Supplementary functions (just do grep)

As far as `struct cool*` is part of `key_part` and `coll_id` is part of `key_part_def`, most of fields defining collation might be evicted from SQL FE.

**Comment by Korablev77** [comment]
It is easy to remove/replace usage of collations from `struct Index` and `struct sqlite3` (after space creation). As for `struct Column`, it turns out that in Tarantool collation is specified only for keys, not for all tuple fields. Meanwhile in SQL it is allowed to set collation for any column. Thus, it is unclear how to substitute those usages (at least now).

**Comment by alyapunov** [comment]
* Nikita Pettik <notifications@github.com> [18/02/08 23:22]:
> It is easy to remove/replace usage of collations from `struct Index` and `struct sqlite3` (after space creation). As for `struct Column`, it turns out that in Tarantool collation is specified only for keys, not for all tuple fields. Meanwhile in SQL it is allowed to set collation for any column. Thus, it is unclear how to substitute those usages (at least now).

We can extend field_def with collation - this sets the collation
for each tuple field.

-- 
Konstantin Osipov, Moscow, Russia, +7 903 626 22 32
http://tarantool.org - www.twitter.com/kostja_osipov
