### ISSUE TITLE
Modify the coroutine scheduler to play nicely with fibers?

### ISSUE THREAD

**Issue by aleclarson** [tarantool/tarantool#3132]
Would it be worth modifying the coroutine scheduler to play nicely with Tarantool's fibers?

You'd be able to use coroutine-based Lua libraries, which expands the Tarantool ecosystem considerably.

**Comment by kostja** [comment]
Lua libraries which use coroutines will continue working with Tarantool. The problem is not with use of coroutines, but of blocking system calls. A library using  blocking I/O rather than Tarantool fio/socket libraries doesn't work well with Tarantool built-in event loop. This is why we can't take lua-websocket, as an example.
