### ISSUE TITLE
Introduce new system space for VIEWs

### ISSUE THREAD

**Issue by kyukhin** [tarantool/tarantool#3180]
Right now, looks like VIEWs implementation is complete mess.
View's data is stored as space. However, the only two fields which are
actually needed are:
1. Name
2. SQL query, to execute to look at view

Everything else bring mess, and should not belong to VIEWs anyway.
So, let's introduce dedicated system space, say `_view`, which will store
view pair: name and query

**Comment by kostja** [comment]
Views belong to the same namespace as base tables in SQL. By putting their definition in a separate space, you'll have to enforce unique constraints on views/table names manually. You also may complicate access control, for the same reason - you may need to differentiate grants on views and grants on tables in access control system. Yes, views being stored in _space system space is not relational, so what. BTW, we need to make sure views are visible in Lua as spaces - otherwise they are useless in NoSQL part of the platform.

**Comment by kostja** [comment]
Suggestion: won't fix.
