### ISSUE TITLE
Per-module logging

### ISSUE THREAD

**Issue by knazarov** [tarantool/tarantool#3211]
I'd like to be able to instantiate logger objects per module, and be able to set log_level per-module as well.

This is needed to debug production problems, as enabling debug logging system-wide produces too much data.

**Comment by Totktonada** [comment]
Reading for inspiration:

https://www.python.org/dev/peps/pep-0282/
https://docs.python.org/3/library/logging.html
http://logback.qos.ch/manual/architecture.html

**Comment by Totktonada** [comment]
Points to don't forget:

* A code that uses logger and want to support hot reload should work gracefully. It seems, we can just make loggers be singletons or kinda: the same name will give the same logger object.
* Optimization: store effective log level in an instance itself (don't traverse the hierarchy upward at each write to log) and update the effective log level at each reconfiguration of the logger or **its ancestor**.
  - Don't forget about such case: we have `foo`, `foo.bar.baz` loggers and the new `foo.bar` is created.

**Comment by akudiyar** [comment]
It would be nice to see a MDC-like context that may be shared between modules in scope of this feature. Also the default logging should respect the module names by default, making effective log separation, if the other custom prefixes are not set.

See:
http://logback.qos.ch/manual/mdc.html
https://www.baeldung.com/mdc-in-log4j-2-logback

**Comment by Totktonada** [comment]
Not everything within one issue :) We'll consider other logger improvements, but, please, file another issue regarding MDC. If you'll mark it with the [logger](https://github.com/tarantool/tarantool/issues?q=is%3Aissue+is%3Aopen+label%3Alogger) label, we'll not miss it.

Regarding automagic determination of a prefix, there are several points against:

* Backward compatibility 1: the old code should produce the same result as before, including syslog identity information. That's good question: should we always set indentity the same as a logger name or leave it 'tarantool' by default with ability to change?
* Backward compatibility 2: the old code -- the same result, so setting a log level of the default logger **must** affect logging of `require('log').{error,warn,info,verbose,debug}(<...>)` messages in modules.
* There is no general way to determine a module name, because file layout may be different: we don't know whether we should give `foo.bar.baz` logger to a module or just `bar.baz`. So it may lead to unexpected effects.

**Comment by Totktonada** [comment]
I guess we want to use the hierarical logger in general purpose modules, so an application developer or an administrator may choose how verbose logs should be for different components of the applicaition.

However a general purpose module should also support older tarantool versions, which have no hierarical logger.

It would be great to provide such API that a module can easily acquire own logger, but fallback to the default logger, when a old tarantool version is used.

To illustrate the idea, the naive attempt to add hierarical logger support would have such API:

```lua
local log = require('log').new('foo.bar.baz')

local function do_work()
    log.info('start work')
    <...>
    log.info('done work')
end
```

However if the module wants to be compatible with old tarantool versions, it should do the folllowing:

```lua
local log = require('log')
if log.new ~= nil then
    log = log.new('foo.bar.baz')
end

<...>
```

That does not look nice: too much code for the most common usage pattern. I have no solution yet.

Another problem here: updating of a module **must not** change behaviour of an application (must not split loggers). Possible solution: always give the default logger (ever for `.new('foo.bar.baz')`) until a particular option like `log.ROOT_LOGGER.cfg{hierarical = true}` is enabled.

Should the `hierarical` option be applicable only for the root logger? I guess it would simplify the implementation. I guess an application either use hierarical logger or does not and there is no much sense to make the option be applicable for any logger.

(I assume that the default logger 'tarantool' is the child of the root logger ''.)

**Comment by Totktonada** [comment]
@AnastasMIPT Are you working on the task? I'll reassign it to your team so (and will exclude from my team's list of candidates for next tasks).

Please, let me know when you'll have a complete design vision (backward compatibility is especially interesing topic here).

**Comment by alyapunov** [comment]
PRD https://hackmd.io/LyoPw0DpQSG2yy9pYXyKJQ?view

**Comment by AnastasMIPT** [comment]
@Totktonada Yes, I'm working on it right now.

The design is not yet completely finished. So far, I am comparing in terms of performance the two methods of alloying - the one you suggested above and the one I described below.

We can use `debug.getinfo().short_src` to find out in which file the function that called `log.info` is defined.  The file name almost always contains the module name. Also, we can build an index in advance that gives the name of the module based on the file name. 
This way will only change the logging function in core, without changing the module code.

**Comment by Totktonada** [comment]
I'm against of autodetermination of a 'module name':

1. Author of a module have no control how its module is named from logger perspective.
2. What name should be issued for `log.info()` call from /some/path/my_module/foo/bar/baz.lua? What if /some/path and /some/path/my_module are present in LUA_PATH both?
3. If I move `log.info()` call from my_module/init.lua to, say, my_module/utils.lua, API of the module will be implicitly changed (a user will need to change its code to enable/disable this log message).
4. How can I set the same logger name for calls in my_module/foo.lua and my_module/bar.lua?
5. `debug.*` is likely not quite fast.

And I don't see why we should aim to the goal 'provide ability to selectively disable logging per-module without changes in modules'. If one want to use the new functionality, so one need to update its module — it is perfectly ok. We should just keep the old code working, sure, but we must not provide ability to selective enabling / disabling of logs for old modules.

**Comment by R-omk** [comment]
@Totktonada, I suggest making an abstraction instead of using the concept of "module".
Introduce the concept of "fields" for an "instance" of a logger.
"Fields" is an ordered map [key-string]value-string.
Each logger instance can be a constructor at the same time to create a new logger, which will be based on the parent one.
Some field keys can be "well known" keys, some of which can be set implicitly in the constructor (for example, module name, version, file path, etc.).
Further, these fields can be used to configure formatters and/or set the logging level.

```lua

local log = require('log')  -- some well known fields exposed automatically

log.info("hello %s", 'world')

local child_logger = log.new{ fields = {{"key1", "value1"}, {"key2", "value2"}} }

child_logger.info("hello %s", 'world')

local another_log = require('log'){ fields = {{"key3", "value3"}} , formatter= some_func }

```

Each individual instance can have its own logging level and formatting function, these settings can be changed at runtime. 
All instances of loggers are stored in the global registry. Instances are searched by fields.

```lua

log = require('log')   -- Using the root log constructor

log.set_level(7, { match = { key = 'key2', value = 'value2' } })  

-- log.set_formatter ( some_func, { match ....})


```

_Currently the fields are already used in a similar manner when setting_ `box.cfg{log_format='json'}`


_Inspired by
https://github.com/sirupsen/logrus
https://github.com/uber-go/zap_

**Comment by unera** [comment]
Looking for a way to do that backward compatible:

```lua
local log = require('log').new('foo.bar.baz')
```

We want to avoid patching modules, so it seems there are several way to do:

- patch `box.{info,debug,...}` to resolve module (package) name
- patch `_G.require('log')`  - to resolve module name per `require 'log'` (@igormunkin's way)


We want to do something like:

```lua
box.cfg {
   log_level = 'DEBUG',
   module_log_level = {
       expirationd = 'INFO',
       ['foo.bar.baz'] = 'SYSERROR'
       -- etc
   },
}
```

Goals:
- A user doesn't need to patch his module to switch log_level per his module.
- Also we could provide `require('log').new(NAME)`, too.

Now we want:
- to get "Proof of concept"
- validate it by @Totktonada and @igormunkin

**Comment by Totktonada** [comment]
I agree with @R-omk, we should not do any sometimes-work automatic logger name determination, we should not introduce concept of the 'module' as replacement for logger name. I already wrote why. I already linked other popular APIs. Please, validate your ideas against my arguments, not me.

**Comment by AnastasMIPT** [comment]
I have implemented some of the proposed methods and measured their performance.

<details>
<summary>Benchmark results</summary>

I. Default log time

II. Time without changing code with simple approach (automatically define the module inside the logging function) module name

III. Time without changing code with simple approach just file

IV. Time with [Alexandr Turenko's approach](https://github.com/tarantool/tarantool/issues/3211#issuecomment-792199926) with module code changes

V. Time with Igor Munkin's modification (described [here](https://github.com/tarantool/tarantool/issues/3211#issuecomment-974001964)) of Alexander Turenko's approach, without module code changes


|                                  | mean    | max      | min    |
| :---                             | :-----: |  :----:  | ---:   |
| I.   Default approach            | 0.2119  | 0.2308   | 0.2020 |
| II.  Simple approach module name | 0.3501  | 0.3536   | 0.3467 |
| III. Simple approach just file   | 0.3109  | 0.3119   | 0.3094 |
| IV.  Alexandr Turenko's approach | 0.2037  | 0.2056   | 0.2023 |
| V.   Igor Munkin's modification  | 0.2105  | 0.2261   | 0.2031 |

|                                  | Need to modify module's code | RPS        |
| :---                             | :---                         |    :----:   |
| I.   Default approach            |  No                          | 471916.46   | 
| II.  Simple approach module name |  No                          | 285553.80   |
| III. Simple approach just file   |  No                          | 321612.82   |
| IV.  Alexandr Turenko's approach |  Yes                         | 490686.84   |
| V.   Igor Munkin's modification  |  No                          | 475016.25   |

</details>

 You can see all the source code [here](https://github.com/AnastasMIPT/ModuleNameExperiments).

**Comment by Mons** [comment]
Do not ever do this by overriding built-in `require`.
1. It will eventually break in case of any wrapping of require.
2. Agree with @Totktonada: file name != module name.

**Comment by AnastasMIPT** [comment]
I implemented a proof-of-concept for the method with the require wrapper.

My thoughts about [these](https://github.com/tarantool/tarantool/issues/3211#issuecomment-971293856) and [these](https://github.com/tarantool/tarantool/issues/3211#issuecomment-986692147) points:

> 1. Author of a module have no control how its module is named from logger perspective.

> 2. Agree with @Totktonada: file name != module name.

In the implementation, the author can call log.new('module name') immediately after calling require('log'), allowing him to put the name he wants.

> 2. What name should be issued for `log.info()` call from /some/path/my_module/foo/bar/baz.lua? What if /some/path and /some/path/my_module are present in LUA_PATH both?

As far as I know, in LUA_PATH paths are not stored in their original form, but as a pattern some/path/?.lua or some/path/?/init.lua and so on. In the situation where there are paths `path/?.lua`, `path/my_module/?.lua` and we analyze path `path/my_module/submodule.lua`, we get the name `my_module.submodule` or `submodule`, depending on which comes first - `path/? .lua` or `path/my_module/?.lua`, because the algorithm sequentially cuts off all prefixes from LUA_PATH and other places where `reqiure` looks for packages. It seems rather strange to me to add to the search directory a directory that is itself a module.

> 3. If I move `log.info()` call from my_module/init.lua to, say, my_module/utils.lua, API of the module will be implicitly changed (a user will need to change its code to enable/disable this log message).

In this case, the name automatically determined by the proposed algorithm would be `my_module.utils` instead of `my_module`. The user does not have to change his code, because when the parent module `my_module` is disabled, the children are disabled as well, including `my_module.utils`. I suppose this is quite expected behavior.

> 4. How can I set the same logger name for calls in my_module/foo.lua and my_module/bar.lua?

They will automatically be named `my_module.foo` and `my_module.bar`, but you can call log.new('module name') in their source code to set the same name. Or just disable the parent module `my_module`.

> 5. `debug.*` is likely not quite fast.

This problem is solved by overloading `require`. This method does not degrade performance according to the [benchmark](https://github.com/tarantool/tarantool/issues/3211#issuecomment-983768922) above. However, the require function itself is now a little slower for arbitrary module queries and a lot slower for `require('log')`.

> 1. It will eventually break in case of any wrapping of require.

If I understand correctly, we are talking about a situation where module loading is wrapped in some script. For example, we have a module `my_module` and we load all packages for it with the script `my_module/loader.lua`. In this case the name will be defined as `my_module.loader`. It seems that in this case we will still have a pretty good name definition. In any case, even if the automatic module definition does not work as expected, it is still possible to expose it yourself with `log.new('my_module')`.


I also think this method is pretty good because it doesn't require rewriting existing module code, if the user doesn't like the name that was automatically defined, he can put it up himself. This way can still be extended to ways that do not introduce the concept of the 'module' as replacement for the logger name suggested by  @Totktonada and  @R-omk , while still being a good basic option.

**Comment by alyapunov** [comment]
Ok, good, `require` redefinition seems to work good. The only problem is that someone can redefine `require` too, and that will break our module determination will break. Am I correct?
Another approach that should be investigated is to cache module name somewhere in lua upvalues..

**Comment by Totktonada** [comment]
What is 'multiple require override problem'? Can you describe it in terms of a behaviour of a user code? IOW, show an example, its expected behaviour and its actual behaviour without the solution you proposed.

**Comment by unera** [comment]
Now it looks like good for me.

You need transform the patch from PoC to common patch, so You need to have a reviewer.

@alyapunov ?

**Comment by unera** [comment]
@alyapunov 

The PoC looks good:

- `+` - Backward compatible changes
- `+` - Nobody can break the mechanism by redefine `require`
- `+` - The way with `log.new('name')` is accessible.

So, I think You should transform the PoC to patch and merge it to master.

**Comment by unera** [comment]
I think that module_name should be concatenated with fiber_name

example:


`main/103/interactive/box.foobar`

**Comment by unera** [comment]
box.cfg format

```lua
box.cfg{
   log_level = 3
}
```

and

```lua
box.cfg{
   log_level = {
       default = 3
   }
}
```

are the same

Then we can configure each module (if we want):

```lua
box.cfg{
   log_level = {
      default = 3,
      modules = {
           expiration  = 4,
           ['foo.bar'] = 1,
      }
   }
}
```

Note: user can use strings instead numbers: `box.cfg{log_level = 'error'}`
