### ISSUE TITLE
Hot-reloading replica in 1.9 regularly failed with "duplicate connection with the same replica UUID"

### ISSUE THREAD

**Issue by Mons** [tarantool/tarantool#3216]
Tarantool 1.9.0-11-g0cf2780

It's a common case to hot-reload code on the replica
During hot reload config applied again
During this replication restarts
So, we have a sequence:
on replica: 
- old connection destroyed.
- new connection created.
on master:
- new connection established
- old connection reset

This rather probable case result in
```
2018-03-06 06:25:37.986 [68533] main/115/applier/127.0.0.1:20011 xrow.c:788 E> ER_CFG: Incorrect value for option 'replication': duplicate connection with the same replica UUID
```
on replica

**Comment by kostja** [comment]
@mons please provide us with steps to reproduce.

**Comment by kbelyavs** [comment]
It seems that this is not an error. This message appears when other side rejects connection because it has not yet been able to change state to 'disconnected' but after that tarantool catch this error and goes to reconnect loop, so after a little time connection will be established.
To prevent this message, you can add a small delay between two box.cfg { ... } call.

**Comment by Mons** [comment]
It seems we can't reproduce raising an error during box.cfg
close for now
