### ISSUE TITLE
Publish packages of every released version

### ISSUE THREAD

**Issue by knazarov** [tarantool/tarantool#3337]
Every released version (including patchlevel increments) should be published in rpm/deb repos for consumption.

This is required to pin certain tarantool version in production to not accidentally get any regressions from updates.

**Comment by Totktonada** [comment]
Many things were changed since 2018:

* We moved from packagecloud.io or our own storage and don't prune packages anymore.
* We stop deploying per-push builds since tarantool 2.10.0. Now only pre-releases and releases are offered for users.

See #3380, #4947 and #6182 ('delivery channels' section).

We may consider publishing some per-push/intermediate builds, debug builds, special builds for using in testing, see https://github.com/tarantool/setup-tarantool/issues/28 and https://github.com/tarantool/setup-tarantool/issues/29. But it is another topic. If it is only for testing of modules, we aren't obligated to support apt/yum repository metadata and offer all the supported distros.

I'll close the issue, because it becomes irrelevant now.
