### ISSUE TITLE
update: allow update absent nullable fields

### ISSUE THREAD

**Issue by Gerold103** [tarantool/tarantool#3378]
Now in tarantool a one can do this:
```Lua
box.cfg{}
format = {}
format[1] = {name = 'field1', type = 'unsigned'}
format[2] = {name = 'field2', type = 'unsigned'}
format[3] = {name = 'field3', type = 'unsigned', is_nullable = true}
format[4] = {name = 'field4', type = 'unsigned', is_nullable = true}
s = box.schema.create_space('test', {format = format})
pk = s:create_index('pk')
s:replace{1, 2}
```
In the inserted tuple `{1, 2}` fields 3 and 4 are 'virtual' nulls - they are interpreted as `NULL`, but are not stored. But the fields presence illusion is dispelled when I do this:
```Lua
s:update({1}, {{'!', 4, 0}})
```
It leads to an error, because update operation `!` can not insert with gaps. But lets allow to do this, if gaps are virtual `NULL`s. This operation must fill gaps with `NULL`s.

Same about `=`. Operation `#` must be able to become no-op, when a field is a virtual NULL.

**Comment by kyukhin** [comment]
Have you implemented this already in your json path update patch?

**Comment by Gerold103** [comment]
No, it is a separate task.

**Comment by alyapunov** [comment]
In this issues we was supposed to do something with 'nullable' fields. It is stated both in title and body.
After some online discussion of the issue we decided to allow update any field of a tuple, despite it's properties. Actually I don't like it because of several reasons. But OK.
Now we are under discussion of what should be done with updates of nested arrays, which could not have nullable fields at all. I think that's should be another issue with difference complexity and priority.
So, in this issues:
 * we must implement extension of tuple itself with nils.
 * we must not extend nested arrays.

For the second part we should create a new issue and start discussion there. And the discussion will be long, believe me.
