### ISSUE TITLE
Deploy package repos on MRG's S3 infra

### ISSUE THREAD

**Issue by kyukhin** [tarantool/tarantool#3380]
The deployment should support mirroring.

**Comment by Totktonada** [comment]
And tarballs too?

**Comment by Totktonada** [comment]
Ouch, it is already here. Sorry.

**Comment by Totktonada** [comment]
> The deployment should support mirroring.

I don't undestood what exactly you meant.

----

Motivation: We want to solve problems we have currently with packagecloud repositories. More precisely, there is the one biggest problem: we have a lot of packages (tarantool itself / modules / connectors and so on × multiple supported distros × multiple versions) and so we call to prune old package versions to keep a [payment](https://packagecloud.io/pricing) within some limit.

Pruning of old packages (even despite that it saves all last versions) makes the repositories unusable for many cases, because one is unable to hold a version of packages w/o saving them locally somewhere. I know projects (including internal ones!) with RPMs within a project repository; I also saw customers' mirrors of our packagecloud repository — users try to workaround the problem. I also saw questions how to install a specific version to, say, bisect some problem.

We have MRG infrastucture that provides S3 compatible storage that abstract us out of most problems with supporting a reliable service.

We have nice [mkrepo](https://github.com/tarantool/mkrepo/) tool that generates and updates yum and apt repositories. It support S3 compatible storages.

Our documentation [shows](https://www.tarantool.io/en/download/os-installation/1.10/debian/) download.tarantool.org URLs that can be switched to another backend almost seamlessly. The only problem here is that packagecloud does not give us private repository keys, so we need to either install our new keys within tarantool package for some time period (and only then switch) or leave instructions how to update keys manually after we'll switch download.tarantool.org repos (see #3736).

----

We discussed a bit how to achieve the goal with @avtikhon. He looking for other tools instead of mkrepo, but I don't see any reason to do so. Hope he'll clarify his points here. I'll show mine points below as answers for questions that were arisen around this task in near days.

From my side, strengths of mkrepo:

* Simple and our own (easy to support).
* Support both apt and yum.
* Support S3 natively as storage (doesn't require a full local copy).

Pros of creating our own repositories instead of mirroring packagecloud ones:

* Simpler infrastructure.
* Less fault points in a deployment process.
* We don't depend on timings when packagecloud will enable support of new distros (they however make this very fast when it is requested explicitly).

I see several cons of proposed using of reprepro (and see no pros):

* First of all: no (working) project website, no public repository.
  - I saw some mirros on github like [this](https://github.com/esc/reprepro/commits/master) which does not look as official nor as supported.
  - Hey, a lot of C code; looks much more complex that our pythonic mkrepo.
* Debian specific (no yum repos support); more on that:
  - What with yum repos? Some other tool is needed?
* Requires to have a local mirror; more on that:
  - A cumulative size of repos will growth in linear way (now it is constant because of pruning).
  - We should support a (more or less) reliable storage for that mirror; that is what we want to avoid by using MRG's S3.
* We don't control behaviour of that tool; more on that:
  - Say, I saw comments that the tool allows to handle only one version of a package. If it is so, then it just contradicts to our goals.
  - I saw comments that it does not report an error in the case when you are trying to push a version of a package that is older then an existing one.

Alexander (@avtikhon) also met several small [problems](https://github.com/tarantool/mkrepo/issues/14) with mkrepo. We'll resolve them; it should not affect our decision. If there is suspect that mkrepo is not enough qualitative, then it should be said explicitly. At the first glance it looks much more maintainable then reprepro and it seems that it fit our needs much more better.

----

As Gentoo user I wondered that we need to separate repositories per \<major\>.\<minor\> tarantool versions (say, 1.10, 2.1, 2.2, 2.3). As I understood, this is workaround for two problems:

* A maintainer is unable to mark different versions of a package as stable / unstable within one repository.
* A user is unable to mask a specific version range to, say, install tarantool of 2.2 series, but receive updates for it.

Brief googling does not give solutions for those problems for apt-get and yum. It seems that package managers in most popular distros are not very flexible.

So we need to provide separate repositories anyway.

**Comment by avtikhon** [comment]
'reprepro' tool is the officially suggested tool by Debian:
https://wiki.debian.org/DebianRepository/Setup#reprepro
```
reprepro
(formerly known as mirrorer)
Goals: Local Debian package repository storing files in a pool/ directory.
Pros:
Strict checking of what comes in, no database server needed.
Cons:
Lots of different options and commands, difficult to use for beginners.
Package: reprepro

Distributions: stable, testing, unstable and squeeze-backports

Dependencies: unstable/utils/reprepro

Automatic repositories: Yes
Incoming mechanism: Yes
Pools: Yes
GPG signing: Yes
Inclusion of .deb without .changes: Yes
Several versions of each package: not in the same Packages instance
Manual: Yes

HOWTOs:
Short HOWTO (official)

Setting up signed Debian repository with reprepro

Setting up your own automatic Debian repository see this article on reprepro. The link is rather outdated, but still contains some useful information.

Setting up reprepro with apache2 and sign key (in italian language) http://www.fabreg.it/reprepro-repository-debian-43/

Creating your own Signed APT Repository and Debian Packages by Jon Cowie
```
Positive:
```
It means that we don't need to follow the changes in Debian packages formats.
No need to support the local tool 'mkrepo'.
```
Other:
```
Yes, we need separate repositories for YUM and DEB and it is right way.
Local repositories won't take much space, also it will provide the local backup and ability to check/work with local copy.
```
mkrepo -  "Supports S3 natively as storage (doesn't require a full local copy)."
```
It means that we have some tool that supports unknown way to use S3, while there is the AWS official tool 's3fs' for mounting the S3 buckets, which is already known as buggy - does it mean that mkrepo is better ?
```

**Comment by Totktonada** [comment]
So, the options are:

* Use the simple (and controlled by us) mkrepo tool that do exactly what we want and support everything what we want.
* Glue three different tools that that doing something more or less what we want, each more complex then mkrepo, non-controlled by us, require extra infra (local mirror) — so it is hard to run just, say, on Travis-CI.

(Note also the reprepro just doesn't fit if it supports storing only a last versions of a package — I already wrote about that above.)

For me the choose is obvious. However this is not my task, so either do it as you want (but don't ask me for review) or ask Kirill (@kyukhin) to decide.

**Comment by Totktonada** [comment]
Mounting S3 storage via FUSE eliminates the need of a local mirror. Other points remain valid.

**Comment by avtikhon** [comment]
Actually found that s3fs really works and mounts the external S3 to the local path, the only issue found that it fails with path names including dots, which produces the 404 not found respond from S3.
