### ISSUE TITLE
TAP testing infra should report SEGFAULTs instead of new

### ISSUE THREAD

**Issue by kyukhin** [tarantool/tarantool#3383]
If a test crashes, TAP testing frequently (or always) reports its result as `new`, which
is wrong. It should report it as `fail`.

E.g. this is the case in #3382. Output was:
```
======================================================================================
WORKR TEST                                            PARAMS          RESULT
---------------------------------------------------------------------------------
[001] sql-tap/gh2548-select-compound-limit.test.lua
[001] TAP13 parse failed: Missing plan in the TAP source
[001] [ new ]
---------------------------------------------------------------------------------
Statistics:
* new: 1
``` 

However, GDB clearly shows that this is actually a crash.

**Comment by Totktonada** [comment]
It will (at least partially) eliminated by fixing https://github.com/tarantool/test-run/issues/68

**Comment by Totktonada** [comment]
Let's consider it as fixed in https://github.com/tarantool/test-run/commit/dac6b2b4640a7dd3d130ddde13bb4b25a730a4ad

After this commit test-run looks at exit code of tarantool that executes a `core = app` test. If it is non-zero (the process exits abnormaly or was killed by a signal), then fail will be reported. This check catches segfaults and unhandled Lua errors.

test-run still can consider a test w/o a result file as `[new]`, however it is hard to mistakely exit from a tap test with zero exit code. We should either call os.exit() explicitly or run box.cfg() with `background = true` option. The former has no sense in a tap test, the latter is anyway not expected by test-run and will not work correctly.
