### ISSUE TITLE
Ignore replication_connect_quorum at bootstrap

### ISSUE THREAD

**Issue by lenkis** [tarantool/tarantool#3428]
At replica set bootstrap -- when calling `box.cfg{}` for the first time, when no replica set exists yet -- an instance currently ignores `replication_connect_quorum` and tries to connect to all replicas in `box.cfg.replication`.

It also ignores replication_connect_quroum when issuing box.cfg{replication} for a second time after box.cfg.

**Comment by GeorgyKirichenko** [comment]
It might be a cause for cluster inconsistency, because all new nodes SHOULD be bootstrapped from one master (at same time exactly).
My proposal is wait for all possible masters until timeout is reached but not raise an error if quorum is reached (this is changed). This allows us to choose the same leader from all currently working replicas. Timeout should be large enough to connect to all working replicas.
