### ISSUE TITLE
sql: check constraint name for duplicate 

### ISSUE THREAD

**Issue by kyukhin** [tarantool/tarantool#3503]
Taken from #2350.

There is no error if two constraints have the same name.
Temporarily this might be okay because constraints
are not stored and it is impossible to drop constraints;
however, eventually those things will be supported, and
I believe it would not be difficult to prevent duplication
within a single CREATE TABLE statement.
```
box.sql.execute("CREATE TABLE te10 (s1 INT, CONSTRAINT c PRIMARY KEY (s1), CONSTRAINT c CHECK (s1 > 0));")
Result = no error.
```

**Comment by Gerold103** [comment]
It is not a trivial task to do not duplicate constraint name because of some non-trivial cases:
1. I can assign a name to NULL/NOT NULL: `box.sql.execute('CREATE TABLE test (id integer primary key, b integer constraint c1 NULL)')`. Where should we store this `c1` constraint? We have no any storage for this now.
2. I can assign a name to DEFAULT: `box.sql.execute('CREATE TABLE test (id integer primary key, b integer constraint c1 default 300)')`. Where should we store this name?
3. The same about COLLATE: `box.sql.execute('CREATE TABLE test4 (id integer primary key, b text constraint c1 collate "binary")')`.

And now realise that we can alter constraints set via adding/dropping indexes, foreign keys.

Possible decisions:
* add an explicit name to each constraint inside box. So `is_nullable` will have an optional name inside format, as well as collation name. I will allow us to insert named collations the same way as anonymous, and internally push them into a hash table per space. First rough and ready example of box API:
```Lua
format = {}
format[1] = {name = 'field1', type = 'unsigned'}
format[2] = {name = 'field2', type = 'string', collation = 'unicode', collation_constraint = 'constr1'}
format[3] = {name= 'field3', type = 'unsigned', is_nullable = false, is_nullable_constraint = 'constr2'}
box.schema.create_space('test', {format = format})
...
```
Looks not okay because of too long names and mixed structure of names among other fields. Another example of API:
```Lua
format = {}
format[1] = {name = 'field1', type = 'unsigned'}
format[2] = {name = 'field2', type = 'string', constraints = {constr1 = {collation = 'unicode'}, constr2 = {is_nullable = false}}}
format[3] = {name = 'field3', type = 'unsigned', constraints = {constr3 = {is_nullable = true}, constr4 = {default = '300 + 100'}}}
...
```
This is better, but looks more complicated though. And does not allow to describe multi-column constraints like checks. Another option, which is more like classic SQL, when constraints are described in a separate section of CREATE TABLE statement:
```Lua
format = {}
format[1] = {name = 'field1', type = 'unsigned'}
format[2] = {name = 'field2', type = 'string'}
format[3] = {name = 'field3', type = 'unsigned'}
constraints = {}
constraint[1] = {name = 'constr1', check = 'field1 < field3'}
constraint[2] = {name = 'constr2', column = 'field2', collation = 'unicode'}
constraint[3] = {name = 'constr3', column = 'field3', is_nullable = false}
box.schema.create_space('test', {format = format, constraints = constraints})
```
This is the best one as I think, but
1) it requires changes in how to store checks. Now they are stored in _space as a `checks` field, but will be stored as a part of `constraints` field. It is easy to convert existing checks into this format in the upgrade script though.
2) it does not allow to describe foreign keys and unique constraints (while). Mostly due to lack transactional DDL. But it is easy to allow these constraints later.

* another major option - create a system space `_constraints`, in which we will insert all constraint names and types in a format like {space_id, constraint_name, constraint_type}. Space_id + constraint_name are primary index and guarantee uniqueness of names inside a table. Type specifies unique, check, default, not null etc. This way looks 1) consuming one more system spaces slot, 2) consuming memory to store these things in tuples instead of a simple and compact hash table in struct space, 3) not working because we do not have transactional DDL to insert at the same time into _space/_index/_fk_constraints and into _constraints.

**Comment by Gerold103** [comment]
@Korablev77 proposed to add more constraint system spaces like here: https://docs.microsoft.com/ru-ru/sql/relational-databases/system-information-schema-views/check-constraints-transact-sql?view=sql-server-2017. @kostja agreed. But note, that it will destroy our 'transactional' DDL which is now executed usually in a single row, and afterwards each DDL operation will change one real system space (_index, _space ...) and one 'information schema' space (CONSTRAINT_TABLE_USAGE, CHECK_CONSTRAINTS ...).

**Comment by Gerold103** [comment]
From this discussion it is clear that column constraints shall not have a name: https://github.com/tarantool/tarantool/issues/3820

**Comment by Korablev77** [comment]
Well, I would like to point out that it is not proposal, it is our goal - to implement informational schema. Hence, sooner or later we should cope with it. On the other hand, we can wait until transactional DDL is implemented.

Also why can't we rely only on _index space during recovery? I mean it doesn't matter what is in information schema (IS) spaces, we will always force values in _index space and propagate them to other IS spaces.

**Comment by pgulutzan** [comment]
The suggestion above "Do not allow to name anything but UNIQUE, PRIMARY KEY, CHECK, FOREIGN KEY/REFERENCES" is good regardless of the result of this issue. That is, default clauses and collate clauses are not constraints so they do not need constraint names.

**Comment by pgulutzan** [comment]
While looking at duplicates in CREATE TABLE syntax, please also consider CREATE TABLE t99 (s1 INT,UNIQUE(s1,s1),PRIMARY KEY(s1));
