### ISSUE TITLE
sql: wrong types on concatenation w/ RANDOMBLOB()

### ISSUE THREAD

**Issue by kyukhin** [tarantool/tarantool#3544]
TYPEOF(randomblob(5) || zeroblob(5)) is 'text'.
This is SQLite behaviour -- || always causes text
or null results -- but once again it seems to be a
rule that depends on the operator, not the operands.
```
box.sql.execute("VALUES (TYPEOF(randomblob(5) || zeroblob(5)));")
```
Result = 'text'

This is a part of #2347

**Comment by Korablev77** [comment]
Ok, this bug turns out to be severe: zeroblob() usage leads to assertion (sic!):
```
tarantool> select zeroblob(5)
Assertion failed: (0), function lua_push_row, file /Users/n.pettik/tarantoolOrigin/tarantool/src/box/lua/sql.c, line 61.
Abort trap: 6
```

I'm not going to open new issue, let's fix it in scope of current problem.

**Comment by Korablev77** [comment]
For the record: according to ANSI, if one of concatenation operands is of TEXT type, then the rest must have the same type. Otherwise, error is raised. The same for binary-like types. Now concatenation operator ('||') accepts even numeric types. I suggest to re-work concatenation operator to allow only string-like types and validate their type equivalence.
