### ISSUE TITLE
Foreign key mismatch error for an integer

### ISSUE THREAD

**Issue by pgulutzan** [tarantool/tarantool#3621]
I have Ubuntu 14.04. I have Tarantool 2.0 pulled from source today.

I execute these statements:

CREATE TABLE char1 (s1 CHAR PRIMARY KEY);
CREATE TABLE char2 (s1 CHAR PRIMARY KEY, s2 CHAR REFERENCES char1 (s1));
CREATE TABLE xchar1 (s1 CHAR COLLATE "unicode_ci" PRIMARY KEY);
CREATE TABLE xchar2 (s1 CHAR PRIMARY KEY, s2 CHAR COLLATE "unicode_ci" REFERENCES xchar1 (s1));
CREATE TABLE real1 (s1 REAL PRIMARY KEY);
CREATE TABLE real2 (s1 REAL PRIMARY KEY, s2 REAL REFERENCES real1 (s1));
CREATE TABLE blob1 (s1 BLOB PRIMARY KEY);
CREATE TABLE blob2 (s1 BLOB PRIMARY KEY, s2 BLOB REFERENCES blob1 (s1));
CREATE TABLE int1 (s1 INT PRIMARY KEY);
CREATE TABLE int2 (s1 INT PRIMARY KEY, s2 INT REFERENCES int1 (s1));

Every one of these statements succeeds -- except the last one. Result:
- error: 'Failed to create foreign key constraint ''FK_CONSTRAINT_1_INT2'': field type mismatch'

Minor problem: issue#3033 sql: make foreign key mismatch error more informative
says that foreign keys can only be created with binary collations, but I succeeded
with a "unicode_ci" collation. Perhaps issue#3033 description is obsolete?

Minor problem: the error message contains the word 'field' rather than 'column'.

Major problem: there is no mismatch for an integer referencing an integer.

**Comment by Korablev77** [comment]
This bug seems to be temporary: now it is occurred due to forcing INT type only on PRIMARY KEY column, meanwhile other columns always have SCALAR type. It started to appear after we had introduced system space holding FK constraints and moved all validations on FK correctness straight to trigger on this space (alter.cc). For instance:

```
CREATE TABLE int1 (s1 INT PRIMARY KEY);
CREATE TABLE int2 (s1 INT PRIMARY KEY, s2 INT REFERENCES int1 (s1));
```

typeof int1.s1 == INT (since it is INT PK)
typeof int2.s2 == SCALAR (since it is not PK) 

After patches on static typing hit the trunk, this issue will be closed automatically.

>  foreign keys can only be created with binary collations

It is behaviour of SQLite foreign keys. AFAIK ANSI doesn't promote this restriction. Now the only restriction on collations - they must match (e.g. both - parent and child can feature "unicode_ci").

**Comment by Korablev77** [comment]
Can't reproduce this bug anymore on fresh 2.1, since strict typing has hit the trunk.
