### ISSUE TITLE
Can not switch master on long WAL write

### ISSUE THREAD

**Issue by Gerold103** [tarantool/tarantool#3710]
The latest 1.10.
Instance 1:
```Lua
-------------------------- Step 1 --------------------------
box.cfg{
	listen = 3313,
	replication = {'localhost:3313', 'localhost:3314'},
	read_only = false,
}
box.schema.user.grant('guest', 'read,write,execute', 'universe')
s = box.schema.create_space('test')
_ = s:create_index('primary')
-------------------------- Step 3 --------------------------
box.error.injection.set("ERRINJ_WAL_DELAY", true)
fiber = require('fiber')
fiber.create(function() s:replace{1} end)
-------------------------- Step 4 --------------------------
box.cfg{
	listen = 3313,
	replication = {'localhost:3313', 'localhost:3314'},
	read_only = true,
}
```

Instance 2:
```Lua
-------------------------- Step 2 --------------------------
box.cfg{
	listen = 3314,
	replication = {'localhost:3313', 'localhost:3314'},
	read_only = true,
}
-------------------------- Step 5 --------------------------
box.cfg{
	listen = 3314,
	replication = {'localhost:3313', 'localhost:3314'},
	read_only = false,
} ------------------------ Hangs here ------------------------
```

Earlier I was able to switch master here. Changes not written to WAL had been sent after turning delay off. Actually, I do not understand, why it is forbidden now on fullmesh.

**Comment by locker** [comment]
This is how `box.cfg{replication}` works by design - it doesn't return until it has synchronized with `box.cfg.replication_connect_quorum` replicas or `box.cfg.replication_sync_timeout` occurs. In the example above the replica can't subscribe until the old relay exits, but it got stuck in WAL.

May be, you wonder why we have to reconfigure replication even if the value of `box.cfg.replication` doesn't actually change? Well, that happens, because the replication configuration is given as a Lua table and no two Lua tables are equal to each other and hence `box/lua/load_cfg.lua:reload_cfg` assumes that the replication configuration has changed while it hasn't and reconfigures replication while it doesn't need to. I guess we could rectify that by making `reload_cfg` more thorough. Would it work for you?

**Comment by Gerold103** [comment]
Thanks, replication_connect_quorum has worked.

**Comment by locker** [comment]
After all, I think it's kinda strange that we reconfigure replication even if the user passes exactly the same value, i.e. `box.cfg{replication = box.cfg.replication}`. We try not to for all other options, e.g. `box.cfg{listen = box.cfg.listen}` is a no-op. I've opened another issue for this: #3711.
