### ISSUE TITLE
LuaJIT does not use LTO with -DENABLE_LTO=ON

### ISSUE THREAD

**Issue by Totktonada** [tarantool/tarantool#3743]
Need to investigate.

**Comment by OKriw** [comment]
First idea we came up with is to do it rather straightforward:
If DENABLE_LTO=ON we set appropriate flags to compiler and linker. 
However, such approach has some significant shortcomings:
- difficult to maintain 
Every module we decided to build with LTO, will get  just copy/paste of all this code.
- a lot of checks that are difficult to follow. 
For example, clang supports lto from 3.4 version, but since 3.9 -flto=thin option is available.
In case of gcc  LTO is usable starting from 5.0+ and binutils prior 2.27, etc.
(http://blog.llvm.org/2016/06/thinlto-scalable-and-incremental-lto.html
http://lists.llvm.org/pipermail/llvm-dev/2009-November/027103.html)
- need to pay attention to link libraries, so that ar can understand LTO objects.
(https://lists.llvm.org/pipermail/llvm-dev/2018-March/122018.html)
First variant and all the discussion can be found here:
https://lists.tarantool.org/pipermail/tarantool-patches/2020-May/017035.html
It works and a lot of projects live with code like this. So it is our first option.
Second option we get is to all system information cmake has. 
This means we will expose some "private" cmake info and will get options we need automatically via CMAKE_C_COMPILE_OPTIONS_IPO and CMAKE_C_LINK_OPTIONS_IPO options.
Shortcoming:
- Code relies on undocumented cmake variables.
See https://gitlab.kitware.com/cmake/cmake/-/issues/16808
Patch and proposal:
https://lists.tarantool.org/pipermail/tarantool-patches/2020-June/017719.html
https://lists.tarantool.org/pipermail/tarantool-patches/2020-June/017732.html
Now we need to decide what way should we move. 
And the last thing to mention - we do not have any proof that  luajit build with LTO gives us some gain. We decided to check it as a separate issue:
https://github.com/tarantool/tarantool/issues/5086
