### ISSUE TITLE
sql: forbid naming column constraints

### ISSUE THREAD

**Issue by Gerold103** [tarantool/tarantool#3820]
Tarantool version:
2.1.0
OS version:
Any
Bug description:
According to standard, it is not allowed to name column constraints (NULL, NOT NULL, DEFAULT, COLLATION). Only table constraints can have a name (UNIQUE, PRIMARY KEY, FOREIGN KEY/REFERENCES, CHECK).
Steps to reproduce:
```Lua
box.sql.execute('CREATE TABLE test (id integer primary key, b integer constraint c1 NULL)')
box.sql.execute('CREATE TABLE test (id integer primary key, b integer constraint c1 default 300)')
box.sql.execute('CREATE TABLE test4 (id integer primary key, b text constraint c1 collate "binary")')
```
All of these statements should raise a syntax error.

**Comment by pgulutzan** [comment]
I do not understand the premise: "According to standard, it is not allowed to name column constraints ...".
I interpreted the clause in the column definition section that begins "If a <column constraint definition> is specified ..." to be saying that the column constraint definition including the name will be taken as equivalent to a table constraint definition. Perhaps we are looking at different sections?

**Comment by Gerold103** [comment]
@pgulutzan I opened 2011 standard, part 2, page 640, and I see, that `DEFAULT` and `COLLATION` are not column constraints. Honestly, I can not find even if these two things are constraints by definition. And despite that, SQLite allows their naming. I think, it should be forbidden in favour of the standard.

Talking of `NULL/NOT NULL` - they are column constraints according to the standard, and even can be named, as I now see. But not sure if it is worth following the standard here, because we already have `is_nullable` tuple field option, which can not be named. And hardly I can image how painful it would be extending this particular constraint by allowance its naming. In terms of compatibility.

**Summary**: `COLLATION` and `DEFAULT` are not constraints, and of course can not be *named* constraints. `NULL/NOT NULL` are discussable, but I think, that their naming also should be prohibited.

What do you think?

Below I copy-paste a part of column definition grammar:
```
<column definition> ::=
  <column name> [ <data type or domain name> ]
      [ <default clause> | <identity column specification> | <generation clause>
      | <system time period start column specification>
      | <system time period end column specification> ]
      [ <column constraint definition>... ]
      [ <collate clause> ]

<data type or domain name> ::=
    <data type>
  | <domain name>

<column constraint definition> ::=
  [ <constraint name definition> ] <column constraint> [ <constraint characteristics> ]
  
<column constraint> ::=
    NOT NULL
  | <unique specification>
  | <references specification>
  | <check constraint definition>
```

**Comment by pgulutzan** [comment]
This looks in part like a response to a comment that I made on a different issue, Issue#3503 sql: check constraint name for duplicate, where I said:
The suggestion above "Do not allow to name anything but UNIQUE, PRIMARY KEY, CHECK, FOREIGN KEY/REFERENCES" is good regardless of the result of this issue. That is, default clauses and collate clauses are not constraints so they do not need constraint names.
... The comment that I made on this issue was solely in reference to your opening sentence "According to standard, it is not allowed to name column constraints ...". Now you appear to agree that in fact it is allowed in the standard, good. As for NOT NULL, my opinion does not matter, I was only commenting about the standard.
