### ISSUE TITLE
Need to add all build targets to Travis per-commit testing

### ISSUE THREAD

**Issue by kyukhin** [tarantool/tarantool#3860]
Tarantool version: 2.x

OS version: Linux

Bug description:
Need to add testing in all build modes to Travis regular testing

**Comment by Totktonada** [comment]
Raw thoughts: Packages built with RelWithDebInfo, so maybe target name Release is confusing and maybe we should name it in some other way.

**Comment by kyukhin** [comment]
Release -> RelWithoutDebInfo
RelWithDebInfo -> Release ?

**Comment by Totktonada** [comment]
I think we should consult with @kostja, because only he knows the history.

**Comment by Totktonada** [comment]
AFAIU RelWithDebInfo is the standard name for cmake target. It seems we should not change it.

I also think there is nothing to do anymore within this issue. @kyukhin, can we close it?

**Comment by Totktonada** [comment]
To sum up: the builds that we offer use RelWithDebInfo and we recommend to use RelWithDebInfo for third-party builds. The reason is that otherwise it'll be hard to debug. I don't see a need to test Release builds.

@kyukhin I guess I can close it now. Feel free to reopen with more information if I missed something.
