### ISSUE TITLE
space:frommap raise "tuple field does not match..." even for nullable field

### ISSUE THREAD

**Issue by filonenko-mikhail** [tarantool/tarantool#3882]
Tarantool version:
1.10.2-3-gacb7032ad

OS version: macos

Bug description:
space:frommap raise error "tuple field does not match..."
 
Steps to reproduce:

make box.space

```[
   {
      "name":"id",
      "type":"string"
   },
   {
      "name":"customerId",
      "type":"integer"
   },
   {
      "name":"bucket_id",
      "type":"unsigned"
   },
   {
      "type":"unsigned",
      "is_nullable":true,
      "name":"createDate",
      "logical_type":"datetime"
   },
   {
      "type":"string",
      "name":"direction",
      "is_nullable":true
   },
   {
      "type":"string",
      "name":"phone",
      "is_nullable":true
   },
   {
      "type":"string",
      "name":"createUser",
      "is_nullable":true
   },
   {
      "type":"string",
      "name":"email",
      "is_nullable":true
   },
   {
      "type":"string",
      "name":"description",
      "is_nullable":true
   },
   {
      "type":"string",
      "name":"state",
      "is_nullable":true
   },
   {
      "type":"integer",
      "name":"linkedPartyId",
      "is_nullable":true
   },
   {
      "type":"unsigned",
      "is_nullable":true,
      "name":"closeDate",
      "logical_type":"datetime"
   },
   {
      "type":"any",
      "name":"interactionItems",
      "is_nullable":true
   },
   {
      "type":"any",
      "name":"channel",
      "is_nullable":true
   },
   {
      "type":"any",
      "name":"contactSite",
      "is_nullable":true
   }
]
```

Try to convert map

```
{
   "bucket_id":12477,
   "createDate":"2018-12-13T12:46:10.000+0000",
   "id":"617f257e-2add-4168-b7fa-0c21189981a1",
   "channel":"test",
   "customerId":1,
   "interactionItems":[

   ]
}
```

The error is

```
Tuple\/Key must be MsgPack array
```

The workaround is set all `nil` dictionary fields `required` by schema to `box.NULL`

**Comment by kshcherbatov** [comment]
Tarantool doesn't know anything about "logical_type";
Field 4 "createDate" has 'unsigned' type, so error looks ok for me

**Comment by filonenko-mikhail** [comment]
But field 4 is nullable

**Comment by kshcherbatov** [comment]
The reason for this strange behavior is that luaL_serializer uses storage optimization to excessively sparse arrays - they are represented as a MP_MAP. Thus, in luamp_encode_tuple, the luamp_encode routine returns MP_MAP instead of MP_ARRAY. Due to the fact that the data in Tarantool tuples are represented as MP_ARRAY, this is unacceptable.
I.e.: for this schema
s2:frommap({bucket_id=12477, createDate="2018-12-13T12:46:10.000+0000", id="617f257e-2add-4168-b7fa-0c21189981a1", customerId=1, interactionItems={}})
Tuple is looking like this
['617f257e-2add-4168-b7fa-0c21189981a1', 1, 12477, '2018-12-13T12:46:10.000+0000', null, null, null, null, null, null, null, null, []]
We must set encode_sparse_ratio in luaL_serializer instance to disable this optimization.

**Comment by kshcherbatov** [comment]
A simpler example in which this bug is related to a very different function box.tuple.new():
t = {}
t[1] = 1
t[2] = 2
t[15] = 15

box.tuple.new(t)
---
- error: Tuple/Key must be MsgPack array
...
