### ISSUE TITLE
Wrong number of rows with SELECT DISTINCT, and with HAVING

### ISSUE THREAD

**Issue by pgulutzan** [tarantool/tarantool#3932]
I have Ubuntu 18.04.
I have Tarantool 2.1, pulled from source today.
I execute these statements:
drop table jj;
create table jj (s1 int, s2 char(1) collate "unicode_ci", primary key(s1));
insert into jj values (1,'A'),(2,'a');
select distinct s2 from jj;
select distinct trim(s2) from jj;
The first SELECT statement returns 1 row.
The second SELECT statement returns 2 rows.

Here is another matter which may be similar:
drop table jj;
create table jj (s1 int, s2 char(1), primary key(s1));
insert into jj values (1,'A'),(2,'a');
select 1 from jj having avg(s2) = 1 and avg(s2) = 0;
The SELECT statement returns 1 row.

**Comment by Korablev77** [comment]
Ok, that's clear: in first case collation of function is not taken into consideration. We will fix it for built-in functions, since we know how its arguments affect resulting collation. But there is still issue with user-defined functions. For instance:
```
custom_concat = function (str1, str2)
 return str1;
end

box.internal.sql_create_function("custom_concat", "STRING", custom_concat, 2)

\set language sql
CREATE TABLE t(id INT PRIMARY KEY, s1 TEXT COLLATE "unicode_ci", s2 TEXT);
INSERT INTO t VALUES (1, 'a', 'A');
INSERT INTO t VALUES (1, 'A', 'a');

SELECT DISTINCT (custom_concat(s1, s2) FROM t;

```
Without "deus ex machina" we can't determine only by SQL means that "custom_concat" should inherit collation from column s2.

Second case is about aggregate misusing. I guess, we should raise runtime error like "incompatible types".

**Comment by pgulutzan** [comment]
It is true that user-defined functions will not know some things about what an SQL caller is passing. We don't promise that they will, so I think it is okay that it is the caller's responsibility to make sure relevant information is passed explicitly. A possible issue is that the function cannot use the utf8 module for all possible collations, but that is not an SQL issue.
