### ISSUE TITLE
sql: support UNSIGNED type

### ISSUE THREAD

**Issue by Korablev77** [tarantool/tarantool#4015]
UNSIGNED types are out of ANSI specification. On the other hand, UNSIGNED is on of native Tarantool types. So, to make our SQL implementation be consistent with NoSQL, we should allow to declare columns with UNSIGNED type and process them inside SQL routines.

**Comment by zilveer** [comment]
It would be really good to have UNSIGNED implemented for SQL tables

**Comment by pgulutzan** [comment]
I worry about two things in branch np-introduce-uint/src/tarantool
One:
I have two shells. On shell#1 I start the server.
On shell#2, using a C client program, I connect.
On shell#2 I say:
create table t1 (s1 unsigned primary key);
insert into t1 values (-1);
create table t2 (s1 unsigned primary key references t);
insert into t2 values (-1);
The first INSERT fails, saying
Tuple field 1 type does not match one required by operation: expected unsigned
Okay.
The second INSERT fails, saying
Supplied key type of part 0 does not match index part type: expected unsigned
I am slightly worried because the error message is different if T2 has a reference to T1.
But I am more worried that the message appears on shell#1:
2019-06-10 09:01:01.914 [4293] main/128/main key_def.h:511 E> ER_KEY_PART_TYPE: Supplied key type of part 0 does not match index part type: expected unsigned
I believe that there is no need to print to the server console.
Two:
CREATE TABLE t3 (s1 INT PRIMARY KEY);
INSERT INTO t3 VALUES (0);
SELECT TYPEOF(s1) FROM t3;
Result = 'unsigned'.
I am slightly worried because this is incompatible with standard SQL.
But I am more worried that this is a behaviour change.
In the current version, main branch, the result is 'integer'.
So, repeating a question asked in a docs issue three weeks ago
https://github.com/tarantool/doc/issues/778
is it proper to declare that version 2.1 is "stable"?
