### ISSUE TITLE
Docker container with Tarantool memory leak.

### ISSUE THREAD

**Issue by dmitry3325** [tarantool/tarantool#4061]
Tarantool version:
1.10.2-119-g21f87c30d

OS version:
Docker Image from alpine:3.5

Bug description:
I have sharded tarantool. Memory leak on container metrics (only on storages, same in master and replicas). Сontainer restart helps. 
Container mem usage graph:
https://yadi.sk/i/qMkkuVRtGHuxgA
During my personal tests i found that reason of the mem leak is insert/upsert.
High probability that reason of error in my code))

Steps to reproduce:
Sent container with test to tarantool dev team.

**Comment by Totktonada** [comment]
Found the problem: tarantool allocates two buffers for input data for each incoming iproto connection and these buffers are initially set to a `readahead` size. So when large readahead is set these buffers are large. But they don't reside in RSS when a connection is created. They are consumed with input data of requests until the end if requests are fit to the rest of a buffer. This looks like a memory leak so, however the real reason is the mistake in configuration: if a user give such large headahead tarantool uses buffers of that size. The same was reported in #3689.

Now there are no reasons to set so large readahead: we have fixed #946 and #2218 and have released 1.10.3.

I reproduced that behaviour with large readhead in that way:

```lua
-- storage.lua
-- -----------
#!/usr/bin/env tarantool

local io = require('io')
local ffi = require('ffi')
local fiber = require('fiber')

ffi.cdef([[
    int getpid(void);
]])

box.cfg({
    listen = 3301,
    -- readahead = 100 * 1024^2, -- 100 MiB
})

box.schema.create_space('s')
box.space.s:create_index('pk')
box.schema.user.grant('guest', 'read,write', 'space', 's')
box.schema.func.create('foo')
box.schema.user.grant('guest', 'execute', 'function', 'foo')

function foo()
    -- no-op
end

fiber.create(function()
    while true do
        local pid = tonumber(ffi.C.getpid())
        local cmd = ([[ps aux | grep \\\b%d | awk '{ print $6; }']]):format(pid)
        local rss = tonumber(io.popen(cmd):read()) / 1024 -- MiB
        local net = box.info.memory().net / 1024 / 1024 -- MiB
        local con = box.stat.net.CONNECTIONS.current
        print(('RSS: %d MiB'):format(rss))
        print(('NET: %d MiB'):format(net))
        print(('CON: %d'):format(con))
        fiber.sleep(1)
    end
end)
```

```lua
-- workload_call.lua
-- -----------------
#!/usr/bin/env tarantool

local net_box = require('net.box')

local conn = net_box.connect('localhost:3301')

while true do
    conn:call('foo', {string.rep('x', 1024)})
end
```

And the following patch instructs tarantool to use just start of the buffer if possible (it is seen on the workload above):

```c
diff --git a/src/box/iproto.cc b/src/box/iproto.cc
index a37238d9b..8152b56a2 100644
--- a/src/box/iproto.cc
+++ b/src/box/iproto.cc
@@ -651,6 +651,9 @@ iproto_connection_input_buffer(struct iproto_connection *con)
                        to_read = mp_decode_uint(&pos);
        }
 
+       if (ibuf_used(old_ibuf) == 0)
+               iproto_reset_input(old_ibuf);
+
        if (ibuf_unused(old_ibuf) >= to_read)
                return old_ibuf;
```

@GeorgyKirichenko proposed another patch in the scope of #3689 ([here][1], g.kirichenko/gh-3689-improve-iproto-ibuf-management branch). I guess his patch better handle the situation when a background buffer contains much unneeded data, while the above one likely don't.

It seems that we should not handle this situation in the code but rather push users to correctly configure tarantool: don't set a large readahead.

[1]: https://github.com/tarantool/tarantool/tree/g.kirichenko/gh-3689-improve-iproto-ibuf-management

**Comment by Totktonada** [comment]
The patch above (slightly changed) was pushed to master (2.2.0-167-ga58b9bb8d), 2.1 (2.1.2-26-g747bd0439) and 1.10 (87dae86462111556751a61d5c7af6d5c4d18af7d).

**Comment by Totktonada** [comment]
Apr, 12 `readahead` was decreased to 64KiB, all nodes was rebooted and everything works fine. Planned upgrade to 1.10.3 and exposing `box.stat.net().CONNECTIONS.current` to metrics.
