### ISSUE TITLE
Use diag_set() to describe VDBE errors in SQL.

### ISSUE THREAD

**Issue by ImeevMA** [tarantool/tarantool#4074]
Currently there are two ways to describe errors in SQL - diag_set() and sqlVdbeError(). This leads to incorrect error descriptions due to possible changes in the error code. It also complicates the work with errors.

This issue continues issues #3965 and #3036.

**Comment by Totktonada** [comment]
I'm a bit late, but it worth to have SQLSTATE errors in a mind when designing the error codes: ODBC and JDBC connectors will need to map tarantool's error codes into SQLSTATE (until we'll support them natively). I found it helpful to have meaningful SQLSTATE codes in a connector, at least because some tools (that are use an ODBC API) show you just code w/o a message when something went wrong. See https://docs.microsoft.com/en-us/sql/odbc/reference/appendixes/appendix-a-odbc-error-codes?view=sql-server-2017 for the list of SQLSTATE codes.

**Comment by kostja** [comment]
diag_set() was designed with sqlstate codes in mind. Just go ahead and augment errcode.h/c with sqlstates. The sqlstate should be chosen by diag_set() automatically, based on the error code, and sent to the client in an extra field. Or you could make sqlstate table an additional piece of metadata available in box.error, so that you can download it on the client and do the mapping on the client. This way you don't even need to change the protocol.

**Comment by kostja** [comment]
sqlstate works is clearly outside the scope of this patch, though.

**Comment by Totktonada** [comment]
Now we support mapping in tarantool-c (in WIP ODBC implementation), this is okay. If we'll decide to add these codes to the protocol in the future it would be convenient for connectors, but of course it is not a blocker and not the scope of this issue.

Don't get the idea about placing sqlstate in box.error w/o touching protocol. It'll not help ODBC/JDBC, because a separate call to catch a last error can show an error from another request. It can help cases when we're able to define a custom function in tarantool.

**Comment by kostja** [comment]
I meant this:
```tarantool> box.error
---
- NO_SUCH_FIELD_NAME: 153
  UNKNOWN_REPLICA: 62
  WRONG_INDEX_RECORD: 106
  NO_SUCH_TRIGGER: 34
  SEQUENCE_EXISTS: 146
  CHECKPOINT_IN_PROGRESS: 120
  CONSTRAINT_EXISTS: 170
  FIELD_TYPE: 23
  SQL_BIND_PARAMETER_MAX: 158
  WRONG_SPACE_FORMAT: 141
```
Today it shows a list of all available errors with all their codes. Tomorrow it could list their SQLSTATES as well, not just the codes.
