### ISSUE TITLE
Data type names 'string' and 'number'

### ISSUE THREAD

**Issue by pgulutzan** [tarantool/tarantool#4192]
Please add two data type names:
'STRING' which is the same as 'TEXT'
'NUMBER' which is the same as 'REAL'
These are new reserved words.

Currently TYPEOF('') = 'string' and TYPEOF(1e4) = 'number',
this is correct (lower case and upper case would both be correct).

'STRING' and  'NUMBER' should be the preferred type names.
In fact if the names 'TEXT' and 'REAL' disappear, I doubt it would be harmful.

This supersedes issue#3811
sql: support tarantool's number type (integral+floating point)

This does not supersede issue#3812
sql: use float32/64 to represent FLOAT, DOUBLE and REAL
because FLOAT and DOUBLE and REAL are not the same as NUMBER.

**Comment by kyukhin** [comment]
@pgulutzan I see no such type `NUMBER` in ANSI. Why do you want this alias?

**Comment by pgulutzan** [comment]
Konstantin Osipov said that for every Tarantool/NoSQL type there should be a corresponding Tarantool/SQL data type with the same name, or at least a similar name. Actually my preference would be "change the Tarantool/NoSQL type name", but it is a bit late for that.

**Comment by Korablev77** [comment]
Meanwhile string can be literally used as an alias to `TEXT` type, `NUMBER` in its NoSQL meaning is different from what `REAL` is supposed to be according to ANSI. Number is kind of union which is able to hold integers as well as doubles. It can be seen from this example:

```
create table t1(id int primary key, a real);
insert into t1 values(1, 9223372036854775807);
box.space.T1:select()
---
- - [1, 9223372036854775807]
```
If you try to execute this snippet using other DBs, you will get sort of:
```
  | id | a
-- | -- | --
1 | 1 | 9,223372E+18

```
This observation seems to be obvious, but it makes `REAL` type name confusing. Hence, mb it is worth replacing (not adding an alias) REAL type (name) with NUMBER.

I can say that `TYPEOF(1e4) = 'number'` happens due to the absence of `REAL` or `FLOAT` types in NoSQL.

**Comment by kostja** [comment]
I guess you've just discovered that our SQL REAL is broken, that's all. E.g. we do support INTEGER both in SQL and NoSQL, and INTEGER is a subset of NUMBER. I guess to support REAL proprely we'll have to push it all the way down to nosql.

**Comment by Korablev77** [comment]
This situation looks like mess with scalar and blob types. I guess we have nothing left to do but introduce 'pure' floating point (underlying) NoSQL type as you suggested.
BTW, is this issue a duplicate for https://github.com/tarantool/tarantool/issues/4116 ?

**Comment by kostja** [comment]
A-ha.

**Comment by Korablev77** [comment]
Closed via https://github.com/tarantool/tarantool/commit/36fc5fe1d35e1086921d234f2ff53b0728e613df and https://github.com/tarantool/tarantool/commit/36bdfbb24f00b84c2b8d1fa3231537d9f60ae298
