### ISSUE TITLE
sql: field of type number is always converted to float

### ISSUE THREAD

**Issue by Korablev77** [tarantool/tarantool#4233]
```
CREATE TABLE t1 (id INT PRIMARY KEY, f REAL);
INSERT INTO t1 VALUES (1, 9223372036854775807);
SELECT * FROM t1;
---
- metadata:
  - name: ID
    type: integer
  - name: F
    type: number
  rows:
  - [1, 9223372036854775808]
...

```
NUMBER is able to hold floating point values as well as integers. So correct answer should be this:
```
box.space.T1:select()
---
- - [1, 9223372036854775807]
...
```
This happens due to extra conversion to floating point value after extracting from tuple:
```
/src/box/sql/vdbe.c
OP_Column: {
2751         if ((pDest->flags & MEM_Int) != 0 &&                                    
2752             pC->eCurType == CURTYPE_TARANTOOL) {                                
...                                                      
2760                 if (pC->uc.pCursor->curFlags & BTCF_TEphemCursor)               
2761                         f = pC->uc.pCursor->index->def->key_def->parts[p2].type;
2762                 else if (pC->uc.pCursor->curFlags & BTCF_TaCursor)              
2763                         f = pC->uc.pCursor->space->def->fields[p2].type;        
2764                 if (f == FIELD_TYPE_NUMBER)                                     
2765                         sqlVdbeMemSetDouble(pDest, pDest->u.i);                 
2766         }  
```
Bug was introduced in 758ab1a4218b23ddc7b8809523e486ee1a92cb17

**Comment by Gerold103** [comment]
Ok, I dropped this piece of code, fixed a couple of trivial problems, and faced with a serious one: arithmetic operations erase operand field types. Consider an example:
```Lua
box.cfg{}
box.execute("CREATE TABLE t3(a NUMBER primary key);")
box.execute("INSERT INTO t3 VALUES(44.0);")
box.execute("INSERT INTO t3 VALUES(56.0);")
box.execute("SELECT (a + 25) / 50 FROM t3")
```
Here `a` has type NUMBER. `a + 25` should keep it, as well as `(a + 25) / 30` - all these values are inside number value ranges. Result should be a couple of floats.
But after I dropped the cast in the first comment of the issue, I get this: `a` has type NUMBER, but stores an integer. `a + 25` is stored as an integer without a field type. Being divided by an integer `30` it results in `1` instead of a float. Things are getting worse because of https://github.com/tarantool/tarantool/issues/4470.
