### ISSUE TITLE
Tarantool cannot be installed on current Fedora

### ISSUE THREAD

**Issue by kmansoft** [tarantool/tarantool#4313]
Tarantool version: 1.10

OS version: Fedora 30

Bug description:

  - nothing provides libyaml.so needed by tarantool-1.10.3.68-1.fc30.i686
  - nothing provides libyaml.so()(64bit) needed by tarantool-1.10.3.68-1.fc30.x86_64
  - nothing provides libreadline.so.7 needed by tarantool-1.7.5.0-2.fc28.i686
  - nothing provides libreadline.so.7()(64bit) needed by tarantool-1.7.5.0-2.fc28.x86_64

Steps to reproduce:

1 - Configure Tarantool repo as described here:

https://www.tarantool.io/en/download/os-installation/1.10/fedora/

2 - sudo dnf install tarantool

No idea why it considers both 1.10.3 and 1.7.5 versions.

Fedora 30 is the current version.

Libreadline has been named just readline since Fedora 28 or 29 it seems.

https://apps.fedoraproject.org/packages/readline

The issue with libyaml (which I already have installed) is that its .so now has a different name:

/usr/lib64/libyaml-0.so.2
/usr/lib64/libyaml-0.so.2.0.5

but no libyaml.so anymore.

**Comment by Totktonada** [comment]
Yep, we aware of that and working to solve. Thanks for noticing.

**Comment by Totktonada** [comment]
The issue with libyaml was fixed in 47b91e90f2a4e23e70a1a6735af3de203ffd59f4, 2.2.0-596-g47b91e90f (on master aka non-released-yet 2.2, but not 2.1 and not 1.10) in the scope of #4090. I'll look into readline linking problem. I guess both problems should be fixed by updating packpack/packpack:fedora-30 docker image.

**Comment by Totktonada** [comment]
Re libreadline: nevermind, I misread the error.

**Comment by Totktonada** [comment]
I successfully proceed with the instruction using fedora:30 docker image.

There was the issue with different libyaml dynamic library name between our docker image where tarantool rpm packages are build and recent Fedora 30 where the package is installed. It seems to be gone with some update of packpack/packpack:fedora-30 docker image. This allows dnf to choose tarantool-1.10 from our repo instead of tarantool-1.7 (that is pushed to fedora's built-in repos and is broken by the similar problem with readline dynamic library). All that however is not relevant to 47b91e90f2a4e23e70a1a6735af3de203ffd59f4, this commit is not part of 1.10 and 2.1.

So the original issue with our repos seems to be resolved. @kmansoft, can you verify it, please?

Now I see timeout errors from packagecloud, so it is possible that dnf will unable to update a repo or download a package from our repository: in this case tarantool-1.7 from built-in repos will be choosen and the error about libreadline will be shown. It can be worked around with retrying `dnf makecache/install` commands until a repo metadata / a package will be successfully downloaded. I asked packagecloud support about that, waiting for an answer.

We also plan to push working tarantool package to built-in Fedora repos to eliminate the error re libreadline and to update a tarantool version. This however is not part of this certain issue.

Waiting for @kmansoft feedback to close the issue.

**Comment by Totktonada** [comment]
Sorry, timeout errors is my local connectivity problem.

**Comment by Totktonada** [comment]
@kyukhin I think this issue can be closed now.
