### ISSUE TITLE
Auth request from "tarantool-c" client is failed

### ISSUE THREAD

**Issue by rtokarev** [tarantool/tarantool#4327]
Tarantool version: 2.1.1-476-gaf74255

OS version: CentOS release 6.4 (Final)

Bug description:

Auth request from "tarantool-c" client is failed with error "Invalid MsgPack - authentication request body".

It seems that the problem is in the following comparison in "authenticate" function (src/box/authentication.cc):
```
memcmp(user->def->hash2, zero_hash, SCRAMBLE_SIZE) == 0
```

"tarantool-c" client doesn't send a password in case of a user is "guest" and this comparison is failed because actually "hash2" value for the "guest" user is equal to debased CHAP_SHA1_EMPTY_PASSWORD

**Comment by Totktonada** [comment]
Just to make things clear: this change allows a connector to authenticate as 'guest' user **without** a password (rather then with empty password that works since 076a842011e09c84c25fb5e68f1b23c9917a3750), when a password for 'guest' is set to the empty string in tarantool (which is default after 076a842011e09c84c25fb5e68f1b23c9917a3750).

**Comment by Totktonada** [comment]
> Totktonada unassigned locker now

This was unintentional, sorry. GitHub does this automatically.
