### ISSUE TITLE
decimal: introduce trim() and rescale() methods

### ISSUE THREAD

**Issue by sergepetrenko** [tarantool/tarantool#4372]
trim() would be useful to remove insignificant trailing zeros, and rescale() can be used, for example, to format the output so that is always has a given number of fractional digits (Could be useful in monetary applications)

**Comment by pgulutzan** [comment]
I don't understand why the title says trim() but the text says truncate().
Anyway, I worry about having a Lua function named truncate() because
someday an SQL user might want to call it, and some SQL people will have
seen a truncate() function in another DBMS that operates quite differently.
(The word is also reserved for the TRUNCATE verb in Tarantool SQL but 
that's probably okay.)

**Comment by sergepetrenko** [comment]
@pgulutzan thank you for noticing.
@kostja has already pointed that out in the mailing list.
The functions will be called trim() and rescale().
I'll change the issue text to conform.

**Comment by pgulutzan** [comment]
And thank you for changing. Of course there's also a Tarantool SQL function with that name (trim(1.5) returns '1.5') but that doesn't matter.
