### ISSUE TITLE
box.session.su does not ask for password

### ISSUE THREAD

**Issue by izmalk** [tarantool/tarantool#4446]
Tarantool version:
1.10.2-1-ge0017ad
OS version:
MacOS 10.14.6
Bug description:
I've connected with _tarantoolctl connect_ to binary port (with default user), used box.session.su('admin'), created two users (pub and pub2) with passwords. And then have tried switching between them.
The error at the end is due user pub2 has not been granted access to execute in universe (apart from user pub) - and now he is locked (cant use box.session.su anymore).

Maybe box.session.su should ask for password?

Steps to reproduce:
```
localhost:3303> box.session.user()
---
- admin
...

localhost:3303> box.schema.user.create('pub2', {password = 'sec2'})
---
...

localhost:3303> box.space._user:select()
---
- - [0, 1, 'guest', 'user', {'chap-sha1': 'vhvewKp0tNyweZQ+cFKAlsyphfg='}]
  - [1, 1, 'admin', 'user', {}]
  - [2, 1, 'public', 'role', {}]
  - [3, 1, 'replication', 'role', {}]
  - [31, 1, 'super', 'role', {}]
  - [32, 1, 'pub', 'user', {'chap-sha1': 'BZCkyWOEpnbcN0XtVaPFQb0QbcQ='}]
  - [33, 1, 'pub2', 'user', {'chap-sha1': 'asMwHR6vgcXXL8ANtAbH7NXbf38='}]
...

localhost:3303> box.session.su('pub')
---
...

localhost:3303> box.session.user()
---
- pub
...

localhost:3303> box.session.su('pub2')
---
...

localhost:3303> box.session.user()
---
- error: Execute access to universe '' is denied for user 'pub2'
...
```

**Comment by kyukhin** [comment]
It think this is wrong way.

**Comment by sergos** [comment]
The execution rights are restricted by the `_func` space contents, unless one grants execution for `universe`. Hence, the access restriction is rather simple - user should be granted with rights in non-system spaces only (otherwise it can fiddle password hash or access masks) and to a particular set of functions from the `_func`.

For a user without universe execute rights it results in console that can't connect:
```
tarantool> console.connect('guest@localhost:3303')
---
- error: Execute access to universe '' is denied for user 'guest'
```

Still the `net.box` connection is possible, still as soon as one switch to the lowered privileges, it has no access to the `box.session.su()` immediately:
```
tarantool> c=netbox.connect('admin@localhost:3303')
tarantool> c:eval('return box.session.user()')
---
- admin
...
tarantool> c:eval('return box.session.su("guest")')
tarantool> c:eval('return box.session.user()')
---
- error: Execute access to universe '' is denied for user 'guest'
...
```
The same is true for the `console`:
```
tarantool> console.connect('admin@localhost:3303')
connected to localhost:3303
---
- true
...
localhost:3303> box.session.su('guest')
localhost:3303> box.session.user()
---
- error: Execute access to universe '' is denied for user 'guest'
...
```
