### ISSUE TITLE
Case insensitive access to Lua spaces from SQL

### ISSUE THREAD

**Issue by kostja** [tarantool/tarantool#4467]
If SQL identifier is unquoted, it is uppercased before store/use. If it is quoted, it is left intact. This is ANSI, but this creates a lot of confusion - first of all, because it is not easy to use, since people don't like their names being mangled by the database and forcefully converted to uppercase, second, because there are Lua spaces, which do not have uppercase representation.

Tarantool should preserve the original case supplied by the user. To ensure the name can be looked up with case-insensitive search, it should add a unique case-insensitive accent-sensitive index for each metadata object which can have a name (spaces, views, field names, functions, triggers). This will allow using Lua spaces and SQL tables in both frontends without mangling the original case: Lua frontend will use case-sensitive search, while SQL frontend will use the case-insensitive one.
By making the case-insensitive index unique we will make sure there is no ambiguity.

For example, if I do `create table foo (a int primary key)`, I should be able to use it from lua using `box.space.foo`.

If I do `box.scheam.space.create('foo')`, `select * from foo` should work fine. 

For quoted SQL identifiers we can continue using the case-sensitive index.
Note: some bizarre use case may actually require that the database upper-cases their object name before store (i.e. strict ansi compatibility). We can keep the uppercasing as an option for these, box.cfg.strict={bunch of flags} is a possible name of the switch.

**Comment by Totktonada** [comment]
Why not just avoid doing any implicit case transformations as all modern programming languages do?

**Comment by kostja** [comment]
This would break a lot of SQL code.

**Comment by Totktonada** [comment]
Since we don't compatible with any SQL dialect of popular databases, manual actions (maybe, a lot of them) will anyway needed to migrate from other database to tarantool. I guess Tarantool/SQL will be mostly used for new projects rather then for adopting old ones. While your objection is true, I think existing code will be 'broken' anyway in many and many ways.

**Comment by Gerold103** [comment]
> Not supporting case insensitive lookup would break a lot of SQL code.
So how does it require to store a second column? Just use case-insensitive comparison when lookup a column name in field array. If it is quoted, lookup like now. If it is not, then use strcasecmp.

**Comment by pgulutzan** [comment]
As admitted in the issue description: the current behaviour is compatible with the standard. I hope that this suggested behaviour change will be rejected.

**Comment by kostja** [comment]
@pgulutzan how exactly is case insensitive access to spaces created from Lua in SQL violates SQL standard? 
This is obviously outside the SQL standard domain.
The same goes to case-sensitive access to SQL tables from Lua.

**Comment by pgulutzan** [comment]
@kostja: You didn't only talk about "spaces created from Lua", you gave an example of creating in SQL. The effect that I expect for CREATE TABLE t is: it also creates table "t". If that is not so, then later I can create table "t" and that means the Lua has two spaces with the same name. If that is so, then later I cannot create table "t" and that means the SQL standard (which says the effect is only to create T) is violated.

**Comment by kostja** [comment]
No, I did not suggest you can create tables with different casing of the same name. The unique index on space name is case insensitive already, and I don't suggest to change it.

**Comment by Gerold103** [comment]
But it is false. It is not case-insensitive already, and won't, because it will totally destroy backward compatibility:
```YAML
tarantool> s1 = box.schema.create_space('test')
---
...

tarantool> s2 = box.schema.create_space('TeSt')
---
...
```

**Comment by kostja** [comment]
Well, I guess it needs to become case-insensitive. Better ask the few users today to rename their spaces before upgrade than suffer indefinitely.

**Comment by pgulutzan** [comment]
So now there is an additional proposal is to make it illegal in Lua to create an object named 'x' if an object named upper('x') exists, and/or change the indexes of system spaces (with a new collation since ones like "unicode_ci" are not appropriate)?

**Comment by knazarov** [comment]
I'll join the discussion and add my $0.02

I've witnessed how unsuspecting users get into confusion with our SQL. They just are used to typing "SELECT * FROM TABLE1 WHERE ...". And when this doesn't work I try to explain why they have to quote table names. They seemingly can't grasp the reason and just ask how they can "continue to type plain old SQL without these workarounds".

What @kostja suggests looks to me as a path of least confusion for the end user. While it keeps things more or less backwards compatible.

**Comment by Totktonada** [comment]
Or another possible way: rather then change anything in Lua box API to fix SQL, change SQL itself to perform two lookups (at max) for table names (and other identifiers): first is in a original case, the second is in upper case (if the first one fails).

**Comment by pgulutzan** [comment]
@Toktonada has made a suggestion that might work.
I guess that there will be a new Unicode Upper collation
(call it UU) and every system table has a non-unique UU 
index. I guess that in SQL statements every delimited
(quoted) identifier will be looked up only via the exact index,
and every regular identifier will be looked up in the new
two-step way. I hope that this will be a server option,
that is, it can still be possible to operate according
to the standard, but you have to specify during install.
I suppose that if I have three Lua spaces named "AA" and "Aa"
and "aA", and I say "DROP TABLE aa;", there should be an
error because exact search matches 0 objects while UU search
matches 3 objects -- but maybe that will never happen.
I regret that users will say "SELECT * FROM A;" successfully
and then wonder why "SELECT * FROM _SPACE WHERE NAME = 'A';"
fails (because UU will not be the default collation).
And I still disagree that any behaviour change is
necessary, but if it happens, at least this "might" work.
