### ISSUE TITLE
sql: replace PRAGMA by SET for some pragmas

### ISSUE THREAD

**Issue by ImeevMA** [tarantool/tarantool#4511]
1) Replace PRAGMA by SET for these pragmas:

a) SQL options
```
count_changes
defer_foreign_keys
full_column_names
recursive_triggers
reverse_unordered_selects
short_column_names
sql_compound_select_limit
sql_default_engine
```

b) Debug settings
```
parser_trace
select_trace
sql_trace
vdbe_addoptrace
vdbe_debug
vdbe_eqp
vdbe_listing
vdbe_trace
```
2) Create a system space that contains these variables and their current values.

**Comment by pgulutzan** [comment]
Someday we will have something like sql/psm, so
BEGIN
  DECLARE sql_reverse_unordered_selects BOOLEAN;
  SET sql_reverse_unordered_selects = TRUE;
END
will be possible in theory, so there will be two
different ways to interpret the SET statement.
What will happen then?

**Comment by kostja** [comment]
Peter, what do you think, shall we keep PRAGMA statement?

**Comment by pgulutzan** [comment]
kostja, it seems to me that a decision has already been made to not keep it, so I am not objecting to that. PRAGMA is not in the manual because I didn't get permission to push, therefore changing the syntax will probably not cause much disruption. I believe that the problem with SET could be solved in various ways, for example making the settings names reserved or preceding them with @@ or adding the word SESSION after SET, or something else -- perhaps Mergen has already thought of a solution, and if so I am once again not objecting.

**Comment by kostja** [comment]
Prepending @@ MySQL style is not such a bad idea. Tarantool style would be _ (single underscore).

**Comment by ImeevMA** [comment]
@pgulutzan @kostja It seems that we are going to solve the problem in a different way: we will create a special space that will contain the settings. This space will only allow updates. So, to change the setting value, you should do something like this:
```
box.execute([[UPDATE "_session_settings" SET "value" = 'vinyl' WHERE "name" = 'sql_default_engine']])
```
or
```
box.space._session_settings:update('sql_default_engine', {{'=', 'value', 'vinyl'}})
```

This will allow us to use the same method to change any settings in any front-end. Also after that we can simply remove the control pragmas.

**Comment by pgulutzan** [comment]
@ImeevMA and @kyukhin:

I think that in general this is really good but I noticed a few small things.
I am using Tarantool 2.4.0 pulled from source today.

1. I could not see _session_settings, using a database that I created
a few weeks ago. I tried box.schema.upgrade(). Should I have done something else?

2. I see this:

tarantool> delete from "_session_settings" where "name" = 'sql_vdbe_debug';
---
- null
- Session_settings space does not support delete()
...

fine, but the error message says Session_settings, it should say _session_settings.

3. Changing reverse_unordered_selects to true does indeed reverse in most cases,
but not if I say select * from "_session_settings" group by "name";

4. Changing sql_defer_foreign_keys to true does defer foreign key checking, but
does not affect ON DELETE SET NULL. That is the correct action,
but in that case, is sql_defer_foreign_keys a good name?
I believe a better name would be: sql_defer_foreign_key_checks.
(By the way, I see that the sql_ prefix is necessary because this setting
does not affect Lua requests, in fact nothing about foreign keys affects Lua requests.)

5. If, after sql_defer_foreign_keys was set, COMMIt fails with error =
"Can not commit transaction: deferred foreign keys violations are not resolved",
there is automatic ROLLBACK. That is the correct action,
but I wonder: was it a deliberate decision?

**Comment by ImeevMA** [comment]
@pgulutzan Thank you for comment.

1) Could you describe the problem in more detail? I will try to reproduce.
2) That is definitely a bug. I will fill an issue.
3) This seems like a bug, but I'm not sure if this is a problem of this space. I mean:
```
tarantool> box.space._session_settings:update('sql_reverse_unordered_selects', {{'=', 2, true}})
---
- ['sql_reverse_unordered_selects', true]
...

tarantool> box.execute('create table t (i int primary key, a int);')
---
- row_count: 1
...

tarantool> box.execute('insert into t values (1,1), (2,2), (3,3), (4,4)')
---
- row_count: 4
...

tarantool> box.execute('select * from t')
---
- metadata:
  - name: I
    type: integer
  - name: A
    type: integer
  rows:
  - [4, 4]
  - [3, 3]
  - [2, 2]
  - [1, 1]
...

tarantool> box.execute('select * from t group by i')
---
- metadata:
  - name: I
    type: integer
  - name: A
    type: integer
  rows:
  - [1, 1]
  - [2, 2]
  - [3, 3]
  - [4, 4]
...
```

If this is a bug, could you please fill an issue?
4) I will add this question to the issue that I will fill.
5) Sorry, I do not know why it is so. I think we can ask @Korablev77

**Comment by pgulutzan** [comment]
1. The .snap file starts with "SNAP.0.13.Version: 2.3.1-1-g4137134c0."
but, as I said, I created a few weeks ago, before #4511 completion.
So _session_settings does not exist, but version number is the same,
so no upgrade happens. Does that make sense?

2. Okay.

3. I could file a bug report, but it would save time if you would
just say "this is deliberate". I can ensure that the manual will
just say it "usually" affects the order.

4. I see that you acknowledged this feature request in issue#4732.
Thanks!

5. As I said, I think this is "correct action". The only reason I ask "is it
deliberate?" is: if it's not, then somebody might (wrongly) think
on some future occasion that it is okay to change the behaviour.

**Comment by Korablev77** [comment]
@pgulutzan Hi,

1. There's no guarantee that upgrade in "between versions" state is legal and won't break upgrading mechanism at all. This happens due to the fact that upgrade from major versions takes place by means of one upgrade function. It can be modified several times in scope of one release (e.g. owing to bug fix in it). @Totktonada promised to come up with ticket to somehow resolve this problem.

3. This looks like a bug, but if it affects only one particular space, I guess it is enough to add a remark to documentation.

5. AFAIR expected behaviour is to keep transaction open. So it is likely to be a bug.

**Comment by pgulutzan** [comment]
@Korablev77: Please consider the standard document:
"[concepts] When a commit statement is executed, all enforced constraints
are effectively checked and, if any enforced constraint is not satisfied,
then an exception condition is raised and the SQL-transaction is terminated
by an implicit rollback statement." ...
"[during commit] If any enforced constraint is not satisfied, then any changes
to SQL-data or schemas that were made by the current SQL-transaction are canceled
and an exception condition is raised:
transaction rollback—integrity constraint violation."
But of course if you have a reason to say the current behaviour is a bug,
that's good too.

**Comment by Korablev77** [comment]
@pgulutzan 

Firstly, deferred foreign keys behaviour has been inherited from SQLite. In turn SQLite leaves transaction open on commit (and as far as I remember I also observed this behaviour in Tarantool SQL some time ago). Secondly, rollback leaves no chance for user to resolve deferred FK violations. Moreover, in case keeping transaction open user is able to execute explicit rollback command (so it is like more versatile behaviour).
All points considered, I'd rather try to fix it rather then document.
