### ISSUE TITLE
Enable LUAJIT_ENABLE_LUA52COMPAT when bulding luajit?

### ISSUE THREAD

**Issue by edam** [tarantool/tarantool#4560]
Building luajit with `-DLUAJIT_ENABLE_LUA52COMPAT` enables some cool features, some of which I would like to use!

In particular, I want:
* `__pairs` and `__ipairs` metamethods

At present, there is no nice way to provide your own table iteration.  I mean, you can redefine `next`, `pairs` or `ipairs`, but that's a bit messy...

According to [this discussion about it](https://github.com/tarantool/tarantool/issues/2921) from a couple of years ago, the idea was initial dismissed because `LUAJIT_ENABLE_LUA52COMPAT` doesn't cause luajit to fully implement 5.2 Lua. But it is the case that luajit *already* implements some 5.2 features. So the situation w.r.t. whether tarantool supports Lua 5.2 would be largely unchanged (i.e., tarantool would still support *some* 5.2 features.)

Would you reconsider?

**Comment by igormunkin** [comment]
Lua 5.2 is not backward compatible with Lua 5.1 therefore Tarantool can't be simply built with `LUAJIT_ENABLE_LUA52COMPAT` enabled (e.g. `os.execute` interface differs in [Lua 5.1](https://www.lua.org/manual/5.1/manual.html#pdf-os.execute) and [Lua 5.2](https://www.lua.org/manual/5.2/manual.html#pdf-os.execute)). We can't apply such changes in 1.10.x / 2.x due to possible users code breakag, but we can discuss enabling `LUAJIT_ENABLE_LUA52COMPAT` by default considering its pros and cons in future major releases.

@kyukhin, @sergos, I see the following ways to resolve the issue for now:
* Write down a rationale to our docs for not enabling that flag and close similar tickets with wontfix label.
* Introduce a specific flag (say `LUAJIT_ENABLE_PAIRSMM`) for enabling the feature has been already requested several times.

**Comment by igormunkin** [comment]
As a result of the offline discussion the latter proposal to be implemented. The `LUAJIT_ENABLE_PAIRSMM` flag is considered to enable only `__pairs` and `__ipairs` metamethods.

@kyukhin, please adjust the issue milestone.

**Comment by olegrok** [comment]
This commit closed this issue - https://github.com/tarantool/tarantool/commit/2110213cb8c4a5ab99071c37dad3b03be8ccb527 (add ipairs metamethod)

**Comment by igormunkin** [comment]
Introduced in tarantool/luajit in tarantool/luajit@d4e985a. The submodule was updated in tarantool in 2.3.0-255-ge12930d06 (e12930d), 2.2.1-134-g076b1ba05 (076b1ba), 1.10.4-63-g2de491f6f (2de491f). `LUAJIT_ENABLE_PAIRSMM` flag is enabled by default in tarantool build in b504ca1.

**Comment by olegrok** [comment]
As https://github.com/tarantool/tarantool/commit/04dd6f430ea58d131620a6c115c36a75f84bad42 reverts this feature reopen the issue

**Comment by igormunkin** [comment]
The changes have been reverted in tarantool/luajit@a9eebfa. The submodule was updated in tarantool in tarantool 2.4.0-37-g04dd6f430 (04dd6f4), 2.3.1-30-gc831f1e5a (c831f1e), 2.2.2-31-g1f41f95b0 (1f41f95), 1.10.5-13-g9bf8cbe1d (9bf8cbe).

Closing the issue with the wontfix reason, since the requested feature breaks the backward compatibility and doesn't comply the Lua 5.1 spec.
