### ISSUE TITLE
Check schema version after tarantool update

### ISSUE THREAD

**Issue by sergepetrenko** [tarantool/tarantool#4574]
Some  users forget to call `box.schema.upgrade()` after updating tarantool, and get stuck with an old schema version until they encounter some hard to debug problems.
Even though tarantool 2.x has all the upgrade handlers, starting from version 1.7.6, configured to auto upgrade the implicit upgrade doesn't happen on instances with configured replication (see https://github.com/tarantool/tarantool/blob/master/src/box/lua/load_cfg.lua#L571-L573). This is invisible to the user at the moment and we should be more verbose about upgrades.
We should check schema version (stored in box.space._schema) on start and print a warning if it doesn't match current tarantool version

**Comment by servoin** [comment]
It looks like currently there is no way to determine schema version which "matches" Tarantool version. This is because of:
1. Tarantool release version itself is not the same as "default" schema version it uses.
2. The "default" schema version (in newly created snapshot) is made from 1.7.5 incrementally upgrading it to some "maximum" version (see table "handlers" in src/box/lua/upgrade.lua, local function upgrade).
3. The table mentioned above is local to upgrade() function and there is now way to know the maximum schema version outside of this function.

What I propose is:
1. Move the above mentioned table "handlers" outside of upgrade function for it to be available for other functions (see below).
2. Introduce get_max_version() function, which would return "maximum" schema version taken from the last tuple of "handlers" table.
3. Compare current schema version (get_version()) to "maximum" schema version (get_max_version()). This way we can see if current schema version "matches" Tarantool version.

What do you think?

**Comment by Totktonada** [comment]
We should check a current schema version against a last available schema version (from list in upgrade.lua). As I see, you propose the same, so I'm okay.
