### ISSUE TITLE
Add message from CURLOPT_ERRORBUFFER

### ISSUE THREAD

**Issue by PersDep** [tarantool/tarantool#4578]
When processing curl request error code, we are collecting error message using curl_easy_strerror. We can provide more info using curl error buffer, which can be collected using curl_easy_setopt with CURLOPT_ERRORBUFFER option.

**Comment by Totktonada** [comment]
@PersDep wrote in https://lists.tarantool.org/pipermail/tarantool-patches/2019-November/012305.html:

> Therefore, our only option seems to be an error buffer in each request,
> which doesn't seem very reasonable, as far as we already have some
> error info and we can also obtain more info using @param verbose option
> of client_object:request() if needed for debug.
>
> As a conclusion for the thoughts above, I decide to exclude this patch
> from the v5 of the current patchset and leave it alone until some
> serious reason to reconsider this decision will come up.

I agree with Ilya and propose to close this issue w/o further actions.

We filed the issue mainly to workaround https://github.com/curl/curl/issues/4310, which was fixed in curl-7.67.0 (see also #4698).
