### ISSUE TITLE
enable backtrace at CentOS 8

### ISSUE THREAD

**Issue by avtikhon** [tarantool/tarantool#4611]
Tarantool version:

OS version:

Bug description:

Steps to reproduce:

Optional (but very desirable):
* coredump
* backtrace
* netstat

**Comment by Totktonada** [comment]
We'll disable support of backtraces in fiber.info() for CentOS 8 packages (which will be added soon, see #4543), because the base system does not contain libunwind package. The package is provided by EPEL and as I see we suggest to enable EPEL before our repo in the [documentation][1]. However I'm tentative about assuming that EPEL is enabled: I don't want to loss ability to pick up a tarantool's RPM package and install it on any CentOS 8 machine.

We can add libunwind to our repos, but here I'm tentative too and the reason is the same: we would unable to just give a user an RPM package (using any communication channel) and being sure that the installation will be successful.

I don't sure, but maybe we can bundle libunwind into our executable for distros where it is not always available.

[1]: https://www.tarantool.io/en/download/os-installation/1.10/rhel-centos-6-7/

**Comment by Totktonada** [comment]
Hm, it seems I misread something and there are no libunwind and libunwind-devel in EPEL for CentOS 8.

**Comment by Totktonada** [comment]
Hm (2). https://pkgs.org/download/libunwind does not show libunwind[-devel] in EPEL for CentOS 8, but the following commands shows that they are there:

```sh
$ docker run -it centos:8 /bin/bash
# yum search libunwind
<...>
No matches found.
# yum install epel-release
# yum search libunwind
<...>
libunwind.x86_64 : An unwinding library
<...>
libunwind-devel.x86_64 : Development package for libunwind
```

However it does not matter much anyway.
