### ISSUE TITLE
netbox: error when client and server have different sets of supported field types

### ISSUE THREAD

**Issue by ImeevMA** [tarantool/tarantool#4632]
When a client connects to the server using netbox, an error may
occur when the client and server have different sets of field
types.

Reproducer (Tarantool version in brackets):
1) Server (1.10):
```
box.cfg{listen=3302}
box.schema.user.grant('guest','read, write, execute', 'universe')
format = {}
format[1] = {type = 'unsigned', name = 'i'}
format[2] = {type = 'any', name = 'a'}
box.schema.space.create('s', {format=format})
box.space.s:create_index('i')
```
2) Client (2.3):
```
remote = require('net.box')
cn = remote.connect(3302)
decimal = require('decimal')
cn.space.s:insert({1, decimal.new('1.123')})
```
3) Server (1.10):

```
box.space.s:select()
```

Result:
```
tarantool> box.space.s:select()
---
- - 'builtin/msgpackffi.lua:546: assertion failed!'
...
```

Another reproducer:
1) Server (2.3)
```
box.cfg{listen=3302}
box.schema.user.grant('guest','read, write, execute', 'universe')
format = {}
format[1] = {type = 'unsigned', name = 'i'}
format[2] = {type = 'decimal', name = 'a'}
box.schema.space.create('s', {format=format})
box.space.s:create_index('i')
```

2) Client (1.10):
```
remote = require('net.box')
cn = remote.connect(3302)
cn.space.s:select()
```

Result:
```
tarantool> cn.space.s:select()
---
- - 'builtin/msgpackffi.lua:546: assertion failed!'
...
```

The problem is more serious if the client is 2.2 and the server has more field types than the client - since in 2.2 we create tuple_format for each server space (#2978). In this regard, if the client detects any new field type in server spaces , we will get assert in dev build or segfault in release build.

**Comment by ImeevMA** [comment]
In case there are more types of fields on the server than on the client, we can solve the problem by not showing spaces with new field types in format to the client. Thus, we also solve the problem with ASSERTION/SEGFAULT. Suggested by @Totktonada.

**Comment by Totktonada** [comment]
To sum up, cases to consider:

1. 1.10 server, 2.3 client:
    i. The client successfully inserts decimal value into a space, but the server unable to decode it (can store anyway).
2. 2.3 server, 1.10 cilent:
    i. Schema fetch fails when there is a 'decimal' field in a space format or a 'decimal' index part.
    ii. Select of a decimal value fails.
    iii. Receive of a decimal value from a function fails.

Hiding space solves only 2.i problem, but others still remains.

I think we should give a meaningful error message when meet a value that old tarantool can not decode: maybe even recognize mp_ext subtypes from newer tarantool versions.

The question is what to do with schema fetching.

Why the schema is needed on a client in the first place? Connectors (including net.box) usually use it to allow a user to perform requests against spaces using space / index names rather then IDs. If a client does not support certain field type / index, then it unable to perform some `insert`, `replace`, `update`, `upsert`, `select` operations (possible to insert `null` to a nullable decimal field or update fields other than decimal one), but it can do `delete`. It does not look worthful to provide such partial support for such spaces, so I would hide them (with warning to a log).

Aside of space / index names the schema is used in net.box to reconstruct a tuple from a space with proper space format ([since 2.2](https://github.com/tarantool/tarantool/issues/2978)): it allows to access a value from tuple by a field name (rather than ID) and also allows to pass a tuple to the binary protocol w/o marshaling over Lua (it saves mp_bin for 'varbinary' without replacing it with mp_str). But this property does not change anything: we mostly unable to operate on such space from an old tarantool.

**Comment by ligurio** [comment]
v1 https://lists.tarantool.org/pipermail/tarantool-patches/2020-May/016822.html

**Comment by Totktonada** [comment]
I want to describe reasons why I think about hiding 'unsupported' spaces.

(First, sorry for the long comment: I don't know how to express this shortly.)

The initial thought was: 'will space format fields and index parts of a net.box space/index objects give correct types'? Now I looked at _vspace and _vindex and I see: types are just strings. So net.box space object will just show those types even if they are not supported. Looks acceptable. (I verified it on net.box from 1.10.6-28-g8a457324b that fetches schema from 2.5.0-62-gbb7c3d167 server.)

Then I looked whether we can do something useful for a space with an unsupported field (described above). In fact, not much. But get it right: it is not the reason for hiding per se—it is more like a reason why we *can* do it if we'll want. So, not a real reason (but the thing we should keep in mind).

The next question is about tuple formats which are created by net.box since [2.2.0-463-g97e8c658f](https://github.com/tarantool/tarantool/commit/97e8c658f842bd9a623b1673f6ae752082502114) after schema fetching. There is no way to create a format with unsupported field type. I verified it on 2.2.3-1-g98ecc909a (which does not support decimal, but creates formats after schema fetch):

```
$ ./src/tarantool 
Tarantool 2.2.3-1-g98ecc909a
type 'help' for interactive help
tarantool> net_box = require('net.box')
---
...

tarantool> c = net_box.connect('/home/alex/listen.socket')
tarantool: /home/alex/p/tarantool-meta/2.2/tarantool/src/box/lua/misc.cc:207: int lbox_tuple_format_new(lua_State*): Assertion `fields[i].type != field_type_MAX' failed.
Aborted
```

We don't update 2.1 and 2.2 anymore (it reaches its EOL), one may ask why I bother about it at all. I'll answer.

The problem is not only in 2.2 in fact. We'll introduce new types and old tarantool will fail as shown above when will try to connect to the new one. It is already possible for UUID field, which was introduced in [2.4.0-183-gb238def80](https://github.com/tarantool/tarantool/commit/b238def8065d20070dcdc50b54c2536f1de4c7c7). All 2.3 will crash after schema fetch if there is an uuid field. Old 2.4 too.

So, the problem exists and we should not ignore it. What we can do?

1. Don't create formats (use default one)? Okay, I guess it is possible. Tuples selected from those spaces will have default (runtime) format and it will not be possible to access fields by names. (BTW, whether offset map will be constructed for them? I guess, no.) In fact, there are not much cases, when select will be successful, but a field with an unsupported type may be nullable and may have `nil` value: such tuple may be selected. Back to the question: this variant is possible, but lead to inconsistency in tuple formats.

2. Replace unsupported field type with 'any' when creating a format? I guess it will work, but I don't know tuple format internals good enough to say how weird consequences will be. This way looks error-prone for me.

3. Create a format w/o known type, but with known name? Don't know whether it is possible, but it would be the best option I think. Looks very similar to 2nd proposal, but I don't sure. I feel a difference between "I know that it is declared as 'any' on the server" and "I don't know a type of this field". I need to dig into tuple formats more to say something here.

4. Hide/lock such space? It is possibile way, but I would consider it as the last resort, because it splits spaces to different types: visible and hidden/locked; so it introduces the new term, which users should keep in heads. Of course we should not do it silently. Previously I proposed to give a warning into a log, but now I have the better idea: we can create a space / an index object, but don't allow operations on them (via a special metatable).

**Comment by Totktonada** [comment]
Hey, I wrote so much about tuple formats, but I missed that we'll not always receive decoding error at decoding a response with an unsupported value (even if both 'msgpack' and 'msgpackffi' modules will give proper errors in the case). Tuples are decoded with msgpuck directly and data placed to a tuple is just mp_next()'ed. It will be placed into a tuple successfully, but then we'll get a decoding error at accessing a tuple field.

Need to think what behaviour should be here.

**Comment by Totktonada** [comment]
@alyapunov proposed to consider an unknown extension type like box does: we can store such value or send somewhere. It is valid content of a tuple. One may even use tarantool to store its own extension types.

The next point from Alexander L.: net.box does not need types in space format in fact: just names. So it looks okay to just ignore them when create a space format. I also consider this way, see the item `3` above.

Alexander L. also proposes to ensure that we able to serialize a tuple with an unknown extensions type (msgpuck [does](https://github.com/tarantool/msgpuck/blob/3cc63d3d1d17c022894d8fb095c5d3dc3ae270aa/msgpuck.c#L36-L56) the same).

Questions that are unclear for me now:

* It seems we should provide a way to get raw field value from a tuple, without decoding. It allows to implement some logic even when tarantool does not support an extension. It seems such access should not be implemented with the same API as a regular field value access (`tuple[1]`, `tuple.foo`) to don't break backward compatibility when tarantool will gain support of such msgpack extension. Say, `tuple.rawget(field-number-or-name)`.
* What we should do with an unknown extension that arrives as a result of a call? Wrap it to some userdata / cdata (but the behaviour will be changed when tarantool will gain support of it)? Give an error right on decoding? Give an error, which may be catched and used to extract raw data?

NB: Relevant issue #5017 is resolved.

**Comment by ligurio** [comment]
Discussed with @Totktonada and decided to consider cases below and decided what should be done in scope of a ticket:

- 1.10 server, 2.x client
The client successfully inserts decimal value into a space, but the server unable to decode it (can store anyway).
- 1.10 client, 2.x server (via netbox)
Current behavior:
i. Schema fetch fails when there is a 'decimal' field in a space format or a 'decimal' index part.
ii. Select of a decimal value fails.
iii. Receive of a decimal value from a function fails.
What should be done: replace assert by error with description.
- 2.x server, 2.x client (via netbox)
Current behavior: ???
What should be done: replace assert by error with description.

Agreed that we should give a meaningful error message when meet a value that old tarantool can not decode (maybe even recognize `mp_ext` subtypes from newer tarantool versions).

- Check unsupported type with  'msgpack' and 'msgpackffi' modules because implementation may be vary. 
- Check access methods to a tuples with foreign type. Ideally it should return correct error.
- Make types not mandatory fields in format. Discuss with Gerold103. See https://github.com/tarantool/tarantool/issues/4632#issuecomment-618469508
- Allow user to work with unsupported types and provide methods to work with raw data in tuples and implement `__serialize` method that allows to show raw data in hex (or base64) (also there is a "lua: read raw msgpack from a tuple" #3909). 
```
t -- our tuple with unknown ext type inside

t[1] -- access
t.rawget() / t.rawfield() -- raw access
t:__serialize() -- print

tarantool> t
- [1, <...>]

tarantool> t[1]
- error: unable to blabla

x = foo(t[1]).bar -- !! lua error !!
```
- check call/eval functions with access to raw msgpack with foreign ext type. Return error with detailed description. See notes from Alexander https://github.com/tarantool/tarantool/issues/4632#issuecomment-663145263

**Comment by locker** [comment]
All the problems with decoding MsgPack data containing an unknown extension have been solved:

1. Errors raised on decoding an unknown MsgPack extension have been fixed. A proper error is now returned.
   <details>
   
   ```
   tarantool> require('msgpack').decode('\x92\x01\xd4\x2a\x00')
   ---
   - error: 'Unsupported MsgPack extension type: 42'
   ...
   
   tarantool> require('msgpackffi').decode('\x92\x01\xd4\x2a\x00')
   ---
   - error: 'builtin/msgpackffi.lua:596: Unsupported extension type'
   ...
   ```
   
   </details>

3. If a client receives a tuple that contains an unknown extension over net.box, they can still use it. An error will be raised only on an attempt to access the unknown extension field. It is possible to encode such a tuple in MsgPack (e.g. to forward it).
   <details>
   
   ```
   tarantool> _ = box.space.test:insert(msgpack.object_from_raw('\x92\x01\xd4\x2a\x00'))
   ---
   ...
   
   tarantool> t = require('net.box').connect(3301).space.test:get(1)
   ---
   ...
   
   tarantool> t[1]
   ---
   - 1
   ...
   
   tarantool> t[2]
   ---
   - error: 'builtin/msgpackffi.lua:596: Unsupported extension type'
   ...
   
   tarantool> msgpack.encode(t)
   ---
   - !!binary kgHUKgA=
   ...
   ```
   
   </details>

3. If a function returns an unknown extension, a net.box call will raise an error. However, one can use the `return_raw` net.box option to return the value as a MsgPack object without decoding it. The MsgPack object can be decoded partially or forwarded.
   <details>
   
   ```
   tarantool> function foo() return msgpack.object_from_raw('\x92\x01\xd4\x2a\x00') end
   ---
   ...
   
   tarantool> o = require('net.box').connect(3301):call('foo')
   ---
   - error: 'Unsupported MsgPack extension type: 42'
   ...
   
   tarantool> o = require('net.box').connect(3301):call('foo', {}, {return_raw = true})
   ---
   ...
   
   tarantool> i = o:iterator()
   ---
   ...
   
   tarantool> i:decode_array_header() -- skips the array header (multi-return)
   ---
   - 1
   ...
   
   tarantool> i:decode_array_header() -- skips the array header
   ---
   - 2
   ...
   
   tarantool> i:decode() -- decodes the first value of the array
   ---
   - 1
   ...
   
   tarantool> i:skip() -- skips the second value (unknown extension)
   ---
   ...
   
   tarantool> i:skip()
   ---
   - error: iteration ended
   ...
   ```
   
   </details>

We may still need to improve the [MsgPack object](https://www.tarantool.io/en/doc/latest/reference/reference_lua/msgpack/#msgpack-object) API. We may also want to let the user register a callback that would be invoked to decode an unknown MsgPack extension. However, these improvements look like different issues. Please file new tickets if you have any suggestions.

What remains to be done in the scope of this ticket is we need to fix a crash in case net.box receives unknown field type while fetching a space format:

```
tarantool: ./src/box/lua/misc.cc:395: int lbox_tuple_format_new(lua_State*): Assertion `fields[i].type != field_type_MAX' failed.
Aborted
```
