### ISSUE TITLE
Use lib/small/small/static in backtrace, drop 12KB BSS buffer

### ISSUE THREAD

**Issue by Gerold103** [tarantool/tarantool#4650]
`lib/core/backtrace.cc` has a static buffer of 12 KB in side. But `lib/small/small/static.h` already offers a thread safe static buffer of a much bigger size. I think it can be used here, and 12 KB backtrace's buffer can be dropped.

**Comment by olegrok** [comment]
It seems that this commit (https://github.com/tarantool/tarantool/commit/2110213cb8c4a5ab99071c37dad3b03be8ccb527) closed wrong issue

Correct is - https://github.com/tarantool/tarantool/issues/4560

**Comment by Gerold103** [comment]
Well, I even said it in the patches mailing list, but seems like our push-man didn't care.

**Comment by igormunkin** [comment]
@Gerold103, I guess it's more my fault, sorry. @OKriw fixed your remark in the patch sent to our lists, but the corresponding remote branch hasn't been synced. I haven't checked it, since I thought the patchlist is a primary source, and asked @kyukhin to apply this patch to our stable branches. Next time I'll check it twice.
