### ISSUE TITLE
Diagnostics are not set on obuf_alloc fail in iproto_reply_error

### ISSUE THREAD

**Issue by PersDep** [tarantool/tarantool#4667]
In:
```
int
iproto_reply_error(struct obuf *out, const struct error *e, uint64_t sync,
		   uint32_t schema_version)
{
	uint32_t msg_len = strlen(e->errmsg);
	uint32_t errcode = box_error_code(e);

	struct iproto_body_bin body = iproto_error_bin;
	char *header = (char *)obuf_alloc(out, IPROTO_HEADER_LEN);
	if (header == NULL)
		return -1;

	iproto_header_encode(header, iproto_encode_error(errcode), sync,
			     schema_version, sizeof(body) + msg_len);
	body.v_data_len = mp_bswap_u32(msg_len);
	/* Malformed packet appears to be a lesser evil than abort. */
	return obuf_dup(out, &body, sizeof(body)) != sizeof(body) ||
	       obuf_dup(out, e->errmsg, msg_len) != msg_len ? -1 : 0;
}
```
on ```obuf_alloc``` fail diag_set must be performed before returning the error

**Comment by Gerold103** [comment]
Well, I think that is done intentionally. Because in case of an error during error reporting there nothing to do with the new error. Besides, iproto_reply_error() is ignored anyway, so it can't lead to any segfaults. And finally, obuf_dup() here does not set a diag as well. But as I said, that is not a problem. Because there is nothing to do in case of OOM anyway.

**Comment by PersDep** [comment]
> Well, I think that is done intentionally. Because in case of an error during error reporting there nothing to do with the new error. Besides, iproto_reply_error() is ignored anyway, so it can't lead to any segfaults. And finally, obuf_dup() here does not set a diag as well. But as I said, that is not a problem. Because there is nothing to do in case of OOM anyway.

Right, missed it
