### ISSUE TITLE
SQL: last_insert_id()

### ISSUE THREAD

**Issue by zilveer** [tarantool/tarantool#4747]
Hi,
Is there a function to retrieve the last inserted ID of a primary key in SQL syntaxes for Tarantool ?

Regards Zilveer

**Comment by pgulutzan** [comment]
There is no exact equivalent of the MySQL/MariaDB last_insert_id() function, but if a table was defined with CREATE TABLE t (c INTEGER PRIMARY KEY AUTOINCREMENT); then SELECT MAX(c) FROM t; can be useful, or SELECT lua('return box.space.T.index[0]:max()[1]');

**Comment by Korablev77** [comment]
@zilveer You can ask any questions in our English-speaking Telegram chat: https://telegram.me/tarantool

I guess this issue is resolved.

**Comment by jobs-git** [comment]
.I dont think it is solve already. From my understanding Select MAX is not atomic and not session based, so if there is another commit that succeeded before SELECT MAX, then it will result to a wrong row being returned. Maybe this should be reopened?

**Comment by Korablev77** [comment]
@jobs-git 

There's no yield points in `SELECT MAX()` query so taking into consideration "single thread nature" of Tarantool, mentioned situation can't happen.

**Comment by jobs-git** [comment]
.does this also work in master-slave, cluster, replication? Are we always guaranteed that it will return the correct one similar to what `last_insert_id` provides?

If its sql implementation will result to performance bottleneck, I would like to propose a solution:

Since tarantool already returns an ID for a transaction via tarantool sync, maybe its also possible to include the current insert ID

**Comment by Korablev77** [comment]
@jobs-git

In Tarantool replication is asynchronous, so there's no guarantee that last inserted id on master and on slave will be the same. 

Moreover, note that all auto-generated ids are returned as meta-information (in addition to `row_count`) in response to `INSERT` request:
```
CREATE TABLE t(id INT PRIMARY KEY AUTOINCREMENT);
INSERT INTO t VALUES (1), (NULL), (NULL);
---
- autoincrement_ids:
  - 2
  - 3
  row_count: 3
...
```

> If its sql implementation will result to performance bottleneck, I would like to propose a solution:

Provided by @pgulutzan ways of fetching last inserted id are lightweight enough to not worry about performance issues.

In case you need (for some reason) built-in function emulating MySQL behaviour (per-session based), please describe your proposal and file a separate issue. Thanks.

**Comment by jobs-git** [comment]
I dont know if I am getting you right but you might have just confirmed that SELECT MAX will not guarantee the correct ID in case of replication? A proper last insert ID should be implemented, thus this issue should be reopened.

Since the row_count of the current insert is also being returned, then, that is also an alternative to insert_id, thanks for that! :)

**Comment by Korablev77** [comment]
> I dont know if I am getting you right but you might have just confirmed that SELECT MAX will not guarantee the correct ID in case of replication? A proper last insert ID should be implemented, thus this issue should be reopened.

It's not the problem with last-insert-id implementation. It is not achievable with asynchronous replication (at least in scope of Tarantool architecture) at all.
