### ISSUE TITLE
sql: introduce type <ARRAY>

### ISSUE THREAD

**Issue by Korablev77** [tarantool/tarantool#4762]
To finish SQL integration with Tarantool NoSQL, we have to allow users to interact with all existing field types. Otherwise, users are not able to operate on spaces containing at least one of field with type which is unsupported (e.g. see https://github.com/tarantool/tarantool/issues/4758 and https://github.com/tarantool/tarantool/issues/4757). One of those types is ARRAY, which is not described in ANSI SQL. To access array elements in first implementation iteration it is suggested to consider built-in helpers like:
`array_get('field_name', 'element_index');`
`array_set('field_name', 'element_index', 'new_value');`
`array_create('values', ...);`
```
CREATE TABLE t (i INT PRIMARY KEY, a ARRAY);
INSERT INTO t VALUES (1, array_create(1, 2, 3));
INSERT INTO t VALUES (2, array_create(2.123, 'abc'));
SELECT * FROM t;
---
- - [1, [1, 2, 3]]
  - [2, [2.123, 'asd']]
...
SELECT a FROM t;
---
- - [[1, 2, 3]]
  - [[2.123, 'asd']]
SELECT array_get(a, 1);
- - [1]
  - [2.123]
SELECT array_get(a, 2), array_get(a, 3) FROM t; 
- - [2, 3]
  - ['abc', NULL]
```
Alternatively `array_get() `may accept third optional argument indicating default value in case array index is out of bounds. Note that throwing an error in this case is likely to be unacceptable since arrays may feature different number of elements.
```
UPDATE t SET array_set(a, 2, 'abc') WHERE array_get(a, 2) = 2;
...
```
`array_get()` and `array_set` can be replaced with `[ ]` indexation operation later.

For the sake of performance these functions can be implemented as separate VDBE opcodes.

Values of array type shouldn't be implicitly or explicitly comparable with values of other types. To compare array values between each other one can use `array_compare('array_lhs', 'array_rhs')`
As for internal representation array can be held packed (i.e. encoded with MP_BIN flag) in `struct Mem` with both `SQL_SUBTYPE_ARRAY` and  `SQL_SUBTYPE_MSGPACK` auxiliary subtypes.

**Comment by ImeevMA** [comment]
@pgulutzan I am planning to add new functionality to the built-in function `LENGTH()`: I want to return the number of items in ARRAY using `LENGTH(<ARRAY value>)` and the number of key-value pairs in MAP using `LENGTH(<MAP value>)`. What do you think about it?

**Comment by pgulutzan** [comment]
I had some comments about arrays in issue #2337 and issue #6251.
But here I will only address the very limited question:
getting the number of array elements if there is an ARRAY data type.

I don't believe LENGTH() is the appropriate function, because I expect that somebody might think it would be useful to know the number of bytes, and LENGTH() is a natural function for returning the number of bytes, because it does so for varbinary.

I do believe that the standard function CARDINALITY() is more appropriate.
For Tarantool/SQL, this would mean that:
CARDINALITY will be a new reserved word -- I failed to think of this when making a list in issue #5807.
CARDINALITY(array-value) will return data type INTEGER, since we assume that no array will ever have too many elements.
If you allow SQL arrays to contain NULLs, then CARDINALITY will include them, and following elements, in the count.
If the value does not have data type ARRAY, or Lua type 'table', then the result is an error.
In this case, "cardinality" means number of elements, not number of unique elements.

**Comment by ImeevMA** [comment]
Thank you for the answer. What about MAP? We can get number of elements for MAP, but I am not sure if this is useful. Still, it might show that MAP is not empty.

**Comment by pgulutzan** [comment]
There's no standard, so I can only make guesses about what someone might like.
A map has 0 or 1 "elements" (although that's probably not the correct term), so CARDINALITY can be used for it.
Or
An empty map is NULL, so you don't use a function, you use IS [NOT] NULL.
Or
An empty map has 0 bytes, so you know it's empty if LENGTH(map-value) = 0.
Or
First decide whether you want a way to get a map's key or a map's value.
