### ISSUE TITLE
Compare integer to boolean

### ISSUE THREAD

**Issue by pgulutzan** [tarantool/tarantool#4783]
I have Ubuntu 18.04. I have Tarantool 2.4, pulled from source today.
I execute these requests:
DROP TABLE t;
CREATE TABLE t (_integer INTEGER PRIMARY KEY);
INSERT INTO t VALUES (0), (1);
SELECT * FROM t WHERE _integer = FALSE;
SELECT * FROM t WHERE 5 = FALSE;
SELECT * FROM t WHERE _integer <> FALSE;
Result of the first select: 0 rows.
Result of the second select: Error, type mismatch.
Result of the third select: Error, type mismatch.

Then I execute these requests:
DROP TABLE t;
CREATE TABLE t (_integer SCALAR PRIMARY KEY);
INSERT INTO t VALUES (0), (1);
SELECT * FROM t WHERE _integer < FALSE;
SELECT * FROM t WHERE _integer > FALSE;
SELECT * FROM t WHERE _integer <> FALSE;
Result of the first select: 2 rows
Result of the second select: 2 rows
Result of the third select: Error, type mismatch.

I hesitate to say which of the selects is wrong,
but I hope it is clear: they cannot all be correct.

**Comment by ImeevMA** [comment]
Hello @pgulutzan ! I think this problem is related to #4230. I can’t say for sure for the first case, since we need to decide whether the behavior for cases when the index can be used is the same as the behavior for cases when it cannot be used. For example, in your example, we can make a small change, and the behavior will change:
```
tarantool> CREATE TABLE t (_integer INTEGER PRIMARY KEY);
---
- row_count: 1
...

tarantool> INSERT INTO t VALUES (0), (1);
---
- row_count: 2
...

tarantool> SELECT * FROM t WHERE _integer + 0 = FALSE;
---
- null
- 'Type mismatch: can not convert unsigned to boolean'
...
```

Another example:
```
tarantool> CREATE TABLE t (i DOUBLE PRIMARY KEY, a DOUBLE);
---
- row_count: 1
...

tarantool> INSERT INTO t VALUES (0, 0), (1, 1);
---
- row_count: 2
...

tarantool> SELECT * FROM t WHERE i in ('a', true, false);
---
- null
- 'Type mismatch: can not convert FALSE to double'
...

tarantool> SELECT * FROM t WHERE a in ('a', true, false);
---
- metadata:
  - name: I
    type: double
  - name: A
    type: double
  rows: []
...
```

Regarding the second example, we need to decide whether we want to use SCALAR rules for this comparison or not. It is worth noting that if we decide that the behavior for cases when the index can be used is the same as the behavior for cases when the index will not be used, then the only possible option is to use SCALAR rules for comparison.
