### ISSUE TITLE
fio.tempdir doesn't respect $TMPDIR

### ISSUE THREAD

**Issue by rosik** [tarantool/tarantool#4794]
It's common practice in linux to use `$TMPDIR` for specifying temp root.

See, for example, `mktemp` documentation:

```man 
$ mktemp --help
Usage: mktemp [OPTION]... [TEMPLATE]
...
  -p DIR, --tmpdir[=DIR]  interpret TEMPLATE relative to DIR; if DIR is not
                          specified, use $TMPDIR if set, else /tmp.
```

But in `fio.tempdir` implementation the template is hardcoded: https://github.com/tarantool/tarantool/blob/6e393aca004629341eebe97497c4573a30ecc7b9/src/lib/core/coio_file.c#L474-L478

My proposal is to respect `$TMPDIR` and allow specifying custom templates.

**Comment by Gerold103** [comment]
@rosik
I made a patch, but it was decided to discuss it before push. The thing is that there are multiple ways to define a template argument. Here are existing options:
* POSIX way. Template is a string, having `XXXXXX` at the end. When a name is generated, these 6X are replaced with some digits and letters. If there are less than 6X, it is an error - invalid template. If there are more than 6X, still only last 6 are replaced. So, `dirXXXXXXXX` will be turned into `dirXXabcdef`. The is a standard, and is implemented on Linux.
* Mac way. Template is any string. If it has any number of `X` in the end, they are all replaced by digits and letters. All templates are valid. So you can use `dirX` - will be turned into `dirXa`, or you can use `dirXXXXXXXX` - will be turned into `dirabcdefgh`. You can even omit `X`, but such a call will succeed only once, of course.

Behaviour is on both systems encapsulated into `mkdtemp()` function. I implemented the standard way, but as @igormunkin noticed, you probably want the Mac behaviour. Regardless of your solution, I will need to implement `mkdtemp()` manually, since as you can see, built-in version does not work the same on Mac and Linux. Whatever you choose, I will make it work the same.

You need to choose what is better. Or propose something different.

Also there is an idea to add an argument `suffixlen`. It is the same as suffix len argument in `mkstemps()` function. It would allow you to have `X` sequence not only in the end of a name. Built-in `mkdtemp()` does not have that argument, but since we reimplement it from the scratch, it is not hard to add the argument. Do you need it?
