### ISSUE TITLE
Cancelling fiber doesn't interrupt netbox operations

### ISSUE THREAD

**Issue by rosik** [tarantool/tarantool#4834]
Tarantool version: 2.2.2-69-g04deb6e33

### Bug description

Cancelling a fiber doesn't interrupt netbox operations

### Steps to reproduce

1. Starting an "unresponsive" service: `nc -l 3301`
2. Copy-paste the following code into tarantool console

```lua
fiber = require('fiber')
conn = require('net.box').connect('localhost:3301', {wait_connected = false})
f = fiber.create(function()  print(pcall(conn.wait_connected, conn)) end)
f:cancel()

f
```

You'll see the fiber is suspended, and it'll remain the same until connection timeouts

```text
---
- status: suspended
  name: lua
  id: 104
...
```

Moreover, in conjunction with `reconnect_after` option it results in immortal fiber:

```lua
fiber = require('fiber')
conn = require('net.box').connect('localhost:9', {reconnect_after = 1, wait_connected = false})
f = fiber.create(function()  print(pcall(conn.call, conn, 'print', {'Foo'})) end)
f:cancel()

f
```

```text                                                                                                                                                                                                
---
- status: suspended
  name: lua                                        
  id: 108                                 
...
```

**Comment by olegrok** [comment]
In fact the reason is #5013

Because net.box call uses `fiber.cond()` under hood. And fiber simply hands in an infinite loop:

https://github.com/tarantool/tarantool/blob/71a24b9f20d1f116d8d0f911dac94bbd7749cf87/src/box/lua/net_box.lua#L415-L419

BTW, It looks like regression after https://github.com/tarantool/tarantool/commit/0f686829a89b87d4f8d10fd25d4acfdea9b3dc60 when each call start to use `fiber.cond()`
