### ISSUE TITLE
fiber.cond:wait() returns when fiber is canceled

### ISSUE THREAD

**Issue by printercu** [tarantool/tarantool#5013]
Tarantool version: 2.3.1

Bug description:

`fiber.cond` works unexpectedly when fiber is canceled. It differs from other cases.

```lua
-- luacheck: no global
fiber = require('fiber')
log = require('log')

function test(name, fn)
    log.info(name)
    local f = fiber.new(function()
        log.info({pcall = {pcall(function()
            log.info({result = {fn()}})
            log.info('after cancel')
        end)}})
        log.info({testcancel = {pcall(fiber.testcancel)}})
    end)
    f:set_joinable(true)
    fiber.yield()
    log.info('before cancel')
    f:cancel()
    f:join()
    log.info('')
end

test('sleep', function() fiber.sleep(10) end)
test('channel', function() fiber.channel():get() end)
test('cond', function() fiber.cond():wait() end)
```

```
sleep
before cancel
{"pcall":[false,"fiber is cancelled"]}
{"testcancel":[false,"fiber is cancelled"]}

channel
before cancel
{"pcall":[false,"fiber is cancelled"]}
{"testcancel":[false,"fiber is cancelled"]}

cond
before cancel
{"result":[]}
after cancel
{"pcall":[true]}
{"testcancel":[false,"fiber is cancelled"]}
```

**Comment by Mons** [comment]
cond must behave like sleep during cancel

```
tarantool> t = {} f = fiber.create(function () local ok, err = pcall(fiber.sleep,1) t.ok = ok t.err = err end) f:cancel()
---
...

tarantool> t
---
- ok: false
  err: fiber is cancelled
...
```

expected behaviour:
```
t = {} f = fiber.create(function () local cond = fiber.cond() local ok, err = pcall(cond.wait, cond) t.err = err end) f:cancel()
---
...

tarantool> t
---
- ok: false
  err: fiber is cancelled
...
```

but got
```
```
t = {} f = fiber.create(function () local cond = fiber.cond() local ok, err = pcall(cond.wait, cond) t.err = err end) f:cancel()
---
...

tarantool> t
---
- ok: true
  err: true
...
```

```

**Comment by rosik** [comment]
N.B. Even if you decide to preserve current behavior it should be documented.

**Comment by sergos** [comment]
We're come to a deadlock here: 
If we fix the interface from returning ```true``` to ```false``` in released versions it will break compatibility and cause errors on an unknown amount of installations after minor upgrade to 1.10.x+1. Which is no good.
Otherwise if we keep old behaviour in released versions and change the interface into 'righteous' as mentioned in the https://github.com/tarantool/tarantool/issues/5013#issuecomment-670556365 we'll end up with connectors/modules overcomplication that will have to support two versions of code. Which is no good again.
