### ISSUE TITLE
Move base CI/CD jobs from Gitlab to Github

### ISSUE THREAD

**Issue by kyukhin** [tarantool/tarantool#5294]
It looks reasonable to have one source for everything, so lets move from Gitlab CI/CD to GitHub.

**Comment by avtikhon** [comment]
As I remember GitHub is a free software, while Gitlab we have as a payed solution, are we sure that it will have the same benefits like images repositories and etc.?

**Comment by Totktonada** [comment]
We can use Docker Hub (GitHub will have [tight limits](https://docs.github.com/en/github/setting-up-and-managing-billing-and-payments-on-github/about-billing-for-github-packages)).

**Comment by avtikhon** [comment]
Ok, so one mirror cut without issues for developers and without support needs looks reasonable to switch CI/CD and spent time for it, isn't it ?

**Comment by Totktonada** [comment]
Pragmatically:

- Cons:
  - Logs are stored for 3 months, not infinitely.
  - Docker Hub for images.
- Pros:
  - Ability to share a workflow within other repositories (offter it for others, reuse).
  - Dynamically [generate](https://github.blog/changelog/2020-04-15-github-actions-new-workflow-features/#new-fromjson-method-in-expressions) build matrices.
  - Wide community and a lot of automation examples (not only per-push jobs are supported, but [events of different kinds](https://docs.github.com/en/actions/reference/events-that-trigger-workflows)). Say, we can run rewrite [docbot](https://github.com/tarantool/docbot) to make it serverless and more reliable.
  - Good interation with GitHub (most critical is #5258).
  - Windows workers (relevant for some connectors, but not for tarantool/tarantool).

Non-pragmatically:

It is proud to use nice things.

**Comment by avtikhon** [comment]
As I see github actions has the following differences to gitlab-ci:

- github action has payed versions and it means that free version will be with minimal features available;
- workflows instead of pipelines, it means that it will be independent jobs without abilities to make different stages, right it may possible to make dependencies  on results, but not pipelines;
- jobs output spent too much time to check due to it needs to be opened each of them;
- GUI interface of the jobs provides abnormal way to show output in internal windows with minimal height and visibility;
- not supported to scroll output of the jobs with page down/up buttons;

-

**Comment by avtikhon** [comment]
> * Pros:
>   
>   * Ability to share a workflow within other repositories (offter it for others, reuse).

Seems that the common is possible in gitlab-ci too.

>   * Dynamically [generate](https://github.blog/changelog/2020-04-15-github-actions-new-workflow-features/#new-fromjson-method-in-expressions) build matrices.

That is absolutely the same that any CI have - all of them have it, but in different format. Check the following:
# some common part
.template: &template_pointer
  <<: *common_definition
  image: ${IMAGE_PERF_BUILT}
  stage: perf
  artifacts:
    when: always
    paths:
      - "*_result.txt"
      - "*_t_version.txt"
  script:
    - ${GITLAB_MAKE} test_all

check_on_clang:
  <<: *template_pointer
  variables:
    CC: clang

check_on_gcc:
  <<: *template_pointer
  variables:
    CC: gcc

>   * Wide community and a lot of automation examples (not only per-push jobs are supported, but [events of different kinds](https://docs.github.com/en/actions/reference/events-that-trigger-workflows)). Say, we can run rewrite [docbot](https://github.com/tarantool/docbot) to make it serverless and more reliable.

Gitalb-ci has really good documentation and examples too - github action not better.

>   * Good interation with GitHub (most critical is #5258).

I have strong my own opinion here. I don't agree to run ALL externally forked pull requests on our local test structure w/o manual decision. As I understood we want to check pull request at the external Tarantool project forks. Ok, let's do it, but do't run it
w/o manual check - in this way it's really easy to pull changes to our local testing branch. Anyway we have not to much PRs and all of them can be checked and pulled to our branches. Otherwise, if there would be a lot of external PRs, I double suggest not to give the access of them to automate its testing on our limited testing resources - we have it just so much as we need and not more (our testing structure is not based on automate cloud resources).

>   * Windows workers (relevant for some connectors, but not for tarantool/tarantool).

We didn't check the ways to run it in gitlab-ci due to not needed at all.

> It is proud to use nice things.

Check my previous comment on 'nice' usability.

**Comment by kyukhin** [comment]
Let's start from moving code coverage to GH actions.
