### ISSUE TITLE
Raft: force replica rejoin on rollback from master 

### ISSUE THREAD

**Issue by cyrillos** [tarantool/tarantool#5445]
Once a replica receives a rollback packet it should initiate re-join procedure if the transactions from the rollback do not present in replica's limbo.

**Comment by Gerold103** [comment]
The reason for this is that the node may be not a leader, but have newer data. This happens in Raft, when a node couldn't win the election somehow, and then was connected to the new leader. Some of its data can be even committed, in case the data was written by asynchronous transactions not waiting for a quorum. Sync transactions can be rolled back without a rejoin, because they were not committed yet. Presence of committed async transactions means the node can't force the same state of its data as on the leader, and can only rejoin.

Things are a bit complicated here, because rejoin can be safe only in case there were no local transactions (with replica_id = 0, into local spaces). But when Raft is enabled, local transactions always exist - the Raft state updates are written to WAL with replica_id = 0. So now rejoin is the only option, even if the follower does not have any committed transactions beyond the new leader. If we want to avoid rejoin sometimes, this issue should be fixed first.
