### ISSUE TITLE
Raft: support symbolic evaluation for quorum number in config

### ISSUE THREAD

**Issue by cyrillos** [tarantool/tarantool#5446]
Using plain number in `replication_synchro_quorum` is not enough. Instead we should provide a symbolic representation which we would evaluate. For example `N/2+1`.

**Comment by cyrillos** [comment]
The formula should be evaluated via `loadstring` wrapped by `setfenv`, for example `N=box.space._cluster:count()`

**Comment by Gerold103** [comment]
The reason is that users will likely not understand how the option should be configured properly, and will break something accidentally. So this idea about allowance to write an expression on the cluster size allows to specify the canonical `N/2 + 1` formula, and not update it manually on all instances, when a new node is added, or an existing one is deleted.
