### ISSUE TITLE
Add box.info.replication.X.downstream.lag

### ISSUE THREAD

**Issue by cyrillos** [tarantool/tarantool#5447]
We have an upstream lag and need a downstream as well.

**Comment by Gerold103** [comment]
It is supposed to help to see how fast the leader collects ACKs in synchronous replication. Because the downstream lag is going to be basically a transaction's RTT. This should simplify monitoring.

The lag should be calculated as `ACK timestamp - transaction replication timestamp`. Both timestamps should be measured using the master's clock. Not to depend on clock desyncs between instances.

**Comment by cyrillos** [comment]
https://lists.tarantool.org/tarantool-patches/20210121171753.186891-1-gorcunov@gmail.com/

**Comment by Gerold103** [comment]
downstream.lag should help to find slow replicas, which should be useful for synchronous replication. Now this 'lag' does not exist for downstream.

There are options how to do it, but they all come together in downstream.lag being the time passed since local WAL write until ACK from replica for this record.

**Option 1**
Downstream.lag is updated only when there is real replication. When there are only hearbeats, nothing to replicate, then lag freezes on the last known value.

Pros: it would be relatively stable, and would update immediately on ACK receipt.
Cons: would tell lie when there are no rows to replication. The real lag is not known.

**Option 2**
Downstream.lag is updated only when ACK is received, but it drops to 0 when there is no rows to wait ACK for.

Pros: when it is not 0, it is correct.
Cons: if the replication is faster than transactions creation, lag would leap back and forth between 0 and non-0. The latter might be quite big if synchronous transactions are slow but not very often. Monitoring plot would look like a saw, hard to read.

**Option 3**
Downstream.lag is updated constantly until there are non-received ACKs. It becomes 0 when no ACKs to wait for. The difference with the option 2 is that the update is literally continuous - each read of downstream.lag shows a bigger value until an ACK is received and corrects it.

Pros: with long transactions it won't freeze for seconds, and would show the truth when not 0.
Cons: the same as in the option 2. Also it is more complex to implement.

**Option 4**
Like option 2 and 3 + make lag decrease slowly instead of immediate drop to 0 when no ACKs to wait for. Maybe even its update must be done gradually too. For instance, using rmean statistics library.

Pros: the monitoring plots would be easier to read.
Cons: shows not exactly the truth, only its approximation. Like RPS counters for instance.

All the options with lag leaps have an issue that a monitoring might easily mill spikes because with not frequent transactions lag would drop to 0 immediately.

**Comment by ochaton** [comment]
For now alerting of high `replication.*.upstream.lag` is done using different tools which are connecting to instances periodically (once per minute) and retrieving `box.info`.

Sometimes smart routers/balancers polls each instance of replicaset 1-2 times per second and stop routing of Read requests to read only replicas (to prevent reading of stale data).

In critical systems some of the transactions must be replicated to quorum replicas before client receive commit (wait_lsn mechanism in older versions, and synchro replication in modern tarantool).

So the online value of `replication.*.downstream.lag` is useful only to investigate perfomance issues. To do this, customers wants metrics which are collected during different time ranges (last second, last minute, last hour) and basic statistics: min/max/med/p99. To collect that we may spawn background fiber in separate module (ex. metrics).

Thus the value of downstream.lag for monitoring/alerting purposes should show average status of significant amount of time (example: 1 minute).

IMO, the best choice to do both is measure downstream.lag as in `Option 3`

**Comment by cyrillos** [comment]
Thanks a huge for comment!

**Comment by cyrillos** [comment]
@ochaton Vlad, here are a few questions we need to know answers of: what is the minimal polling time monitor tools are using to detect lag problems? You've said

> polls each instance of replicaset 1-2 times per second

so can we assume that 500 ms is the minimum value here? IOW we should report last lag at least for 500 ms even if there is no more data coming between master and replica node?

This as well implies second question -- should we ever drop the lag to 0?
@Gerold103 @sergepetrenko
