### ISSUE TITLE
Fix luacheck warnings for luajit tests

### ISSUE THREAD

**Issue by ligurio** [tarantool/tarantool#5470]
Blocked by #5631

**Comment by igormunkin** [comment]
@ligurio, besides the warning suppression there is also the patch with [LGTM](https://lists.tarantool.org/pipermail/tarantool-patches/2020-July/018749.html) in LuaJIT repo (tarantool/luajit@5bc0393). I guess you've missed it, since this one doesn't refer the original issue. @kyukhin, can we apply it out of order?

**Comment by ligurio** [comment]
@igormunkin Yeah, missed it. I'll ask Kirill to merge it.

**Comment by ligurio** [comment]
@Totktonada Yep.

**Comment by igormunkin** [comment]
There is also c9653cb to be applied.

**Comment by ligurio** [comment]
Blocked by #5631

**Comment by igormunkin** [comment]
@ligurio, I've moved all LuaJIT-related static analysis into luajit repo (here is the [WIP branch](https://github.com/tarantool/luajit/tree/imun/gh-4862-cmake)). I'll take this issue on me and it will be closed with the patches made for #4862. The fixes for #5631 can be also found on the branch mentioned above.

**Comment by igormunkin** [comment]
The issue is initally fixed in scope of tarantool/luajit@8fc103f and is fully resolved in scope of  tarantool/luajit@6dd4724. The submodule was updated in tarantool in 2.8.0-82-g07c83aab5 (07c83aa), 2.7.1-73-gd112a4e6e (d112a4e), 2.6.2-70-g1b00de081 (1b00de0), 1.10.9-46-g5d25b860a (5d25b86).
