### ISSUE TITLE
modules: RPM / Deb deploy infrastructure for S3 based repositories

### ISSUE THREAD

**Issue by Totktonada** [tarantool/tarantool#5494]
I made [attempt][p] to use our [update_repo.sh][u] script for deploying tarantool-php connector and found the following downsides:

- A lot of surrounding code is necessary.
- A lot of secret variables (+encrypted files) need to be filled in CI settings.
- No way to update packages metainformation in a 'transactional' way: with appropriate looks (the script has machine-level locks, but it is not sufficient for containers created on demand by a CI provider).

We have [rocks.tarantool.org][r] server, which accepts rocks (source tarballs) for luarocks using HTTP PUT. This way looks convenient and I would implement a similar service for deploying RPM / Deb packages to our S3 based repositories. We can use the same `update_repo.sh` script under the hood.

[p]: https://github.com/tarantool/tarantool-php/pull/162
[u]: https://github.com/tarantool/tarantool/blob/bc6caac60d5ef070460374149cb7abe2b0db3cde/tools/update_repo.sh
[r]: https://github.com/tarantool/rocks.tarantool.org

**Comment by LeonidVas** [comment]
Hi, guys!
I think this information may be interesting to @Totktonada, @avtikhon, @romanhabibov.
The first iteration of MVP is available for reviewing here.
The microservice has been writen with using the Flask framework and prepared for deploment on Heroku.
Now the microservice can deploy packages (recived over HTTP using authentication) to the deb/rpm repositories on S3.
When implementing MVP, I had to chose one of mkrepo and update_repo.sh for generate metainformation of repositories (this discussion might be useful for review). These tools use different ways to generate metainformation of repositories.
In the case of using "mkrepo", metainformation is generated in accordance with the current state of the repository.
In the case of using the "update_repo.sh", the information about a new package is added to the current metainfarmation without checking the current state of the repository.
In other words, in the case of using "mkrepo", adding a package and updating metainformation can be done at different times ("asynchronously"), in the case of using "update_repo.sh", adding a package and updating metainformation is most be done in one transaction("synchronously").
At the moment, the "asynchronous" variant has been implemented, because I think that this is a correct and simple model. However, a switching to a "synchronous" model is possible. For these purpose need to implement the "S3SyncModel" class with the same interface as "S3AsyncModel"(after that the config can be used to switch the model).
Possible problems during the implementation of the "S3SyncModel":

"update_repo.sh" needs to be rewritten in python, because working with a bash script that is larger than 100 lines causes despondency and depression (and this is not only my opinion (https://google.github.io/styleguide/shellguide.html#when-to-use-shell)). Seriously, if you want to write a script on bash larger than 100 lines in 2020, you must have a very good arguments
Likely, in this case we will have problems when deploying to Heroku (causes is dependencies)

**Comment by igormunkin** [comment]
>  * "update_repo.sh" needs to be rewritten in python, because working with a bash script that is larger than 100 lines causes despondency and depression (and this is not only my opinion (https://google.github.io/styleguide/shellguide.html#when-to-use-shell)). Seriously, if you want to write a script on bash larger than 100 lines in 2020, you must have a very good arguments

[Oh, shit...](https://lists.tarantool.org/tarantool-patches/ec2505c1db7c56aa5fd17990b8a1d24d6de17c9b.1613065868.git.imun@tarantool.org/T/#u)

**Comment by LeonidVas** [comment]
> > * "update_repo.sh" needs to be rewritten in python, because working with a bash script that is larger than 100 lines causes despondency and depression (and this is not only my opinion (https://google.github.io/styleguide/shellguide.html#when-to-use-shell)). Seriously, if you want to write a script on bash larger than 100 lines in 2020, you must have a very good arguments
> 
> [Oh, shit...](https://lists.tarantool.org/tarantool-patches/ec2505c1db7c56aa5fd17990b8a1d24d6de17c9b.1613065868.git.imun@tarantool.org/T/#u)

)

**Comment by avtikhon** [comment]
> In the case of using "mkrepo", metainformation is generated in accordance with the current state of the repository.

1. The main issue in this way is that any of the changes made in repository by 3rd parties will legalized de-facto. So repository should have some up control process that checks the list of changes made. Let's imagine that some parallel process will add/remove packages and current process will legalize (make it signed) it without check - and nobody will detect it ever.
2. Also the time needed to update the meta files in repository on each package add/remove call would increase on each added package, due to it checks all of the packages in repository and updates all its meta files. To get all the checksums for all the files all of them should be downloaded.
3. To get meta information for the packages better use well known generators for it like [reprepro](https://unixforum.org/viewtopic.php?t=79513) and [createrepo](https://linux.die.net/man/8/createrepo).

**Comment by Totktonada** [comment]
https://github.com/tarantool/rws
