### ISSUE TITLE
Add ERRINJ to pass path to a bootstrap snapshot

### ISSUE THREAD

**Issue by ligurio** [tarantool/tarantool#5540]
original idea described in https://lists.tarantool.org/pipermail/tarantool-patches/2020-November/020808.html

**Comment by Gerold103** [comment]
Why can't you simply start from the folder, where a snapshot of an older version is stored? The built-in snapshot is used only to start first time, when there are no existing snapshots in the workdir.

**Comment by Totktonada** [comment]
It is mainly to run the replication tests on a non-upgraded instance (#4801).

**Comment by Totktonada** [comment]
The test-run's part is trackerized [here](https://github.com/tarantool/test-run/issues/239).

**Comment by Gerold103** [comment]
But you didn't answer on the question. Why can't you use a workdir, where you would have an older snapshot? Why do you need to insert it into the process memory via some errinj?

**Comment by Totktonada** [comment]
AFAIU, we'll got a clash by a replica id if we'll try use the same snapshot to bootstrap a master and a replica. In theory we could place a snapshot to memtx_dir of the master and leave the directory empty for the replica, but it would require comprehensive look over the all replication tests, would require changes in the testing system and the tests. And I don't know, how to handle multi-master case (run a first from a snapshot and others without?).

I guess there are other cases, which would require a special attention if we'll pick up the approach you propose. At least, tests, which use a custom (say, a temporary) memtx_dir.

Since we want to emulate bootstrapping from an old-schema-version snapshot, the most straignforward and convenient way would be letting tarantool know where to find it and use the usual bootstrapping logic (not one that is used for local recovery).

**Comment by Gerold103** [comment]
Boostrap of a replica from a master node will fetch its snapshot, which is going to be the old one, like you want (but that must be checked). Otherwise you can simply have separate old snapshots for replicas.

Talking of the idea you are trying to introduce - you will simulate an impossible situation, which is not a point of error injections. They make something unlikely happen. And you will make something impossible happen, which may result into testing not what is actually used. Initial snapshot creation may have some special rules and assumptions. Now or in future. And the injection is likely to break them, maybe not now. In turn, resulting into the same situation - either change the tests, or use proper way to start instances.

It may look more complex to do, but doing the injection solution only because it is easy and probably will work now does not look good in perspective.

**Comment by Gerold103** [comment]
However I do not insist on any solution if it won't affect real usage, and I am not the one how need to implement and support it :)

**Comment by Totktonada** [comment]
We had a voice discussion with @Mons and @ligurio regarding whether the proposed functionality may be useful outside of the linked testing task. There was the idea about a bootstrap snapshot for an application, however if it is not a lot of data, an application may write it to the database from Lua at first start.

Aside of this @Mons proposes to just implement an option, not something available only in a debug build. He said that a power user may find it useful. We didn't discuss whether it should be documented, though. (I guess we both assume a `box.cfg()` option, because it looks more appropriate than a cli argument.)

If we'll add ability to set box.cfg options with environment variables in future, we'll able to feed the bootstrap snapshots to tarantool instances that are started from a test using `io.popen()`.

**Comment by kyukhin** [comment]
> We had a voice discussion with @Mons and @ligurio regarding whether the proposed functionality may be useful outside of the linked testing task. There was the idea about a bootstrap snapshot for an application, however if it is not a lot of data, an application may write it to the database from Lua at first start.
> 
> Aside of this @Mons proposes to just implement an option, not something available only in a debug build. He said that a power user may find it useful. We didn't discuss whether it should be documented, though. (I guess we both assume a `box.cfg()` option, because it looks more appropriate than a cli argument.)

If so, I guess the new issue for the feature. I'll close this one, but feel free to reopen if needed.
