### ISSUE TITLE
Add tarantool to brew

### ISSUE THREAD

**Issue by khmelevskii** [tarantool/tarantool#580]

**Comment by rtsisyk** [comment]
I discussed this problem with @bigbes:

* Official homebrew repository doesn't allow `live` (e.g. `git`) formulas, so it is not possible to build Tarantool directly from GitHub using official brew.
* Every brew formula validates hard-coded checksum to match the tarball checksum, so it is not possible to just create dynamic tarantool-1.6.tar.bz on our web-site with the latest version of Tarantool.
* Any modification of formulas should be pushed to official repository via pull requests. Review usually take up to two weeks.

=> There is not way to automatically upload latest Tarantool on each build using our buildbot due to homebrew limitations.

Please do the following things:
1) Create a custom brew repository (brew tap) on `http://tarantool.org/dist/` with the latest version of Tarantool. 
https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/brew-tap.md
2) Push current major release of Tarantool 1.6.7 to upstream repository.

**Comment by rtsisyk** [comment]
Downstream ticket: https://github.com/Homebrew/homebrew/pull/47495

**Comment by bigbes** [comment]
Done
