### ISSUE TITLE
Demangling of C symbols inside memprof

### ISSUE THREAD

**Issue by Buristan** [tarantool/tarantool#5813]
We can use `Dl_info` and `dladdr()` function to provide the name of <*.so> file and the name of the C function, where allocation event occurred. It's better than just raw C address that tells nothing.

**Comment by olegrok** [comment]
Currently seems it affects a case when we call some function over netbox.

Simple server
```lua
box.cfg{listen = 3301}
box.schema.user.passwd('admin', 'test')

function alloc(n)
    if n == nil then
        n = 100500
    end
    local _ = string.rep('x', n) .. string.rep('y', n)
end

misc.memprof.start('./memprof.test')
box.ctl.on_shutdown(function()
    misc.memprof.stop()
end)
``` 

Simple client:
```lua
tarantool> netbox = require('net.box')
---
...

tarantool> c = netbox.connect('admin:test@localhost:3301')
---
...

tarantool> c:call('alloc')
---
...

tarantool> c:call('alloc', {1000})
---
...

tarantool> c:call('alloc', {1000}, {is_async = true})
---
- id: 7
  on_push: 'function: builtin#91'
  method: call_17
  cond: cond
  on_push_ctx: []
...

tarantool> c:call('alloc', {1000}, {is_async = true})
---
- id: 8
  on_push: 'function: builtin#91'
  method: call_17
  cond: cond
  on_push_ctx: []
...

tarantool> for i = 1, 1e5 do c:call('alloc', {i}, {is_async = true}) end
---
...

tarantool> for i = 1, 1e6 do c:call('alloc', {i}, {is_async = true}) end
---
...
```

Output:
```
ALLOCATIONS
CFUNC 0x1084939c0: 2200010	519202360	0
CFUNC 0x10af06a10: 1100004	52800192	0
@test.lua:4, line 8: 277	429667	0
INTERNAL: 2	676	0
CFUNC 0x10af06a40: 1	24	0
@test.lua:0, line 14: 1	40	0
@builtin/box/tuple.lua:93, line 94: 1	24	0

REALLOCATIONS
INTERNAL: 16	264344	528184
	Overrides:
		@test.lua:4, line 8
		INTERNAL

@test.lua:4, line 8: 2	393216	147456
	Overrides:
		@test.lua:4, line 8


DEALLOCATIONS
INTERNAL: 3262979	0	565742991
	Overrides:
		@test.lua:4, line 8
		CFUNC 0x1084939c0
		CFUNC 0x10af06a10
```

I don't know that first two rows actually mean:
```
CFUNC 0x1084939c0: 2200010	519202360	0
CFUNC 0x10af06a10: 1100004	52800192	0
```

**Comment by fckxorg** [comment]
Because symbol tables in memprof and sysprof are the same, it seems wise to move it to a separate module, which both of them will use. The process of symbols resolution should be either effective or should happen after the profiling process to avoid distortion of profiling data. 

Considering everything above, **I propose the following implementation**:
- Keep the same format for Lua symbols
- Dump information about ".so" files in the following way: 
`|  SYMTAB_SO (magic number)   |   path to .so   |    it's address    |   CRC-32 hash   |`

CRC-32 hash of ".so" file will be used for situations when it is needed to perform profile data parsing on a machine different from that one, from where profile came, to ensure that ".so" files are identical.

**Alternatives:**
- Dump Lua symbol table on profile start, and save addresses of C functions to Lua table in the process of profiling. Resolution of C symbols takes place on profile stop. 
Known issues: sysprof handler can be called in the middle of malloc call, so it may fail to allocate memory in Lua table, which holds C symbols.
- Dump Lua table on profile start with all of the C symbols from all loaded ".so" files.
Known issues: resolving all symbols from all ".so" files can be quite a long process, so benchmarking is needed.
