### ISSUE TITLE
Introduce UUID type support in SQL

### ISSUE THREAD

**Issue by sergos** [tarantool/tarantool#5886]
UUID type is supported in box interface, we need to implement support to comply the Tarantool types (#5847)

Supposedly the representation should be as blob in SQL with a set of built-in functions to support explicit conversions. 
All implicit casts should be implemented according to cast table in #5847.

**Comment by Korablev77** [comment]
But there's still no any cast table in #5847 yet...There's should be no implicit casts for uuid type at all - like for any other non-trivial type (map, array, datetime, varbinary etc).

**Comment by pgulutzan** [comment]
* Do the words "set of built-in functions to support explicit conversions"
mean that CAST to/from STRING, CAST to/from VARBINARY will be allowed,
and nothing else?
* When will UUID become a reserved word?
* Are comparison operators < = etc. legal for comparing two UUIDs?
* Is IS NULL true if value is 00000000-0000-0000-0000-000000000000?
* If CAST(uuid_value TO STRING) is legal, does the result have '-'s?
* If CAST(uuid_value to VARBINARY) is legal, is it necessary to
support byte-order as with Lua uuid_object:bin([byte-order])?
* Are there any built-in SQL functions that will work with uuid?
Specifically HEX(), IFNULL(), LENGTH(), TYPEOF()?
* How do I pass uuid_value to ODBC?
* What is the name of the function that returns a new uuid_value?
* Is it legal to insert a uuid_value into a column with data type SCALAR?
* What does SELECT * result look like if any column has data type UUID?

**Comment by tsafin** [comment]
> 
> 
> But there's still no any cast table in #5847 yet...There's should be no implicit casts for uuid type at all - like for any other non-trivial type (map, array, datetime, varbinary etc).

Yes, there is no yet published spec (see your inbox for draft soon). And I disagree that uuid should behave similarly to container type - all SQL vendors allow conditional implicit conversion from properly formatted string literals if they used in uuid context. More details see in the spec soon.

**Comment by tsafin** [comment]
Thanks for your questions - they are quite on-topic and challenging: 
> 
>     * Do the words "set of built-in functions to support explicit conversions"
>       mean that CAST to/from STRING, CAST to/from VARBINARY will be allowed,
>       and nothing else?

Looks like.
> 
>     * When will UUID become a reserved word?

Yup, I think so - we need to have such type known to parser.

> 
>     * Are comparison operators < = etc. legal for comparing two UUIDs?

Good question - it's not yet described in spec, I'll try to explain it further. My assumption is that uuids should be similarly comparable as blobs, according to current collation rules.
> 
>     * Is IS NULL true if value is 00000000-0000-0000-0000-000000000000?

Hmm, why it should be so? It's not generic NULL value.
> 
>     * If CAST(uuid_value TO STRING) is legal, does the result have '-'s?

Yes.
> 
>     * If CAST(uuid_value to VARBINARY) is legal, is it necessary to
>       support byte-order as with Lua uuid_object:bin([byte-order])?

Good question, for consistency sake it rather should support the same default mode. 
We should rather support that extra option in the builtin used for similar purposes.

> 
>     * Are there any built-in SQL functions that will work with uuid?
>       Specifically HEX(), IFNULL(), LENGTH(), TYPEOF()?
I didn't add anything MySQL specific to the list of suggested functions (yet). Please see my draft
coming to your inbox soon. 
It's a subject to discussion in any case.

> 
>     * How do I pass uuid_value to ODBC?

Isn't it the question to connector? That's their problem to properly encode binary and put correct
argument type at the binding time. 

> 
>     * What is the name of the function that returns a new uuid_value?

![image](https://user-images.githubusercontent.com/4956130/111143009-5f932700-8596-11eb-92a0-d0e98c4e4efb.png)

> 
>     * Is it legal to insert a uuid_value into a column with data type SCALAR?

Nope, so far I assume that uuid is not a scalar type. (Subject to discussion though)

> 
>     * What does SELECT * result look like if any column has data type UUID?

Same as today with uuid in box. Why it should behave anyhow differently?
(Well if we order 'select * from table' with uuid column today, then we would 
get nice SEGFAULT, but I'm talking about space:select() here)

**Comment by pgulutzan** [comment]
Your kind words about my questions do not discourage me from trying to cause trouble.

>>     * Do the words "set of built-in functions to support explicit conversions"
>>       mean that CAST to/from STRING, CAST to/from VARBINARY will be allowed,
>>       and nothing else?

> Looks like.

>>     * When will UUID become a reserved word?

> Yup, I think so - we need to have such type known to parser.

So version 2.7?

>>     * Are comparison operators < = etc. legal for comparing two UUIDs?

> Good question - it's not yet described in spec, I'll try to explain it further. My assumption is that uuids should be similarly comparable as blobs, according to current collation rules.

I ran uuid.new() a few times and concluded that it always generates
version-4 variant-1 UUIDs, though we don't document that. Therefore big-endian.
However, oddly, uuid.fromstr() allowed me to insert garbage variant bits:
uuid.fromstr('Ffffffff-ffff-ffff-dfff-ffffffffffff') is not an error.
So it's possible for a user to import UUIDs that are vaiant-2
(little-endian), but we will ignore this in comparisons, right?

>>     * Is IS NULL true if value is 00000000-0000-0000-0000-000000000000?

> Hmm, why it should be so? It's not generic NULL value.

I asked because
uuid.fromstr('00000000-0000-0000-0000-000000000000'):isnil()
is true.
I wonder whether this was a mistake -- sure it's called a "nil" UUID
in official UUID descriptions but why should that mean it is the same as Lua nil?
Anyway, even if it was not a mistake in Lua, it would be bad in SQL.

>>     * If CAST(uuid_value TO STRING) is legal, does the result have '-'s?

> Yes.

I bungled that question, I should have said AS, and I see that "Yes" is obvious.
However, CAST(string-value AS UUID) is not as easy, because
uuid.fromstr('x') returns null, while CAST('x' AS UUID) should
cause an error, right?.

>>     * If CAST(uuid_value to VARBINARY) is legal, is it necessary to
>>       support byte-order as with Lua uuid_object:bin([byte-order])?

> Good question, for consistency sake it rather should support the same default mode. 
> We should rather support that extra option in the builtin used for similar purposes.

So CAST(uuid_value AS VARBINARY 'h'), or some pretty variant, is legal syntax.
I have no idea why 'h' is default in Lua, but it is too late to change that now.

>>     * Are there any built-in SQL functions that will work with uuid?
>>       Specifically HEX(), IFNULL(), LENGTH(), TYPEOF()?

> I didn't add anything MySQL specific to the list of suggested functions (yet). Please see my draft
> coming to your inbox soon. 
> It's a subject to discussion in any case.

Those are Tarantool/SQL functions too.
I think they would not be hard to support, but it's easy to tell users:
we don't have HEX(uuid_value) but you can say HEX(CAST(uuid_value AS VARBINARY)).


>>     * How do I pass uuid_value to ODBC?

> Isn't it the question to connector? That's their problem to properly encode binary and put correct
> argument type at the binding time. 

You are right, it is not a relevant question for this issue.

>>     * What is the name of the function that returns a new uuid_value?

> ![image](https://user-images.githubusercontent.com/4956130/111143009-5f932700-8596-11eb-92a0-d0e98c4e4efb.png)

On that chart I see five functions that could return a new uuid value,
which you have included in the Tarantool column, so I guess you like thme.
I do not like them.
The four uuid_generate_... functions are PostgreSQL-like (perhaps my bias against
PostgreSQL is visible again); our current Lua generation with uuid.new()
seems to always be version-4 unless I analyzed incorrectly; the fifth
name uuid() seems adequate but using a reserved word for a function
name can fool a primitive program which would highlight the colour.
(By the way the SQL manual has an error-filled SQL colour scheme
because it uses such Denisovan technique, as I wrote in doc issue#1835.)
However, for the moment, let's assume uuid() will be legal.

I hope this is a good time to specify:
CREATE TABLE u (s1 UUID PRIMARY KEY DEFAULT uuid());
is illegal but would be a reasonable feature request someday.

>>     * Is it legal to insert a uuid_value into a column with data type SCALAR?

> Yup, uuid is same way scalar as string or blob. (Subject to discussion though)

I remember that somebody suggested that UUID values should be greater than VARBINARY values,
but I can't remember who. An alternative is: sort them mixed with VARBINARY values.

>>     * What does SELECT * result look like if any column has data type UUID?

> Same as today with `uuid` in box. Why it should behave anyhow differently?
> (Well if we order `'select * from T'` with `uuid` column today, then we would 
> get nice SEGFAULT, but I'm talking about space:select() here)

The question only affects box.execute([[select ...]]) which can look like this:

for select randomblob(1):

- metadata:
  - name: COLUMN_1
    type: varbinary
  rows:
  - [!!binary gQ==]
...

Not cute, eh? But now, from your answer, we know it will look like this:

for select uuid():

- metadata:
  - name: COLUMN_1
    type: uuid
  rows:
  - [7f8681f1-77fc-42bb-9191-8dcb951feab5]
...

**Comment by Mons** [comment]
> I ran uuid.new() a few times and concluded that it always generates
> version-4 variant-1 UUIDs, though we don't document that. Therefore big-endian.
> However, oddly, uuid.fromstr() allowed me to insert garbage variant bits:
> uuid.fromstr('Ffffffff-ffff-ffff-dfff-ffffffffffff') is not an error.
> So it's possible for a user to import UUIDs that are vaiant-2
> (little-endian), but we will ignore this in comparisons, right?

Yes, for now internal uuid implementation is v4 only (that's a problem).
But we should support either storage or generation of other versions.

> I asked because
> uuid.fromstr('00000000-0000-0000-0000-000000000000'):isnil()
> is true.
> I wonder whether this was a mistake -- sure it's called a "nil" UUID
> in official UUID descriptions but why should that mean it is the same as Lua nil?
> Anyway, even if it was not a mistake in Lua, it would be bad in SQL.


It doesn't looks like Lua's nil or box/ffi NULL:
```yaml
tarantool> uuid.fromstr('00000000-0000-0000-0000-000000000000') == nil
---
- false
...

tarantool> uuid.fromstr('00000000-0000-0000-0000-000000000000') == box.NULL
---
- false
...
```

> On that chart I see five functions that could return a new uuid value,
> which you have included in the Tarantool column, so I guess you like them.
> I do not like them.
> The four uuid_generate_... functions are PostgreSQL-like (perhaps my bias against
> PostgreSQL is visible again); our current Lua generation with uuid.new()
> seems to always be version-4 unless I analyzed incorrectly; the fifth
> name uuid() seems adequate but using a reserved word for a function
> name can fool a primitive program which would highlight the colour.
> (By the way the SQL manual has an error-filled SQL colour scheme
> because it uses such Denisovan technique, as I wrote in doc issue#1835.)
> However, for the moment, let's assume uuid() will be legal.

Heh, I very like PostgreSQL, so during a review with Timur I like to reference to it :)
But in this case I found `uuid_generate_*` family as kinda ugly. Maybe it would be better to use arguments to `uuid()`?

> I hope this is a good time to specify:
> CREATE TABLE u (s1 UUID PRIMARY KEY DEFAULT uuid());
> is illegal but would be a reasonable feature request someday.

I like this
