### ISSUE TITLE
Implement ability to pass several listening uris in different ways with different properties

### ISSUE THREAD

**Issue by alyapunov** [tarantool/tarantool#5928]
After #5645 we need to move further to iproto encryption.
We need to open different  iproto ports and set different properties. Later, we'll allow to turn on encryption on some of them.

**Comment by olegrok** [comment]
Seems related to https://github.com/tarantool/tarantool/issues/3554

**Comment by EvgenyMekhanik** [comment]
There are several options for solving this problem:
1. At this moment we bind socket in main thread and then listen it in all iproto threads. We can change this behaviour and require the user to set the listening address for each iproto thread. I don't think that it is a good idea.
2. We can leave the default behavior as it is and allow the user to set the listening address for a specific iproto thread, using box.cfg.
3. The most preferred option from my point of view is implement iproto thread object in Lua word in `net_box` or separate module. For example:
```
net_box = require('net.box')
-- get iproto thread object by number of thread
iproto_thread = net_box.iproto_thread(1)
-- Set a listening address for a specific iproto thread, that is different from the one specified in box.cfg{}
-- Starting from this time box.cfg { listen }, does not touch listening address of this thread and other network options
-- for this thread.
iproto_thread.listen("127.0.0.1", 8081)
-- If user wants to return this thread to default behaviour he must enter specific command, like this
iproto_thread:default_listen()
```

I think if we choose (3) , then it will be simply to add various functions to determine the behavior of specified ipproto thread.
For example:
-- Encrypt all data for this thread using openssl.
iproto_thread.encrypt("openssl")

**Comment by Gerold103** [comment]
Another approach - do the iproto threads like I proposed before: no connection pinning + handling of IO events and their scheduling into the workers always in one thread at a time (a so called shared scheduler). Then you could have many listening sockets handled in multiple threads using only libev means and a few inter-thread communication primitives. This way the worker threads sharing would be fair, and the users wouldn't need to bind number of threads to the number of ports they listen. These would be 2 separate parameters. You might even have a single thread and several listen sockets, in case you are sure the load is not big and the single thread would manage to handle it.

**Comment by Totktonada** [comment]
Aside of the question whether to pin a socket to a thread or not, I want to give my two coins about the API.

*(I had intention to leave a short note, but after some thoughts it becomes more like an API proposal.)*

I vote up extending of the existing `box.cfg{listen = <...>}` option like so: 

```lua
-- Now.
box.cfg{listen = '10.10.0.1:3301'}

-- Several URIs.
box.cfg{listen = {'10.10.0.1:3301', '10.10.0.2:3301'}}

-- Extended URI form, with options.
--
-- `transport` is the list of transport layers in the order of
-- preference. Omitted transports are forbidden.
--
-- For one transport one may pass a string (`tls`) instead of
-- a table with this string (`{'tls'}`).
--
-- Default: `{'tls', 'plain'}`.
box.cfg{listen = {uri = '10.10.0.1:3301', transport = {'plain', 'tls'}}

-- Examples:
--
-- Require TLS.
box.cfg{listen = {uri = '10.10.0.1:3301', transport = 'tls'}
-- Forbid TLS.
box.cfg{listen = {uri = '10.10.0.1:3301', transport = 'plain'}
-- Prefer TLS (should be default).
box.cfg{listen = {uri = '10.10.0.1:3301', transport = {'tls', 'plain'}}

-- Options encoded as part of URI.
--
-- It is convenient for administration.
box.cfg{listen = '10.10.0.1:3301?transport=tls,plain}
```

I'll list points that motivates me to propose this API, not some other.

1. Using a Lua table to list several URIs looks natural and would be consistent with `box.cfg{replication = <...>}`. It is easy to distinguish it from a map like `{uri = <...>, transport = <...>}`.
2. I dislike the `http://` vs `https://` story and I think that a client and a server should choose a protocol during handshake using a mechanism like [XEP-0115](https://xmpp.org/extensions/xep-0115.html) ('Entity Capabilities') (but simpler). AFAIK, ssh doing something like this for protocol versions and authorization methods and ssh 'just works' from the user perspective. That's nice.
3. Ability to pass connection options either separately from an URI or as part of the URI is usual for JDBC (Java) and [PEP-0249](https://www.python.org/dev/peps/pep-0249/) ('Python Database API Specification v2.0') drivers. The former is convenient for programmatic choice, the latter for using in a config file.
4. I think that we should prefer TLS by default and let user explicitly disable it if necessary. However it **requires** clear built-in metrics how much time is spent for TLS encoding and decoding (otherwise a user would not have enough information to choose). Those metrics should answer the question: 'How to latency and throughput will change on given workload if we'll disable TLS?'.

NB: Don't forget about #5602: we should support comma separated URIs for the TT_LISTEN environment variable. Don't forget about question mark, ampersand and comma escaping. Example:

```lua
box.cfg{
    listen = {
        '10.10.0.1:3301?transport=plain,tls',
        '10.10.0.2:3301?transport=plain,tls',
    }
}
```

has the same meaning as

```sh
TT_LISTEN=10.10.0.1:3301%3Ftransport=plain%2Ctls,10.10.0.2:3301%3Ftransport=plain%2Ctls
```

(if we'll use URL encoding here).

Known areas for improve and thoughts:

1. URL encoding of an URI is not very convenient to read (see the example above).  We can consider other variants, e.g.:

```lua
box.cfg{
    listen = {
        '10.10.0.1:3301[transport=plain,tls]',
        '10.10.0.2:3301[transport=plain,tls]',
    }
}
```

```sh
TT_LISTEN=10.10.0.1:3301[transport=plain,tls],10.10.0.2:3301[transport=plain,tls]
```

2. If we'll going forward to #3549 (bind an binary protocol port without box.cfg), we should NOT expose such API from net.box (it is the client). I guess we should do something like 'log' built-in module, but for iproto: `require('iproto').cfg{<...>}`.

**Comment by Gerold103** [comment]
Couldn't agree more with everything. Except that if it is going to be a separate module `iproto`, we need more thoughts on this.

Because if it is just `iproto`, not `box.iproto`, it assumes we might allow to hang your own handlers on the iproto requests. So as not always talk to the local storage. Like solutions did (but entirely in Lua in TX thread). This is related to storage queries, DML, SQL, authentication and authorization - if you allow to start it as a separate module, you need to do something with the storage-related requests.

Additionally, if it is going to support TLS, we need to design how to update netbox client so as it could talk to a TLS iproto port. At least in terms of netbox API changes.

Talking of the issue with pinning or not pinning the sockets - it is related. Although not to the API, but still important. The issue #5990 becomes more severe when some sockets use TLS, because they will use much more CPU than plain protocol sockets and it is easier to get the threads imbalanced. Especially bad it would be if we would start pinning the listening sockets.

**Comment by alyapunov** [comment]
The idea of this issue is to allow user to create several listen addresses regardless of how many network threads does he have. A user may open a dozen of ports with single thread or create a dozen of thread with a single address - why not. Pinning of listen socket to threads should be an additional option, see below.

I think we should make the API more convenient if possible. Somebody would like expression and unambiguity of tables, other - prefer short and backward-compatible strings. So I think we should support both table and string API. Considering all above I would suggest the following:
```lua
listen = '10.10.0.1:3301' -- one string address
listen = {'10.10.0.1:3301'} -- array with one string address
listen = {uri='10.10.0.1:3301'} -- one object
listen = {{uri='10.10.0.1:3301', transport='plain'}} -- array with one object
listen = {{uri='10.10.0.1:3301', transport='plain'}, {uri='10.10.0.1:3313', transport='tls'}} -- array with 2 objects
listen = {uri='10.10.0.1:3301', transport = {'tls', 'plain'}} -- one object with array in option
listen = {uri='10.10.0.1:3301', transport = 'tls, plain'} -- one object with comma-separated option values
listen = '10.10.0.1:3301,10.10.0.1:3313' -- comma delimits addressed if they passed on one string
listen = '10.10.0.1:3301?transport=plain, 10.10.0.1:3313?transport=tls' -- I like URI style
--listen = '10.10.0.1:3301?transport=plain,tls' -- that's seem to be out of URI standard. It fails because comma is delimit URIs
listen = '10.10.0.1:3301?transport=plain&transport=tls' -- common way to pass multiple values for one key
listen = '10.10.0.1:3301?transport=plain/tls' -- I'm not sure about this another non-standard way
listen = '10.10.0.1:3301?transport=plain+tls' -- I'm not sure about this another non-standard way too
listen = {'10.10.0.1:3301?transport=plain,tls'} -- But in one URI we could allow commas to delimit values
listen = {'10.10.0.1:3301?transport=plain;tls'} -- Semicolon should also delimit as comma
```
This approach does not need escaping when passed via environment:
```
TT_LISTEN="10.10.0.1:3301?transport=plain&transport=tls,10.10.0.1:3313?transport=plain&transport=tls"
```

It seems that `replication` option should use the same parser. Afaik it doesn't have any options, but when it have we'll be ready.

As for pining - common practice is to use masks. I'm sure it's obvious. It could be like that:
```lua
listen = {
  {uri='10.10.0.1:3301', transport = 'plain', thread_mask=0x01},
  {uri='10.10.0.1:3301', transport = 'tls', thread_mask=0xFE},
}
```

**Comment by EvgenyMekhanik** [comment]
There are two additional questions about this task:
1. In previous version, only string was valid to box.listen. Now table is valid also.
    So what user should see when he typing `box.cfg.listen` ?
    At the moment, I made it so that the user saw what he entered, converting to a string view, for example:
   1.1. box.cfg { listen = "127.0.0.1:8080, 127.0.0.1:8081" }
          box.cfg.listen
          ---
          - 127.0.0.1:8080, 127.0.0.1:8081
          ...
   2.2 box.cfg{ listen = { { uri = "127.0.0.1:8080", transport = "plain&tls" }, { uri = "127.0.0.1:8081, 127.0.0.1:8082" } }  }
         ---
         - - 127.0.0.1:8080?transport=plain&tls
           - 127.0.0.1:8081, 127.0.0.1:8082
         ...
        Also user can see only listen adresses using box.info.listen, for example in case (2.2) he see
        ---
        - 127.0.0.1:8080, 127.0.0.1:8081, 127.0.0.1:8082
        ...
2.  Another questions about replication. Should `box.cfg { replication }` behave the same way as box.cfg { listen } and accept as input a table with different options in the same format?
@Mons what do you think about it?

**Comment by Totktonada** [comment]
Side note:

> 127.0.0.1:8080?transport=plain&tls

From URL point of view we have two parameters here: 'transport' with value 'plain' and 'tls' without a value.

**Comment by unera** [comment]
If a user configures only one listen URL, `box.cfg.listen` have to be compatible with current `box.cfg.listen` format.
If he configures more than one URLs, we can change `box.cfg.listen` format.

So If user configures

`box.cfg{listen={'127.0.0.1:3301'}}`

He receives `box.cfg.listen = '127.0.0.1:3301'` - backward compatible.
