### ISSUE TITLE
Lua box messagepack encoding issues for floats

### ISSUE THREAD

**Issue by tsafin** [tarantool/tarantool#5933]
_This is described in https://github.com/tarantool/tarantool/discussions/5910 in more details_

```
tarantool> \set language sql
---
- true
...
tarantool> create table t1(a1 double primary key)
---
- row_count: 1
...
tarantool> insert into t1 values(423.0)
---
- row_count: 1
...
tarantool> insert into t1 values(423.13)
---
- row_count: 1
...

tarantool> \set language lua
---
- true
...
tarantool> box.space.T1:insert({424.13})
---
- [424.13]
...
tarantool> box.space.T1:insert({424.0})
---
- error: 'Tuple field 1 type does not match one required by operation:
expected double'
...
tarantool> ffi = require 'ffi'
---
...
tarantool> box.space.T1:insert({ffi.cast('double', 424.0)})
---
- [424]
...
```

Here is the problem, as it seems today:

-   We create a Lua table {424.0} with a single entry of number type;

-   Inside of box\_insert, the tuple we passed is being serialized to MessagePack array using a generic approach, and a normalized number 424 is serialized as MP\_UINT (unsigned positive int);

-   But, later on unsigned integer is not accepted according to the space schema, which is expecting double here. The only dirty work-around today, which would allow to save such normalized doubles, is to use ffi.cast(‘double’, value) which could enforce double value in table, but which is quite ugly and may be unexpected by customers.

## Proposal

We believe, that *space, which does have schema attached,* should not proceed with a *generic* MessagePack serialization routine using the *value-based approach*, but rather ought to use a type-based algorithm according to the space’s format. This format type would be a hint for selection of the MP\_\* type encoding schema necessary for the field.

**Comment by ImeevMA** [comment]
Not sure that this can be labeled as SQL issue.

**Comment by unera** [comment]
There are two (or several) way:

- repack tuple before insert
- fix format/index checkers in TREE index to avoid the error (NOTE: R-TREE index has already done the mechanism)

So, @alyapunov, Could You select a variant, or suggest the other?

**Comment by alyapunov** [comment]
I'm sure that we better fix comparators, it's the second variant.

**Comment by Totktonada** [comment]
Highlights:

* We met it in crud: https://github.com/tarantool/crud/issues/298. The situation is worse here[^1]: we can't suggest a user to use the `ffi.cast()` hack, because even if one will do it on the router, the number will be passed to crud's Lua function on the storage with loss information about the cast. IOW, no simple workaround. (Moreover, even if we would workaround it, the problem would persist for users, which want to call to crud's insert/replace/upsert/update functions from a language connector directly, without extra Lua wrappers; it is quite often case).
* Our users met the similar problem in vshard, but in context of string/varbinary: https://github.com/tarantool/vshard/issues/327.

[^1]: Comparing to a single instance application.
