### ISSUE TITLE
Memprof parser refactoring

### ISSUE THREAD

**Issue by Buristan** [tarantool/tarantool#5994]
Memory profiler's parser needs to be refactored with the following improvements:
* [ ] use config for global options like `--leak-only`, some other options (like `--human-readable` for KB/MB notation instead of "bytes" notation) requires knowledge about them not inside the main chunk (<memprof.lua>) , but inside other modules. 
* [ ] refactor `primary` field of `event` structure. This is the list of links heap chunks from the newest (last allocated) to the oldest (first allocated). It uses numeric indexes without strict declaration, for now. That should be fixed.
* [ ]  #9217

**Comment by igormunkin** [comment]
There are more inputs within [this thread](https://lists.tarantool.org/tarantool-patches/20210414143453.GA29703@tarantool.org/T/#md3343d85861b257e9ff2d725cf3cc35a7a92d885).

**Comment by Shishqa** [comment]
Also, there is a rather annoying problem associated with integration with Tarantool. 

When all the Lua modules are merged into one big binary by some template magic, they are identified by their filename and not the path: `<file-name>.lua ~ file_name_lua`
https://github.com/tarantool/tarantool/blob/4b2016ab3d35b505ea4712998458c2cd553b0271/src/lua/init.c#L84-L133

As we want to enrich the `laujit/tools/` folder with sysprof parser modules (containing `parse.lua` as well as memprof), we need to name them somehow in `init.c` file, but some names are already taken. 

E.g. there is a conflict between `memprof/parse.lua` and `sysprof/parse.lua` as we cannot name specific variables in `init.c` other than `parse_lua`.

A possible solution is folder structure refactoring: e.g. `memprof/parse.lua -> memprof-parse.lua`, but it can lead to the cluttering of the `tools/` folder. More gentle solution is Tarantool's ["merge-tool"](https://github.com/tarantool/tarantool/blob/master/src/lua/init.c) refactoring so that it can take folder structure into account.
