### ISSUE TITLE
ER_WAL_IO if wake up fiber on wal_write()

### ISSUE THREAD

**Issue by rtsisyk** [tarantool/tarantool#603]
Try to call fiber:wakeup() on fiber waiting for wal_write():

```
2014-10-22 16:02:10.226 [9297] main/166/receiverd_worker_45 txn.cc:218 E> ER_WAL_IO: F
ailed to write to disk
2014-10-22 16:02:10.226 [9297] main/166/receiverd_worker_45 txn.cc:218 E> ER_WAL_IO: F
ailed to write to disk
```

wal_write() must yield again if it was woken up explicitly by :wakeup() call.

**Comment by kostja** [comment]
The fiber should not permit wakeup if it's waiting for wal writer. fiber.wakeup() should return an error for fibers which do not permit it. There is a flag in the fiber to this purpose, fiber_cancellable, it should be checked by wakeup.

**Comment by rtsisyk** [comment]
Currently we don't allow to cancel non-Lua fibers:

```
static int
lbox_fiber_cancel(struct lua_State *L)
{
	struct fiber *f = lbox_checkfiber(L, 1);
	if (! (f->flags & FIBER_USER_MODE))
		luaL_error(L, "fiber.cancel(): subject fiber does "
			   "not permit cancel");
	fiber_cancel(f);
	return 0;
}
```

**Comment by kostja** [comment]
Another part of the fix is to renmae FIBER_CANCELLABLE to FIBER_RESUMABLE.
If a fiber is not resumable(), wakeup returns asn error.
FIBER_USER_MODE should be removed altogether, or set for almost all fibers except very critical ones. 

fiber.cancel() thus is this:

fiber->flags |= cancelled (always)
iif (fiiber_is_resumable(fiber))
  fiber_wakeup(fiber))

**Comment by kostja** [comment]
I fixed lbox_fiber_wakeup to not wakeup a fiber that is not cancellable.
I don't think we should bother any more with this.
