### ISSUE TITLE
luajson: Seems that global static shared buffer is used for json lua

### ISSUE THREAD

**Issue by filonenko-mikhail** [tarantool/tarantool#6050]
**Bug description**

**Steps to reproduce**
```lua
ffi = require('ffi')
log = require('log')
json = require('json') 
b = nil
function gc()
    b = json.encode({a=1, b=2})
end

for i=1,1e6 do
    ffi.gc(ffi.new('char*'), gc)
end

for i=1,1e6 do
    r = json.encode({q=3,t=5})
    assert(r == [[{"q":3,"t":5}]], r)
end
```

**Comment by Gerold103** [comment]
NB: I found 2 more places where static buf is used in Lua, but these are about UUID and decimal types. In the json code it is worse - instead of the static buf there is a global variable keeping a singleton malloced buffer (`strbuf_t encode_buf;`). The hard part is that this is a third_party module, and its too extensive change must be avoided if possible. The best option so far is to use `cord_buf *ibuf` inside of `strbuf_t`. It would be quite intrusive, but only in the buffer part, not in the logic of how to encode/decode JSON.
