### ISSUE TITLE
box.cfg memtx_memory failed to preallocate even if server has enough memory available

### ISSUE THREAD

**Issue by RunsFor** [tarantool/tarantool#6087]
This issue describes two points:

- box.cfg {memtx_memory = ...} during bootsrap may fail even if a server has enough available memory
- runtime memtx_memory update does not actually allocate memory

**Description**

I have a server with about 100GB memory available according to `free -h`. When I'm bootstrapping an instance with 60GB, it fails to allocate chunk of memory with `failed to preallocate`.

However, I can bootstrap with `memtx_memory = 40GB` and then change the option in runtime once again up to 60GB. It will work just fine.

It turned out, that **no memory allocation actually happen during runtime configuration**:

https://github.com/tarantool/small/blob/279fa38ac89be526dcef0a9dd88cf4775367f5c5/small/quota.h#L106-L123

This kind of behaviour inconsistency may be ok locally but is inconvenient in production with many instances deployed.

1. I would like to be able to start an instance on machine which has enough available memory
2. I would like to be sure, if I succeeded to change memtx_memory in runtime, than I can use memory up to that limit

OS: Linux / RHEL
Tarantool: 2.3.1 Enterprise

**Comment by RunsFor** [comment]
Here is some configuration on affected customer's server. Hope this adds more context to the issue. OS prohibits overcommiting memory:

```bash
[user@hostname ~]$ free -hw
              total        used        free      shared     buffers       cache   available
Mem:           754G        344G        315G        942M         13M         94G        405G
Swap:          4,0G          0B        4,0G
[user@hostname ~]$ cat /proc/sys/vm/overcommit_memory
2
[user@hostname ~]$ cat /proc/sys/vm/overcommit_ratio
100
```

**Comment by locker** [comment]
Apart from the memtx arena, Tarantool allocates memory for other needs (internal objects, network buffers, etc). This memory isn't limited (at least, not directly) and can amount to a substantial share of all memory used by the Tarantool process. So even if we did preallocate memory when `box.cfg.memtx_memory` is increased, as suggested in the issue description, this wouldn't guarantee that Tarantool would function normally afterwards - it could easily panic somewhere on a failed attempt to malloc a system object or throw an unexpected ENOMEM error in Lua code. What is worse, other applications could easily start to panic, because the VM limit is global.

Preallocating memtx arena when the limit is increased is complicated. Since it wouldn't solve the problem, we're not going to do that.

The proper way to avoid situations like this is to enable VM overcommit, because modern apps tend to allocate more virtual memory than they actually use.
