### ISSUE TITLE
Updates mechanism refactoring and optimization

### ISSUE THREAD

**Issue by iskander232** [tarantool/tarantool#6117]
There are some problems with existing updates mechanism:

1. There are some cases when update is slow. For instance if we have array `[1, 2, ... 1e6]`, than update `{1, {'+', 1e6 - 100, 1}, {{'+', 1e6 - 99, 1}, ..., {'+', 1e6, 1}}}` is several times faster than update `{1, {'+', 1e6, 1}, {{'+', 1e6 - 1, 1}, ..., {'+', 1e6 - 100, 1}}}` but they do the same thing.

2. It is hard to use information about `format` inside update operation due to now it is used only for map field_no <-> field_name.

3. It contains ~ 3000 lines of code, that is difficult to understand.

**Comment by Gerold103** [comment]
1. Can you provide a real usecase for having a million columns? And how it related to refactoring? It looks like an optimization, which I don't see why is needed so far.
2. I don't see here the event <-> consequence link here. It is used, yes. What prevents you from using it more? And the more important question - why do you need to use it more that it is used now?
3. Number of lines is actually quite small for such a huge feature as JSON updates. Secondly, number of lines has nothing to do with complexity. I am afraid you need more constructive points to initiate a rewrite. You can't go and recreate subsystems from the scratch just because you failed to understand them immediately.

**Comment by iskander232** [comment]
1. The problem is that if you want to update field at the end of array you need to iterate over previous fields and if there are update of several fields at the end of array and these updates are in bad order, then it will be more than one iteration through previous fields. 
I illustrated this problem with big array(yes, it is bad example). Maybe, better example is array of big nested maps. The main point is that iterating over the previous fields should be quite long. Of course, a measurement is required to verify this.
This problem can be solved by reorder updates before starting the applying.
2. If array contains NULLable fields, than it will be good to have information about them from `format`.
3. I believe, that applying of reordered updates is simpler than applying unordered updates and we can simplify code.

**Comment by Gerold103** [comment]
1. Yeah, ok, now I see the point about a not big array of deep maps/arrays. Still looks like an optimization. And not necessarily must be done via the reordering.
2. Why do you need it? It works just fine now with nullables, they even get autofilled. It is done already. And to extend it to build maps/arrays into depth it is not necessary to know the format either. What is exactly the feature you are trying to implement here or a bug to fix?
3. Well, good luck with that. Most of the code is not here because of the update order, but because it tries to reduce number of allocations, split update field types into independent files to work with each one easier, and reduce number of msgpack decodings where possible. Moreover, some updates you simply can not reorder. For instance, field insertions and deletions, but still the code must support them. And finally, reordering is going to be a tough one even if you do not care about `!` and `#`. Because of the json paths. You basically have multiple dimensions to reorder. Might worth trying to produce more ideas before going straight to implement the reordering.

**Comment by iskander232** [comment]
1. Ok, it is optimization, not refactoring.
2. I think, the next update operation must cause an error, but it only adds nulls 
```
box.cfg{}
s = box.schema.create_space('test', 
    {
        format = {
            {'id', 'unsigned'},
            {'f1', 'unsigned', is_nullable = true}
        }
    }
)
s:create_index('pk')
s:insert{1}
s:update(1, {{'=', 5, 5}}) -- [1, null, null, null, 5]
```
Also it will help in implementing of #5991 
3.  My idea how it can be implemented:
    * Sort all updates.
    * `!` and `#` change field_nums, so add field `offset` to each update operation and estimate it after previous step. It can be implemented via modification of `Segment tree`, that support additions on segments(each `!` or `#` update changes offsets of previous updates in terms of initial order by the same number) in O(`updates_num` * log(`updates_num`)) time.  
    * I don't know good solution for working with json paths. I think, we need `offset` for each dimension and separate estimation of `offset`s  in each json path with more than 1 update.

> it tries to reduce number of allocations
If updates in right order it is possible to estimate memory for new tuple and create it there.
>  split update field types into independent files to work with each one easier, and reduce number of msgpack decodings where possible
I think it should stay as it is.

Yes, it seems to be more of an optimization rather than a refactoring.

**Comment by olegrok** [comment]
> I think, the next update operation must cause an error, but it only adds nulls

Why? It's perfectly valid. At least because we can insert such tuple.

```lua
box.cfg{}
s = box.schema.create_space('test', 
    {
        format = {
            {'id', 'unsigned'},
            {'f1', 'unsigned', is_nullable = true}
        }
    }
)
s:create_index('pk')
tarantool> s:insert{1, box.NULL, box.NULL, box.NULL, 5}
---
- [1, null, null, null, 5]
...
``

**Comment by iskander232** [comment]
> Why? It's perfectly valid. At least because we can insert such tuple.

My fault. Documentation says, that it is ok, but, for me, it is strange behavior.

**Comment by Gerold103** [comment]
> It will help in implementing of #5991

Hm. But still, why do you need the format for that? How is it different from the flat format when it comes to updates? Let the xrow update work like now (with your possible reorder optimization). If the result will violate the format, the result validation simply won't pass. Anyway you will create a tuple on what was created in the result of update using `box_tuple_new()` or something (it is done everywhere in the end), and it will check the format is correct.

As you can see, now xrow update does not validate anything from the format. Because its check happens later + other checks like validation of SQL `CHECK` objects on the newly created tuple. In xrow update code you can optimistically assume that everything is allowed.

**Comment by iskander232** [comment]
>  But still, why do you need the format for that?

Yeah, you are right. I couldn't come up with an example where information of format is needed inside of updates processing, optimistic update and checking correction of format at the end of update is fine.
