### ISSUE TITLE
Add NUMBER as a type

### ISSUE THREAD

**Issue by ImeevMA** [tarantool/tarantool#6221]
NUMBER is currently a meta-type. This means that we can create a space with a field type of NUMBER, but there are no values ​​of type NUMBER (although `SELECT TYPEOF (CAST (1 AS NUMBER));` returns "number"). We have now decided to add NUMBER as a type in SQL so that values ​​of that type will appear.

Rules for this type:
1) Any two values ​​of this type can be compared and the result is always determined.
2) Values ​​of types UNSIGNED, INTEGER, DOUBLE and DECIMAL can be implicitly cast to NUMBER.
3) NUMBER can be implicitly cast to SCALAR and ANY.
4) NUMBER cannot be implicitly cast to any type other than SCALAR and ANY.

As you can see, arithmetic/bitwise operations are not defined for values of type NUMBER. This may be changed in the future.

**Comment by ImeevMA** [comment]
About explicit cast: value of type NUMBER can be explicitly cast to INTEGER, UNSIGNED, DOUBLE, DECIMAL (when this type appear in SQL), SCALAR, and STRING.

**Comment by pgulutzan** [comment]
Tarantool/SQL already has a NUMBER data type
https://www.tarantool.io/en/doc/latest/reference/reference_sql/sql_user_guide/#operand-data-types
and the manual says "Since version 2.4.1, the NUMBER type is processed in the same way as the number type in NoSQL Tarantool."
So I interpret this as a proposal to change the existing behaviour.

If I have understood correctly what you say about implicit casting, then
for number_value comparison-operator decimal_value
the number_value will be converted to decimal_value, never the other way around.
And for number_value arithmetic-operator decimal_value the result will be DECIMAL,
never NUMBER. This means there will be errors for values that are within the
NUMBER range but not within the DECIMAL range. And there will be errors for
assignments like SET decimal_column = number_value.
For example:
(where number_column contains 1e20)
SELECT number_column + 1 FROM t; which is legal today will be illegal tomorrow
SELECT number_column > 1 FROM t; which is legal today will be illegal tomorrow
(where number_column contains 1e1)
UPDATE t SET integer_column = number_column; which is legal today will be illegal tomorrow
SELECT TYPEOF(LEAST(2,number_column)) FROM t; which is 'number' today will be 'integer' tomorrow

And, since "bitwise" operations which are currently defined will become undefined
SELECT number_column << 1 FROM t; which is legal today will be illegal tomorrow

And, since you say that explicit cast is possible for some data types but don't mention BOOLEAN,
CAST(number_column AS BOOLEAN) which is legal today will be illegal tomorrow

I think that when you say "always determined" it might be better to say "deterministic".

**Comment by ImeevMA** [comment]
@pgulutzan I believe you misunderstood.

What we have now:
INTEGER is a type, we have values of this type and fields of this type. An arithmetic operation on values of this type will give us a value of that type.
DOUBLE is a type, we have values of this type and fields of this type. An arithmetic operation on values of this type will give us a value of that type (except `%`, which implicitly converts to INTEGER).
DECIMAL is a type (coming to SQL in the next couple of weeks), we have values of this type and fields of this type. An arithmetic operation on values of this type will give us a value of that type (except `%`, which implicitly converts to INTEGER).
UNSIGNED is a type, we have values of this type and fields of this type. This type is actually part of INTEGER type. An arithmetic operation on values of this type will give us a value of INTEGER type.
NUMBER is a meta-type, we have fields of this meta-type but do not have values of this type.

`CAST(<something> AS NUMBER)` give us INTEGER or DOUBLE.
Select from NUMBER field give us INTEGER, DOUBLE or DECIMAL.

What I suggest:
INTEGER, DOUBLE, DECIMAL and UNSIGNED remains the same.
NUMBER will be type, so we will have values of this type and fields of this type. 

CAST (<something> AS NUMBER) gives us a value of type NUMBER. Ditto for select from the NUMBER field.
When we compare a NUMBER value with an INTEGER, DOUBLE, DECIMAL, or UNSIGNED value, the not-NUMBER value will be implicitly cast to the NUMBER type. Same for INSERT/UPDATE: INTEGER, DOUBLE, DECIMAL or UNSIGNED will be implicitly cast to NUMBER.

No arithmetic operations will be defined for type NUMBER, so CAST (1 AS NUMBER) + 1 raises an error.

Implicit casting will only work from INTEGER, DOUBLE, DECIMAL, and UNSIGNED to NUMBER, but not vice versa. I mean, inserting an INTEGER, DOUBLE, DECIMAL or UNSIGNED value into the NUMBER field will work, but inserting `CAST (1 AS NUMBER)` into the INTEGER field will throw an error.

I believe there will only be two ways to get NUMBER values: select from the NUMBER field and use the CAST operator.

The part about arithmetic and implicit cast from NUMBER may change in the future. For now, we do this so that we can statically define any value type.

**Comment by ImeevMA** [comment]
As for BOOLEAN:
1) BOOLEAN can be explicitly cast to STRING;
2) STRING can be explicitly cast to BOOLEAN, if UPPER(<string value>) == "TRUE" or "FALSE".
3) There will be no implicit cast for BOOLEAN values.

**Comment by pgulutzan** [comment]
I believe that I have not misunderstood and so this proposal will have bad consequences. We will know for sure when you try to implement it.
