### ISSUE TITLE
Add iproto request to query server features

### ISSUE THREAD

**Issue by locker** [tarantool/tarantool#6253]
Currently, the only way for a client (connector or other Tarantool instance) to check if the server supports a certain feature is to analyze the version string sent by the server in a greeting message, such as

`Tarantool 2.9.0 (Binary) bb381d4c-e6cb-4633-8422-98f52433011b`

This approach complicates client code and looks fragile. Besides, it doesn't allow us to change the version format reported in a greeting message (#6183) without taking a risk of breaking older clients.

The suggested solution is to add a new iproto request that would allow a client to query the feature set available on the server.

**Comment by Totktonada** [comment]
I'm agree that feature testing is much more convenient than analyzing a version string.

Which existing features we plan to add here? Everything that exists in 2.* and does not exist in 1.10? Or we'll consider some 2.X as the baseline?

**Comment by kyukhin** [comment]
How should we report the version according to the new release policy proposed? Or are we about to not manifest the version of the new format via iproto?

**Comment by locker** [comment]
> How should we report the version according to the new release policy proposed? Or are we about to not manifest the version of the new format via iproto?

We could add the version to the feature set returned via iproto.

**Comment by pgulutzan** [comment]
I do not understand why this requires a new IPROTO constant but I hope this is the appropriate place for a feature request:
a _vfeature system view with
name          string, unique name of feature
introduced    string, canonical identifier
deprecated    boolean, true if deprecated
description   string, can be blank

Feature.name is an important thing in Oracle because
DBA_FEATURE_USAGE_STATISTICS https://docs.oracle.com/en/database/oracle/oracle-database/21/refrn/DBA_FEATURE_USAGE_STATISTICS.html#GUID-B8A38B9B-3AAA-4341-AA05-4309870CE73B
and although we have no plan to use it like that, a client could.

Feature.introduced will have whatever format is decided elsewhere -- and if it changes that's okay, provided there's a function that translates queries with the old format so that they find rows with the new format.. The important thing is that
people can get a list of all the features that appeared, and can search with GT not just EQ.

Feature.deprecated is necessary to that people don't just see that it's in the list and conclude that it's supported fully. Perhaps boolean is not enough -- SQL Server has a "Deprecated features" object
https://docs.microsoft.com/en-us/sql/relational-databases/performance-monitor/sql-server-deprecated-features-object?view=sql-server-ver15&redirectedfrom=MSDN&viewFallbackFrom=sql-server-2014
with various levels.

Feature.description is unimportant.

I don't think something like box.info() would be as good because the contents are static, and because I can use SQL to get at system views.

**Comment by locker** [comment]
> I do not understand why this requires a new IPROTO constant but I hope this is the appropriate place for a feature request:
a _vfeature system view

I like the idea of having a system view containing the set of supported features - it looks more flexible indeed and doesn't require extending the network protocol.

**Comment by locker** [comment]
Related feature: IPROTO_SESSION (#6191). The goal of IPROTO_SESSION is to let the server know about features/attributes supported by the client (e.g. whether it supports graceful shutdown). We could return features supported by the server in the response to that command.
