### ISSUE TITLE
build: disable backtraces on Mac/M1

### ISSUE THREAD

**Issue by Korablev77** [tarantool/tarantool#6272]
Originally backtraces are turned on on Mac M1. However, they are now working properly: it can be seen from failing `app/fiber.test.lua`. For some reason libunwind returns wrong stack call for some fibers (call to `unw_step()` produces only bottom frame). Investigation is quite complicated since OSX uses its own (system) libunwind. Backtraces are known to be optional feature and tests are designed to work without it. So as a temporary workaround (not sure if this feature is worth wasting days for it) let's disable them until https://github.com/tarantool/tarantool/issues/6060 is resolved (probably there's could be a bug in Mac's libunwind, so the issue will turn out to be resolved on casual library update).

**Comment by Egor2001** [comment]
AFAICS, `fiber.top` is disabled on Arm too, but the corresponding test in a `fiber.test.lua` doesn't regard the possibility of build without `fiber.top`. Because this problem is also fiber-related functionality which must be temporarily disabled on Arm, it was fixed in the second patch c8a97e0 from the same patchset #6303.
