### ISSUE TITLE
Explore and try to implement auto-completion for streams such as it implemented for connections.

### ISSUE THREAD

**Issue by EvgenyMekhanik** [tarantool/tarantool#6305]
Explore and try to implement auto-completion for streams such as it implemented for connections.
Streams use lazy space copy from connections, so auto-completion does not work for them. Explore the possibility of implementation auto-completion for streams.

**Comment by sergos** [comment]
@locker please have a look - I kept the original iterator over all candidates as is, providing a new table from the __autocomplete as you proposed. The `net.box.future` is even simpler - just return it's metatable itself.

**Comment by locker** [comment]
> @locker please have a look - I kept the original iterator over all candidates as is, providing a new table from the __autocomplete as you proposed. The `net.box.future` is even simpler - just return it's metatable itself.

From a quick glance looks good. A couple of notes:

- Better add the `__autocomplete` callback in a separate commit, because it's useful on its own, without net.box.
- The new callback needs to be documented, since it can be used by users for their own object types.
- We need a test. I think we could call `internal.completion_handler` from tests to check that completion works as expected.

Once this is done, please open a pull request.

**Comment by sergos** [comment]
The `__autocomplete` is a substitution for the `__index` for the sake of tab completion. I don't see reasoning to separate it from the use of it in the tab completion process.
The documentation is internal, since it is not user-visible. I'm ready to explain in details - more than in commit message - although we have to agree on the place.
