### ISSUE TITLE
Literals for DECIMAL

### ISSUE THREAD

**Issue by ImeevMA** [tarantool/tarantool#6356]
There are currently no literals for DECIMAL in SQL. We have to decide which literals should be classified as DECIMAL and implement that decision.

**Comment by pgulutzan** [comment]
This has been discussed in issue #5910 and issue #6334.
I favour treating 1.5 as DECIMAL but said I worried there will be
objections because now it is a change in documented behaviour.
tsafin proposed doing it anyway.
Most recently ImeevMA said
"That is quite problematic in current parser design, since we have to determine of value is INTEGER or DECIMAL. Since we not always can see sign of the value, we have some problems due to the fact that INTEGER is not symmetrical.
This surprises me. If the decision is that an INTEGER literal does not contain a
decimal point (i.e. "."), and a DECIMAL literal does contain a decimal
point but does not contain an exponent (i.e. "E"),  I had expected that
detecting a DECIMAL literal would not be the main problem.

Anyway, until this is resolved, I see only two ways to
put in DECIMAL literals currently, and it will be necessary
to say so in the manual.
1: Example: CAST(1000 AS DECIMAL)
Simple, but this won't work for very large integers or for numbers with many post-decimal digits.
2: Example: LUA('return require("decimal").new("12345678901234567890")')
Not simple, but this will work with any numbers.

**Comment by ImeevMA** [comment]
Detecting literals with decimal point is not a problem. The problem is with literals like `100000000000000000000000000000`
Or do you think that we shouldn't see them as DECIMALs? In this case there is no point to expect that hex literals like `0xFFFFFFFFFFFFFFFFFFFFFFFFFFFF` can be treated as DECIMAL.

About putting DECIMAL into space: in case you have INTEGER, DOUBLE, you can just use implicit cast:
```
tarantool> box.execute([[CREATE TABLE t(d DEC PRIMARY KEY);]])
---
- row_count: 1
...

tarantool> box.execute([[INSERT INTO t VALUES(1), (1.5), (1e10);]])
---
- row_count: 3
...

tarantool> box.execute([[SELECT * FROM t;]])
---
- metadata:
  - name: D
    type: decimal
  rows:
  - [1]
  - [1.5]
  - [10000000000]
...
```

In case of big DECIMALs cast from STRING should work:
```
tarantool> box.execute([[INSERT INTO t VALUES(CAST('999999999999999.999999999999999' AS DECIMAL));]])
---
- row_count: 1
...

tarantool> box.execute([[SELECT * FROM t WHERE d > 999999999999999;]])
---
- metadata:
  - name: D
    type: decimal
  rows:
  - [999999999999999.999999999999999]
...
```

**Comment by pgulutzan** [comment]
Indeed integers outside the range range -9223372036854775808 to +18446744073709551615 could be considered as decimal.
I don't believe that we should recommend that users depend on implicit casts
from non-exact numbers. For the example 1.5 they're okay, but we know they're
not okay when there are many digits, for example
CAST(12345.678901234567890 AS DECIMAL) = CAST('12345.678901234567890' as DECIMAL)
is false, because only the conversion from string is reliable.
But, as I said, conversion from string "needs more testing". Am I worrying too much?

**Comment by ImeevMA** [comment]
Implicit cast from integer to decimal is always precise, however you are right, this may be not true for implicit cast from double to decimal.

About string to decimal: in case we have less than 38 digits in string, we have nothing to worry about. If there are more than 38 digits at the left from the decimal point, then we will get an error. If we have 38 or less digits at the left of the decimal point, but the total number of digits is more than 38, then the number will be rounded. The rules are the same as in the 'decimal' module in Lua.

**Comment by pgulutzan** [comment]
So it's confirmed: I worry too much. Thanks for explaining.

**Comment by pgulutzan** [comment]
@ImeevMA: just one small thing: you mentioned that there is an uncommon case where "the number will be rounded". For example
tarantool> box.execute([[SELECT CAST('.00000000000000000000000000000000000005' AS DECIMAL) / CAST(2 AS DECIMAL);]])
---
- metadata:
  - name: COLUMN_1
    type: decimal
  rows:
  - [0.00000000000000000000000000000000000003]
...
This is neither a bug nor a behaviour change, but it is different from what we do with integers: 5/2 is 2, and that is https://www.tarantool.io/en/doc/latest/reference/reference_sql/sql_user_guide/#operators documented. Does anybody care if it's not consistent?

**Comment by ImeevMA** [comment]
I agree that this looks inconsistent, since it works the same way with integer DECIMALs:
```
tarantool> n = '33333333333333333333333333333333333333'
---
...

tarantool> box.execute([[SELECT CAST(? AS DECIMAL) / CAST(2 AS DECIMAL);]], {n})
---
- metadata:
  - name: COLUMN_1
    type: decimal
  rows:
  - [16666666666666666666666666666666666667]
...
```

However, this is how our DECIMAL works:
```
tarantool> require('decimal').new(n) / 2
---
- 16666666666666666666666666666666666667
...
```

I believe we should describe this behavior in the SQL manual, or at least say that it works the same way as our DECIMAL does.

**Comment by ImeevMA** [comment]
This issue is mostly closed. The only remaining problem is deciding whether we need to change the result of the `CAST (<double value> AS STRING)` and DOUBLE in the error messages. @pgulutzan @igormunkin what do you think?

**Comment by pgulutzan** [comment]
@ImeevMA: I'm sorry, I'm not understanding well. Can you give an example?

**Comment by ImeevMA** [comment]
For example ```SELECT CAST(5e0 AS STRING);``` returns `5.0`, though `5.0` is literal for DECIMAL.

**Comment by pgulutzan** [comment]
According to SQL:2016 6.13 "cast specification" General Rule 12)b)i) which applies for casting approximate-numeric to variable-length character string, the result should be '5.0E0' or '5.0e0'. That doesn't answer your question whether we "need" to change, but to me it means: please change if you decide it's not too much work.

**Comment by ImeevMA** [comment]
@unera is very opposed to this idea, so I decided to remove this question from this issue. I created issue #6652 to move dicussion there. I close this issue.
