### ISSUE TITLE
fiber: joinable fibers that aren't joined leak

### ISSUE THREAD

**Issue by olegrok** [tarantool/tarantool#6455]
```lua
./src/tarantool -lfiber                
Tarantool 1.10.11-6-g77e01180a
type 'help' for interactive help
tarantool> collectgarbage('count')
---
- 1188.365234375
...

tarantool> for i = 1, 1e5 do f = fiber.new(function() end) f.storage['a'] = 'a' f:set_joinable(true) end
---
...

tarantool> collectgarbage()
---
- 0
...

tarantool> collectgarbage()
---
- 0
...

tarantool> collectgarbage('count')
---
- 50164.112304688
...

tarantool> for i = 1, 1e5 do f = fiber.new(function() end) f.storage['a'] = 'a' f:set_joinable(true) end
---
...

tarantool> collectgarbage()
---
- 0
...

tarantool> collectgarbage()
---
- 0
...

tarantool> collectgarbage('count')
---
- 99329.862304688
...
```

Looks like a leak. It should be fixed or at least documented.

**Comment by mkostoevr** [comment]
The issue is reproduced without using the fiber-local storage.

The fiber API allows a user to retrieve the return value of the joined fiber. That means if a fiber is joinable, Tarantool can't free its stack until someone has joined it and fetched the return value from the stack. This prevents the system from freeing the some of data allocated for the joinable fiber.

The fiber-local storage is freed on the fiber death though, so there's no issue with it.

Transfered the issue into the tarantool/doc#3790.
