### ISSUE TITLE
Implement master fencing

### ISSUE THREAD

**Issue by sergepetrenko** [tarantool/tarantool#6661]
A leader doesn't track its connectivity to the rest of the cluster.
Once it is elected, it stays in leader position until receives a newer term from some remote node.
In case the leader is partitioned from the rest of the cluster, it'll remain being a leader as long as the cluster is split up. Even if the rest of the cluster have already elected a new leader.

Let's make the leader track follower connections, and step off to being a follower as soon as it loses a quorum of connections.

Additionally the former leader shouldn't CONFIRM/ROLLBACK any of the synchronous transactions which were in flight at the moment of step down. Otherwise we might end up in a situation when the leader which lost connectivity rolls back a transaction which is already confirmed by a new leader.

Looks like the leader has to perform the following actions in order to step down once connectivity is lost:
1. Enter follower state (without bumping the term), become ro
2. Stop any operations on the synchro queue. Don't CONFIRM/ROLLBACK anything that's in flight. Stop waiting for acks on synchronous transactions.

**Comment by R-omk** [comment]
The terminology of "fencing" is not suitable if you are going to make a node just a follower. "Fencing"  is about isolation, that is, even if the node temporarily lost connection, then when the connectivity is restored, it should not affect the general state in any way, which in the case of a "follower" is not true, since the node will transmit data that has accumulated during the absence of a connection.
This terminology might be appropriate if the node were to do a full rejoin to the cluster.

**Comment by t1-10** [comment]
@R-omk what would you suggest to call it instead?

**Comment by R-omk** [comment]
@t1-10 

`Auto revoke leadership on quorum loss`

Timeout should be taken into account so that at one point in time there can never be more than one leader.
That is, leadership _autorevoke_ should always happen before followers start choosing a new one.

**Comment by sergepetrenko** [comment]
> Additionally the former leader shouldn't CONFIRM/ROLLBACK any of the synchronous transactions which were in flight at the moment of step down. Otherwise we might end up in a situation when the leader which lost connectivity rolls back a transaction which is already confirmed by a new leader.

This means that once fencing is implemented, ROLLBACK becomes obsolete. An active leader should never write ROLLBACK. Because ROLLBACK is basically a sign of lost connectivity. Now instead of writing ROLLBACK the leader should simply step down. And ROLLBACK (as part of PROMOTE or DEMOTE) may only be issued during a master change.

**Comment by sergos** [comment]
> leadership _autorevoke_ should always happen before followers start

Unfortunately, there can be manual intervention so this one can't be held. Consider you have a datacenter DC1 disconnected with the majority of the cluster in it. You decide to lower the quorum and promote a leader by hands in DC2 to keep the service availability. Then if at some point the DC1 is back we have to decide which of two operable clusters is real.

First, we will have divergence in the promotion history - the DC2 has its own starting from hand made promotion. If we track the history we can figure out this divergence during the DC1 is back and trying to join. We can simply assume the hand made change as supreme and forcing DC1 leader to step down, but the logic can be more sophisticated. 

Second, we have to block replication from the 'non-real' DC. The reason is the data possibly accepted by a 'non-real' may conflict - or even worse, they may not. As per Sergey's comment above it should be done by DC2 with issuing of PROMOTE with DC1's leader LSN at the point of hand made promotion. This should protect DC2 from accepting any data from DC1, although for DC1 there's no other opportunity but rebootstrap apparently, since the data can be CONFIRMed with DC1 majority and can't be rolled back.

**Comment by R-omk** [comment]
>You decide to lower the quorum and promote a leader by hands in DC2 to keep the service availability.

Look like it is about "cluster recover" flow. I believe that in this case it should be a separate cluster, which itself ensures its integrity and does not allow outsiders.
