### ISSUE TITLE
Trigger definer should return a number

### ISSUE THREAD

**Issue by pgulutzan** [tarantool/tarantool#669]
Suppose I say `box.session.on_connect(X)` i would be interested in knowing whether I or somebody else has already made a trigger. If the return value was a number = number of triggers, rather than null, then this would be clear. I am aware that issue #655 "List all triggers" would give more detail, but it would be less current.

Also, If I say `box.session.on_connect(X,Y)` I do not get an error return if there is no trigger for Y. So it might help me to be told "now there are more triggers than you expected", because that would hint that I made an error.

**Comment by kostja** [comment]
In the end we return a Lua table with all triggers.

**Comment by pgulutzan** [comment]
I do not understand the comment on this issue =
"In the end we return a Lua table with all triggers."
As user admin I did these requests:
box.schema.create_space('t')
box.space.t:create_index('primary',{})
function f1 () x = x + 1 end
function f2 () x = x + 1 end
box.space.t:on_replace(f1)
box.space.t:on_replace(f2)
x = 0
box.space.t:insert{0}
x
The second on_replace request returns this:
"
tarantool> box.space.t:on_replace(f2)
---
- 'function: 0x40f701f8'
...
"
... That is not a Lua table with all triggers.
(The later display of x shows that two triggers exist.)
It is probably acceptable to say "we decided not to
return either a number or a Lua table with all triggers",
and close this issue again.

**Comment by Sulverus** [comment]
on_replace() without arguments returns lua table, for example:
```
tarantool> f = function() print('hello') end
---
...
tarantool> f2 = function() print('world') end
---
...
tarantool> box.space.test:on_replace(f)
---
- 'function: 0x402c6e40'
...
tarantool> box.space.test:on_replace(f2)
---
- 'function: 0x402c7e58'
...
tarantool> box.space.test:on_replace()
---
- - 'function: 0x402c6e40'
  - 'function: 0x402c7e58'
...
```

**Comment by kostja** [comment]
When you define a trigger, you get back an object which can be used to later on clear or reset this trigger. In theory the type of that object should not interest you, but it happens to be a Lua function which you passed in. In Lua a function is a first-class object. So, yes, instead of a numeric identifier, we return a handle - Lua function. Invoking the trigger-definition function (on_* function) with no arguments lists all triggers, i.e. returns handles of all trigger objects. We had a discussion internally when approaching the implementation, and decided to do it this way. Please document this, or, if you feel it's a bad solution, share what problems you see with it.
