### ISSUE TITLE
Assertion in before_replace trigger

### ISSUE THREAD

**Issue by EvgenyMekhanik** [tarantool/tarantool#6780]
#! /home/evgeny/TARANTOOL/MASTER/tarantool/src/tarantool

os.execute("rm -rf *.xlog *.snap")

box.cfg{}

box.schema.space.create('memtx_space', {engine = 'memtx'})
box.space.memtx_space:create_index('primary', {
    parts = {2, 'unsigned'}
})
box.space.memtx_space:format({
    {name = 'x', type = 'string'},
    {name = 'y', type = 'unsigned'},
    {name = 'z', type = 'unsigned'}
})
box.space.memtx_space:before_replace(function(old, new) end)
box.space.memtx_space:insert({2})

/home/evgeny/TARANTOOL/MASTER/tarantool/src/box/tuple_extract_key.cc:355: char* tuple_extract_key_slowpath_raw(const char*, const char*, key_def*, int, uint32_t*) [with bool has_optional_parts = false; bool has_json_paths = false; uint32_t = unsigned int]: Assertion `key_buf - key <= data_end - data' failed.

box.space.memtx_space:insert({})
char* tuple_extract_key_slowpath_raw(const char*, const char*, key_def*, int, uint32_t*) [with bool has_optional_parts = false; bool has_json_paths = false; uint32_t = unsigned int]: Assertion `field_count > 0' failed.

**Comment by drewdzzz** [comment]
Since `before_replace` trigger needs an old tuple (tuple from a space with the same pk value), it extracts primary key from a new tuple. The problem is the presence of pk in the tuple is not checked, that is why assertion fails. So we need to check the new tuple. We have 3 options:
1. The new tuple must correspond to the space format before it was changed by `before_replace` trigger (there will be backwards compatibility problems, at least the update from old version [takes advantage of this feature](https://github.com/tarantool/tarantool/blob/005fbb6bb6fffafc7f077e704039c3c9b25786e3/src/box/lua/upgrade.lua#L185));
2. The new tuple must correspond to the primary index only before it was changed by `before_replace` trigger;
3. If fields indexed by the primary index are incorrect, `before_replace` trigger will receive nil as an old tuple argument.

**Comment by unera** [comment]
1. The new tuple must correspond to space format (must be checked) before the first trigger is called
2. The new tuple must correspond to space format (must be checked) before after each trigger is called

So we should call check function for
- original tuple
- tuple from each trigger-call
