### ISSUE TITLE
Decimal (fixed point) type

### ISSUE THREAD

**Issue by 17e** [tarantool/tarantool#692]
Please add decimal data type (fixed point) in Tarantool. For instance, It's useful in finance operation.

See also https://github.com/tarantool/tarantool/issues/1273 "BSON data types" and gh-465 "user defined types"

Links:

http://www.bytereef.org/mpdecimal/
http://speleotrove.com/decimal/
http://download.icu-project.org/files/decNumber/

**Comment by rtsisyk** [comment]
I also vote for this feature.
@17e I have an experimental code for that:

```
local function tomoney(str)
    local sep = str:find(".", 1, true)
    local kopecks = 0
    if sep then
        kopecks = str:sub(sep + 1)
        local roubles = str:sub(1, sep - 1)
        if #kopecks == 2 then
            kopecks = tonumber(kopecks)
        elseif #kopecks == 1 then
            kopecks = tonumber(kopecks) * 10
        elseif #kopecks == 0 then
            kopecks = 0
        else
           die('Invalid amount: %s', str)
        end
        str = roubles
    end
    if #str == 0 then
        return kopecks
    else
        return tonumber(str) * 100 + kopecks
    end
end

local function frommoney(num)
    num = 0LL + num
    local roubles = tonumber(num / 100)
    local kopecks = math.abs(tonumber(num % 100))
    if roubles == 0 and num < 0 then
        return string.format("-0.%02d", kopecks)
    end
    return string.format("%d.%02d", roubles, kopecks)
end
```

I hope this example will help you.

**Comment by zloidemon** [comment]
Decimal implementation in python is good, you can see links below:

[PEP 327](https://www.python.org/dev/peps/pep-0327/)
[decimal](https://docs.python.org/3/library/decimal.html)

**Comment by filonenko-mikhail** [comment]
Implemented using decnumber library

https://github.com/tarantool/ldecnumber/

**Comment by kyukhin** [comment]
We might want to take a look at http://download.icu-project.org/files/decNumber/

**Comment by sergepetrenko** [comment]
Here's a proposed format for decimal MsgPack encoding:
We use MsgPack `ext` type to encode decimals.
According to [MsgPack specification](https://github.com/msgpack/msgpack/blob/master/spec.md), `ext` type has the following
format:
```
+------+------------------+------+======+
| code | length(optional) | type | data |
+------+------------------+------+======+
```
Where `code` is one of the: `0xd4`, `0xd5`, `0xd6`, `0xd7`, `0xd8`, `0xc7`, `0xc8`, `0xc9`
`0xd4` - `0xd8` omit the `length` field, because they imply fixed-length data: 1, 2, 4, 8 and 16 bytes, respectively.
`0xc7`, `0xc8` and `0xc9` imply length fields of 1, 2 and 4 bytes in size, respectively.
`length` is an unsigined integer, representing the length of `data`.
`type` is a signed 8-bit integer, holding either user-defined types (types from 0 to 127) or predefined types (-128 ... -1).
Currently the only predefined type in MsgPack is the Timestamp extension type (`type` = `-1`)

We haven't used MsgPack `ext` type in Tarantool before, so we can use `type` = `0` to encode decimals.
The only remaining point in question is `data` representation.

[This open pull request to MsgPack spec](https://github.com/msgpack/msgpack/pull/249/commits/4ca8be02c89d2fef558ba2f0e6b0a8c7f1d9c59e?short_path=958e727#diff-958e7270f96f5407d7d980f500805b1b) also suggests using `ext` type, and decimal interchange floating-point formats from IEEE 754-2008 to store the decimal value.

The aforementioned format is useful for storing `decimal32`, `decimal64` and `decimal128` types defined in IEEE 754-2008, which are stored as 3 decimal digits per 10 bits of space plus exponent plus sign and some additional flags.
We decided to use decNumber decimal floating-point library and write a wrapper for it to enforce fixed-point calculations. Fixed-point decimals have 2 additional attributes: `precision` and `scale`, which define the number of decimal digits the number consists of and the number of decimal digits that go after the dot.
We have decided that maximum precision should be 38 digits. The same value is used in Oracle DB, in Microsoft SQL server and in SQLite.
Unfortunately, `decimal128` can hold only 34 digits of precision. So, we have to use `decNumber` structure from the decNumber library, and convert decimals to some other value. The library suggests serializing arbitrary-precision decNumbers as Binary-Coded Decimals, that is, 2 decimal digits per 8 bits of space. The number scale should be stored separately.
This means it will take us at most `38/2 + 1 = 20` bytes to store decimal digits of the highest-precision number, plus `2` bytes for storing `precision` and `scale`.
The upside is that smaller numbers will require less bytes to serialize them (`ceil((precision+1)/2) + 2` bytes plus additional 3 bytes maximum to store the `ext` header) when using Binary-Coded Decimal format.
There is also `Decimal{k}` format in IEEE 754-2008, where `k` is a multiple of `32`, we could use `Decimal160` for our purposes, but decNumber doesn't have it, and, besides, we would use up a lot of extra space on storing small-digit numbers.

That said, the proposed fixed-point decimal representation in MsgPack looks like this:
```
+------+------------------+------+-----------+-------+=====+
| code | length (if > 16) | type | precision | scale | BCD |
+------+------------------+------+-----------+-------+=====+
```
`precision` and `scale` are 1-byte unsigned integers there, and `BCD` is `length` bytes of Binary-Coded Decimal notation, where `length` = `ceil(precision+1/2) + 2`. We have to store both `precision` and `length`, because both `2*k-2` and `2*k-1` precisions result in length = `k + 2`, so precision is ambiguous

**Comment by pgulutzan** [comment]
These are my expectations.
They are also the expectations of K. Osipov, if I understand correctly.
If they are incorrect, it would be good to know now.
* This really will be in version 2.2.
* The abbreviation DEC  is okay and DEC is a reserved word.
* NUMERIC is not okay.
* Default scale = 0, default precision = 38, so DECIMAL is the same as DECIMAL(38,0).
* Users may specify DECIMAL|DEC [precision [, scale]].
  In fact specified precision will be ignored, just as length is ignored for varchar(length).
* the data type of 1.1 is no longer float it is decimal, for a float, you must say 1.1e0.
* For type information e.g. typeinfo() we will see 'decimal' not 'decimal(precision,scale)'.
* For ordering in SCALAR columns, 'decimal' values are mixed in with values of other numeric data types.

**Comment by sergepetrenko** [comment]
A small update to decimal internal representation:
It is possible to omit `scale` and `precision` in `struct decimal`, here's how:
decNumber numbers have `digits` and `exponent` fields, which may be used to evaluate `precision` and `scale` from them as follows:
If `exponent < 0` then `precision = digits` and `scale = -exponent`
If `exponent >= 0` then `precision = digits + exponent`, and `scale = 0`

**Comment by sergepetrenko** [comment]
### A summary on current feature design state
#### decimal type
Fixed point decimal is a number type, which has 2 attributes: `precision` and `scale`, where `precision >= scale`.
A value of such type is suitable for storing numbers in a range
[`-9...9.9...9`; `+9...9.9...9`] with fixed accuracy = `10^(-scale)`, where `±9...9.9...9` have `scale` decimal digits after the decimal point and `precision` decimal digits in total.
#### Used library
We use [decNumber](http://download.icu-project.org/files/decNumber/) library as a foundation for our decimal type.
Currently, decNumber is linked statically into tarantool, the possibility is being discussed to link it dynamically.
A small wrapper around decNumber is written to enforce fixed-point computations. The wrapper sets a  single context for all the arithmetic operations (+, -, *, /). This context allows for computations with maximum precision = 38.
New type `decimal` is a synonym to `decNumber` type from the decNumber library.
`decimal` values do not have explicit `precision` and `scale`, but these values can be evaluated from `decNumber`'s `digits` and `exponent` fields using the following formulae:
```
             / MAX(digits, -exponent); exponent < 0
precision = |
             \ digits + exponent ; exponent >= 0

scale = MAX(-exponent, 0)
```
#### Arithmetic operations
The supported operations are
- addition
- subtraction
- multiplication
- division

As mentioned above, a single decNumber context is used inside a decimal wrapper for the arithmetic ops. All the arithmetic ops are limited by maximum `precision` = 38.
Until precision is not exceeded, all the calculations are exact, meaning there is no rounding of operands, and operation results generally have bigger precision and scale, than the ones of the operands.
#### Rounding to the desired precision
If result precision exceeds desired precision, and result `scale > 0`, rounding will take place. The rounding algorithm of choice is "round half up", which means that `0.5` is rounded to `1`, `0.49` is rounded to `0`, `0.15` is rounded to `0.2`, `0.149` is rounded to `0.1`
Say, `precision` is `3`, and we have a number `12.34`. It has `precision = 4` and `scale = 2`. After rounding, we will get `12.3` with `precision = 3` and `scale = 1`.
Say, `precision` is `3` and the number is `1234`. `scale = 0`, so rounding is impossible, and an overflow occurs. This is an error, and the operation result cannot be used.
#### Math functions
Supported math functions are
- log10
- ln
- pow
- exp
- sqrt

All these functions accept result precision as a parameter and have a temporary context inside, which enforces the desired precision. If result precision exceeds the desired one, rounding happens, as described above.
#### Conversions
Decimal values may be constructed from string with number representation and from signed/unsigned integers.
Note, that you cannot construct decimals from floats.
Decimals may be converted to their string representation and to integers by rounding.
#### Decimal and MsgPack
MsgPack [ext](https://github.com/msgpack/msgpack/blob/master/spec.md#ext-format-family) type is used to encode decimals.
The format goes as follows:
```
+------+------------------+------+======+
| code | length(optional) | type | data |
+------+------------------+------+======+
```
Where `code` is one of the: `0xd4`, `0xd5`, `0xd6`, `0xd7`, `0xd8`, `0xc7`, `0xc8`, `0xc9`
`0xd4` - `0xd8` codes omit the `length` field, because they imply fixed-length data: 1, 2, 4, 8 and 16 bytes, respectively.
`0xc7`, `0xc8` and `0xc9` imply length fields of 1, 2 and 4 bytes in size, respectively.
`length` is an unsigined integer, representing the length of `data`.
`type` is a signed 8-bit integer, holding either user-defined types (types from 0 to 127) or predefined types (-128 ... -1).
The only predefined type in MsgPack at the moment is the Timestamp extension type (`type` = `-1`)
We haven't used MsgPack `ext` type in Tarantool before, so we can use `type` = `0` to encode decimals.
Let `MP_DECIMAL = 0` - MsgPack extension type for tarantool decimals.

##### Packed decimal representation
As stated [above](https://github.com/tarantool/tarantool/issues/692#issuecomment-486768480), we will use the decPacked notation for decimal values. It stores a decimal number as an array of bytes, where each byte stands for 2 decimal digits (4 bits per digit), and an additional 4-bit nibble that holds the sign (and nothing else in our case). The scale is implied in this representation, so we have to store it separately.
Thus, 
```
+------+-------------------+------+-------+=====+
| code | length (optional) |   0  | scale | BCD |
+------+-------------------+------+-------+=====+
```
is the format to store decimals as MsgPack.
`code` is a byte with a value `0xd4-0xd8` or `0xc7-0xc9`.
`length` is a byte (two/four bytes) depending on `code`
`scale` is a byte
`BCD` is a byte array.

This document will be updated as the feature design process goes.

**Comment by sergepetrenko** [comment]
Using ffi to call C code is said to be faster since it doesn't break JIT traces, so we have compared the performance of ffi approach to exposing decimals to Lua versus the Lua C call approach (the one existing on the branch ATM).
As can be seen below, the current approach is actually faster by ~35%, compared to the ffi one.

Here's the testing script used (`decimal_tonumber`, `decimal_tostring` and `decimal_add` are aliases for `decimal.new`, `decimal.tostring` and `decimal.__add ` -- the `+` operation:
```Lua
local fiber = require('fiber')

function timer(func, ...)
    local s = fiber.time()
    func(...)
    fiber.yield()
    return fiber.time() - s 
end

function test(iters)
    local sum = 0 
    for i = 1,iters do
        for j = 1, i do
            local deci = decimal_tonumber(tostring(i))
            local decj = decimal_tonumber(tostring(j))
            local sloc = tonumber(decimal_tostring(decimal_add(deci, decj)))
            for k = 1, 1000 do
                sum = sum + k 
            end 
            sum = sum + sloc
        end 
    end 
    return sum 
end
```

The script produces these results (can be obtained by `timer(test, iterations)`:

iterations |ffi, jit.off | ffi, jit.on | Lua C call, jit off | Lua C call, jit on
----- | ----- | ----- | ----- | -----
100 | 0.025 | 0.023 | 0.022 | 0.019
1000 | 2.048 | 2.050 | 1.426 | 1.406
2000 | 8.55 | 7.92 | 5.931 | 5.807
10000 | 218.371 | 219.944 | 169.210 | 162.094

So, let's use Lua C call interface for the matter.

**Comment by sergepetrenko** [comment]
We have added a decimal library to Lua (3ab387a45e52ed01059b727596b35b8efad0b460)
Further work, which is allowing to insert decimals into spaces and build indices over them, will be done in the scope of #4333
