### ISSUE TITLE
luajit harness - 301-basic.t is flaky

### ISSUE THREAD

**Issue by tsafin** [tarantool/tarantool#7058]
I've found it the harder way (while trying to run CI for #6923 that 301-basic.t is flaky on all macosx jobs

i.e. 
```
Test Summary Report
-------------------
/Users/tntmac01.tarantool.i/actions-runner/_work/tarantool/tarantool/third_party/luajit/test/lua-Harness-tests/301-basic.t      (Wstat: 0 Tests: 223 Failed: 1)
  Failed test:  12
Files=50, Tests=1907,  3 wallclock secs ( 0.17 usr  0.09 sys +  2.04 cusr  0.54 csys =  2.84 CPU)
[tarantool-lua-harness-301-failing.log](https://github.com/tarantool/tarantool/files/8532883/tarantool-lua-harness-301-failing.log)

Result: FAIL
```
https://github.com/tarantool/tarantool/runs/6115138405?check_suite_focus=true#step:4:9566

this problem could be worked around with this ugly hack in luatest runner script:

```diff
index d4b2306aa..fe82a9e1a 100644
--- a/test/luajit-test-init.lua
+++ b/test/luajit-test-init.lua
@@ -41,3 +41,5 @@ end
 function _dofile(filename)
   return dofile(path_to_sources..filename)
 end
+
+collectgarbage('collect')
```
[tarantool-lua-harness-301-failing.log](https://github.com/tarantool/tarantool/files/8532898/tarantool-lua-harness-301-failing.log)

**Comment by igormunkin** [comment]
The aforementioned test belongs to the external [lua-Harness suite](https://framagit.org/fperrad/lua-Harness), that tests the behaviour of LuaJIT GC assuming the script is loaded without much Lua code before the checks (one can find the source code [here](https://github.com/tarantool/luajit/blob/tarantool/master/test/lua-Harness-tests/301-basic.t)).

So the committed solution is not a workaround but quite a solid fix for the problem, since Tarantool loads much Lua code generating a bunch of garbage to be collected. Hence `collectgarbage('collect')` is called prior to the test body (preparing Lua runtime is the main purpose of `test/luajit-test-init.lua` helper).

So the only thing worth to be change is the comment and commit message, but both these places refers this issue, so inquistive readers now have the answer. Closing.
