### ISSUE TITLE
Fix libicu update problem

### ISSUE THREAD

**Issue by Mons** [tarantool/tarantool#7087]
[PM link](https://www.notion.so/tarantool/Fix-libicu-update-problem-87bb191dc00b45b5895bfbdbb08fcdeb)

Libicu has very weird upgrade policy: every update it changes its library version major. So after update of libicu every tarantool on this machine no longer working until rebuild.

```
dyld: Library not loaded: /opt/homebrew/opt/icu4c/lib/libicui18n.69.dylib
```

Mostly this affects tarantool on MacOS (because almost every update of brew updates libicu), but also this affects so,e linux, like CentOS or RedOS.

**Comment by Totktonada** [comment]
This issue proposes a solution in the title, but it is not the only solution for the problem.

Context:

* A typical libicu build includes major version number in symbol names. It is changed at incompatible changes.
* Linux distributions don't change major version of libraries due to ABI compatibility matters (they backport fixes instead). However there are some corner cases:
  * Rolling release distros/packages collections (Gentoo, brew on Mac OS).
  * Installation of a package built for one distribution on a distro from the same family (CentOS -> RedOS and so on).
* Those incompatible changes may have negative effect on comparators (see #6695). However it likely occurs on rarely used collations.
* icu git repository is large (543M for a fresh clone of https://github.com/unicode-org/icu).

So there are two problems:

1. If we build tarantool against libicu-X, we can't run it against libicu-Y without a rebuild.
2. Changing of libicu major version or using different libicu version in a replicaset may lead to hard-to-predict behaviour.

Let's throw out the second problem (AFAIU it'll be investigated in #6695) and look on possible solutions for the first one.

Possible solutions:

1. Add icu as a submodule.
    - Con: significant git clone slowdown.
    - Pro: solves problem 2, at least until we'll want to update the library.
2. Use a static library from the target system.
    - Not possible, libicu.a is not shipped in -dev/-devel packages (at least not on all distros).
3. Ship our own icu developer packages with static libicu build for all supported systems.
    - Con: increases our effort for supporting various distros.
    - Con: does not solve brew's problem.
    - Pro: same as 1.
5. Use `dlopen("icu-X", <...>)` for different X's plus `dlsym(<...>)` in runtime, exclude `-licu` from linker options. See https://github.com/tarantool/smtp/pull/32, https://github.com/tarantool/smtp/pull/33 and https://github.com/tarantool/smtp/pull/51.
    - Con: don't even partially solve problem 2.
    - Pro: no git clone slowdown.

I propose the fourth solution.

----

Regarding problem 2: it requires a careful investigation. We should look on it at different angles and take care to different possible solutions: a) do nothing; b) setup a process of marking unstable collations and warning users (possibly with writing icu major version into a snapshot); c) ship our own icu package; d) bundle icu partially by copying; e) bundle icu entirely as a submodule disregarding its size; f) find alternative library, more lightweight. Anyway, I propose to don't spin on **this** problem here.

**Comment by alyapunov** [comment]
We can download and build libicu on macOS, as we do in static build. Is it good for everybody? @Gerold103 wdyt?

**Comment by Totktonada** [comment]
@alyapunov I doubt that it'll be accepted by brew's maintainers for tarantool's brew formula. So, well, even if we can do so, it likely will not change things for end users.

**Comment by NeraverinTarantool** [comment]
We have decided not to fix this issue. Switching to tt eliminates this problem - as it always builds tarantool statically.
