### ISSUE TITLE
"Strict" fencing mode

### ISSUE THREAD

**Issue by sergepetrenko** [tarantool/tarantool#7110]
Our current fencing implementation still leaves a small window (max `replication_death_timeout = 4 * replication_timeout`) of time, where the old partitioned from everyone else leader doesn't step down even though the healthy part of the cluster might've already elected a new leader.

In order to fix this, fencing timeout (which is not configurable yet and is equal to `replication_death_timeout`), should be twice as small as `replication_death_timeout` on all nodes.

This guarantees that the old leader steps off before other nodes even start elections.

Such a mode should be optional, because it basically doubles time to react to leader death.

**Comment by R-omk** [comment]
As I [wrote earlier](https://github.com/tarantool/tarantool/issues/6661#issuecomment-981551400), I still do not see a solution to the problem of protecting shared resources.

Please read [what fencing is](https://en.wikipedia.org/wiki/Fencing_(computing)).

From what I see now, the old master will still not be isolated in any way, and when it appears on the network, replication will occur, followed by a possible violation of integrity in spaces with disabled synchronous replication, i.e. there will be conflicts and silent overwriting of data in tuples.

To solve the problem, it is required that all replicas **ignore any data in the replication flow** from the old master. In this case, the old master, when returning to the cluster, must check the vclock and, if there are discrepancies, then do a **rebootstrap** with a full recovery from the current state of the cluster.

**Comment by sergepetrenko** [comment]
@R-omk 

> From what I see now, the old master will still not be isolated in any way, and when it appears on the network, replication will occur, followed by a possible violation of integrity in spaces with disabled synchronous replication, i.e. there will be conflicts and silent overwriting of data in tuples.

This is not true. A fenced node is read-only, so it can't write to neither synchronous nor asynchronous spaces.
Moreover, once the node enters fencing, it stops committing and rolling back synchronous transactions which are in flight.
The only way to get out of fencing is by reading some remote PROMOTE. Or issuing your own one manually via `box.ctl.promote()`

Ok, after giving it a second thought I see what you mean. There is an interval in time between the moment connectivity is lost and the moment it is noticed by fencing. During this interval in time the node will be writeable and will commit asynchronous transactions.
None of the synchronous transactions will be committed during this time though. And once the node regains connectivity, all the synchronous transactions that accumulated during this interval will be rolled back.

Speaking of asynchronous transactions, yes, they will appear after connectivity restore , and they might rewrite other asynchronously committed data. This is expected, and we made this decision when working on 560d71b454431792f5d589387657718b2e3904eb. This patch adds a filter,  and the filter only works on synchronous transactions.
If you think this should be changed somewhy, please give me your reasons.

Short answer is: everything is fine with synchronously replicated data.
If you are using asynchronous replication, you take this risk.

**Comment by R-omk** [comment]
> If you are using asynchronous replication, you take this risk.

In this case, the use of the term "fencing" is simply poorly chosen and not appropriate in this case. Because in systems without a strict system of synchronous replication, it has a different meaning.


> everything is fine with synchronously replicated data. 

Okay, but that was fixed in the previous issue,   as for the current topic, let's look at the description
> This guarantees that the old leader steps off before other nodes even start elections.

everything looks like this is useful just in those cases where asynchronous replication is used and does not make much sense if you are already using synchronous replication.

Since you decide to add this capability (i.e. when a new writable node appears strictly after the old one was supposed to go into read mode), **let's identify the key advantage** of this '_fencing_' mode  and, maybe, simplify the work with asynchronous replication.

For example, you can completely disable data replication if the raft term is out of date, or provide the ability to access additional data in the context of a "before replace" trigger so that the user can decide for himself what to do with those data.

I know it's complicated, it's not clear what to do in a situation where an asynchronous transaction was not replicated to a quorum, or in situations where `replication_synchro_quorum` is less than half of all nodes. After all, all these cases can theoretically lead to a violation of integrity. ...There are too many "what ifs" .


However, I do know one good case that can be useful for strictly "fencing" mode.

I would prefer that the host does a rebootstrap on next connect to cluster if it is absolutely sure that no data has been replicated to any replica since the loss of the network. This ensures that when a host appears on the network, none of its data will be replicated and cannot lead to conflicts. This is a situation in which some transactions are guaranteed to be lost, but this choice was made consciously when the user chose asynchronous replication. However, the data can still be saved, for example, the old master who has lost quorum can move/rename the WAL  logs + last snapshot , in which case it will still be possible to access orphaned transactions that could not be replicated anywhere.


Ultimately, what I want to see is let all the problems of asynchronous replication be left to master-to-master replication.
But in the case of strictly "fencing" to try to reach a situation where conflicts and owerwriting  are impossible, it's better to lose modification. 


P.S. I believe this should be a key benefit of the strict "fencing" mode of operation. In this case, the meaning of the term _fencing_ will correspond to the generally accepted definition of this concept.

**Comment by sergepetrenko** [comment]
Thanks a lot for the explanation! I understand your point better now.
I'll return to you once we discuss it with the team.

**Comment by R-omk** [comment]
It seems I came up with an implementation.

The main goal is that since we guarantee that only one master is running at a time, then for the user all changes should look like they were written sequentially, even if data is lost after commit confirmation (this is the same as losing data with fsync disabled) .

In short, the algorithm is as follows: when choosing a new leader, you need  to collect a quorum, remember the maximum vclock position of the previous master from all nodes of quorum, wait inside the quorum for synchronization to this position, block (fence) replication from nodes not included in the quorum until it turns out that it is safe to return to the quorum ( you can safely return if the vclock of the old leader is no more than what was recorded in the quorum, or a full reboot is performed with a reset of the accumulated data that appeared after disconnecting from the quorum)

The described scheme will allow to discard both asynchronous transactions and synchronous transactions that were committed with less than a quorum (ex replication_synchro_quorum = 2  when total count of nodes is 5 )

**Comment by sergepetrenko** [comment]
This will work, indeed. 
This looks quite a lot like an extension to our split-brain detection technique (#5295). Fence from the old leader as soon as it sends **any** data from the obsolete term.
