### ISSUE TITLE
clock_lowres_tick: Assertion `clock_lowres_thread_is_owner()' failed.

### ISSUE THREAD

**Issue by olegrok** [tarantool/tarantool#7408]
In Debug build in TDG CI I see:
```
2022-07-14T02:12:54.5475017Z WARNING  localhost:45166:server.py:42 tarantool: /__w/sdk/sdk/tarantool-master/tarantool/src/lib/core/clock_lowres.c:59: clock_lowres_tick: Assertion `clock_lowres_thread_is_owner()' failed.
```

2.11.0-entrypoint-5-g4aa52ce0b-r499

It shoots in tests that uses https://github.com/tarantool/kafka module.

**Comment by drewdzzz** [comment]
The module kafka creates threads and does not block signals on them. The problem is that there are some signals in tarantool that are only required to be delivered to the main thread (this is what failing assertion checks for). You must block all signals when creating threads in the module (both `tnt_kafka` and `librdkafka`). This seems to solve the problem.

**Comment by olegrok** [comment]
> The module kafka creates threads and does not block signals on them. The problem is that there are some signals in tarantool that are only required to be delivered to the main thread (this is what failing assertion checks for). You must block all signals when creating threads in the module (both `tnt_kafka` and `librdkafka`). This seems to solve the problem.

Firstly I don't want to do that. Secondly I'm not sure that librdkafka allow to do it. Thirdly it doesn't solve an issue. Because there will be another modules that creates threads under the hood.
