### ISSUE TITLE
Yielding in on_shutdown triggers doesn't work if tarantool shuts down normally

### ISSUE THREAD

**Issue by gmoshkin** [tarantool/tarantool#7434]
**Bug description**

Yielding inside `on_shutdown` triggers doesn't work if tarantool shuts down due to the script fiber finishing normally. This will happen for example if you press ctrl-d inside the interactive console, or if the script execution reaches end of file (without calling `os.exit()`).

Any platform, latest version.

**Steps to reproduce**

Run tarantool with this script (`tarantool test.lua`):
```lua
box.ctl.on_shutdown(
    function()
        print 'before yield'
        require 'fiber'.sleep(0)
        print 'after yield'
    end
)
```

**Actual behavior**

This will only print one line
```
before yield
```

**Expected behavior**

Should print 2 lines
```
before yield
after yield
```

Note that if you add `os.exit()` to the end of the script, then both the lines will be printed.

**Comment by locker** [comment]
Looks related: https://github.com/tarantool/tarantool/issues/6801

**Comment by gmoshkin** [comment]
> Looks related: #6801

Nope, that one is caused by nothing other then the `os.exit`'s implementaion
```lua
local function exit(code)
    code = (type(code) == 'number') and code or 0
    ffi.C.tarantool_exit(code)
    -- Make sure we yield even if the code after
    -- os.exit() never yields. After on_shutdown
    -- fiber completes, we will never wake up again.
    while true do fiber.yield() end
end
rawset(os, "exit", exit)
```
https://github.com/tarantool/tarantool/blob/master/src/lua/init.lua#L65

**Comment by Gumix** [comment]
In case of shutdown by `os.exit()` or `signal_cb()`, they invoke `tarantool_exit()`, which waits for shutdown triggers completion and then breaks the event loop. Then `tarantool_exit()` is invoked from `main()` for the second time, and does nothing.

In the opposite case (Ctrl+D or the end of the script), at first `ev_break()` is called from `run_script_f()`, then `tarantool_exit()` is invoked from `main()`, but trigger-fibers cannot be longer scheduled, because the event loop is already stopped.

This can be fixed by the simple patch, however it should be reworked a bit.
```diff
diff --git a/src/lua/init.c b/src/lua/init.c
index b08a9e7c3..cf9f6367e 100644
--- a/src/lua/init.c
+++ b/src/lua/init.c
@@ -967,7 +967,7 @@ end:
     */
    if (!aux_loop_is_run)
        fiber_sleep(0.0);
-   ev_break(loop(), EVBREAK_ALL);
+   tarantool_exit(0);
    return 0;

 luajit_error:
```
