### ISSUE TITLE
Test backtraces for fiber.info()

### ISSUE THREAD

**Issue by kyukhin** [tarantool/tarantool#7535]
Looks like enabling stack protector may (or may not) break backtraces for fiber.info().
Need to add a test case to cover this.

**Comment by Totktonada** [comment]
It becomes important in reflection of #7535 and #5372, because (as I guess from the git history) the hardened profiles (PIE, stack protector) were disabled in Deb/RPM packages specifically to don't break `fiber.info()` backtraces. Maybe everything is fine now and we can just enable the security enhancements. See #5372 for my findings.

Examples of broken backtraces can be found in #5326 and #4278. I think we should at least test that an expected Lua function can be found in one of frames and the same for a C function (say, from a dynamic module).
