### ISSUE TITLE
Assertion `replicaset.applier.connected > 0' failed

### ISSUE THREAD

**Issue by rosik** [tarantool/tarantool#7590]
**Bug description**

While debugging a test we've encountered the error:

```
/home/rosik/w/picodata/tarantool-sys/src/box/replication.cc:502: void replica_on_applier_disconnect(replica*): Assertion `replicaset.applier.connected > 0' failed.
```

Tarantool version: 2.10.0-29-g1ec2a9d15

**Steps to reproduce**

I only have a picodata-based repro: https://git.picodata.io/picodata/picodata/picodata/-/issues/129

**Comment by sergos** [comment]
The error didn't appear in regular run of the testing as per [link](https://git.picodata.io/picodata/picodata/picodata/-/issues/129), while #7592 error was reproduced.
I have no details on what happened "While debugging" - probably some C interfaces were called at a random moment of execution?

**Comment by Serpentian** [comment]
`replicaset.applier.connected` is decremented only in one place, but it also becomes equal zero in one more place. We don't equate this value to something other than zero, it's only incremented or decremented. So, there's only two possible variants to make the assertion fail:

1. Equate `replicaset.applier.connected` to zero and then decrement the value.
2. Decrement the value more times then increment it.

### Decrementing the value

The first case (decrementing) is done only in the following code. Assertion, which we're talking about in the current issue, fails right here too.

```lua
static void
replica_on_applier_disconnect(struct replica *replica)
{
	switch (replica->applier_sync_state) {
	case APPLIER_SYNC:
		assert(replicaset.applier.synced > 0);
		replicaset.applier.synced--;
		FALLTHROUGH;
	case APPLIER_CONNECTED:
		assert(replicaset.applier.connected > 0);
		replicaset.applier.connected--;
		break;
	case APPLIER_LOADING:
		assert(replicaset.applier.loading > 0);
		replicaset.applier.loading--;
		break;
	case APPLIER_DISCONNECTED:
		break;
	default:
		unreachable();
	}
	replica->applier_sync_state = replica->applier->state;
	if (replica->applier_sync_state == APPLIER_LOADING)
		replicaset.applier.loading++;
}
```

It's a part of the following trigger:

```Lua
static int
replica_on_applier_state_f(struct trigger *trigger, void *event)
{
	switch (replica->applier->state) {
        ...
	case APPLIER_DISCONNECTED:
		replica_on_applier_disconnect(replica);
		break;
	...
}
```
This trigger is bounded to the `replica.on_applier_state` variable and it's invoked when the applier changes its state:

```Lua
static struct replica *
replica_new(void)
{
        ...
	trigger_create(&replica->on_applier_state,
		       replica_on_applier_state_f, NULL, NULL);
        ...
}
```

```Lua
void
replica_set_applier(struct replica *replica, struct applier *applier)
{
	assert(replica->applier == NULL);
	replica->applier = applier;
	trigger_add(&replica->applier->on_state,
		    &replica->on_applier_state);
}
```

```Lua
static inline void
applier_set_state(struct applier *applier, enum applier_state state)
{
	applier->state = state;
	say_debug("=> %s", applier_state_strs[state] +
		  strlen("APPLIER_"));
	trigger_run_xc(&applier->on_state, applier);
}
```

So the value `replicaset.applier.connected` (`replicaset.applier` is the state of the appliers and not appliers actually) is decremented, when the following occurs:

1. `applier_set_state` with `APPLIER_DISCONNECTED` flag is invoked
2. Triggers `applier_on_state_f` and `replica_on_applier_state_f` (the second one depends on the first one, they're added to the same list of triggers and will be executed consequently) executed one after the other with `trigger_run_xc` from the `applier_set_state`.
3. Accoring to the fact that the applier becomes disconnected and the replica thought it was connected, we decrement the value of known connected appliers in the current replicaset.

Applier becomes disconnected, when some kind of error occurs in the `applier_f`:

```Lua
static inline void
applier_disconnect(struct applier *applier, enum applier_state state)
{
	applier_set_state(applier, state);
        ...
}
```

```Lua
static int
applier_f(va_list ap)
{
        while (!fiber_is_cancelled()) {
                try {
                        ...
		} catch (ClientError *e) {
			} else if (e->errcode() == ER_SYSTEM || e->errcode() == ER_SSL) {
				/* System error from master instance. */
				applier_log_error(applier, e);
				applier_disconnect(applier, APPLIER_DISCONNECTED);
				goto reconnect;
                        }       
                ...
		} catch (SocketError *e) {
			applier_log_error(applier, e);
			applier_disconnect(applier, APPLIER_DISCONNECTED);
			goto reconnect;
		} catch (SystemError *e) {
			applier_log_error(applier, e);
			applier_disconnect(applier, APPLIER_DISCONNECTED);
			goto reconnect;
		} catch (SSLError *e) {
			applier_log_error(applier, e);
			applier_disconnect(applier, APPLIER_DISCONNECTED);
			goto reconnect;
                }
               ...
        }
}
```

This can be either system, ssl error on the remote master, or system, ssl, socket error on the current instance. These errors're the only way we can trigger decrementing of the `replicaset.applier.connected` value.

### Equate to zero

During the reconfiguration we drop the value to zero:

```Lua
/**
 * Update the replica set with new "applier" objects
 * upon reconfiguration of box.cfg.replication.
 */
static void
replicaset_update(struct applier **appliers, int count, bool keep_connect)
{
        ...
	replicaset.applier.total = count;
	replicaset.applier.connected = 0;
	replicaset.applier.loading = 0;
	replicaset.applier.synced = 0;
	
	replicaset_foreach(replica) {
                ...
		if (keep_connect && other != NULL &&
		    (replica->applier->state == APPLIER_FOLLOW ||
		     replica->applier->state == APPLIER_SYNC)) {
			/*
			 * Try not to interrupt working appliers upon
			 * reconfiguration.
			 */
			replicaset.applier.connected++;
			replicaset.applier.synced++;
                        ...
		} else {
                       ...
		}
		applier_stop(applier);
		applier_delete(applier);
	}

	/* Save new appliers */
	replica_hash_foreach_safe(&uniq, replica, next) {
	        ...
		replica->applier_sync_state = APPLIER_CONNECTED;
		replicaset.applier.connected++;
	}
        ...
}
```

### Conclusion

AFAICS, you reconfigure the node in your tests. The problem might be the fact, that during the reconfiguration of the replication part, some appliers failed due to the any of error, I mentioned above. before `replicaset.applier.connected` was incremented at least once. It's possible because reconfiguration is initiated in the main cord, when appliers work in their own.

Actually, I suppose that it was `SocketError`, which can be encountered while using some hardcoded ports. You possibly had some tests running in the other repo and occupying ports. `SocketError` looks like that:

```
[Instance "box_1_b" returns with non-zero exit code: 1]

Last 15 lines of Tarantool Log file [Instance "box_1_b"][/home/alver/Programming/Work/vshard/build/test/var/001_rebalancer/box_1_b.log]:
2022-08-18 20:09:48.079 [723433] main/111/main I> remote vclock {1: 47} local vclock {1: 47}
2022-08-18 20:09:48.079 [723433] main/106/gc I> wal/engine cleanup is resumed
2022-08-18 20:09:48.815 [723433] relay/127.0.0.1:51070/101/main I> recover from `/home/alver/Programming/Work/vshard/build/test/var/001_rebalancer/box_1_b/00000000000000000047.xlog'
2022-08-18 20:09:48.869 [723433] main/132/console/::1:41400 I> Starting reconfiguration of replica db778aec-267f-47bb-9347-49828232c8db
2022-08-18 20:09:48.869 [723433] main/132/console/::1:41400 I> Box has been configured
2022-08-18 20:09:48.869 [723433] main/133/lua I> Old replicaset and replica objects are outdated.
2022-08-18 20:09:49.289 [723433] main/112/applier/storage@127.0.0.1:3301 I> can't read row
2022-08-18 20:09:49.289 [723433] main/112/applier/storage@127.0.0.1:3301 coio.c:348 E> SocketError: unexpected EOF when reading from socket, called on fd 29, aka 127.0.0.1:55244, peer of 127.0.0.1:3301: Broken pipe
2022-08-18 20:09:49.289 [723433] main/112/applier/storage@127.0.0.1:3301 I> will retry every 0.10 second
2022-08-18 20:09:49.289 [723433] relay/127.0.0.1:51070/101/main coio.c:348 E> SocketError: unexpected EOF when reading from socket, called on fd 25, aka 127.0.0.1:3302: Broken pipe
2022-08-18 20:09:49.289 [723433] relay/127.0.0.1:51070/101/main I> exiting the relay loop
2022-08-18 20:09:49.321 [723433] main C> got signal 15 - Terminated
2022-08-18 20:09:49.321 [723433] main/143/iproto.shutdown I> tx_binary: stopped
Starting instance box_1_b...
Start failed: builtin/box/console.lua:918: failed to create server localhost:46990: Address already in use
[ fail ]
``` 

Of course, it can be also `SystemError` or `SSLError`, who knows. There can also be places, where we don't increment the value properly and while disconnecting of all appliers the number of decrements turns out to be more than increments. Still investigating.

Anyway the problem should be solved.

**Comment by sergos** [comment]
I have the following :
```
export i=0; while ./test-run.py --build ../build --var ./var2 $(yes 7590 | head -n 800) && true || false; do echo $i; export i=$((i+800)) ; done
69600 passed tests
```

**Comment by sergepetrenko** [comment]
This should be in 2.10: https://github.com/tarantool/tarantool/pull/8682#issuecomment-1557417558
Will backport in scope of #8682
