### ISSUE TITLE
Builtin modules overloading

### ISSUE THREAD

**Issue by igormunkin** [tarantool/tarantool#7774]
@Totktonada: The idea is to offer something similar to Perl's dual-file modules. We should elaborate package loader rules to allow convenient writing of built-in libraries replacements.

**Comment by Totktonada** [comment]
Fixed by the following pull requests:

* https://github.com/tarantool/tarantool/pull/8173
* https://github.com/tarantool/tarantool/pull/8253
* https://github.com/tarantool/tarantool/pull/8250
* https://github.com/tarantool/tarantool/pull/8300
* https://github.com/tarantool/tarantool/pull/8335
* https://github.com/tarantool/tarantool/pull/8348
* https://github.com/tarantool/tarantool/pull/8351

Landed to 2.11.0-rc1.
