### ISSUE TITLE
Tarantool crashes after executing SQL INSERT query (as a part of SQL tutorial)

### ISSUE THREAD

**Issue by EmirVildanov** [tarantool/tarantool#7798]
In a Tarantool SQL [tutorial](https://www.tarantool.io/ru/doc/latest/how-to/sql/sql_tutorial/#create-table) there is a subsection about creating tables. After creating table with executing
```
CREATE TABLE table2 (column1 INTEGER,
                     column2 VARCHAR(100),
                     column3 SCALAR,
                     column4 DOUBLE,
                     PRIMARY KEY (column1, column2));
```
and executing 3 inserts
```
INSERT INTO table2 VALUES (1, 'AB', X'4142', 5.5);
INSERT INTO table2 VALUES (1, 'CD', X'2020', 1E4);
INSERT INTO table2 VALUES (1, 'AB', X'A5', -5.5);
```
Tarantool crashes.

* OS: Linux
* OS Version: Ubuntu 20.04
* Architecture: amd64

Tarantool 2.11.0-entrypoint-83-g2e067472f

**Steps to reproduce**
1. Run tarantool
2. `box.cfg{}`
3. `\set language sql`
4. `\set delimiter ;`
5. Execute commands above ^^^.

**Comment by Totktonada** [comment]
I see no crash on 2.11.0-entrypoint-545-g8dcefeb2b:

```yaml
# tarantool> INSERT INTO table2 VALUES (1, 'AB', X'A5', -5.5);
---
- null
- !!binary RHVwbGljYXRlIGtleSBleGlzdHMgaW4gdW5pcXVlIGluZGV4ICJwa191bm5hbWVkX1RBQkxFMl8xIiBpbiBzcGFjZSAiVEFCTEUyIiB3aXRoIG9sZCB0dXBsZSAtIFsxLCAiQUIiLCAiQUIiLCA1LjVdIGFuZCBuZXcgdHVwbGUgLSBbMSwgIkFCIiwgIqUiLCAtNS41XQ==
...
```

(It is tarantool that is built with vanilla libyaml, bundled libyaml may give better output. This encoding is used for strings with unprintable characters, but vanilla libyaml has no UTF-8 characters printability detection mechanism.)

The error message means the following:

```yaml
# tarantool> print(yaml.decode('!!binary RHVwbGljYXRlIGtleSBleGlzdHMgaW4gdW5pcXVlIGluZGV4ICJwa191bm5hbWVkX1RBQkxFMl8xIiBpbiBzcGFjZSAiVEFCTEUyIiB3aXRoIG9sZCB0dXBsZSAtIFsxLCAiQUIiLCAiQUIiLCA1LjVdIGFuZCBuZXcgdHVwbGUgLSBbMSwgIkFCIiwgIqUiLCAtNS41XQ=='))
Duplicate key exists in unique index "pk_unnamed_TABLE2_1" in space "TABLE2" with old tuple - [1, "AB", "AB", 5.5] and new tuple - [1, "AB", "¥", -5.5]
```

And, yes, `[1, "AB"]` (a primary key from the first insert) and `[1, "AB"]` (from the third insert) are actually the same key.

If you see a crash, please, show us a backtrace. If you see an error other than one above, show it.

If you trying to paste the three inserts at once and receive the following error:

```yaml
# tarantool> INSERT INTO table2 VALUES (1, 'AB', X'4142', 5.5);
# INSERT INTO table2 VALUES (1, 'CD', X'2020', 1E4);
# INSERT INTO table2 VALUES (1, 'AB', X'A5', -5.5);
---
- null
- 'At line 2 at or near position 1: keyword ''INSERT'' is reserved. Please use double
  quotes if ''INSERT'' is an identifier.'
...
```

—it is due to bracketed paste mode enabled in readline by default. We'll disable it in PR #7347. BTW, @Lord-KA, how about extracting this patch into its own PR and merge sooner?

**Comment by kyukhin** [comment]
No feedback for more than 2 wws. Closing.

**Comment by EmirVildanov** [comment]
After more then 7 months I've finally made myself add a comment, shame on me...

I just wanted to say that after I've switched to tarantool `2.10.5-18-g080d07d71` there was no error anymore on the same device and OS.
