### ISSUE TITLE
Platform and lua profiler

### ISSUE THREAD

**Issue by kostja** [tarantool/tarantool#781]
We need a profiler for Lua, so that we can find out, when necessary, how much real time each Lua line takes in production.

**Comment by rtsisyk** [comment]
At least two customers asked me how to profile Lua...
I think we should try to port LuaJIT 2.1 profiler or update to 2.1:
http://repo.or.cz/w/luajit-2.0.git/blob_plain/v2.1:/doc/ext_profiler.html

**Comment by benagricola** [comment]
:+1: this. I'm using ProFi at the moment (pure lua) but it has a significant impact on cpu usage. 

I did have a quick try using Systemtap (specifically, with https://github.com/openresty/nginx-systemtap-toolkit#sample-bt) since it's been excellent for creating flamegraphs of other luajit / openresty code in the past, but didn't have much luck there with tarantool. Might be worth some investigation?

**Comment by zloidemon** [comment]
benagricola, ProFi based on sytemtap or dtrace. Unfortunately my branch with dtrace has deleted. It might have a lot time to make that again.
