### ISSUE TITLE
Application server language

### ISSUE THREAD

**Issue by vmakhaev** [tarantool/tarantool#782]
I have not found any mention on reason of choosing Lua as application server language? What other variants have you considered? I'm particularly interested in Javascript.

**Comment by kostja** [comment]
Two years ago we did this:
 https://github.com/rtsisyk/tarantool_js_primer

nobody got super excited. 

We may bring it up to date in a few months from now.

Is there any practical reason you need JS?

**Comment by vmakhaev** [comment]
The reason is: JS is a way more popular than Lua and there is no need to learn one more language if you have read an article about Tarantool and want to play with it a little bit and see how it can be used in your new project.

**Comment by kostja** [comment]
We work on this project  not to become rich, popular, likable, etc, but because we believe it's the best way to solve certain data management needs, and Lua handles itself very well for the cases at hand - better than JS,  in particular, especially when it comes to predictable garbage collection, low execution overhead, simplicity, extensibility.

Our issues database is not a place to give free advice, and this advice is neither original nor new. 

Thank you for your interest in Tarantool and a recommendation that could help increase its adoption.
