### ISSUE TITLE
flaky test: `app-luatest/gh_5747_crash_multiple_args_test.lua`

### ISSUE THREAD

**Issue by Gumix** [tarantool/tarantool#7886]
The test frequently fails:
```
[024] app-luatest/gh_5747_crash_multiple_args_test.l>
[024] TAP13 parse failed ('utf-8' codec can't decode bytes in position 162-163: invalid continuation byte).
[024]
[024] No result file (app-luatest/gh_5747_crash_multiple_args.result) found.
```

It fails because the result file contains binary data:
```sh
TAP version 13
1..1
# Started on Wed Nov  2 18:45:11 2022
# Starting group: app-luatest.gh_5747_crash_multiple_args
LuajitError: stdin:1: malformed number near '1é³s<9e>e'
fatal error, exiting the event loop
ok     1        app-luatest.gh_5747_crash_multiple_args.test_multiple_args
# Ran 1 tests in 0.083 seconds, 1 succeeded, 0 failed
```

~~The error means that the argument of the `-e` option is somehow corrupted.~~ Here is an example of a similar error message:
```
$ tarantool -e 1xxx
LuajitError: (command line):1: malformed number near '1xxx'
fatal error, exiting the event loop
```

~~Maybe it's a bug in `getopt_long`, or its usage.~~ Valgrind and ASan don't detect anything.

According to the dashboard, the test fails on centos_7, centos_8, debian_9, debian_10, ubuntu_16_04, ubuntu_18_04.
But it always pass on fedora_34, fedora_35, fedora_36, opensuse_15_1, opensuse_15_2, ubuntu_20_04, ubuntu_22_04.
Therefore it looks like a `glibc < 2.31` issue.

**Comment by Totktonada** [comment]
I have Gentoo Linux with glibc 2.35 and Debian Buster (10) with glibc 2.28 in docker. I compared behaviour of the following command:

```lua
$ ./src/tarantool
<...>
tarantool> io.popen(arg[-1] .. ' -ea=10 -e b=20 -ec=30 -e d=40 -e"print(a+b+c+d)"'):read()
```

The host system gives just 100, the container gives the following:

```lua
LuajitError: stdin:1: malformed number near '4lüéZFA '
fatal error, exiting the event loop
---
- '100'
...
```

The number value is different each time.

Digged down to this code:

https://github.com/tarantool/tarantool/blob/d1111c8be3a416057dc3126e161b71803aa237fc/src/lua/init.c#L1007-L1009

It seems, the actual difference is around stdin that the child got from the parent. Let's look at [`io.popen`](https://github.com/tarantool/luajit/blob/e0c8ecbf57bdddd13f8f6f9b7e82aee68f6a9916/src/lib_io.c#L407-L425).

Host system (glibc 2.35):

```lua
tarantool> io.popen('cat'):read()
<..waiting for input..>
```

Debian Buster (10) (glibc 2.28):

```lua
tarantool> io.popen('cat'):read()
cat: -: Bad file descriptor
cat: closing standard input: Bad file descriptor
---
- null
...
```

May be related to https://sourceware.org/bugzilla/show_bug.cgi?id=17490.

Maybe not. Just guess.

Even if `stdin` is closed or bad, it is wrong to attempt to execute a garbage in the case. So I would also look inside `luaL_loadfile(L, NULL)` disregarding whether the root of the problem is in `io.open()` or not.

**Comment by Gumix** [comment]
According to strace, the difference between glibc versions is that during [_IO_new_proc_open](https://elixir.bootlin.com/glibc/glibc-2.28/source/libio/iopopen.c#L122) version 2.28 closes the file descriptor `0` in between `clone` and `execve` system calls, while version 2.36 doesn't. As a result, when fd 0 is closed, the forked Tarantool calls `open(/dev/urandom)`, which returns the lowest unused fd, which is 0, then Tarantool reads from `stdin`, in effect reading random numbers.
