### ISSUE TITLE
`log_modules` option can not be set thru env var on box.cfg{}

### ISSUE THREAD

**Issue by nshy** [tarantool/tarantool#8051]
`box.cfg{}` [currently can read](https://github.com/tarantool/tarantool/blob/435e5efe982025233977effa3dab27e729c57c8a/src/box/lua/load_cfg.lua#L968) only arrays from env variable if option type is `table`:

```lua
    if param_type:find('table') and raw_value:find(',') then
        assert(not param_type:find('boolean'))
        local res = {}
        for i, v in ipairs(raw_value:split(',')) do
            res[i] = tonumber(v) or v
        end
        return res
```
Thus `log_modules`  option for example can not be set thru env var:

```console
$ TT_LOG_MODULES=aaa=info,bbb=error ./build-dev/src/tarantool
Tarantool 2.11.0-entrypoint-779-g5784a14ed
type 'help' for interactive help
*tarantool> box.cfg{}
---
- error: 'Incorrect value for option ''module name'': should be of type string'
...
 tarantool>
```

Also there is a different issue with setting table with single value:

```console
$ TT_LOG_MODULES=aaa=info ./build-dev/src/tarantool
Tarantool 2.11.0-entrypoint-779-g5784a14ed
type 'help' for interactive help
 tarantool> box.cfg{}
---
- error: 'builtin/box/load_cfg.lua:20: builtin/box/load_cfg.lua:1001: assertion failed!'
...
 tarantool>
```

I expect in both cases `log_modules` should be set successfully to `{aaa="info", bbb="error"}` and `{aaa="info"}` respectively.

**Comment by Mons** [comment]
In the #5602 there were no support for key-value paramaters, since Tarantool didn't contain any nested key-value options earlier.
So, key-value should also be supported.

To maintain simplicity for basic options and ability to pass complex options we should allow passing such an options with JSON.
So, the rules should be the following:

If param_type is a `table` and first symbol of value is `{` or `[`, then parse it as JSON.

And after splitting by "`,`":
If the param is a table and the value contains `=`, then split value into two parts by splitting it by first =
