### ISSUE TITLE
Provide names in IPROTO responses

### ISSUE THREAD

**Issue by alyapunov** [tarantool/tarantool#8147]
Now if a user wants to know selected tuples' format, they have to select spaces format manually and maintain its relevance using SCHEMA_VERSION mechanism in IPROTO. Note that this approach is durable only for direct IPROTO DML, such as replaces or selects, while in general doesn't work for IPROTO calls.

Let's provide an optional field(s) in response that describes format of tuple in the response. We should discuss the details - what exactly must be placed in that field(s) and how optional it should be.

**Comment by olegrok** [comment]
After implementing this feature please make sure that it won't lead to performance degradation. (Try to test several projects/modules).

Once we faced an issue because netbox.self returned cdata tuple in contrast of usual netbox that automatically converted response to table. https://github.com/tarantool/tdg2/issues/1835#issuecomment-1490602427
