### ISSUE TITLE
support async WAL delivery on Mac OS and FreeBSD with filesystem events

### ISSUE THREAD

**Issue by kostja** [tarantool/tarantool#832]
Avoid using stat() for asynchronous replication on Mac OS X and FreeBSD.
See gh-808 for a similar issue on Linux.

**Comment by dedok** [comment]
For Mac OS X better choice is FSEvents API (Carbon), but while ago FSEvent did not trace some events, probably apple fixed this behaviour.

P.S. And they did, since 10.7, https://developer.apple.com/library/mac/documentation/Darwin/Reference/FSEvents_Ref/index.html#//apple_ref/doc/constant_group/FSEventStreamCreateFlags, see kFSEventStreamCreateFlagFileEvents.

For BSD kqueue.

Kostia,
I have already done such features for OSX/BSD before, so I can attach code from my previous project. But I guess I can do it not before this sunday.

**Comment by zloidemon** [comment]
We also can try to use that library https://github.com/dmatveev/libinotify-kqueue on OSX and FreeBSD.
