### ISSUE TITLE
Refactor pagination test

### ISSUE THREAD

**Issue by drewdzzz** [tarantool/tarantool#8507]
Now, `engine-luatest/pagination_test.lua` is hardly maintainable. Similar cases are copy-pasted, `net.box` and read views have their own similar pagination tests. We should rewrite this test smarter and unify all the test cases for indexes, read views and `net.box`.

**Comment by locker** [comment]
Even though the tests are quite similar, parameterizing them by the tested object type (regular space, remote space, read view space) doesn't seem to be an easy task because:
1. Some test cases are so complex that we have to reopen the read view between checks. For net.box and space it isn't required.
1. There are a few test cases unique to each object type. For example, for a regular space we need to test that iteration is resumed properly after a modification while for a space read view this doesn't make sense.
1. Unifying the tests would complicate further development because we'd have to patch all the three pagination implementations together in one PR (regular, read view, net.box) otherwise the tests would fail CI. This is complicated, especially in case of read views, which are implemented in the Tarantool EE repository.

Overall, the development effort doesn't seem to be worth eliminating code duplication. After all, these are just tests that are likely to remain the same forever so code duplication isn't critical in this case.
