### ISSUE TITLE
datetime_strptime_fuzzer: ASSERT: mday >= 1 && mday <= 31

### ISSUE THREAD

**Issue by ligurio** [tarantool/tarantool#8525]
**Bug description**

Fuzzing test for `datetime_strptime` is broken by asserts:

https://github.com/tarantool/tarantool/blob/abb172a245a80e51a81b545f8d5d34cc21023271/src/lib/core/datetime.c#L148-L149

```
INFO: Running with entropic power schedule (0xFF, 100).
  | INFO: Seed: 3480450009
  | INFO: Loaded 1 modules   (34816 inline 8-bit counters): 34816 [0x93e648, 0x946e48),
  | INFO: Loaded 1 PC tables (34816 PCs): 34816 [0x946e48,0x9cee48),
  | /mnt/scratch0/clusterfuzz/bot/builds/clusterfuzz-builds_tarantool_c6a08d9c704777ebe38728ec73f5e6d849eea0cd/revisions/datetime_strptime_fuzzer: Running 1 inputs 100 time(s) each.
  | Running: /mnt/scratch0/clusterfuzz/bot/inputs/fuzzer-testcases/8ff941e0d3ea7116167dc4eb58f808a1083a1870e6ebd72d608117d18071fefe
  | datetime_strptime_fuzzer: ./src/lib/core/datetime.c:148: _Bool tm_to_datetime(struct tnt_tm *, struct datetime *): Assertion `mday >= 1 && mday <= 31' failed.
```

We need to replace these assert's to `if`..`then`.

Reproducer: 
[clusterfuzz-testcase-minimized-datetime_strptime_fuzzer-6575551489114112.txt](https://github.com/tarantool/tarantool/files/11136545/clusterfuzz-testcase-minimized-datetime_strptime_fuzzer-6575551489114112.txt)

https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=57602

**Comment by tsafin** [comment]
Those `assert`s were actually useful for us here, because in `tm->tm_mday` we have received `-179` which is obviously wrong here. And we should never receive such values, rgeardless of a year and pattern used. Apparently we need to modify the coe in 681-687:

https://github.com/tarantool/tarantool/blob/abb172a245a80e51a81b545f8d5d34cc21023271/src/lib/tzcode/strptime.c#L681-L688
