### ISSUE TITLE
В продолжении TNT-597 

### ISSUE THREAD

**Issue by Thorwinz** [tarantool/tarantool#8568]
В продолжении TNT-597:
```
TARANTOOL=2.10.4-0-g59fba21ad-r523-nogc64
TARANTOOL_SDK=2.10.4-0-g59fba21ad-r523-nogc64
```
```lua
box.cfg{memtx_max_tuple_size = 10*(1024^2), memtx_memory = 512*1024*1024}
box.schema.space.create('test',{if_not_exists = true})
box.space.test:create_index('pk', {if_not_exists = true})
for i= 1, 100 do
  box.space.test:insert({i, 1, i.. ("a"):rep(1024*1024*5)})
end
assert(box.slab.info().arena_used > box.space.test:bsize())
```

**Comment by alyapunov** [comment]
Remove from core to trigger triage process.

**Comment by alyapunov** [comment]
Discussed it with product team and others. Decided the following:
`arena_used` shows the right thing now: the memory allocated on tuple arena. Big tuples are not allocated on arena since tuple arena has size limitation, they are allocated with general malloc. We should not change `arena_size` metic.
On the other hand there are another metrics `box.info().memory().data` and `box.info().memory().index` that shows exactly what it is wanted - total memory used for data and indexes.

**Comment by alyapunov** [comment]
The only problem is that the proper stat is in 3.0.
Perhaps we could backport it to 2.11?

**Comment by unera** [comment]
No, we don't want to backport it to 2.11.

**Comment by alyapunov** [comment]
Closing then.
