### ISSUE TITLE
tarantoolctl can't connect with password contain '}'

### ISSUE THREAD

**Issue by mixMugz** [tarantool/tarantool#8695]
**Bug description**

If admin (possibly other users) contains special char in password, I can not log in by using the **tarantoolctl connect** command.

* OS: Linux
* OS Version: CentOS7
* Architecture: amd64

Tarantool 2.10.4-0-g816000e10

**Steps to reproduce**

1. Create a user with a password containing the '}' character.
2. Try to use tarantoolctl connect admin:}password{@localhost:3301

**Actual behavior**

Can't log in. Got error:
```
builtin/box/console.lua:819: Usage: console.connect("[login:password@][host:]port")
```

**Expected behavior**

Successful login.

**Comment by kyukhin** [comment]
Please, make sure that tt will be fixed as well (or if problem affects it at all).

**Comment by LeonidVas** [comment]
> Please, make sure that tt will be fixed as well (or if problem affects it at all).

`tt` doesn't have this problem (but there is [another](https://github.com/tarantool/tt/issues/475))

**Comment by LeonidVas** [comment]
After discussion, the following decisions were made:
- Since `tarantoolctl` will soon be marked as obsolete, it is recommended to use [`tt`](https://github.com/tarantool/tt) to connect to an instance with a similar password.
- The use of `{` in credentials sent with a URI is not correct, according to https://datatracker.ietf.org/doc/html/rfc3986.html#section-3.2.1.
