### ISSUE TITLE
The HTTP client shouldn't make the 'chunked' request when the 'Content-Length' header is set

### ISSUE THREAD

**Issue by andreyaksenov** [tarantool/tarantool#8744]
* OS: MacOS
* Architecture: arm
* Version: 2.11

The code below with the `chunked` option set to `true` should make the regular POST request (without `Transfer-Encoding`) if the `Content-Length` header is set:
```
local http_client = require('http.client').new()

local data = 'any data'
local io = http_client:post('http://127.0.0.1/anything', nil, {chunked = true, headers = {
        ['Content-Length'] = tostring(string.len(data))
    }})
io:write(data:sub(1, 3))
io:write(data:sub(4))
io:finish()
```

Instead, this request sets both `Content-Length` and `Transfer-Encoding` headers. See the attached screenshot.

<img width="800" alt="image" src="https://github.com/tarantool/tarantool/assets/38073144/33ca72f7-d003-4893-92c6-7ca9233cf323">

**Comment by oleg-jukovec** [comment]
The logic does not work:

https://github.com/tarantool/tarantool/blob/116df1d70cf768b2cc8569074b2f6715ef84860f/src/httpc.c#L653-L655

Probably we need to move set up `CURLOPT_UPLOAD` instead of `Transfer-Encoding: chunked`.

https://github.com/tarantool/tarantool/blob/116df1d70cf768b2cc8569074b2f6715ef84860f/src/httpc.c#L470
