### ISSUE TITLE
C stored functions: implement "unload"/"reload"

### ISSUE THREAD

**Issue by kostja** [tarantool/tarantool#910]

**Comment by rtsisyk** [comment]
Proposed API:

```
void
tarantoolopen_${MODULENAME}(void);

void
tarantoolclose_${MODULENAME)(void);
```

**Comment by mejedi** [comment]
### Proposed API
```lua
box.schema.func.reload('package.function') —> true, nil
                                           —> false, 'Error message'
```
Reload a shared library implementing the particular stored function. If the function is implemented in Lua, reports success and does nothing.

Other stored C functions from the same binary are implicitly reloaded as well.

*Reload* unloads the currently loaded instance of the shared library first. If *reload* fails, future calls to the affected stored C functions may fail as well.

*Reload* will fail if a library was loaded for other reasons rather than providing an implementation for a Tarantool C stored function. (Ex: loaded in Lua script with `ffi.load`.)

```lua
box.schema.function.reload('package')
```
Reload entire package contents.

```lua
box.schema.function.reload()
```
Reload everything.

**Comment by kostja** [comment]
Sounds good to me. I would, however, also add flush(), which flushes a
function but doesn't load it.
18 дек. 2015 г. 8:47 PM пользователь "Nick Zavaritsky" <
notifications@github.com> написал:

**Comment by rtsisyk** [comment]
there is no more customer => wishlist

**Comment by rtsisyk** [comment]
New customer is Platonov, re-scheduling to 1.7.x.

**Comment by rtsisyk** [comment]
rolling feature => 1.7.3

**Comment by rtsisyk** [comment]
=> 1.7.4

**Comment by lenkis** [comment]
What's the use to allow 'module.func-name' if we always reload the entire library? This is confusing. Let's take only module name as input.

**Comment by rtsisyk** [comment]
OK, we can allow only module name as well as modulename.funcname.
