### ISSUE TITLE
Hash Index select/get operations malfunction

### ISSUE THREAD

**Issue by wh75er** [tarantool/tarantool#9306]
**Bug description**

* OS: CentOS
* OS Version: CentOS 7
* Architecture: x86_64

Place `tarantool --version` output here.

```bash
tarantool --version
Tarantool 2.11.1-0-g96877bd
Target: Linux-x86_64-RelWithDebInfo
Build options: cmake . -DCMAKE_INSTALL_PREFIX=/usr -DENABLE_BACKTRACE=TRUE
Compiler: GNU-8.3.1
C_FLAGS:-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic -fexceptions -funwind-tables -fasynchronous-unwind-tables -fno-common -fopenmp -msse2 -Wformat -Wformat-security -Werror=format-security -fstack-protector-strong -fPIC -fmacro-prefix-map=/build/usr/src/debug/tarantool-2.11.1=. -std=c11 -Wall -Wextra -Wno-gnu-alignof-expression -fno-gnu89-inline -Wno-cast-function-type -Werror
CXX_FLAGS:-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic -fexceptions -funwind-tables -fasynchronous-unwind-tables -fno-common -fopenmp -msse2 -Wformat -Wformat-security -Werror=format-security -fstack-protector-strong -fPIC -fmacro-prefix-map=/build/usr/src/debug/tarantool-2.11.1=. -std=c++11 -Wall -Wextra -Wno-invalid-offsetof -Wno-gnu-alignof-expression -Wno-cast-function-type -Werror
```

There is one created space with no data with primary index:
```
box.schema.create_space('foo')
box.space.foo:create_index('primary', {
      type = 'HASH',
      parts = {
        1, 'number'
      }
    })
  end

data tuple looks like:
{int, string}
```

Index is created successfully
```
box.space._index:select()
  - [512, 0, 'primary', 'HASH', {'unique': true}, [[0, 'number']]]
```

If I create data through my application via go-tarantool library ([viciious](https://github.com/viciious/go-tarantool)) by calling replace or insert call then request is successfull (there are no errors) but data cannot be extracted by calling select or get calls

Also it's impossible to gather data from tarantool's console on tarantool itself by calling box.space.foo:select{333}

However by calling select{} on index and space it is possible to find inserted data there:
```
box.space.foo.index.primary:select{}
(my tuple showed here)
{333, 'some data'}

box.space.foo.index.foo:select{333}
- []

box.space.foo:select{}
(my tuple showed here)
{333, 'some data'}

box.space.foo:select{333}
(but it's impossible to index that tuple in the space)
- []
```

Also there is an interesting fact. If I create and select tuple in the tarantool's console then everything works perfectly well:

box.space.addrbook:insert{666, 'helloworld'}
box.space.addrbook:select{666}
{666, 'helloworld'}

**Steps to reproduce**

I can not provide any steps to reproduce this issue. However there is a possibility that it might be connected with duplicated data in the index

How to run:

Just type `tarantool test.lua`.

**Actual behavior**

Data is inserted into the database, but there is no way to read it and get it by using :select or :get statements

**Expected behavior**

Data is inserted into the database. I can get it back by using :select or :get statements by id. e.g. :replace{333, 'helloworld'}, :select{333} must return tuple {333, 'helloworld'}

**Comment by alyapunov** [comment]
Since there's no reproduce I can only make assumptions.
For performance reasons when tarantool calculates hash of a field or a key, in most cases it calculates hash of msgpack encoded value.
On msgpack side an integer value could be encoded with different byte sequences. For example `5` can be encoded as `0x05`, `0xcc 0x05`, `0xcd 0x00 0x05`, `0xce 0x00 0x00 0x00 0x05` or `0xcf 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x05`. On the other hand msgpack recommends [serializers SHOULD use the format which represents the data in the smallest number of bytes](https://github.com/msgpack/msgpack/blob/master/spec.md#serialization-type-to-format-conversion).
So if an encoder does not follow this recommendation and packs the same number in different formats - hash function will be different and hash index won't work. In other words for using HASH index the encoder **must** follow recommendation above. This is known behavior that will not be changed.

If my hypothesis is correct then you can prove it:
* if you insert the same data in console and via go-tarantool you will get different bsize: `box.space.addrbook:select{}[1]:bsize()`.
* it will work with big keys like 1e10.

If my hypothesis is not correct - please provide more info.

**Comment by kyukhin** [comment]
No response for 3 weeks, closing.
