### ISSUE TITLE
permissions to create, alter and drop space

### ISSUE THREAD

**Issue by 0xBF** [tarantool/tarantool#945]
guest user with all permissions can't remove or alter spaces they didn't create:

grant permissions:

```
box.schema.user.grant('guest', 'read,write,execute', 'universe', '', { if_not_exists = true })
```

try to drop space:

```
> box.space.counters:drop()

---
- error: Create or drop access denied for user 'guest'
...
```

**Comment by rtsisyk** [comment]
This fix requires significant changes in privileges structure.
Re-scheduling to 1.6.9, may be even for 1.7.x.

**Comment by vitalyisaev2** [comment]
Are there any opportunities for doing the space truncate in 1.6.x  (except dropping all the ```*.snap``` and ```*.xlog```)?

**Comment by funny-falcon** [comment]
вообщем, я вообще не смог выделить права, чтобы пользователь смог truncate
````lua
box.schema.user.grant('test', 'read,write,create,drop,alter', 'space', 'test')                                                                                                                                      
box.schema.user.grant('test', 'read,write', 'space', '_index')                                                                             
box.schema.user.grant('test', 'read,write', 'space', '_space')
````  
и всё равно
`Failed to truncate: Create, drop or alter access on space is denied for user 'test'`
Что я ещё забыл?

**Comment by zaglex** [comment]
> Are there any opportunities for doing the space truncate in 1.6.x (except dropping all the *.snap and *.xlog files)?

This workaround helped me:
box.session.su('admin')
box.space.myspace:truncate()

**Comment by shemanov** [comment]
Another workaround or solution is create objects with owner
[https://tarantool.org/doc/book/box/box_schema.html](https://tarantool.org/doc/book/box/box_schema.html)

`box.schema.create_space('test', {if_not_exists = true, user = 'guest_or_your_custom_user'})`

**Comment by rtsisyk** [comment]
@kostja I have no idea how to fix this ticket

**Comment by rtsisyk** [comment]
=> add `create` and `drop` privileges in addition to `read`, `write`, `execute`.

**Comment by kostja** [comment]
How to fix this bug:

First of all, all DDL internally should use admin_credentials to avoid "access denied" errors when working with system spaces. Requiring explicit grants on system spaces was a poor man solution to fully fledged ACL implementation we should do now.

While deploying admin_credentials, we should be careful to avoid privilege escalation wherever possible. I.e. it should be only possible to enforce admin_credentials in C code.

Second, we should introduce explicit ACL for all DDL statements. Not all ACL are meaningful for all objects, so we need to agree on a range of ACL we introduce. We should check with sqlite and SQL 
standard, when deciding on the list of ACL:

Legend: currently we have READ, WRITE, EXECUTE with the following meaning:

- **READ** - read an object. If the object is a space, read data from any index. If the object is a universe, read from any space.
- **WRITE** - write data to an object. If an object is a space, write rows/update the space. If the object is a universe, modify any space in the universe
- **EXECUTE** - execute an object. Applicable to stored procedures/functions only. If the object is a universe, then execute any function in the universe.

Off the top of my head we need the following ACLs in addition to the existing ones:

- **CREATE**: create an object. If an object is a function or space, then create that space. If an object is UNIVERSE, then create any object in the universe
- **DROP**: drop an objet. If an object is a function or space, then drop that object. If an object is universe, then drop any object in the universe (except the system spaces of course, the suicide should be available to the superuser only).
- **ALTER**: modify object metadata. E.g. modify space metadata - create indexes. As usual, for universe, implies modification of any object metadata.

We should scout other products to check whether they have useful general purpose privileges, but I don't think we need to many - this makes the system complicated. 7 kinds of actions should be enough. If not 7, then perhaps 11. But not more :)

This is patch 1 of the 3 in the patch set: its goal is to extend the list of ACLs and fix access_check_ddl() to use the new ACLs instead of the clutch it uses right now.

Step 2 is implementing CREATE privilege properly.

To do it, we should change the grant implementation to maintain its own object cache, and not rely on space and func cache. This is necessary for CREATE to function properly - we should be able to find existence of create privilege while there is no object created yet. Alternatively, we should maintain only CREATE priivlege object cache, and keep privileges of created objects within these objects as before. The function to patch is access_find().

Step 3 is implementing GRANT OPTION

**GRANT OPTION** allows the owner of a privilege to grant it to another owner. GRANT OPTION is not a privilege, it is a property of a granted privilege. It should not be part of ACL. To implement GRANT OPTION we should extend _priv system space to reflect the option in it. As usual, the option goes as a yet another field in the space. If the tuple has no field, then it has no option, this is how we keep things backward compatible. We of course patch the upgrade script to explicitly add mp_nil to all old tuples in _priv system space, and patch the snapshots accordingly.

**Comment by rtsisyk** [comment]
Please move to the next major release

**Comment by Gerold103** [comment]
@IlyaMarkovMipt  and @GeorgyKirichenko , please, write a documentation request for privileges here.

**Comment by kostja** [comment]
This is done.
