### ISSUE TITLE
net.box.connect yields, when `wait_connected = false`

### ISSUE THREAD

**Issue by Serpentian** [tarantool/tarantool#9489]
Must be fully async. Repro:

```
tarantool> box.cfg{listen = 3301}
tarantool> f = require('fiber')
tarantool> print(f.self().csw()) c = require('net.box').connect(3301, {wait_connected = false})  print(f.self().csw())
240
241
---
...
```

**Comment by sergos** [comment]
Please provide details why is it important - there some problems with some code? Perhaps the reason is not here?

**Comment by Gerold103** [comment]
It is important, if I am creating a connection from a trigger where yields are not allowed, or from inside of a transaction without mvcc, or I just want to create many connections in a loop and be sure that they won't be changed by some other fiber before the loop is complete. Otherwise `wait_connected = false` is not really usable in this context and requires crutches.

**Comment by Serpentian** [comment]
I agree with Vlad's opinion. `wait_connected` must work the same way `is_async` option behaves now.
