### ISSUE TITLE
Temporary spaces abort all DDL even without MVCC

### ISSUE THREAD

**Issue by Gerold103** [tarantool/tarantool#9720]
The reproducer requires 2 instances:
```Lua
--
-- Instance 1
--
-- Step 1
--
box.cfg{
    listen = 3301,
    replication = {3301, 3302},
}
box.once('grant guest', function() 
    box.schema.user.grant('guest', 'read,write,execute', 'universe')
end)

--
-- Step 3
--
format = {{name = 'id', type = 'unsigned'}}
space = box.schema.create_space('test', {format = format})
_ = space:create_index('pk')
do
    box.begin()
    for i = 1, 1000 do
        space:replace{i, i}
    end
    box.commit()
end

--
-- Step 5
--
table.insert(format, {name = 'val', type = 'unsigned'})
space:format(format)
```
and
```Lua
--
-- Instance 2
--
-- Step 2
--
box.cfg{
    listen = 3302,
    replication = {3301, 3302},
}
box.once('grant guest', function() 
    box.schema.user.grant('guest', 'read,write,execute', 'universe')
end)

--
-- Step 4
--
box.error.injection.set('ERRINJ_CHECK_FORMAT_DELAY', true)

--
-- Step 6
--
space = box.schema.space.create('TMP', { type = 'temporary' })
space:drop()
```

The result is that the step-6 will abort the long DDL txn in the applier, combing from the instance-1, even though those 2 DDL txns are not related anyhow. The temporary spaces don't even yield or store any actual data on disk.

This hits the users who are trying to use the temporary spaces as short living objects, creating and deleting them frequently.

The bug seems to be appearing since this commit: https://github.com/tarantool/tarantool/commit/8f4be3227635ef606581dda7e85f254a96347c0e.

**Comment by CuriousGeorgiy** [comment]
> The bug seems to be appearing since this commit: 8f4be3227635ef606581dda7e85f254a96347c0e.

This doesn't seem to be a bug. We currently lack support of DDL in transactions:

> One of the problems is that caches for metadata structures (like space_cache, user_cache, func_cache) are not versioned. Possible solution is to keep lists of corresponding structures with the TX id for each unique entry in the cache. It is likely to be enough for the most structures (user, func, coll) [^1].

So right now we simply apply the strongest restriction:
https://github.com/tarantool/tarantool/blob/b0b32bff022caeffd64ca687baab908f25fa2fcb/src/box/memtx_engine.cc#L599-L600

> Secondly, on committing transaction that provides DDL changes let's abort all
other transaction since they may refer to obsolete schema objects. The last
restriction may seem too strict, but it is OK as primitive workaround until
transactional DDL is introduced. In fact we should only abort transactions that
have read dirty (i.e. modified) objects. [^2]

However, I think we can add partial support of DDL for this specific case:

> This hits the users who are trying to use the temporary spaces as short living objects, creating and deleting them frequently.

AFAIC, we can add two checks here to relax the restriction:
https://github.com/tarantool/tarantool/blob/b0b32bff022caeffd64ca687baab908f25fa2fcb/src/box/memtx_tx.c#L686-L702

1. If the `ddl_owner` uses only on temporary spaces, we can allow transactions containing only applier rows to continue. Since we do this in `engine_prepare`, we can be sure that `ddl_owner` will not have any other statements, while the transaction containing only applier rows, by definition, cannot use temporary spaces, so we have no conflict here. 

Regarding `before_replace` or `on_replace` triggers on applier transactions: although no DDL can be use in them, they can still use obsolete temporary spaces. However, if we see that an applier transaction contains only applier rows at the moment of `ddl_owner` preparation, it should be safe to let them continue, since later usage of the committed temporary space DDL changes would be consistent.

2. If the `ddl_owner` contains only applier rows, we can allow transactions that use only temporary spaces to continue. It should be safe to do this, since later usage of committed DDL changes by the latter transactions would be consistent.

[^1]: #6138
[^2]: 8f4be3227635ef606581dda7e85f254a96347c0e

**Comment by locker** [comment]
A DDL operation must not abort **all** transactions. It should only abort those transactions that read from or wrote to the modified space. Before commit 8f4be3227635ef606581dda7e85f254a96347c0e, it already worked like this for Vinyl, see commit d3e12369565151ba8c0632a84adab4bf90eff23f. We should probably do something similar in memtx. See also #10375.

**Comment by locker** [comment]
> A DDL operation must not abort **all** transactions. It should only abort those transactions that read from or wrote to the modified space. Before commit [8f4be32](https://github.com/tarantool/tarantool/commit/8f4be3227635ef606581dda7e85f254a96347c0e), it already worked like this for Vinyl, see commit [d3e1236](https://github.com/tarantool/tarantool/commit/d3e12369565151ba8c0632a84adab4bf90eff23f). We should probably do something similar in memtx. See also #10375.

I'm planning to fix the issue in Vinyl by filtering out Vinyl transactions in [`memtx_tx_abort_all_for_ddl()`](https://github.com/tarantool/tarantool/blob/625afe418151de1015483ed24acaa57e1f85efb3/src/box/memtx_tx.c#L687). I filed a separate feature request for memtx/mvcc to make DDL abortion more fine-grained, see #10377.
