### ISSUE TITLE
`box.info.replication[...].downstream.lag` shows the same value regardless of actual replication state

### ISSUE THREAD

**Issue by winmaxdev** [tarantool/tarantool#9748]
tnt_replication_lag

{alias="kvee-r01-s02",id="2",stream="downstream"}
получает первое значение при старте и далее больше не меняется (до следущего рестарта инстанса) ,но при рестарте кластера всё зануляется

**Comment by Gerold103** [comment]
The replication downstream lag means the real time difference between this instance and the remote replica, recorded at the last confirmed transaction. I.e. when your instance commits any transaction, it is sent to the remote replica, which writes it to WAL, remembers the real time, and sends this timestamp back to the original instance. That master instance will subtract the received time from the local current real time. This is the downstream lag.

For example, instance `Master` commits a txn `TX`. It is sent to `Replica` instance. `Replica` writes it to the local WAL and sends a confirmation to the `Master` with the local real time attached `T_replica`. The `Master` receives it, gets the current real time locally `T_master = now()`, and saves `downstream.lag = T_master - T_replica`. This value gets updated every time when the `Replica` confirms receipt of a new transaction and sends a new `T_replica` to the Master.

As you can see, it will stay zero as long as the instance doesn't receive any transactions. And it will stay any other non-zero value if you did a transaction and then no transactions are happening again. This is documented here: https://www.tarantool.io/en/doc/latest/reference/reference_lua/box_info/replication/.

What was the expected behavior?
