### ISSUE TITLE
tarantool net.box from 1.6.5 can't connect to 1.6.6

### ISSUE THREAD

**Issue by 0xBF** [tarantool/tarantool#982]
tarantool> c = require('net.box'):new( '10.0.0.10', 3301)
tarantool: Can't load schema: builtin/net.box.lua:856: attempt to perform arithmetic on a table value

net.box from 1.6.6 can work with both 1.6.5 and 1.6.6

**Comment by kostja** [comment]
We will not fix this,  sorry.

**Comment by kostja** [comment]
The cause of this is not the version of net.box, but the version of the data dictionary. It should not be a problem during upgrade, since during upgrade the structure (schema) of the data dictionary will stay the same (1.6.5 format), so net.box from 1.6.5 will be able to work with 1.6.6 as long as 1.6.6 is running over the old format of the snapshot.
