### ISSUE TITLE
Rollback of DDL on `_space` space is completely broken

### ISSUE THREAD

**Issue by CuriousGeorgiy** [tarantool/tarantool#9893]
**Steps to reproduce**

```lua
os.execute('rm -rf *.snap *.xlog *.vylog 512')

box.cfg{}

box.error.injection.set("ERRINJ_WAL_IO", true)
box.space._space:alter{is_sync = false}
box.error.injection.set("ERRINJ_WAL_IO", false)

require('console').start()
```

**Actual behavior**

```console
tarantool> box.space._space:select{}
---
- error: 'console: exception while formatting the output: "builtin/msgpackffi.lua:622:
    Unsupported extension type"'
...

tarantool> box.space._space:alter{is_sync = false}
---
- error: 'builtin/box/schema.lua:941: assertion failed!'
...

```

Under ASAN build, this reproducer crashes. While, I was modifying the source code to insert additional log messages I also experienced crashes.

**Expected behavior**

Everything works correctly.

**Comment by CuriousGeorgiy** [comment]
I managed to pin down the bug.

DDL is essentially a replace operation in the `_space` space, which also invokes the `on_replace_dd_space` trigger. In this trigger, among other things, we swap the indexes of the original space, `alter->old_space`, which is equal to the corresponding transaction `stmt->space`, with the indexes of the newly created space, `alter->new_space`:
https://github.com/tarantool/tarantool/blob/de80e0264f7deb58ea86ef85b37b92653a803430/src/box/alter.cc#L1036-L1047

If then a rollback happens, we first rollback the replace operation, using `stmt->space`, and only after that do we swap back the indexes in `alter_space_rollback`:
https://github.com/tarantool/tarantool/blob/de80e0264f7deb58ea86ef85b37b92653a803430/src/box/memtx_engine.cc#L659-L669

https://github.com/tarantool/tarantool/blob/de80e0264f7deb58ea86ef85b37b92653a803430/src/box/alter.cc#L916-L925

For DDL on the `_space` space, the replace operation and DDL occur on the same space. This means that during rollback of the replace, we will try to do a replace in the empty indexes that were created for `alter->new_space`. Not only does this break the replace operation, but also the newly inserted tuple, which remains in the index, get's deleted, and access to it causes undefined behavior (heap-use-after-free).

**Comment by drewdzzz** [comment]
AFAICS, the option `is_sync` is stored in `space->def->opts` and has no effect on the space as container itself. It's only checked when the transaction is being committed. So, I propose a solution:
1. On replace in `_space`, we could check if only `is_sync` field is changed. Then, we have no need to build the new space, move indexes and so on - only set this option (and think about commit/rollback). It will solve your problem with `_space:alter{is_sync=...}` and it will speed up such alter for other system spaces.
2. On replace in `_space`, if `new_def->id == BOX_SPACE_ID`, we forbid any alter instead of one described above.

P.S. Also, we can do the same thing with all options that don't require space rebuild.
